#+TITLE: Grammaire du Hjalpi’
#+INCLUDE: "headers.org"

* Introduction
Le Hjalpi’ est la langue parlée par les dieux dans l’univers de mon roman. La langue dont je présente ci-dessous la grammaire n’est cependant pas réellement la langue divine mais la représente ; en effet, le Hjalpi’ a été imaginée comme étant bien trop complexe pour être entièrement apprise par un humain, l’élaboration de phrases simples requière quelques années d’études déjà. Bien évidemment, il est impossible pour un humain de créer une telle langue, mais je reste toujours dans cette optique de création de langue complexe, et le résultat me paraîtra complexe mais il se peut que pour certains (du fait des langues qu’ils maîtrisent déjà) n’aient pas cette impression.

Cette langue sera également utilisée pour créer d’autres langues qui auront évolué depuis la langue divine en des langues (me paraissant) beaucoup plus simples afin de créer des langues pour les mortels.

* Sons et système d’écriture
** Phonologie
Dans cet ouvrage, j’utiliserai principalement la translittération des mots, expressions et phrases du Hjalpi’ pour illustrer mes propos, exemples et explications de la grammaire de cette langue. Toutefois, il est important de savoir comment correctement prononcer le Hjalpi’, et pour cela j’utiliserai l’alphabet phonétique international afin de retranscrire la prononciation correcte du Hjalpi’. Il est important de relever les deux styles différents de transcription phonétique qui seront utilisés dans cet ouvrage :
-  /transcription large/ :: ce type de transcription ne prend pas en compte les divers cas d’allophonie présents en Hjalpi’ et retranscrit individuellement chaque symbole ayant une signification phonétique dans son orthographe translittérée.
- [transcription rapprochée] :: ce style de transcription prend en compte les changements de prononciation dû aux modifications entre phonèmes. Cela représente donc la prononciation réelle des locuteurs, qui n’est pas représentée de manière exacte par la translittération du Hjalpi’.

Généralement, j’utiliserai la transcription large lorsque j’aurai besoin de transcrire de façon phonétique des éléments de langage, à moins que je souhaite que vous, le lecteur, portiez votre attention sur un élément particulier de la prononciation de la langue divine, auquel cas j’userai de la transcription rapprochée, comme lors de la discussion sur l’[[allophonie][allophonie]]. La prononciation des mots du [[glossaire][glossaire]] sera notée en transcription large.

*** <<phon-voyelles>>Voyelles
Le Hjalpi’ dispose d’un inventaire de voyelle très large comparé à la majorité des langues existantes dans notre monde, avec dix-sept voyelles simples, et quelques autres diphtongues (discutées plus bas dans [[phon-diphtongues][Diphtongues]]). Voici la liste des voyelles utilisées dans le Hjalpi’ :

#+CAPTION: Voyelles du Hjalpi’
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | i / y       | u            |
|   | pré-fermées | í / ý       | ú            |
|   | mi-fermées  | e / ò       | o            |
|   | mi-ouvertes | é / ö       | ó            |
|   | ouvertes    | a           | á            |

Le Hjalpi’ dispose également de deux consonnes syllabiques, le /ń/ et le /ĺ/, qui sont respectivement le /n/ et le /l/ prononcés comme des voyelles. Voici ci-dessous le même tableau, avec chaque voyelle remplacée par sa valeur phonétique en IPA :

#+CAPTION: Voyelles du Hjalpi’ (IPA)
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | iː / yː     | uː           |
|   | pré-fermées | ɪ / ʏ       | ʊ            |
|   | mi-fermées  | eː / øː     | oː           |
|   | mi-ouvertes | ɛ / œ       | ɔ            |
|   | ouvertes    | aː          | ɑ            |

Avec le /ń/ et le /ĺ/ ayant respectivement pour valeur /n̩/ et /l̩/.

On peut remarquer que, à l’exception de /ń/ et /ĺ/, toutes les voyelles ont un couple ouverte-courte/fermée-longue. Dans les mots racine (c’est à dire non altérés par une quelconque règle grammaticale), la distinction revêt une importance capitale, porteuse de sens et de distinction de certains mots entre eux. Ainsi, /þran/ [θrãː] n’aura pas la même signification que /þrán/  [θrɑ̃] (pour l’explication de la prononciation, voir [[allophonie][l’allophonie]]). En revanche, comme on le verra plus tard, les addition grammaticales verront leurs voyelles s’accorder avec les voyelles du mot racine en ouverture-longueur.

**** Voyelles courtes
-  /ɑ/ : á
Le /á/ est une voyelle ressemblant au « â » que l’on retrouve en français dans des mots tels que « pâte ». Il s’agit de la voyelle ouverte antérieure non-arrondie.

-  /œ/ : ö
Il s’agit ici du son « eu » tel qu’on le retrouve en français tel que dans le mot « neuf ».

-  /ɪ/ : í
Cette voyelle est une voyelle se situant entre le son « i » et le son « e » ; on peut le retrouver en anglais dans des mots tels que « hit » ou « this ». Il s’agit de la voyelle pré-fermée antérieure non-arrondie.

-  /ɛ/ : é
Nous avons ici la voyelle « è » que l’on retrouve en français par exemple dans le mot « cette ».

-  /ɔ/ : ó
Il s’agit du « o » ouvert, que l’on retrouve en français dans le mot « sort » par exemple.

-  /ʏ/ : ý
Cette voyelle est un équivalent du « u » français ouvert, que l’on peut retrouver en Allemand comme dans « Müller » par exemple. Il s’agit de la voyelle antérieure pré-fermée arrondie.

-  /ʊ/ : ú
Cette voyelle est un équivalent du « ou » Français ouvert, telle que l’on peut la retrouver dans le mot « book » en Anglais britannique.

**** Voyelles longues
-  /aː/ : a
Cette voyelle est le « a » que l’on peut retrouver dans le français tel que dans « patte », à la différence que le « a » de le Hjalpi’ est prononcé un peu plus longuement que le « a » français.

-  /øː/ : ò
Cette voyelle est la même que le « eu » français que l’on retrouve dans le mot « deux », à la différence que le « ò » divin est prononcé un peu plus longuement que le « eu » français.

-  /iː/ : i
Cette voyelle est la même que le « i » français, à la différence que le « i » de le Hjalpi’ est prononcé un peu plus longuement que le « i » français.

-  /eː/ : e
Cette voyelle est la même que le « é » français, à la différence que le « i » de le Hjalpi’ est prononcé un peu plus longuement que le « i » français.

-  /oː/ : o
Cette voyelle est la même que le « o » français comme dans « eau », à la différence que le « o » de le Hjalpi’ est prononcé un peu plus longuement que le « o » français.

-  /yː/ : y
Cette voyelle est la même que le « u » français, à la différence que le « u » de le Hjalpi’ est prononcé un peu plus longuement que le « u » français.

-  /uː/ : u
Cette voyelle est la même que le « ou » français, à la différence que le « ou » de le Hjalpi’ est prononcé un peu plus longuement que le « ou » français.

**** <<cons-syll>>Consonnes syllabiques
-  /n̩/ : ń
Le « ń » est la consonne « n » (la même que le « n » standard français), mais considérée et prononcée comme une voyelle, tel qu’on peut l’entendre dans certains mots anglais comme dans « button » qui peut être prononcé  /bʌtn̩/.

-  /l̩/ : ĺ
Le « ĺ » est la consonne « l » (la même que le « l » français), mais considérée et prononcée comme une voyelle, tel qu’on peut l’entendre dans certains mots anglais comme dans « bottle » qui peut être prononcé  /bɔtl̩/, avec le /ʊ/ qui est omis et le  /l/ devenant syllabique.

**** <<phon-diphtongues>>Diphtongues

*** <<phon-consonnes>>Consonnes
En plus d’un important inventaire de voyelle, le Hjalpi’ dispose également d’un inventaire de consonnes assez important. Voici ci-dessous lesdites consonnes :

#+CAPTION: Consonnes du Hjalpi’
| / | >             | >      | >          | >     | >    | >         | >      | >      | >       | >     | >       |
|   |               | bilab. | lab.-dent. | dent. | alv. | pal.-alv. | rétro. | palat. | vélaire | uvul. | glottal |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | nasal         | m      |            |       | n    |           |        |        | ň       |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | occlusif      | p b    |            |       | t d  |           | ţ ḑ    |        | k g     |       | '       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | fricatif      |        | f v        | þ ð   | s z  | ß ź       |        | š ž    |         | x ŗ   | h       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | spirante      |        |            |       | ŕ    |           |        | j      |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | roulé         |        |            |       | r    |           |        |        |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | fric.-lat.    |        |            |       | ł    |           |        |        |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | spir.-lat.    |        |            |       | l    |           |        |        |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | semi-voyelles | w      |            |       |      |           |        |        |         |       |         |

#+CAPTION: Consonnes du Hjalpi’ (IPA)
| / | >             | >      | >          | >     | >    | >         | >      | >      | >       | >     | >       |
|   |               | bilab. | lab.-dent. | dent. | alv. | pal.-alv. | rétro. | palat. | vélaire | uvul. | glottal |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | nasal         | m      |            |       | n    |           |        |        | ŋ       |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | occlusif      | p  b   |            |       | t  d |           | ʈ  ɖ   |        | k  ɡ    |       | ʔ       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | fricatif      |        | f   v      | θ  ð  | s  z | ʃ ʒ       |        | ç  ʝ   |         | χ   ʁ | h       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | spirante      |        |            |       | ɹ    |           |        | j      |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | roulé         |        |            |       | r    |           |        |        |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | fric.-lat.    |        |            |       | ɬ    |           |        |        |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | spir.-lat.    |        |            |       | l    |           |        |        |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | semi-voyelles | w      |            |       |      |           |        |        |         |       |         |

*** Accentuation
L’accentuation des mots en langue divine porte sur l’avant-dernière voyelle racine si le mot racine dispose de deux syllabes ou plus, sur la voyelle racine unique sinon. L’accentuation des mots étant régulière, elle n’est pas marquée par l’orthographe et la translittération de la langue.
Pour ce qui est de l’accentuation des phrases, le ton est généralement tombant, avec le terme que le locuteur estime le plus important de la phrase bénéficiant d’une remontée du ton sur ce terme précisément. Si le locuteur estime que le terme est très important, alors il peut même le prononcer avec une voix de tête, voire étirer de manière exagérée la première syllabe racine du terme. Un verbe interrogatif bénéficie nécessairement de la remontée du ton de la phrase sur ce terme, tandis qu’une phrase exclamative voit son ton recommencer à descendre à partir de la même hauteur que celle du début de phrase. Une phrase affirmative continue la descente de ton jusqu’à la dernière syllabe racine qui bénéficie d’une accentuation.

*** Romanisation et translittération
La romanisation et la translittération d’une langue sont deux choses très différentes ; en effet, la première a pour but de représenter de façon grossière la prononciation de la langue avec l’alphabet latin, sans se soucier de l’orthographe exacte, tandis que la translittération a pour but de reproduire de manière précise l’orthographe de la langue transcrite, sans se soucier de savoir si le lecteur saura prononcer correctement la transcription s’il n’a pas été initié avant à la langue transcrite.

Pour moi le meilleur exemple que je puisse donner pour ce qui est de la différence entre romanisation et translittération est en Tibétain. Nous avons des termes Tibétain romanisés “dorje”, “chorten” ou encore “yak” en anglais dont une de leur translittération possible respective est “rdo rje”, “mchod brten” et “gyag”. Bien évidemment, toute personne n’ayant aucune notion de translittération du Tibétain et/ou de son orthographe peut être confuse quant à ce qu’ils viennent de lire, et c’est tout naturel : leur but est de savoir précisément comment écrire ces mots, et une personne sachant écrire en tibétain pourra, en ayant lu ces exemples, écrire les mots sans faute si je n’en ai pas fait non plus à la rédaction de cet ouvrage. Comme je l’ai indiqué, il s’agit dans cet exemple d’une romanisation anglophone ; en effet, la romanisation dépend de la langue du lecteur. Étant donné que ce dernier doit pouvoir se forger une idée de la prononciation du mot étranger, il faut utiliser les conventions de lecture de l’alphabet de sa propre langue afin d’approcher au mieux la prononciation originale. Ainsi, “dorje” en anglais pourrait être écrit « dordjé » en français, “chorten” pourrait être écrit « tchortène » (« yak » garde la même orthographe dans les deux langues, et est même dans les dictionnaires anglophones et francophones).

Ainsi, dans mon (ou mes ?) livre(s ?) qui s’adressera (s’adresseront ?) à un public général, j’utiliserai des romanisation de la langue divine si je souhaite que le lecteur ait une idée de la prononciation du mot ou de la phrase qu’il vient de rencontrer –et à l’inverse, si je souhaite être plus graphique, j’utiliserai soit la translittération, soit l’écriture native du Hjalpi’. Toujours est-il que dans cette référence grammaticale, je n’utiliserai que de la translittération (les graphèmes et lettres correspondantes furent décrites dans [[phon-consonnes][Consonnes]] et [[phon-voyelles][Voyelles]]), et ne ferai usage de la romanisation que dans ce chapitre où j’explique ci-dessous le processus de l’écriture du Hjalpi en romanisation.

Voici ci-dessous un tableau avec chaque phonème du Hjalpi’, sa translittération, et sa romanisation francophone. Pour un équivalent anglophone, se référer à la version anglophone de cet ouvrage si cette dernière existe.

#+CAPTION: Translittération des voyelles du Hjalpi’
| / | >       | >      |      |
|   | phonème | trans. | rom. |
|---+---------+--------+------|
|   | iː      | i      | i    |
|   | yː      | y      | u    |
|   | uː      | u      | ou   |
|   | ɪ       | í      | i    |
|   | ʏ       | ý      | u    |
|   | ʊ       | ú      | ou   |
|   | eː      | e      | é    |
|   | øː      | ò      | e    |
|   | oː      | o      | o    |
|   | ɛ       | é      | è    |
|   | œ       | ö      | eu   |
|   | ɔ       | ó      | au   |
|   | aː      | a      | a    |
|   | ɑ       | á      | a    |

#+CAPTION: Translittération des consonnes du Hjalpi’
| / | >       | >      |      | <> | >       | >      |      |
|   | phonème | trans. | rom. |    | phonème | trans. | rom. |
|---+---------+--------+------+----+---------+--------+------|
|   | p       | p      | p    |    | b       | b      | b    |
|   | t       | t      | t    |    | d       | d      | d    |
|   | ʈ       | ţ      | tr   |    | ɖ       | ḑ      | dr   |
|   | k       | k      | k    |    | ɡ       | g      | g    |
|   | f       | f      | f    |    | v       | v      | v    |
|   | θ       | þ      | th   |    | ð       | ð      | dh   |
|   | s       | s      | s    |    | z       | z      | z    |
|   | ʃ       | ß      | sh   |    | ʒ       | ź      | j    |
|   | ç       | š      | sh   |    | ʝ       | ž      | jh   |
|   | m       | m      | m    |    | n       | n      | n    |
|   | ŋ       | ň      | ng   |    | ʔ       | ’      | ’    |
|   | r       | r      | r    |    | h       | h      | h    |
|   | χ       | x      | rh   |    | ʁ       | r      | r    |
|   | ɬ       | ł      | lh   |    | ɹ       | r      | r    |
|   | l       | l      | l    |    | j       | j      | y    |
|   | w       | w      | w    |    |         |        |      |

** Phonologie dérivationnelle
Ci-dessous se trouve une liste d’abréviations que l’on trouvera souvent dans les règles formelles :
- ~C~ = consonne
- ~V~ = voyelle
- ~N~ = nasale
- ~F~ = fricative
- ~P~ = consonne labiale
- ~L~ = voyelle longue
- ~S~ = voyelle courte
- ~#~ = limite d’un mot
- ~Ø~ = silencieux, muet, rien

*** <<allophonie>>Allophonie
En Hjalpi’, il existe de nombreuses règles sur la modification de prononciation de phonèmes selon leur emplacement au sein d’un mot et leur environnement phonétique, donnant lieu à des allophones desdits phonèmes. Ces règles sont les dernières règles à s’appliquer sur la modification de prononciation des mots, les autres règles comme les [[deriv-accord-voy][accords des voyelles]] ou les [[deriv-accord-cons][accords des consonnes]] s’appliquant avant les règles d’allophonie. Ces règles s’appliquent dans leur ordre d’apparition ci-dessous.

**** Voyelles
Il existe relativement peu d’allophones parmi les voyelles de le Hjalpi’, cependant on peut en relever certains comme suit :
- La prononciation standard du « ń », comme mentionné ci-dessus dans [[cons-syll][Consonnes syllabiques]], est /n̩/. Cependant, cette voyelle peut également être prononcée /m̩/ si le /ń/ est précédé et/ou suivi par une consonne bilabiale, et il peut être palatalisé en /ɲ̩/ ou /m̩ʲ/ si le /ń/ est également adjacent à une des voyelles /i/ ou /í/, ou bien la consonne /j/ (notées ~I~).
 -  /n̩/ > [m̩] / _P
 -  /n̩/ > [m̩] / P_
 -  /n̩/ > [ɲ̩] / _I
 -  /n̩/ > [ɲ̩] / I_
 -  /n̩/ > [m̩ʲ] / P_ I
 -  /n̩/ > [m̩ʲ] / I_ P
- Le « ĺ » peut également être palatalisé en cas d’adjacence à une des voyelles /i/ ou /í/ ou bien la consonne /j/, et donc être prononcée /l̩ʲ/.
 -  /l̩/ > [l̩ʲ] / _I
- Une voyelle ou un groupe de voyelles placé devant une consonne nasale se nasalise.
 - V > [+nasal] / _N

**** Consonnes
Plusieurs de ces consonnes disposent d’allophones, c’est à dire de prononciations alternatives à la prononciation exacte mentionnée plus haut, sans que cela n’affecte le sens des mots ou le sens d’une phrase.
- La prononciation standard du /f/ et /v/ sont respectivement ~/f/~ et ~/v/~, cependant il arrive également qu’ils soient respectivement prononcés ~/p\/~ et ~/B/~ entre deux voyelles, ou en début de mot si immédiatement suivis d’une voyelle ou d’une semi-consonne (également notée ~V~).
 -  /f/ > [ɸ] / #_ V
 -  /f/ > [ɸ] / V_ V
 -  /v/ > [β] / #_ V
 -  /v/ > [β] / V_ V
- Le  /ɦ/ est considéré comme étant un allophone du  /h/. Cet allophone se produit entre deux voyelles, en début de mot immédiatement suivit d’une voyelle, entre une consonne voisée et une voyelle, ou une voyelle et une consonne voisée. En revanche, au contact du /i/, /í/ ou /j/ (notés ~I~), le  /h/ se palatalise en un  /ç/. Similairement, un  /ɦ/ obtenu grâce au premières règles ci-dessous change en  /ʝ/.
 -  /h/ > [ɦ] / #_ V
 -  /h/ > [ɦ] / V_ V
 -  /h/ > [ç] / _I
 -  /h/ > [ç] / I_
 -  [ɦ] > [ʝ] / _I
 -  [ɦ] > [ʝ] / I_
- Le /ŗ/ a pour prononciation standard le /ʁ/, cependant il est généralement prononcé /ʀ/ entre deux voyelles et/ou consonne voisée (notées ~V~).
 -  /ʁ/ > [ʀ] / V_ V
- Le /x/ est habituellement prononcé /χ/, cependant il est prononcé /x/ lorsqu’il est en contact avec une consonne fricative sourde (notée ~FS~).
 -  /χ/ > [x] / FS_
 -  /χ/ > [x] / _FS
- Une consonne nasale devient silencieuse si elle est précédée d’une voyelle et suivie d’une consonne ou d’un silence. Cela fait suite à la nasalisation de la voyelle précédente.
 - N > Ø / V_ #
 - N > Ø / V_ C
- Si deux consonnes fricatives toutes deux voisées ou sourdes se suivent successivement, même entre deux mots distincts, la première fricative devient silencieuse.
 - F > Ø / _F
- Si une consonne fricative voisée (notée ~FV~) est précédée par une fricative sourde (notée ~FS~), elle devient elle-même sourde. À l’inverse, si une fricative sourde est précédée par une fricative voisée, la première devient également voisée.
 - FS > [+voisée] / FV_
 - FV > [+sourde] / FS_

**** Exemples
- raòm ::  /raøm/ est prononcé [rãø̃]

*** <<deriv-accord-voy>>Accord des voyelles
L’accord des voyelles a lieu principalement lors de la déclinaison d’un nom ou de la conjugaison d’un verbe, lors d’un cas où la juxtaposition d’une voyelle à une autre est obligatoire. Cela donne alors lieu à un accord des voyelles.

1. Les deux voyelles sont fusionnées en une diphtongue.
2. Si l’un des deux phonèmes est une consonne syllabique /ń/ ou /ĺ/, alors celle-ci reste inchangée.
3. Si la première voyelle est une diphtongue, alors le second phonème est remplacé par la seconde voyelle après que cette dernière ait été accordée en longueur à la longueur de premier phonème de la diphtongue.
4. Si la seconde voyelle était également une diphtongue, alors elle perd son second phonème.
5. Si le second phonème de la diphtongue est plus ouvert que le premier, alors il est refermé afin d’être au moins aussi fermé que le premier phonème.
6. Si le premier phonème de la diphtongue est une voyelle antérieure, alors elle devient son équivalent phonétique postérieur selon la table suivante :
| / | >                 |                 |
|   | phonème d’origine | nouveau phonème |
|---+-------------------+-----------------|
|   | u                 | y               |
|   | ú                 | ý               |
|   | o                 | ò               |
|   | ó                 | ö               |
|   | á                 | a               |

*** <<deriv-accord-cons>>Accord des consonnes
*** Phonotaxes
**** Attaque
**** Rime
***** Noyau syllabique
***** Coda

** Système d’écriture
* Éléments de la phrase
** Noms
*** Articles
*** <<morpho-nom-genre>>Genre
Le Hjalpi’ est une langue riche en genres grammaticaux, étant donné qu’elle dispose de *neuf genres* différents
1. Genre divin : se réfère à toute personne considérée comme divine, que ce soit par les Divins ou par les mortels (humains comme non humains). Aucune distinction n’est faite selon leur sexe biologique. Les méduses, du fait d’être une icône divine, sont considérées étant également du genre divin. Il se réfère également à ce qui fait partie de leur domaine, que ce soit leurs Demeures ou leurs Œuvres majeures, tels que les Tours ou le Temps.
2. Genre mental : se réfère à tout élément non physique ou concept, comme des pensées ou des couleurs. Les lieux physiques et temporels sont également classifiés dans le genre mental. Bien que le temps en lui-même soit considéré comme étant du genre divin, les événements sont considérés comme étant des éléments mentaux.
3. Genre liquide : se réfère, comme son nom l’indique, à tout liquide, et en particulier à l’eau, mais ne couvre pas tous les fluides ; par exemple, l’air n’est pas considéré comme un liquide, malgré le fait que ce soit un fluide.
4. Genre masculin humain : se réfère à tout être humain ou semi-humain mâle, ou à un groupe à prédominance numérique ou de puissance masculine.
5. Genre féminin humain : se réfère à tout être humain ou semi-humain femelle, ou à un groupe à prédominance numérique ou de puissance féminine.
6. Genre neutre humain : se réfère à tout être humain ou semi-humain dont on ne connaît pas le sexe biologique, ou si un groupe n’a pas de prédominance numérique ou de puissance masculine ou féminine.
7. Genre animal : se réfère à tout être mortel n’étant pas un humain ou semi-humain et étant animé.
8. Genre végétal : se réfère à tout être mortel n’étant pas un humain ou semi-humain, ou membre d’animaux.
9. Genre inanimé : se réfère à tout être non-vivant n’étant pas inclus par les trois premiers genres.

Le genre est inclus sémantiquement dans chaque nom commun du Hjalpi’, en revanche la majorité des éléments rattachés au nom s’accorderont en genre, ainsi que les verbes suivant si le nom influe la conjugaison du verbe.

Le Hjalpi’ dispose également de *quatre sur-genres*, regroupant les genres en catégories qui sont utilisées dans certains contexte, comme pour la déclinaison ou la conjugaison des verbes.
1. Le sur-genre supérieur : rassemble les genres divin et mental
2. Le sur-genre humain : rassemble les genres humains (masculin, féminin et neutre)
3. Le sur-genre vivant : rassemble les genres du vivant non-humain (animal et végétal)
4. Le sur-genre inanimé : rassemble les genres liquide et inanimé

Une déclinaison des éléments humains neutres est possible, auquel cas on peut décliner ainsi l’élément dont on souhaite changer le genre :
| / | >        |             |
|   | genre    | déclinaison |
|---+----------+-------------|
|   | masculin | -e          |
|   | féminin  | -am         |

Ce genre de déclinaison est en général utilisé pour les mots se référant à un être humain dont le genre syntaxique est neutre, mais que l’humain référé est d’un genre connu. Par exemple, si l’on parle de plusieurs personnes de nombre inconnu (donc singulatif, voir les [[morpho-nom-nombre][Nombres]]) mais que la majorité des individus est de genre féminin, alors on déclinera /ðenmóíl/ (individu/personne) en /ðenmóílelam/ (personne.sf.5g). La déclinaison en féminin s’affixe à la déclinaison au singulatif du fait qu’il s’agit du groupe qui prend le genre féminin, indiquant que le groupe n’est pas uniquement mais majoritairement féminin. Si le groupe n’est composé que de femmes, alors /ðenmóíl/ se déclinera en /ðenmóílamel/ (personne.5g.sf).

Il est également possible de changer le genre d’un sujet de phrase (agent nominatif, patient ergatif ou expérienceur) en accordant le reste de la phrase suivant le genre que l’on veut lui donner. Ainsi, pour déifier le chat de la phrase « Ce chat se comporte comme un dieu céleste », on peut dire :
| se.comporter-1SG.gnomique.obj.certain | dieu.celeste-EQU.1s | chat-NOM.1s | ce.1s |

*** <<morpho-nom-nombre>>Nombre
En plus d’avoir une riche quantité de genres, le Hjalpi’ dispose également de cinq nombres distincts qui se marquent par une déclinaison du nom ou de l’élément accordé en nombre (hormis le verbe).

| / | >          | >           |                                    |
|   | nombre     | déclinaison | description                        |
|---+------------+-------------+------------------------------------|
|   | singulier  | (aucune)    | élément unique                     |
|   | singulatif | -el         | ensemble d’éléments semblables     |
|   | duel       | -(a)t       | deux éléments semblables           |
|   | triel      | -(e)þ       | trois éléments semblables          |
|   | pluriel    | -(o)st      | quatre éléments semblables ou plus |

Le singulatif, comme décrit ci-dessus, est utilisé pour regrouper des éléments semblables et est une alternative au singulier ou pluriel dans le cas où l’élément est indénombrable ou éligible au pluriel mais le locuteur n’a pas d’idée précise du nombre d’éléments présents dans le groupe (exemples en français : « de la farine », « des gens »).

Pour des raisons grammaticales il existe également un sur-nombre, le /super-singulier/ qui regroupe tous les nombres qui ne sont pas le pluriel. Le super-singulier est utile notamment pour les déclinaisons qui distinguent uniquement le super-singulier et le pluriel.

** Pronoms
** Adjectifs
** Adverbes
** Verbes
*** <<verbes-temps>>Temps
Il existe techniquement sept temps en Hjalpi’, considérés tous comme étant distincts les uns des autres :
- Le *passé lointain* et le *futur lointain* sont associés à des temps à échelle d’une civilisation et au delà de temps à échelle d’une vie humaine. Ainsi, si un événement quelconque est mentionné comme s’étant passé il y a plus d’une soixantaine d’années, les locuteurs du Hjalpi’ s’y référeront au moyen du passé lointain, et à l’inverse, un événement qui se produira dans un siècle sera référé au moyen du futur lointain.
- Le *passé moyen* et le *futur moyen*, plus souvent appelés respectivement *passé* et *futur*, se réfèrent à des événements à échelle d’une vie humaine, c’est à dire à plus ou moins une soixantaine d’années dans le passé ou dans le futur.
- Les deux temps précédents n’empiètent cependant pas sur le *passé proche* et le *futur proche*, qui se réfèrent à des événements se produisant de deux jours dans le passé à deux jours dans le futur. Ils sont aussi utilisés pour des événements imminents ou venant de se produire.
- Le *présent* se réfère quand à lui à des événements ayant cours au moment de la locution et, contrairement au français, ne peut se référer à un autre temps, comme le futur immédiat.

Chacun de ces temps se marquent via la conjugaison des verbes.

Il y a également deux temps utilisés uniquement par les dieux (célestes comme terrestres) qui sont le *passé divin* et le *futur divin*, chacun ayant pour limite la création du monde et sa fin avec lesquels ils se réfèrent à des événements dans des temps plus lointains que ceux situés dans la même ère civilisée que le locuteur, c’est à dire des événements se produisant à environ dix mille ans du temps de locution. Ces temps divins se marquent par une double conjugaison du verbe au temps lointain correspondant. Les mortels n’ayant pas la même notion du temps que les divins utiliseront à la place les temps lointains, à l’exception d’universitaires ayant eu le privilège d’avoir pu converser avec un divin, l’impact du contact avec ces derniers permettant un changement radical de la vision des mortels dans la vision du monde. Cependant, l’utilisation des temps divins reste tout de même rare même parmi ces universitaires et est considéré comme étant plutôt pédant lorsqu’il est utilisé par un mortel.

Dans le Hjalpi’, le temps est visualisé comme une pluie tombante, ou plutôt comme le cycle de l’éther avec le ciel représentant le passé lointain, tombant jusqu’à l’arrière de la tête du locuteur (passé moyen), allant sur son épaule droite (passé proche), dans la tête du locuteur (présent), sur son épaule gauche (futur proche), devant son visage (futur moyen) puis dans le sol (futur lointain). On peut voir dans cette visualisation du temps que les dieux sont considérés comme étant les êtres à l’origine du monde, résidants dans les cieux, et leur bénédiction tombant sur les mortels et passant en eux avant qu’ils fassent face au futur qui va se joindre au sol et au monde, comme ce à quoi chaque mortel est destiné. Pour les divins, cette visualisation commence aux confins de l’espace, en dehors de l’univers d’où vient le Dieu Créateur, représentant lui-même le passé pour les divins, et le futur divin se situant au centre du monde où résident les flammes qui y mettront fin lors de l’arrivée de la fin des temps.

**** Temps antérieurs
Chaque passé dispose d’un *passé antérieur* se référant à une date antérieure au narratif. Cette conjugaison se faisant à l’aide d’un auxilliaire, la conjugaison déterminera le passé relatif au temps de narration, le participe du verbe indiquant le temps d’origine. Aussi connu sous le nom de *plus-que-parfait*. Un équivalent existe également pour les événements antérieurs à un futur de narration : le *futur antérieur*, applicable de la même façon à tous les futurs.

**** Temps postérieurs
Inversement, le *passé postérieur* permet d’exprimer une situation future au passé d’énonciation, de même que le *futur postérieur*. Leur marque se porte également sur l’auxilliaire et le participe du verbe racine.

*** <<verbe-cert>>Certainté
Le Hjalpi’ dispose d’un concept de certainté et est omniprésent dans les verbes. En effet, la véracité et vérifiabilité des dires du locuteur est très importante pour les divins, et ce premier doit en toutes circonstances statuer de l’état de ses affirmations, et cela se fait via la conjugaison du verbe. Il existe quatre niveaux de certainté :
- certainté objective forte :: Le locuteur affirme que sa proposition est vraie sans nécessairement avoir personnellement vérifié cette affirmation par lui-même, mais il implique que cela est une vérité générale ou absolue. Par exemple, dans notre monde, la phrase « Il y a des yaks au Tibet » serait une phrase à certainté objective forte, il s’agit d’une vérité générale qui ne sera normalement pas remise en question.
- certainté objective relative :: Le locuteur fait part d’une vérité vérifiée par lui-même ou dont il est certain sans qu’il s’agisse nécessairement d’une vérité générale ou absolue. Ainsi, on peut affirmer avec une objectivité relative « J’habite au quatrième étage de mon immeuble », j’affirme que cela est vrai et objectif sans pour autant que ce soit une vérité générale (je n’y habiterai pas toujours, et ce n’est pas une connaissance commune non plus).
- certainté subjective forte :: Le locuteur émet une opinion qu’il considère comme étant généralement partagée par son ou ses interlocuteurs. Par exemple, un parisien pourra dire en subjectivité forte à un autre parisien qu’il fait froid lorsqu’en plein milieu de l’hiver il fait -5°C à Paris, ce avec quoi l’autre parisien sera généralement d’accord ; en revanche un Canadien, un Russe ou un habitant des pays Scandinaves pourra montrer son désaccord. Le locuteur peut permettre de partager également des informations dont le locuteur est relativement sûr mais pas entièrement, l’empêchant d’utiliser une certainté objective.
- certainté subjective relative :: Le locuteur émet une opinion qui lui est propre et qui ne sera pas forcément partagée par son interlocuteur. Ce degré de certainté est utilisé pour partager des opinions qui ont un caractère plus personnel. Par exemple, si le locuteur dit « Je n’aime pas la menthe », il le dira avec une subjectivité relative, ne s’attendant pas forcément à voir son opinion partagée ou non par son interlocuteur. Cela peut être aussi utilisé pour partager une information dont le locuteur n’est pas sûr, ou bien pour partager des souvenirs dont le locuteur peut se permettre de douter.

Le degré de certainté est marqué avec la conjugaison du verbe.

Il est tout à fait possible pour le locuteur d’utiliser volontairement un degré de certainté erroné afin d’appuyer le message de sa phrase, d’y mettre une emphase. Par exemple, quelqu’un qui parle d’un restaurant huppé dans la ville à son ami qui vient d’arriver peut tout à fait lui dire que ce restaurant est excellent tout en utilisant l’objectif fort afin de sous entendre qu’il s’agit d’une opinion largement partagée, voire même d’une vérité générale dans la ville. À contrario, un locuteur qui doute d’une vérité générale utilisera une subjectivité relative afin de démettre cette vérité générale vers une simple opinion ; c’est ce qu’aurais pu faire Galilée avec la phrase « la Terre est plate », remettant ainsi en doute cette vérité générale de l’époque (qui, par ailleurs, n’était crue que par le bas peuple, les personnes cultivées savaient que la Terre est ronde). Cependant, attention à l’abus d’utilisation erronée du degré de subjectivité, les personnes qui en abusent sont souvent vus comme étant des hypocrites ou des manipulateurs par leurs pairs.

*** Aspects
Bien que le [[verbes-temps][temps]] et le [[verbe-cert][degré de certainté]] donnent déjà quelques informations sur le verbe et l’événement décrit, beaucoup d’autres informations manquent toujours : l’événement se répète-il, parle-t-on du processus de l’événement où de l’événement en tant qu’objet ? Ces questions sont répondues par les aspects du verbe que je listerai ici. Notez que différents aspects peuvent être utilisés en simultané.

**** Perfectif et imperfectif
Le *perfectif* et *l’imperfectif* sont deux aspects omniprésents avec les verbes ; l’un de ces deux aspects est obligatoire. Ces deux aspects s’opposent dans leur représentation du verbe, le perfectif décrivant l’événement comme un objet, comme un tout, alors que l’imperfectif le décrit comme un processus. On peut retrouver un exemple de cette opposition en Français avec les phrases « Henri IV régna vingt et un ans » (phrase perfective) et « Henri IV régnait vingt et un ans » (phrase imperfective). Ainsi, si l’on souhaite considérer un événement comme un processus, ou afin de mettre en place un décors pour d’autres éléments, on utilisera l’aspect perfectif du verbe ; à contrario, ce sera l’imperfectif qui sera utilisé pour considérer un événement comme un tout, comme par exemple comparer le règne de Henri IV à celui d’un autre monarque.

En Hjalpi’, l’aspect par défaut entre ces deux aspects est l’imperfectif, qui n’est pas marqué. L’imperfectif est également le seul aspect autorisé lors de l’utilisation du présent. Si on souhaite passer un verbe au perfectif, il faudra le marquer au moyen d’une conjugaison différente de la conjugaison par défaut (utilisée donc pour l’imperfectif).

**** Complétif et incomplétif
Ces aspects permettent de porter l’accent sur le fait que l’action ou l’événement soit arrivé, arrive ou arrivera à son terme de façon certaine ou non. Par défaut, tous les verbes sont incomplétifs (sauf exceptions notées dans leur définition dans le [[glossaire][glossaire]]), cependant passer le verbe au complétif permet de changer son sens afin d’exprimer le fait que l’événement arrive à son terme. Ainsi, le verbe /eŕbölýþ/ (voler dans les airs) mis au complétif prend la signification « se poser » ou « atterrir » avec l’attention portée sur la fin de l’événement qu’était le vol, et non sur le fait d’être sur le sol. Le complétif est marqué par une déclinaison de la racine du verbe.

**** Inceptif
L’inceptif porte l’attention sur le début de l’événement décrit par le verbe. Ainsi, le verbe /eŕbölyþ/ décliné à l’inceptif prend la signification « décoller », avec l’attention portée sur le fait de commencer à voler, et non sur le fait de ne plus être au sol. L’inceptif est par défaut absent des verbes et doit être marqué lorsqu’un verbe a une valeur inceptive (sauf exceptions notées dans le [[glossaire][glossaire]]) À l’instar du complétif, l’inceptif est également marqué par une déclinaison de la racine du verbe.

**** Habituel, fréquentatif et itératif
Ces aspects du verbe marquent tous trois un événement se répétant dans le temps. *L’habituel* permet de marquer une emphase sur une situation caractéristique du temps employé, son nom est d’ailleurs assez explicatif. Il se marque par une conjugaison du verbe par un auxiliaire.

Le *fréquentatif* permet de marquer une action répétée irrégulièrement. Il se marque par une déclinaison de la racine du verbe.

*L’itératif* à l’inverse permet de marquer une action répétée régulièrement sur une période donnée, il marque des actions divisées en instances séparées et répétées régulièrement. Cet aspect est marqué par une déclinaison de la racine du verbe, et va souvent de paire avec le [[cas-distemp][distributif-temporel]].

**** Implicatif
*L’implicatif* permet de marquer la situation comme ayant un impact sur le temps utilisé ou sur un temps ultérieur. Par défaut, les verbes ne sont pas implicatifs, cependant des exceptions signalées comme telles dans le [[glossaire][glossaire]] existent et peuvent être modifiées en *non-implicatif*. Ces deux aspects se marquent par une déclinaison de la racine du verbe.

**** Rétrospectif
Un aspect parfait d’un verbe implique une situation du passé ou du futur avec des conséquences ou implications présentes (généralement marqué également à l’implicatif). On peut également utiliser les termes *retrospectifs* pour les éléments passés et *prospectif* pour les éléments futurs. Il existe avec cet aspect plusieurs types de parfait :
- Parfait de Résultat :: les implications ou conséquences sont toujours d’actualité pour les verbes passés, marqués par la conjugaison.
- Parfait exprienciel :: cet aspect inplique que la situation s’est déjà produite au moins une fois par le passé, ou se produira au moins une fois avant le temps utilisé. Il est marqué par la déclinaison de la racine du verbe.
- Parfait de percistence :: il permet de marquer le passage d’une situation d’un temps à un autre, notamment la continuité depuis le passé jusqu’au présent. Exeple : « j’ai comencé à travailleur sur le Hjalpi’ originel en début 2018 » (sous-entendu, je suis à l’heure actuelle).
- Parfait de récence :: cet aspect ne peut être utilisé que lors de l’utilisation du passé proche afin de mettre en valeur la récence de la situation. Il ne peut s’utiliser que pour faire référence à une situation s’étant produite deux heures avant le temps présent tout au plus. Ce parfait se marque par une déclinaison de la racine du verbe.

**** Progressif
Le progressif marque une situation en cours, que ce soit dans le passé, présent ou futur. Il peut être utilisé pour emphaser le processus ou pour porter la signification d’une situation temporaire. Il peut également permettre de marquer une progression, même si cette dernière est délimitée dans le temps par un perfectif. Cela est marqué par un auxilliaire utilisé avec le verbe décliné au progressif, l’auxilliaire étant porteur du temps d’origine du verbe, de son aspect et de son mode.

**** Découpage du temps
***** Gnomique
Le temps gnomique permet d’exprimer une situation universellement vraie. Un temps gnomique ne peut être utilisé qu’avec une certainté objective, forte ou faible.

***** <<verbe-dec-ponct>>Ponctuel
Le ponctuel est un aspect permettant d’exprimer une situation qui ne dure qu’un instant. Cet aspect se marque par la conjugaison du verbe.

***** Délimitatif
Similairement au [[verbe-dec-ponct][ponctuel]], de délimitatif se réfère à une situation courte dans le temps, et se marque par le ponctuel associé au progressif.

***** Duratif
Le duratif et une emphase sur une action qui s’étend dans un temps unique. Le duratif s’utilise pour exprimer le progressif perfectif, et se marque comme le progressif avec l’auxilliaire conjugué avec un aspect perfectif.

**** Télique et atélique
Une activité *télique* est une activité ayant un but, qu’il s’agisse d’un produit ou d’’un accomplissement. Une activité n’ayant pas de résultat est *atélique*. La télicité d’une action est inclue dans la sémantique des verbes, mais une inversion de télicité peut aussi être marquée par l’ajout d’une particule précédant le verbe (généralement il s’agit de rendre le verbe télique). Par exemple, en français « persuader » est un verbe télique, car cette activité est en réalité généralement la tentative de persuation d’une personne, avec pour but que cette personne soit persuadée. En rendant « persuader » atélique, « avoir persuadé quelqu’un » ne veut pas forcément dire que la personne a été persuadée, mais que l’on a tout de même tenté de la persuader.

*** Modes

*** Valence du verbe
La valence d’un verbe est le nombre d’arguments que ce dernier peut prendre. Les verbes intransitifs prennent au moins en argument un expérienceur, les verbes transitifs prennent au moins un agent et un patient. Si le verbe est également un verbe d’action, il prendra également en argument un bénéfactaire, bien qu’il soit souvent omis s’il est inconnu (ce qui est souvent le cas lorsque le locuteur ne parle pas à la première personne) ou s’il est identique avec l’expérienceur, l’agent nominatif ou le patient ergatif. Il est d’ailleurs également possible d’élipser l’agent nominatif ou le patient ergatif d’une phrase si le contexte permet aux locuteurs de les déduire aisément. En français cela donnerait quelque chose comme ceci : « Tu sais ce qu’a fait Éreþ hier ? A couru pendant quatre heures d’affilées pour Tama ».

Il est également possible de réduire ou d’augmenter la valence d’un verbe selon plusieurs procédés décrits ci-dessous.

**** Passif et antipassif
La voix passive et anti-passife permet d’ellipser un élément cœur de la proposition si le contexte le rend suffisamment évident. Il est également possible de transformer un verbe en un adjectif au patient, permettant d’ellipser l’agent dans certains cas, notamment : l’agent était un pronom impersonnel. Par exemple, en français à la palce de dire « on boit de la bière ici » on peut dire « la bière est bue ici ».

Le passif et l’antipassif permettent également l’inversion de l’agent et du patient, permettant d’ellipser l’agent dans les phrases nominatives et le patient dans les phrases ergatives.

**** Réflexif
La voix réflexive permet d’unifier l’agent et le patient d’une phrase et permet effectivement d’élipser le patient nominatif ou l’agent ergatif en modifiant le verbe de verbe transitif à verbe intransitif via une inflexion de la racine dudit verbe.

**** Réciproque
La voix réciproque permet quant à elle d’exprimer une action à double-sens entre l’agent et le patient, promouvant ce dernier en agent de la phrase nominative ou l’agent en patient d’une phrase ergative. Cela perrmet ainsi d’ignorer le patient ou l’agent de la phrase selon le cas. Le réciproque à l’instar du réflexif se marque par une inflexion de la racine du verbe.

**** Causatif
Le causatif ajoute un argument au verbe : l’élémant causant l’événement. Dans la phrase « Tama a fait se lever le soldat », Tama est responsable du fait que le soldat se soit levé, ainsi le verbe gagnee l’aspect causatif en plus de son aspect réflexif.

*** Impersonnalité
# 1excl.singulier

** <<decl-morph-decl>>Déclinaisons
Suivant le rôle du nom dans la phrase, il est possible de le décliner à l’un des nombreux cas grammaticaux qu’offre le Hjalpi’. Dans cette section, j’expliquerai simplement la signification brève de chacune de ces déclinaisons. Pour un détail de comment décliner les noms, veuillez vous référer au [[decl-morph-decl][chapitre dédié]]. Je regrouperai ici les déclinaison par catégorie. Chaque cas sera présenté de la manières suivante :
- Cas grammatical (/ABBRÉVIATION/) :: définition
| morphologie |
Exemple en français
| exemple | en Hjalpi’  |
| détail  | grammatical |

Les déclinaisons se présentent sous la forme de particules (préfixes, infixes et suffixes) à ajouter au mot racine. Notez que la partie entre parenthèse peut ne pas être spécifiée, auquel cas il faudra se référer à l’harmonisation des voyelles ou des consonnes selon le cas si une voyelle est accolée à une autre voyelle, de même pour les consonnes.
- V(C)- :: le préfixe est (ou fini par) une voyelle V, il se rajoute donc au début du mot racine. Si ce dernier commence avec une voyelle, la consonne C est rajoutée entre la voyelle V et le mot racine.
- C(V)- :: le préfixe est (ou fini par) une consonne, il se rajoute donc au début du mot racine. Si ce dernier commence avec une consonne, la voyelle (V) est rajoutée entre la consonne C et le mot racine.
- -C_{1}V(C_{2})- :: l’infixe commence par consonne, il se placera donc à la fin du mot racine, entre la dernière voyelle et la dernière consonne du mot racine. Si le mot racine se termine par une voyelle, l’ensemble C_{1}VC_{2} agira comme un suffixe.
- -(C_{1})VC_{2}- :: l’infixe commence par une voyelle, il se placera donc au début du mot racine, entre la première consonne et la première voyelle. Si le mot racine commence par une voyelle, l’ensemble C_{1}VC_{2} agira comme un préfixe.
Notez que la déclinaison se produit avant l’accord en genre et en nombre de l’élément décliné, et après application de [[deriv-accord-voy][l’accord des voyelles]] et de [[deriv-accord-cons][l’accord des consonnes]] de l’élément. Notez également que la ou les voyelles présentée dans les tableaux s’accorde en ouverture et longueur avec la voyelle du mot racine sur laquelle porte l’accent. Ainsi, ajouts de voyelles sur /mén/ via des déclinaisons s’accorderont en voyelles longues et ouvertes. Si la juxtaposition de deux voyelles est obligatoire, se référer à [[deriv-accord-voy][l’accord des voyelles]] ci-dessus. Si la juxtaposition de deux consonnes est obligatoire, se référer à [[deriv-accord-cons][l’accord des consonnes]], idem pour [[deriv-accord-voy][l’accord des voyelles]].

Le nombre représente le [[morpho-nom-genre][genre]] de l’élément décliné, le /s/ et le /p/ représentent respectivement le super-singulier et le pluriel, comme décrits dans les [[morpho-nom-nombre][nombres des noms]].

*** Lieu
- <<cas-ade>>Cas adessif (/ADE/) :: indique un lieu adjacent à l’élément.
| 1s     | 1p     | 2s      | 2p     | 3s      | 3p     | 4s     | 4p      | 5s     | 5p      |
| ix(a)- | ix(e)- | ix(a)-  | ix(e)- | ix(a)-  | ix(e)- | iź(a)- | iź(ei)- | iź(a)- | iź(ei)- |
|        | 6s     | 6p      | 7s     | 7p      | 8s     | 8p     | 9s      | 9p     |         |
|        | iź(a)- | iź(ei)- | iź(a)- | iź(ei)- | iŗ(a)- | iŗ(a)- | iŗ(e)-  | iŗ(e)- |         |
Exemple : La rivière (majeure) est à côté des maisons.
| ándjo           | iŗménél               | reveanis                                      |
| rivière.majeure | ADE-maison-singulatif | être.certain.objectif-présent.indicatif.3s1SG |

- <<cas-ante>>Cas antessif (/ANTE/) :: indique un lieu antérieur à l’élément.
| 1s      | 1p     | 2s     | 2p     | 3s    | 3p    | 4s    | 4p     | 5s    | 5p    |
| vwo(n)- | vw(o)- | v(o)-  | vw(o)- | vwo-  | vo-   | we-   | w(e)-  | w(o)- | w(e)- |
|         | 6s     | 6p     | 7s     | 7p    | 8s    | 8p    | 9s     | 9p    |       |
|         | v(e)-  | v(wo)- | vw(o)- | v(u)- | v(u)- | v(u)- | vw(o)- | vu-   |       |
Exemple : vwomén (ANTE-maison) avant la maison / devant la maison

- <<cas-apu>>Cas apudessif (/APU/) :: indique un lieu à côté, proche de l’élément. L’élément n’est pas adjacent au lieu, auquel cas il faudrait utiliser le cas adessif.
| 1s    | 1p    | 2s    | 2p     | 3s     | 3p    | 4s     | 4p    | 5s    | 5p     |
| þ(e)- | ð(e)- | ð(e)- | ðe-    | þ(e)-  | ð(e)- | þe(n)- | þ(e)- | v(e)- | ve(n)- |
|       | 6s    | 6p    | 7s     | 7p     | 8s    | 8p     | 9s    | 9p    |        |
|       | þ(e)- | ð(e)- | ð(ei)- | ðe(m)- | f(e)- | fe-    | vei-  | fei-  |        |
Exemple : veimén (APU-maison) à côté de la maison

- <<cas-ine>>Cas inessif (/INE/) :: indique un lieu à l’intérieur de l’élément.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p      | 5s      | 5p   |
| -(a)ŕo- | -(e)ŕo- | -ŕo(n)- | -(ń)ŕo- | -(a)ŕo- | -ŕo-    | -(e)ŕo- | -(a)ŕo- | -(e)ŕo- | -ŕo- |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s      | 9p      |      |
|         | -ŕo-    | -(a)ŕo- | -(o)ŕo- | -(a)ŕo- | -(a)ŕo- | -(u)ŕo- | -(e)ŕo- | -(a)ŕo- |      |
Exemple : mérón (<INE>maison) dans la maison

- <<cas-intrt>>Cas intratif (/INTRT/) :: indique un lieu entre des éléments. L’élément décliné ne peut être singulier.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p      | 5s      | 5p      |
| -fu(þ)- | -fu(ð)- | -fu(ð)- | -fu(ð)- | -fy(þ)- | -fy(ð)- | -fu(þ)- | -fy-    | -fy(ð)- | -fy(ð)- |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s      | 9p      |         |
|         | -fu(ð)- | -þy(ð)- | -(f)yþ- | -fu-    | -fi(ŕ)- | -fe(ŕ)- | -fu(ð)- | -fu(þ)- |         |
Exemple : ménatĺ (maison.duel.INTRT) entre deux maisons.

- <<cas-loc>>Cas locatif (/LOC/) :: indique que l’élément décliné est le lieu indiqué (usage général).
| 1s    | 1p    | 2s    | 2p     | 3s     | 3p    | 4s    | 4p    | 5s     | 5p    |
| l(a)- | l(e)- | l(i)- | l(e)-  | le(þ)- | l(e)- | l(e)- | l(e)- | lj(a)- | l(a)- |
|       | 6s    | 6p    | 7s     | 7p     | 8s    | 8p    | 9s    | 9p     |       |
|       | ła-   | ł(a)- | l(au)- | l(ai)- | l(a)- | la-   | ĺ-    | l(e)-  |       |
Exemple : Il est à la maison (sans précision du lieu précis)
| òt       | ĺména          | neßòis                                         |
| 3s6G-ERG | LOC-maison-ABS | être.subjectif.certain-présent.indicatif.3s2SG |

- <<cas-pert>>Cas pertingent (/PERT/) :: indique un contact avec un lieu.
| 1s    | 1p     | 2s     | 2p    | 3s     | 3p     | 4s    | 4p    | 5s    | 5p    |
| m(a)- | m(a)-  | m(a)-  | m(e)- | mj(a)- | mj(e)- | m(e)- | m(e)- | m(a)- | m(e)- |
|       | 6s     | 6p     | 7s    | 7p     | 8s     | 8p    | 9s    | 9p    |       |
|       | mj(ò)- | mj(e)- | m(e)- | m(u)-  | m(a)-  | m(o)- | m(e)- | m(e)- |       |
Exemple : memén (PERT-maison) en contact avec la maison

- <<cas-poste>>Cas postessif (/POSTE/) :: indique un lieu postérieur à l’élément.
Exemple : ménýßt (maison-POSTE) après la maison.
| 1s    | 1p     | 2s    | 2p    | 3s    | 3p     | 4s    | 4p     | 5s     | 5p    |
| -(u)ß | -(u)ßt | -(y)ß | -(y)ž | -(u)š | -(u)št | -(u)š | -(u)ß  | -(u)ß  | -(u)þ |
|       | 6s     | 6p    | 7s    | 7p    | 8s     | 8p    | 9s     | 9p     |       |
|       | -(u)ž  | -(y)š | -(u)ß | -(u)ź | -(y)ź  | -(y)ž | -(y)tß | -(y)ßt |       |

- <<cas-sube>>Cas subessif (/SUBE/) :: indique un lieu sous l’élément.
| 1s    | 1p     | 2s    | 2p     | 3s    | 3p     | 4s     | 4p     | 5s    | 5p    |
| ň(o)- | ň(wo)- | n(o)- | n(wo)- | ň(o)- | ň(o)-  | nw(o)- | n(we)- | ň(e)- | ň(o)- |
|       | 6s     | 6p    | 7s     | 7p    | 8s     | 8p     | 9s     | 9p    |       |
|       | ne-    | ňe-   | ňe-    | ňo-   | nw(a)- | n(wa)- | n(a)-  | na-   |       |
Exemple : namén (SUBE-maison) sous la maison

- <<cas-supe>>Cas superessif (/SUPE/) :: indique un lieu sous l’élément.
| 1s     | 1p      | 2s      | 2p      | 3s      | 3p     | 4s     | 4p      | 5s     | 5p     |
| tß(a)- | tß(ań)- | tß(ai)- | tßau-   | tß(e)-  | tß(a)- | ßt(e)- | tß(ei)- | tß(e)- | št(a)- |
|        | 6s      | 6p      | 7s      | 7p      | 8s     | 8p     | 9s      | 9p     |        |
|        | ßt(a)-  | ßt(a)-  | tß(ao)- | tß(ae)- | tßa-   | ßta-   | ßt(e)-  | tß(a)- |        |
Exemple : ßtemén (SUPE-maison) sur la maison / sur le toit de la maison (impliqué)

*** Mouvement depuis un élément
- <<cas-abl>>Cas ablatif (/ABL/) :: indique un déplacement s’éloignant de l’élément.
| 1s    | 1p     | 2s     | 2p     | 3s     | 3p    | 4s     | 4p     | 5s     | 5p     |
| l(i)- | l(e)-  | li(s)- | le(ž)- | l(i)-  | ĺ(ž)- | li(ß)- | li(ź)- | li(ß)- | li(ź)- |
|       | 6s     | 6p     | 7s     | 7p     | 8s    | 8p     | 9s     | 9p     |        |
|       | li(s)- | li(z)- | lń(d)- | lń(d)- | ĺ(z)- | ĺ(z)-  | ĺ(v)-  | ĺ(v)-  |        |
Exemple : Je pars de Ðbńo. (décision motivée par moi-même)
| wyhakéís                      | liÐbńovu     | né       |
| quitter(NOM prés-indic 1s2SG) | ABL-Ðbńo-ACC | 1s6G.NOM |

- <<cas-del>>Cas délatif (/DEL/) :: déplacement depuis la surface de l’élément.
| 1s    | 1p    | 2s    | 2p     | 3s     | 3p    | 4s    | 4p     | 5s     | 5p    |
| ß(a)- | ß(e)- | ß(e)- | ß(e)-  | ß(ai)- | ß(a)- | š(a)- | š(e)-  | ž(a)-  | ž(e)- |
|       | 6s    | 6p    | 7s     | 7p     | 8s    | 8p    | 9s     | 9p     |       |
|       | ž(a)- | ž(a)- | ß(eu)- | ß(eu)- | ß(a)- | ß(a)- | ßa(l)- | ße(l)- |       |
Exemple : La mouche s’envola (volontairement) du livre (de l’extérieur du livre, sous entendu de sa couverture)
| proböléntí                      | ßaraòm    | paŗevir    |
| s’envoler-(NOM passé m p 3s3SG) | DEL-livre | NOM-mouche |

- <<cas-ela>>Cas élatif (/ELA/) :: déplacement depuis l’intérieur de l’élément.
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s    | 5p     |
| -(a)ły | -(e)ły | -(a)ły | -(a)łu | -(e)ły | -(e)ły | -(ł)y  | -(ł)y  | -(ł)y | -(ł)yi |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p    |        |
|        | -(ł)u  | -(ł)yi | -ły    | -(a)ły | -(ł)ay | -(ł)ey | -(ł)ay | -łay  |        |
Exemple : La mouche s’envola (volontairement) du livre (sous entendu depuis une page / l’intérieur du livre, le livré étant ouvert)
| proböléntí                      | raòmey    | paŗevir    |
| s’envoler-(NOM passé m p 3s3SG) | livre-ELA | NOM-mouche |

- <<cas-init>>Cas initiatif (/INIT/) :: indique le point de départ d’une action (cas général)
| 1s     | 1p    | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p      |
| -(a)kĺ | -(k)ĺ | -(e)kĺ | -(a)kĺ | -(k)ĺ  | -(k)ĺ  | -(e)kĺ | -(e)kń | -(a)kĺ | -(ei)kń |
|        | 6s    | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |         |
|        | -akĺ  | -ekĺ   | -(a)kĺ | -(e)kń | ak(ĺ)- | k(ń)-  | -(k)ĺ  | -(k)ń  |         |
Exemple : Je voyage depuis Ðbńo (sous-entendu, Ðbńo était de point de départ du voyage)
| etrjáléís                     | Ðbńokĺ    | né       |
| voyager(NOM prés-indic 1s2SG) | Ðbńo-INIT | 1s6G.NOM |

*** Mouvement vers un élément
- <<cas-all>>Cas allatif (/ALL/) :: indique un mouvement vers les environs de l’élément (cas général), n’indique pas nécessairement de finalité ou de point précis.
| 1s      | 1p       | 2s      | 2p      | 3s      | 3p       | 4s      | 4p      | 5s      | 5p      |
| -li(ß)- | -li(ts)- | -li(ð)- | -li(ð)- | -li-    | -li-     | -li(s)- | -li(ź)- | -li(z)- | -li(š)- |
|         | 6s       | 6p      | 7s      | 7p      | 8s       | 8p      | 9s      | 9p      |         |
|         | -li(x)-  | -li(x)- | -li(ŗ)- | -li(ŗ)- | -li(þt)- | -li(v)- | -(l)iþ- | -(l)ið- |         |
Exemple : Je voyage vers Ðbńo (sans nécessairement aller à Ðbńo même).
| etrjáléís                     | Ðbńoðil   | né       |
| voyager(NOM prés-indic 1s2SG) | Ðbńo<ALL> | 1s6G.NOM |

- <<cas-ill>>Cas illatif (/ILL/) :: mouvement vers l’intérieur de l’élément, n’indique pas nécessairement de finalité.
| 1s      | 1p       | 2s       | 2p      | 3s      | 3p      | 4s      | 4p      | 5s      | 5p      |
| -(p)òn- | -(p)on-  | -(f)òn-  | -(f)on- | -òn-    | -(p)òn- | -(s)òn- | -(s)en- | -(s)en- | -(s)an- |
|         | 6s       | 6p       | 7s      | 7p      | 8s      | 8p      | 9s      | 9p      |         |
|         | -(ps)òn- | -(ps)en- | -òn-    | -(v)òn- | -(ŕ)òn- | -(ŕ)òn- | -(ŕ)òn- | -(ŕ)en- |         |
Exemple : La mouche vole vers la maison (sous entendu, elle va y rentrer)
| eŕbölay                      | monén       | paŗevir    |
| voler-(NOM prés-indic 3s3SG) | <ILL>maison | NOM-mouche |

- <<cas-lat>>Cas latif (/LAT/) :: mouvement vers l’élément (cas général), n’indique pas nécessairement de finalité.
| 1s    | 1p     | 2s     | 2p     | 3s     | 3p    | 4s     | 4p     | 5s    | 5p  |
| -(l)a | -(l)ei | -(l)òĺ | -(l)e  | -(l)au | -(l)ĺ | -(l)ń  | -(l)a  | -(l)a | -le |
|       | 6s     | 6p     | 7s     | 7p     | 8s    | 8p     | 9s     | 9p    |     |
|       | -la    | -la    | -(a)la | -(e)la | -(l)e | -(l)ai | -(l)ae | -la   |     |
Exemple : Je pars de Notń pour Ðbńo.
| wyhakéís                      | liNotńvu     | Ðbńolòĺ  | né       |
| quitter(NOM prés-indic 1s2SG) | ABL-Notń-ACC | Ðbńo-LAT | 1s6G.NOM |

- <<cas-subl>>Cas sublatif (/SUBL/) :: mouvement vers la surface de l’élément.
| 1s | 1p    | 2s     | 2p    | 3s     | 3p     | 4s     | 4p     | 5s     | 5p     |        |
|    | -(i)ţ | -(i)ţ  | -(e)ţ | -(i)ḑ  | -(i)ţ  | -(i)nţ | -(i)fţ | -(i)þţ | -(e)nţ | -(eu)ţ |
|    | 6s    | 6p     | 7s    | 7p     | 8s     | 8p     | 9s     | 9p     |        |        |
|    | -(a)ţ | -(i)nţ | -(i)ţ | -(i)ßţ | -(i)šţ | -(i)ţ  | -(r)iţ | -iţ    |        |        |
Exemple : La mouche vole vers le livre. (sous-entendu, la couverture)
| eŕbölay                      | raòmiţ     | paŗevir    |
| voler-(NOM prés-indic 3s3SG) | livre-SUBL | NOM-mouche |

- <<cas-term>>Cas terminatif (/TERM/) :: le mouvement a pour but l’élément.
| 1s     | 1p      | 2s      | 2p      | 3s      | 3p     | 4s     | 4p     | 5s     | 5p   |
| -(ae)n | -(ae)ň  | -(þ)aen | -(ð)aen | -(þ)aeň | -(ae)m | -(ae)n | -aem   | -aeň   | -aem |
|        | 6s      | 6p      | 7s      | 7p      | 8s     | 8p     | 9s     | 9p     |      |
|        | -(ae)nz | ae(ň)-  | -(ae)n  | -(ae)n  | -(ae)m | -ae    | -(ai)n | -(ai)ň |      |
Exemple : Je voyage jusqu’à Ðbńo.
| etrjáléís                     | Ðbńoþaen  | né       |
| voyager(NOM prés-indic 1s2SG) | Ðbńo-TERM | 1s6G-NOM |

*** Déplacement via un élément
- <<cas-per>>Cas perlatif (/PER/) :: mouvement au travers ou le long de l’élément.
| 1s    | 1p     | 2s     | 2p    | 3s    | 3p    | 4s     | 4p     | 5s     | 5p     |
| ž(u)- | ž(y)-  | ž(u)-  | š(u)- | š(y)- | ž(u)- | š(ui)- | ž(ui)- | š(eu)- | š(ey)- |
|       | 6s     | 6p     | 7s    | 7p    | 8s    | 8p     | 9s     | 9p     |        |
|       | š(oy)- | ž(ou)- | ž(u)- | ž(e)- | ž(u)- | ž(u)-  | š(y)-  | ž(u)-  |        |
Exemple : Je voyage le long de la rivière.
| etrjáléís                     | šyłánt                 | né       |
| voyager(NOM prés-indic 1s2SG) | PERL-(rivière mineure) | 1s6G-NOM |

- <<cas-prol>>Cas prolatif (/PROL/) :: mouvement en utilisant l’élément ou sur sa surface.
| 1s    | 1p    | 2s    | 2p     | 3s    | 3p     | 4s    | 4p     | 5s    | 5p    |
| š(a)- | š(a)- | š(e)- | š(ae)- | ž(a)- | š(ay)- | ša-   | š(e)-  | š(e)- | ž(a)- |
|       | 6s    | 6p    | 7s     | 7p    | 8s     | 8p    | 9s     | 9p    |       |
|       | š(e)- | še-   | š(a)-  | šei-  | še-    | š(a)- | š(ey)- | ž(e)- |       |
Exemple : Je navigue sur l’océan côtier.
| ’elḑökay                       | šielt               | né       |
| naviguer(NOM prés-indic 1s2SG) | PROL-(océan côtier) | 1s6G-NOM |

*** Temps
- <<cas-atemp>>Cas accusatif-temporel (/ATEMP/) :: indication d’une durée de temps, peut remplacer l’accusatif d’une proposition nominative-accusative avec un verbe transitif.
| 1s  | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p      |
| -źu | -źu    | -źu    | -źu    | -źoy   | -źou   | -(a)źu | -(e)źu | -(u)źu | -(ai)źu |
|     | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |         |
|     | -(i)źu | -(u)źu | -(o)źu | -(o)źu | -(o)źu | -(o)źu | -(o)źu | -(o)źu |         |
Exemple : J’ai dormis sept heures.
| ’oherénté                    | heolí’            | pńtwánźu   | né       |
| dormir-(NOM passé m p 1s2SG) | heure(mesure)-GEN | sept-ATEMP | 1s6G-NOM |

- <<cas-ess>>Cas essif (/ESS/) :: l’élément indique la date où le moment où un événement se produit.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p        | 5s        | 5p      |
| -(þ)yd- | -(þ)yd- | -(þ)ud- | -(þ)ud- | -(þ)yd- | -(þ)ud- | -(þ)yḑ- | -(þ)yḑ-   | -(ð)yţ-   | -(ð)yţ- |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s        | 9p        |         |
|         | -(þ)ud- | -(þ)ud- | -þy(d)- | -þy(d)- | -þy(d)- | -þy(d)- | -(oi)þyd- | -(oi)þyd- |         |
Exemple : Je dors habituellement à sept heures.
| ’oheroméis                   | hebéómi’  | pudńtwán  | né       |
| dormir(NOM prés-habit 1s2SG) | heure-GEN | <ESS>sept | 1s6G-NOM |

- <<cas-limit>>Cas limitatif (/LIMIT/) :: l’élément indique une limite dans le temps.
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p     |
| -(ò)mp | -(e)mp | -(ò)mp | -(ò)mp | -(ò)mp | -(ò)mp | -(ò)mp | -(ò)mp | -(ò)mp | -(ò)mp |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |        |
|        | -(e)mp | -(ò)mp | -(a)mp | -(a)mp | -(a)mp | -(a)mp | -(ò)mp | -(ò)mp |        |
Exemple : Je dors habituellement jusqu’à sept heures.
| ’oheroméis                   | hebéómi’  | pńtwánòmp  | né       |
| dormir(NOM prés-habit 1s2SG) | heure-GEN | sept-LIMIT | 1s6G-NOM |

- <<cas-temp>>Cas temporel (/TEMP/) :: l’élément désigne un moment (cas général).
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p      | 5s    | 5p      |
| -(i)ňni | -(i)ňni | -(i)ňni | -(i)mi  | -(i)ňni | -(i)nji | -(y)ňni | -(ň)ne  | -eňni | -(i)mji |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s      | 9p    |         |
|         | -(i)ňni | -(iň)ni | -(i)ňni | -(i)ňni | -(e)ňni | -(i)ňni | -(y)ňni | -iňni |         |
Exemple : à sept heures
| hebéómi’  | pńtwániňni |
| heure-GEN | sept-TEMP  |

- <<cas-distemp>>Cas distributif-temporel (/DISTEMP/) :: Similaire au [[cas-distributif][cas distributif]], montrant une répétition temporelle se produisant à chaque élément temporel décliné.
| 1s  | 1p  | 2s  | 2p    | 3s  | 3p   | 4s     | 4p  | 5s  | 5p  |
| -be | -be | -ve | -be   | -va | -fe  | -be    | -ba | -ba | -ve |
|     | 6s  | 6p  | 7s    | 7p  | 8s   | 8p     | 9s  | 9p  |     |
|     | -ve | -va | -(b)e | -be | -bei | -(b)ei | -be | -be |     |

*** Alignement morphosyntaxique
- <<cas-abs>>Cas absolutif (/ABS/) :: indique le patient d’un verbe transitif ou le sujet d’un verbe intransitif dans une proposition ergative. S’oppose à l’[[cas-erg][ergatif]].
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s    | 4p    | 5s    | 5p    |
| -(ts)a | -(ts)a | -(tß)a | -(tß)a | -(ts)a | -(ts)a | -(t)a | -(š)a | -(p)a | -(v)a |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p    | 9s    | 9p    |       |
|        | -(st)a | -(ž)a  | -(r)a  | -(r)a  | -(x)a  | -(š)a | -(ŗ)a | -(ž)a |       |
Exemple : J’ai brisé le vase. (action sous-entendue comme involontaire)
| néí      | nweţuŗa  | kĺnéínté                    |
| 1s6G.ERG | vase-ABS | briser(ERG passé m p 1s2SG) |

- <<cas-acc>>Cas accusatif (/ACC/) :: indique le patient d’un verbe transitif dans une proposition nominative. S’oppose au nominatif.
| 1s  | 1p     | 2s     | 2p     | 3s     | 3p  | 4s     | 4p     | 5s     | 5p     |
| -vo | -vwo   | -vu    | -vwu   | -vo    | -vo | -(e)vo | -(e)vo | -(e)vo | -(e)vo |
|     | 6s     | 6p     | 7s     | 7p     | 8s  | 8p     | 9s     | 9p     |        |
|     | -(a)vo | -(a)vo | -(u)vo | -(u)vo | -vu | -vu    | -vy    | -vy    |        |
Exemple : J’ai brisé le vase. (action sous-entendue comme volontaire)
| kĺnénté                     | nweţuvy  | né       |
| briser(NOM passé m p 1s2SG) | vase-ACC | 1s6G.NOM |

- <<cas-erg>>Cas ergatif (/ERG/) :: indique l’agent d’un verbe transitif dans une proposition ergative. S’oppose à l’[[cas-abs][absolutif]]. Peut-être remplacé par le [[cas-peg][pégatif]].
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p     |
| -(u)jo | -(y)jo | -(í)jo | -(é)jo | -(u)jo | -(u)jo | -(ò)jo | -(y)jo | -(lj)o | -(lj)o |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |        |
|        | -(mj)o | -(lj)o | -jo    | -jo    | -(o)jo | -(e)jo | -(u)jo | -(u)jo |        |
Exemple : J’ai brisé le vase. (action sous-entendue comme involontaire)
| néí      | nweţuŗa  | kĺnéínté                          |
| 1s6G.ERG | vase-ABS | briser(ERG passé moy. pft. 1s2SG) |

- <<cas-instructive>>Cas instructif (/INSTRUCTIVE/) :: indique le moyen employé, répond à la question /comment ?/.
| 1s    | 1p     | 2s    | 2p  | 3s    | 3p     | 4s    | 4p    | 5s     | 5p    |
| -(e)ň | -(e)ň  | -(a)ň | -eň | -(e)ň | -(a)ň  | -(e)ň | -eň   | -aň    | -(e)ň |
|       | 6s     | 6p    | 7s  | 7p    | 8s     | 8p    | 9s    | 9p     |       |
|       | -(ea)ň | -(e)ň | -eň | -eňt  | -(e)ňz | -(e)ň | -(e)ň | -(e)ňt |       |
Exemple : J’ai brisé le vase en tombant. (comme je suis tombé, sous-entendu involontairement, j’ai brisé le vase)
| néí      | žybdinobyente                    | nweţuŗa  | kĺnéínté                          |
| 1s6G.ERG | tomber(ERG pas. moy. pft. 1s2SG) | vase-ABS | briser(ERG passé moy. pft. 1s2SG) |

- <<cas-instr>>Cas instrumental (/INSTR/) :: indique l’instrument utilisé, répond à la question /au moyen de quel objet ?/.
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s    | 5p  |
| -(d)ĺ | -(d)ĺ | -(d)ĺ | -(ḑ)ĺ | -(d)ĺ | -(ḑ)ĺ | -(d)ĺ | -(ţ)ĺ | -(d)ĺ | -ḑĺ |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p    |     |
|       | -(d)ĺ | -(d)ń | -(d)ĺ | -(d)ĺ | -(d)ń | -(ḑ)ń | -(d)ĺ | -(d)ĺ |     |
Exemple : J’ai brisé (involontairement) le vase avec mon pied (avec un coup de pied).
| néí      | pńtédń             | nweţuŗa  | kĺnéínté                          |
| 1s6G.ERG | pied.POSS-6s.INSTR | vase-ABS | briser(ERG passé moy. pft. 1s2SG) |

- <<cas-nomin>>Cas nominal (/NOMIN/) :: indique que l’élément décliné doit être considéré comme un nom dérivé de l’élément décliné, généralement traduisible à peu près par « /celui qui .../ ». Notez que le genre du resultat est le genre humain si ledit résultat décrit un humain, peu importe le genre d’origine, par défaut neutre.
| 1s     | 1p     | 2s     | 2p      | 3s      | 3p     | 4s     | 4p     | 5s      | 5p    |
| -(eu)s | -(eu)ß | -(eu)s | -(eu)ßt | -(eu)st | -(eu)s | -(eu)s | -(eo)ß | -eus    | -eušt |
|        | 6s     | 6p     | 7s      | 7p      | 8s     | 8p     | 9s     | 9p      |       |
|        | -eus   | -(eu)ß | -(eu)s  | -(eu)ß  | -(eu)s | -(ei)š | -(eu)s | -(eu)st |       |
Exemple : un cavalier (genre humain neutre) : naeleus (cheval-NOMIN)

- <<cas-nom>>Cas nominatif (/NOM/) :: indique le sujet d’un verbe intransitif ou l’agent d’un verbe transitif dans une proposition nominative. S’oppose à l’[[cas-acc][accusatif]]. Peut-être remplacé par le [[cas-peg][pégatif]].
| 1s    | 1p     | 2s    | 2p     | 3s     | 3p     | 4s     | 4p     | 5s  | 5p  |
| p(a)- | p(e)-  | p(a)- | p(e)-  | p(a)-  | p(a)-  | pa(n)- | pa(ń)- | pń- | pń- |
|       | 6s     | 6p    | 7s     | 7p     | 8s     | 8p     | 9s     | 9p  |     |
|       | pa(m)- | pa-   | pa(l)- | pa(l)- | pa(ß)- | pe(ß)- | pa-    | pa- |     |
Exemple : J’ai brisé le vase. (action sous-entendue comme volontaire)
| kĺnénté                     | nweţuvy  | né       |
| briser(NOM passé m p 1s2SG) | vase-ACC | 1s6G.NOM |

- <<cas-obl>>Cas oblique (/OBL/) :: marque le verbe, indique la proposition comme étant une citation. Les sous-propositions n’ont pas besoin d’être marquée. Remplace l’[[cas-acc][accusatif]] dans les propositions nominatives, et l’[[cas-abs][absolutif]] dans les propositions ergatives.
| 1s     | 1p      | 2s     | 2p      | 3s     | 3p     | 4s     | 4p      | 5s      | 5p     |
| -(ŗ)eß | -(ŗ)eßt | -(ŗ)ef | -(ŗ)eft | -(ŗ)eß | -(x)eß | -(ŗ)ef | -(ŗ)òß  | -(ŗ)ef  | -(ŗ)òß |
|        | 6s      | 6p     | 7s      | 7p     | 8s     | 8p     | 9s      | 9p      |        |
|        | -(ŗ)ef  | -(ŗ)òß | -(x)eß  | -(x)eß | -(x)eß | -(x)eß | -(x)uiß | -(x)oiß |        |
Exemple : j’ai dis que j’ai cassé (involontairement) le vase.
| ŗeðénté                   | kĺnéntéŗòß                  | nweţuŗa  | né       |
| dire(NOM passé m p 1s2SG) | briser(NOM passé m p 1s2SG) | vase-ACC | 1s6G.NOM |

- <<cas-peg>>Cas pégatif (/PEG/) :: Remplace le [[cas-nom][nominatif]] et l’[[cas-erg][ergatif]] dans une proposition ayant un argument datif.
| 1s  | 1p  | 2s  | 2p  | 3s  | 3p  | 4s  | 4p  | 5s  | 5p  |
| ey- | eu- | ey- | ey- | eu- | ei- | ey- | ei- | ei- | eu- |
|     | 6s  | 6p  | 7s  | 7p  | 8s  | 8p  | 9s  | 9p  |     |
|     | ey- | eu- | eu- | ey- | ey- | ey- | ei- | ey- |     |

*** Relation
- <<cas-evit>>Cas aversif (/EVIT/) :: indique que l’élément est évité ou craint.
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p  | 4s    | 4p    | 5s    | 5p    |
| ł(e)- | ł(e)- | ła-   | ł(e)- | ł(e)- | ła- | ł(e)- | ła-   | la-   | ł(e)- |
|       | 6s    | 6p    | 7s    | 7p    | 8s  | 8p    | 9s    | 9p    |       |
|       | ła-   | ł(e)- | ł(e)- | ł(e)- | ła- | l(e)- | ł(e)- | ł(e)- |       |
Exemple : Je navigue sur l’océan côtier tout en évitant Notń.
| ’elḑökay                       | łaNotń    | šielt               | né       |
| naviguer(NOM prés-indic 1s2SG) | EVIT-Notń | PROL-(océan côtier) | 1s6G-NOM |

- <<cas-ben>>Cas bénéfactif (/BEN/) :: indique la personne ou le concept motivant une proposition d’un verbe d’action. S’il est omis à la première personne, on assume que le bénéfacteur est le sujet ou l’agent ; à la seconde ou à la troisième personne, on assume que le bénéfacteur est inconnu.
| 1s  | 1p  | 2s     | 2p  | 3s  | 3p   | 4s  | 4p  | 5s  | 5p  |
| -at | -et | -at    | -at | -at | -aţ  | -at | -aţ | -aţ | -aţ |
|     | 6s  | 6p     | 7s  | 7p  | 8s   | 8p  | 9s  | 9p  |     |
|     | -et | -(v)et | -at | -et | -ast | -aþ | -at | -et |     |
Exemple : Je navigue sur l’océan côtier (l’action est motivée par ou due à Mérian).
| Merianaţ   | ’elḑökay                       | šielt               | né       |
| Merian-BEN | naviguer(NOM prés-indic 1s2SG) | PROL-(océan côtier) | 1s6G-NOM |

- <<cas-caus>>Cas causal :: indique la cause d’une proposition
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p     |
| -(o)by | -(o)bu | -(u)by | -(o)by | -(ob)y | -(b)y  | -(o)by | -(o)by | -(o)by | -(o)by |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |        |
|        | -(o)bu | -(o)bu | -(o)vu | -(e)vy | -(e)vy | -(e)vy | -vy    | -vy    |        |

- <<cas-com>>Cas comitatif (/COM/) :: indique un accompagnement par l’élément décliné, comparable au « avec » ou « et » en Français. L’action doit être partagée entre le sujet ou agent de la proposition et l’élément décliné, c’est à dire que l’élément est souvent un compagnon dans la situation (sans conotation positive ou négative).
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s       | 5p    |
| -ðai- | -ðei- | -ðei- | -ðai- | -ðei- | -ðey- | -ðeń- | -ðei- | -ðei(n)- | -ðey- |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p       |       |
|       | -ðei- | -ðey- | -ðei- | -ðei- | -ðeu- | -ðei- | -ðeu- | -ðeu-    |       |
Exemple : Je voyage le long de la rivière accompagné de Romur. (Romur et moi partageons l’expérience du voyage).
| etrjáléís                     | šyłánt                 | Romyðeńr   | né       |
| voyager(NOM prés-indic 1s2SG) | PERL-(rivière mineure) | <COM>Romyr | 1s6G-NOM |

- <<cas-dat>>Cas datif (/DAT/) :: élément recevant ou direction de l’action vers l’élément.
| 1s   | 1p   | 2s      | 2p   | 3s   | 3p    | 4s   | 4p   | 5s   | 5p   |
| -at- | -et- | -at-    | -at- | -at- | -aţ-  | -at- | -aţ- | -aţ- | -aţ- |
|      | 6s   | 6p      | 7s   | 7p   | 8s    | 8p   | 9s   | 9p   |      |
|      | -et- | -(v)et- | -at- | -et- | -ast- | -aþ- | -at- | -et- |      |
Exemple : Je crie (par colère) sur mon voisin.
| ţýbýmáý                     | ketipŕým    | né       |
| crier(NOM prés-indic 1s2SG) | <DAT>voisin | 1s6G-NOM |

- <<cas-distributif>>Cas Distributif (/DISTR/) :: Marque une distribution équitable entre les éléments déclinés. Comparable au cas [[cas-distemp][distributif-temporel]].
| 1s     | 1p     | 2s     | 2p      | 3s      | 3p      | 4s      | 4p     | 5s     | 5p     |
| xe(š)- | xe(l)- | xe(ž)- | xe(l)-  | ŗe(š)-  | ŗe(ž)-  | he(l)-  | he(l)- | he(l)- | he(l)- |
|        | 6s     | 6p     | 7s      | 7p      | 8s      | 8p      | 9s     | 9p     |        |
|        | ha(l)- | ha(l)- | hei(l)- | hea(l)- | hea(l)- | hea(l)- | še(l)- | še(l)- |        |

- <<cas-gen>>Cas génitif (/GEN/) :: montre une relation entre deux éléments, l’élément décliné définit l’élément situé immédiatement après. Attention, contrairement à certaines langues, le génitif de dénote pas la possession de l’élément ; pour cela, il faut utiliser le [[cas-poss][possessif]].
| 1s    | 1p     | 2s     | 2p    | 3s    | 3p     | 4s  | 4p    | 5s     | 5p  |
| ţ(y)- | ţ(u)-  | ţ(y)-  | ţ(y)- | ţ(y)- | ţ(yi)- | ţy- | ţy-   | ţy(i)- | ţy- |
|       | 6s     | 6p     | 7s    | 7p    | 8s     | 8p  | 9s    | 9p     |     |
|       | ţ(eu)- | ţo(y)- | ţy-   | ţ(u)- | ţ(u)-  | ţu- | ţ(y)- | ţ(u)-  |     |

- <<cas-poss>>Cas possessif (/POSS/) :: marque l’élément comme le propriétaire de l’élément suivant immédiatement l’élément décliné. Il n’est pas utile de décliner l’élément (voire même de placer l’élément dans la phrase) si l’élément propriété est également décliné avec les déclinaisons possessives.
| 1s  | 1p     | 2s     | 2p    | 3s     | 3p    | 4s   | 4p   | 5s     | 5p   |
| -ţy | -ţy    | -(i)ţy | -ţy   | -(eu)ţ | -(y)ţ | -eţy | -eţy | -(i)ţy | -oţy |
|     | 6s     | 6p     | 7s    | 7p     | 8s    | 8p   | 9s   | 9p     |      |
|     | -(e)uţ | -(o)iţ | -(ţ)y | -(e)ţy | -iţy  | -ţy  | -yţ  | -iţ    |      |

- <<cas-priv>>Cas privatif (/PRIV/) :: indique un manque ou une absence de l’élément décliné. Ce manque n’a aucune conotation positive ou négative.
| 1s  | 1p  | 2s  | 2p  | 3s  | 3p  | 4s  | 4p  | 5s   | 5p  |
| ei- | ei- | eń- | ež- | ei- | éĺ- | ei- | ae- | eiḑ- | ei- |
|     | 6s  | 6p  | 7s  | 7p  | 8s  | 8p  | 9s  | 9p   |     |
|     | ei- | ei- | ei- | ei- | ei- | ei- | eń- | eń-  |     |

- <<cas-sempl>>Cas semplatif (/SEMPL/) :: indique une similitude entre le sujet/expérienceur ou l’agent de la proposition et le ou les éléments déclinés.
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p     |
| -(ŗ)wo | -(ŗ)wo | -(ŗ)we | -(ŗ)wo | -(ŗ)wo | -ŗwo   | -ŗwe   | -(ŗ)wo | -ŗwo   | -(ŗ)wo |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |        |
|        | -ŗwo   | -ŗwe   | -(ŗ)wo | -(ŗ)wo | -(ŗ)we | -(ŗ)wo | -(ŗ)wo | -(ŗ)wo |        |

- <<cas-soc>>Cas sociatif (/SOC/) :: indique que la situation de la proposition s’est déroulée avec l’agent ou le sujet étant avec l’élément décliné. L’élément n’a pas à partager la situation avec l’agent/sujet.
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s    | 5p    |
| t(o)- | t(e)- | t(o)- | t(o)- | ţ(o)- | te-   | t(o)- | t(e)- | ţe-   | t(o)- |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p    |       |
|       | to-   | ţo-   | te-   | t(o)- | t(o)- | to-   | t(o)- | t(o)- |       |
Exemple : Je voyage le long de la rivière avec mes jumelles. (Les jumelles ne peuvent partager l’expérience dû au fait qu’elles soient inanimées et ne sont certainement pas mon moyen de voyage)
| etrjáléís                     | šyłánt                 | tovyelegot   | né       |
| voyager(NOM prés-indic 1s2SG) | PERL-(rivière mineure) | SOC-jumelles | 1s6G-NOM |

*** Sémantiques
- <<cas-ptv>>Cas partitif (/PTV/) :: s’utilise pour indiquer une quantité de l’élément donné s’il s’agit de désigner un sous-groupe, sans spécifier d’identité ou bien de marquer une partie uniquement de l’élément décliné.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p      | 5s       | 5p       |
| -’i(l)- | -’i(l)- | -’y(l)- | -’u(l)- | -’i(l)- | -’i(l)- | -’i(l)- | -’il-   | -’il(y)- | -ili(’)- |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s      | 9p       |          |
|         | -’i(ł)- | -’e(ł)- | -’i(l)- | -gi(l)- | -’i(l)- | -ki(l)- | -’i(l)- | -’i(l)-  |          |

- <<cas-voc>>Cas vocatif (/VOC/) :: permet de s’adresser à quelqu’un en déclinant l’expression ou le nom utilisé pour s’y adresser.
| 1s  | 1p  | 2s  | 2p  | 3s  | 3p     | 4s  | 4p  | 5s   | 5p     |
| -wa | -we | -wa | -wa | -we | -(d)wa | -wa | -ja | -je  | -v(w)e |
|     | 6s  | 6p  | 7s  | 7p  | 8s     | 8p  | 9s  | 9p   |        |
|     | -va | -ve | -wa | -wa | -wein  | -wa | -wa | -weŕ |        |

*** État
- <<cas-abe>>Cas abessif (/ABE/) :: signale l’abscence que quelque chose en particulier
| 1s    | 1p     | 2s     | 2p    | 3s    | 3p     | 4s     | 4p     | 5s     | 5p     |
| e(m)- | e(ň)-  | e(n)-  | e(n)- | e(l)- | e(dl)- | e(ň)-  | e(t)-  | e(st)- | e(ßt)- |
|       | 6s     | 6p     | 7s    | 7p    | 8s     | 8p     | 9s     | 9p     |        |
|       | e(nt)- | e(ňt)- | e-    | e(s)- | e-     | e(ňt)- | e(mt)- | e(ňt)- |        |

- <<cas-adv>>Cas adverbial (/ADV/) :: transforme un nom en adverbe
| 1s  | 1p  | 2s  | 2p  | 3s  | 3p  | 4s     | 4p     | 5s     | 5p  |
| -ei | -ey | -ei | -ei | -ey | -ey | -ei    | -ai    | -ai    | -ei |
|     | 6s  | 6p  | 7s  | 7p  | 8s  | 8p     | 9s     | 9p     |     |
|     | -eu | -ey | -ei | -ei | -ei | -(r)ei | -(ei)r | -(ey)r |     |

- <<cas-comp>>Cas comparatif (/COMP/) :: indique une similarité de l’élément décliné avec l’élément nominatif ou absolutif de la proposition.
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p  |
| -(oi)r | -(oi)r | -(oi)r | -(oi)ţ | -(oi)r | -(oi)t | -(oi)t | -(oi)ţ | -oir   | -er |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |     |
|        | -(oi)r | -oit   | -(oi)r | -(oi)r | -or    | -(oi)r | -oiŗ   | -(oi)ŗ |     |

- <<cas-equ>>Cas équatif (/EQU/) :: indique une comparaison entre l’élément décliné et l’élément nominatif ou absolutif de la proposition.
| 1s    | 1p    | 2s    | 2p    | 3s     | 3p     | 4s    | 4p    | 5s    | 5p    |
| -(ń)t | -(ń)t | -(ń)t | -(ĺ)t | -(ń)st | -(ń)ft | -(ń)t | -(ń)ḑ | -(ń)ţ | -(ń)t |
|       | 6s    | 6p    | 7s    | 7p     | 8s     | 8p    | 9s    | 9p    |       |
|       | -(ĺ)ḑ | -(ń)ţ | -(ń)t | -(ń)t  | -ńt    | -(ń)t | -(ń)t | -ńt   |       |

- <<cas-exe>>Cas exessif (/EXE/) :: Marque une transition de condition depuis l’élément décliné
| 1s  | 1p  | 2s  | 2p  | 3s    | 3p    | 4s  | 4p  | 5s  | 5p  |
| -ex | -ex | -eŗ | -ex | -ix   | -ex   | -ex | -eŕ | -ex | -aŗ |
|     | 6s  | 6p  | 7s  | 7p    | 8s    | 8p  | 9s  | 9p  |     |
|     | -ex | -eŗ | -ex | -(e)x | -(a)x | -ex | -eŕ | -ex |     |

- <<cas-ess-form>>Cas essif formel (/ESSF/) :: indique un état d’être temporaire, une condition qualitative physique
| 1s    | 1p    | 2s    | 2p    | 3s     | 3p    | 4s     | 4p     | 5s     | 5p  |
| -(ò)ţ | -(ò)d | -(o)d | -(o)ḑ | -(ò)d  | -(ò)ň | -(ţ)òd | -(ţ)ed | -(ţ)òd | -òd |
|       | 6s    | 6p    | 7s    | 7p     | 8s    | 8p     | 9s     | 9p     |     |
|       | -(ò)d | ò(d)- | -òd   | -(ò)ns | -òd   | -òts   | -(ò)ß  | -(ò)ßt |     |

- <<cas-ess-mod>>Cas essif modal (/ESSM/) :: indique un état d’être temporaire, une condition qualitative non-physique
| 1s      | 1p      | 2s     | 2p      | 3s     | 3p      | 4s      | 4p     | 5s     | 5p     |
| -(’)uix | -(’)uix | -’yiŗ  | -(’)yiŗ | -(’)uŗ | -(’)uiŗ | -(’)uŗ  | -(’)uŗ | -’u    | -(’)yŗ |
|         | 6s      | 6p     | 7s      | 7p     | 8s      | 8p      | 9s     | 9p     |        |
|         | -(’)yiŗ | -(’)yŗ | -(’)uŗ  | -(’)u  | -(’)u   | -(’)ust | -(’)uŗ | -(’)uŗ |        |

- <<cas-ide>>Cas identique (/IDE/) :: indique que l’élément décliné est identique (en certains points ou en totalité) avec l’élément nominatif ou absolutif de la proposition.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p     | 4s   | 4p      | 5s      | 5p      |
| -(e)tyr | -(a)tur | -(a)tyr | -(e)tur | -(e)tur | -tyr   | -tur | -(e)tur | -(a)tur | -(e)tur |
|         | 6s      | 6p      | 7s      | 7p      | 8s     | 8p   | 9s      | 9p      |         |
|         | -tyr    | -tyr    | -(e)tur | -(e)tur | -(t)ur | -tur | -(e)tur | -(o)tur |         |

- <<cas-ori>>Cas orientatif (/ORI/) :: indique une orientation d’un élément vers l’élément décliné.
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s    | 5p    |
| f(o)- | f(o)- | f(u)- | f(o)- | þ(o)- | f(o)- | f(o)- | v(o)- | þ(o)- | ð(o)- |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p    |       |
|       | þ(o)- | þo-   | f(o)- | f(u)- | f(o)- | vo-   | þo-   | fo-   |       |

- <<cas-transl>>Cas translatif (/TRANS/) :: indique un changement, une transition d’état vers l’élément décliné.
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s    | 5p    |
| -(i)n | -(i)n | -(y)n | -(e)n | -in   | -(i)n | -(i)n | -(y)m | -(i)ň | -(i)n |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p    |       |
|       | -(i)m | -(i)n | -(i)n | -(i)n | -in   | -iň   | -iň   | -iň   |       |



| 1s     | 1p     | 2s     | 2p      | 3s      | 3p     | 4s     | 4p     | 5s      | 5p    |
| -(eu)s | -(eu)ß | -(eu)s | -(eu)ßt | -(eu)st | -(eu)s | -(eu)s | -(eo)ß | -eus    | -eušt |
|        | 6s     | 6p     | 7s      | 7p      | 8s     | 8p     | 9s     | 9p      |       |
|        | -eus   | -(eu)ß | -(eu)s  | -(eu)ß  | -(eu)s | -(ei)š | -(eu)s | -(eu)st |       |

src_latex{\newpage}
** Formation d’un mot
** Conjonctions
** Chiffres et nombres
** Interjections
* Structure des phrases
** Phrase et ordre des mots
** Constructions de phrases complexes
** Constructions spéciales

src_latex{\newpage}
* <<glossaire>>Glossaire

- clef ::  /transcription large/ /élément de langage./ Définition(s)
Définition

Abréviations :
- 1-9 : numéro de genre (voir [[morpho-nom-genre][les genres]])
- adj. : adjectif
- ind. : indénombrable
- n.X : nom du Xème genre
- pron. : pronom
- vi. : verbe intransitif
- vt : verbe transitif

** À trier
- kipŕým :: (n.6) voisin
- ŗeðyþ :: (vt.) dire
- vyelegot :: (n.9) jumelles (instrument)

** Actions physiques
- kĺnyþ ::  /kl̩.nyːθ/ (vt.) casser, briser
- ţýbýmýþ ::  /ʈʏ.bʏ.mʏθ/ (vi.) crier par colère, par rage
- žybdinyþ ::  /ʐyːb.diː.nyːθ/ (vi.) tomber
- ’oheryþ ::  /?o:.he:.ry:þ/ (vi.) dormir
** Amour
** Animaux
- nael ::  /nael/ (n.7) cheval
- ŗevír ::  /ʁeː.vɪr/ (n.7) mouche
** Art
- raòm ::  /raøm/ (n.9) livre
** Astronomie
- <<glos-béóm>>béóm ::  /bɛɔm/ (n.1) Soleil. Étymologie : /[[glos-b%C3%A9m][bém]]/ + /[[gloss-jaom][jaom]]/, astre du jour
- <<gloss-jaom>>jaom ::  /jaom/ (n.1) astre
** Bâtiments
- mén ::  /mɛn/ (n.9) maison (bâtiment)
** Commerce
** Conflits
** Conteneurs
** Corps
- gar ::  /ɡaːr/ (n.6) tête
- <<glos-pńt>>pńt ::  /pn̩t/ (n.6) main
- <<glos-wán>>wán ::  /waːn/ (n.6) pied
** Couleurs
- <<glos-ðúr>>ðúr ::  /ðʊr/ (adj.) argent (couleur)
** Dimensions
** Direction
- ňam ::  /ŋaːm/ (n.2) ouest
- watßúd ::  /waːt.ʃʊd/ (n.2) nord
- wémšal ::  /wɛm.çaːl/ (n.2) est (direction)
- zelðeg ::  /zeːl.ðeːɡ/ (n.2) sud
** Eau
- ánd ::  /ɑnd/ (n.3) rivière majeure, cours d’eau dans lequel s’est jeté une autre rivière, mais ammenée à se jeter elle-même dans un autre cours d’eau
- hanḑ ::  /haːnɖ/ (n.3) fleuve mineur, cours d’eau n’ayant aucun confluent se jetant directement dans la mer ou l’océan
- ielt ::  /ielt/ (n.3) océan côtier, vaste étendue d’eau au contact des côtes
- łánt ::  /ɬɑt/ (n.3) rivière mineure ou ruisseau, cours d’eau dans lequel ne s’est jeté aucun autre cours d’eau mais ammené à se jeter dans un autre cours d’eau
- omd ::  /oːmd/ (n.3) océan non-côtier, vaste étendue d’eau n’étant pas au contact des côtes
- vilţ ::  /viːlʈ/ (n.3) fleuve majeur, cours d’eau ayant reçu d’autre cours d’eau et se jetant directement dans la mer ou l’océan
- ’élḑ ::  /ʔɛlɖ/ (n.3) mer, petite étendue d’eau connectée à d’autres mers ou océans, ou région d’océan côtier
** Effort
** Éléments
** Émotions
- feŗan ::  /feː.ʁaːn/ (n.2) tristesse
** Évaluation
- ’eßtef ::  /ʔeːʃ.teːf/ (adj.) mauvais
** Événements
- gén ::  /ɡɛn/ (n.2) acte, action
** Existence
- neßòm ::  /neːʃøːm/ (vt.) être (subjectif certain)
- revòm ::  /reːvøːm/ (vt.) être (objectif certain)
** Famille
- ánám ::  /ɑ.nɑm/ (n.6) parent
- mánám ::  /mɑ.nɑm/ (n.5) mère, maman
- pánám ::  /pɑ.nɑm/ (n.4) père, papa
** Forme
** Gouvernement
** Grammaire
- pöb ::  /pœb/ (pron. interrogatif) quoi, idée générale d’élément. Peut être décliné afin d’obtenir des questionnements plus précis.
*** Pronoms interrogatifs
**** Temps
- pejb ::  /pejb/ (pron. interr. essif) quand, à quel moment. /pöb/ décliné à l’essif.
- pöémp ::  /pœɛmp/ (pron. interrogatif limitatif) jusqu’à quand. /pöb/ décliné au limitatif.
- pövwó ::  /pœ.vwɔ/ (pron. interrogatif accusatif) sur quelle durée, pendent combien de temps. /pöb/ décliné à l’accusatif.

** Guerre
- wóúl ::  /wɔʊl/ (n.2) attaque
** Légal
** Lieux
** Lumière
** Mental
** Mesures
** Métaux
** Mouvement
- etrjálòm ::  /eːt.rjɑ.lʏθ/ (vi.) voyager
- eŕbölýþ ::  /eːɹ.bœ.lʏθ/ (vi.) voler (dans le airs)
- jĺšek ::  /jl̩.çeːk/ (n.9) chemin, voie
- probölýþ ::  /proː.bœ.lʏþ/ (vi.) s’envoler
Exemple : Proböléntí paŗevir. La mouche s’envola.
- wyhakòm ::  /wyː.haː.køːm/ (vt.) quitter, partir.
Exemple : Né liÐbńovu wyhakéís. Je pars de Ðbńo.
- ’elḑökýþ ::  /ʔeːlɖœkʏθ/ (vi.) naviguer
** Nature
** Nombres
- pńtwán ::  /pn̩twɑn/ (nbrc) sept. Étymologie : /[[glos-p%C5%84t][pńt]]/ + /[[glos-w%C3%A1n][wán]]/
** Nourriture
** Outils
** Parole
- vár ::  /vɑr/ (n.2) langue (linguistique), langage, parole
** Péchés
** Physique
** Possession
** Religion
- hjalp ::  /hjaːlp/ (n.1) dieu céleste
- melex ::  /meː.leːχ/ (n.1) dieu terrestre
** Savoir
- bóljòluþ ::  /bɔ.ljøː.luːθ/ (vt.) savoir
- wanmjöd ::  /waːn.mjœd/ savoir, connaissance
** Sensations
- feŗtef ::  /feːʁ.teːf/ (n.2) douleur mentale, dépression. Étymologie : /feŗan/ + /’eßtef/, une /tristesse mauvaise/
- núótöm ::  /nʊɔ.tœm/ (vt.) voir
** Sexe
** Société
** Substances
- lúb ::  /lʊb/ (n.9) air
** Temps
- <<glos-bém>>bém ::  /bɛm/ (n.2) jour (mesure de temps)
- hebéóm ::  /heːbɛɔm/ (n.2) heure (repère de temps). Étymologie : /[[glos-heol][heol]]/ + /[[glos-b%C3%A9%C3%B3m][béóm]]/ l’heure par le Soleil
- <<glos-heol>>heol ::  /heol/ (n.2) heure (mesure de temps)
- łail ::  /ɬail/ (n.2) année (mesure de temps)
- ţealnat ::  /ʈealnaːt/ (adj.) précision temporelle, précis.
*** Jours de la semaine
- ðúbém ::  /ðʊ.bɛm/ (n.2) septième jour de la semaine / jour d’agent. Étymologie : /[[glos-%C3%B0%C3%BAr][ðúr]]/ + /[[glos-b%C3%A9m][bém]]/
** Travail
** Végétaux
** Vêtements
** Vie et santé
- ðenmóíl ::  /ðeːn.mɔɪl/ (n.6) personne, individu
