#+TITLE: Grammaire du Hjalpi’
#+INCLUDE: "headers.org"

* Introduction
# Ajouter un peu de détails
Le Hjalpi’ est la langue parlée par les dieux dans l’univers de mon roman. La langue dont je présente ci-dessous la grammaire n’est cependant pas réellement la langue divine mais la représente ; en effet, le Hjalpi’ a été imaginée comme étant bien trop complexe pour être entièrement apprise par un humain, l’élaboration de phrases simples requière quelques années d’études déjà. Bien évidemment, il est impossible pour un humain de créer une telle langue, mais je reste toujours dans cette optique de création de langue complexe, et le résultat me paraîtra complexe mais il se peut que pour certains (du fait des langues qu’ils maîtrisent déjà) n’aient pas cette impression.

Cette langue sera également utilisée pour créer d’autres langues qui auront évolué depuis la langue divine en des langues (me paraissant) beaucoup plus simples afin de créer des langues pour les mortels.

* Phonologie
Dans cette ouvrage, j’utiliserai principalement la translittération des mots, expressions et phrases du Hjalpi’ pour illustrer mes propos, exemples et explications de la grammaire de cette langue. Toutefois, il est important de savoir comment correctement prononcer le Hjalpi’, et pour cela j’utiliserai l’alphabet phonétique international afin de retranscrire la prononciation correcte du Hjalpi’. Il est important de relever les deux styles différents de transcription phonétique qui seront utilisés dans cet ouvrage :
-  /transcription large/ :: ce type de transcription ne prend pas en compte les divers cas d’allophonie présents en Hjalpi’ et retranscrit individuellement chaque symbole ayant une signification phonétique dans son orthographe translittérée.
- [transcription rapprochée] :: ce style de transcription prend en compte les changements de prononciation dû aux modifications entre phonèmes. Cela représente donc la prononciation réelle des locuteurs, qui n’est pas représentée de manière exacte par la translittération du Hjalpi’.

Généralement, j’utiliserai la transcription large lorsque j’aurai besoin de transcrire de façon phonétique des éléments de langage, à moins que je souhaite que vous, le lecteur, portiez votre attention sur un élément particulier de la prononciation de la langue divine, auquel cas j’userai de la transcription rapprochée, comme lors de la discussion sur l’[[allophonie][allophonie]]. La prononciation des mots du [[glossaire][glossaire]] sera notée en transcription large.

** <<phon-voyelles>>Voyelles
Le Hjalpi’ dispose d’un inventaire de voyelle très large comparé à la majorité des langues existantes dans notre monde, avec dix-sept voyelles simples, et quelques autres diphtongues (discutées plus bas dans [[phon-diphtongues][Diphtongues]]). Voici la liste des voyelles utilisées dans le Hjalpi’ :

#+CAPTION: Voyelles du Hjalpi’
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | i / y       | u            |
|   | pré-fermées | í / ý       | ú            |
|   | mi-fermées  | e / ò       | o            |
|   | mi-ouvertes | é / ö       | ó            |
|   | ouvertes    | a           | á            |

Le Hjalpi’ dispose également de deux consonnes syllabiques, le /ń/ et le /ĺ/, qui sont respectivement le /n/ et le /l/ prononcés comme des voyelles. Voici ci-dessous le même tableau, avec chaque voyelle remplacée par sa valeur phonétique en IPA :

#+CAPTION: Voyelles du Hjalpi’ (IPA)
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | iː / yː     | uː           |
|   | pré-fermées | ɪ / ʏ       | ʊ            |
|   | mi-fermées  | eː / øː     | oː           |
|   | mi-ouvertes | ɛ / œ       | ɔ            |
|   | ouvertes    | aː          | ɑ            |



Avec le /ń/ et le /ĺ/ ayant respectivement pour valeur /n̩/ et /l̩/.

On peut remarquer que, à l’exception de /ń/ et /ĺ/, toutes les voyelles ont un couple ouverte-courte/fermée-longue. Dans les mots racine (c’est à dire non altérés par une quelconque règle grammaticale), la distinction revêt une importance capitale, porteuse de sens et de distinction de certains mots entre eux. Ainsi, /þran/ [θrãː] n’aura pas la même signification que /þrán/  [θrɑ̃] (pour l’explication de la prononciation, voir [[allophonie][l’allophonie]]). En revanche, comme on le verra plus tard, les addition grammaticales verront leurs voyelles s’accorder avec les voyelles du mot racine en ouverture-longueur.

*** Voyelles courtes

-  /ɑ/ : á
Le /á/ est une voyelle ressemblant au « â » que l’on retrouve en français dans des mots tels que « pâte ». Il s’agit de la voyelle ouverte antérieure non-arrondie.

-  /œ/ : ö
Il s’agit ici du son « eu » tel qu’on le retrouve en français tel que dans le mot « neuf ».

-  /ɪ/ : í
Cette voyelle est une voyelle se situant entre le son « i » et le son « e » ; on peut le retrouver en anglais dans des mots tels que « hit » ou « this ». Il s’agit de la voyelle pré-fermée antérieure non-arrondie.

-  /ɛ/ : é
Nous avons ici la voyelle « è » que l’on retrouve en français par exemple dans le mot « cette ».

-  /ɔ/ : ó
Il s’agit du « o » ouvert, que l’on retrouve en français dans le mot « sort » par exemple.

-  /ʏ/ : ý
Cette voyelle est un équivalent du « u » français ouvert, que l’on peut retrouver en Allemand comme dans « Müller » par exemple. Il s’agit de la voyelle antérieure pré-fermée arrondie.

-  /ʊ/ : ú
Cette voyelle est un équivalent du « ou » Français ouvert, telle que l’on peut la retrouver dans le mot « book » en Anglais britannique.

*** Voyelles longues
-  /aː/ : a
Cette voyelle est le « a » que l’on peut retrouver dans le français tel que dans « patte », à la différence que le « a » de le Hjalpi’ est prononcé un peu plus longuement que le « a » français.

-  /øː/ : ò
Cette voyelle est la même que le « eu » français que l’on retrouve dans le mot « deux », à la différence que le « ò » divin est prononcé un peu plus longuement que le « eu » français.

-  /iː/ : i
Cette voyelle est la même que le « i » français, à la différence que le « i » de le Hjalpi’ est prononcé un peu plus longuement que le « i » français.

-  /eː/ : e
Cette voyelle est la même que le « é » français, à la différence que le « i » de le Hjalpi’ est prononcé un peu plus longuement que le « i » français.

-  /oː/ : o
Cette voyelle est la même que le « o » français comme dans « eau », à la différence que le « o » de le Hjalpi’ est prononcé un peu plus longuement que le « o » français.

-  /yː/ : y
Cette voyelle est la même que le « u » français, à la différence que le « u » de le Hjalpi’ est prononcé un peu plus longuement que le « u » français.

-  /uː/ : u
Cette voyelle est la même que le « ou » français, à la différence que le « ou » de le Hjalpi’ est prononcé un peu plus longuement que le « ou » français.

*** <<cons-syll>>Consonnes syllabiques
-  /n̩/ : ń
Le « ń » est la consonne « n » (la même que le « n » standard français), mais considérée et prononcée comme une voyelle, tel qu’on peut l’entendre dans certains mots anglais comme dans « button » qui peut être prononcé  /bʌtn̩/.

-  /l̩/ : ĺ
Le « ĺ » est la consonne « l » (la même que le « l » français), mais considérée et prononcée comme une voyelle, tel qu’on peut l’entendre dans certains mots anglais comme dans « bottle » qui peut être prononcé  /bɔtl̩/, avec le /ʊ/ qui est omis et le  /l/ devenant syllabique.

*** <<phon-diphtongues>>Diphtongues

** <<phon-consonnes>>Consonnes
En plus d’un important inventaire de voyelle, le Hjalpi’ dispose également d’un inventaire de consonnes assez important. Voici ci-dessous lesdites consonnes :

#+CAPTION: Consonnes du Hjalpi’
| / | >             | >      | >          | >     | >    | >         | >      | >      | >       | >        | >       |
|   |               | bilab. | lab.-dent. | dent. | alv. | pal.-alv. | rétro. | palat. | vélaire | uvulaire | glottal |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | nasal         | m      |            |       | n    |           |        |        | ň       |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | occlusif      | p b    |            |       | t d  |           | ţ ḑ    |        | k g     |          | '       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | fricatif      |        | f v        | þ ð   | s z  | ß ź       |        | š ž    |         | x ŗ      | h       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | spirante      |        |            |       | ŕ    |           |        | j      |         |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | roulé         |        |            |       | r    |           |        |        |         |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | fric.-lat.    |        |            |       | ł    |           |        |        |         |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | spir.-lat.    |        |            |       | l    |           |        |        |         |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | semi-voyelles | w      |            |       |      |           |        |        |         |          |         |

#+CAPTION: Consonnes du Hjalpi’ (IPA)
| / | >             | >      | >          | >     | >    | >         | >      | >      | >       | >        | >       |
|   |               | bilab. | lab.-dent. | dent. | alv. | pal.-alv. | rétro. | palat. | vélaire | uvulaire | glottal |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | nasal         | m      |            |       | n    |           |        |        | ŋ       |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | occlusif      | p  b   |            |       | t  d |           | ʈ  ɖ   |        | k  ɡ    |          | ʔ       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | fricatif      |        | f   v      | θ  ð  | s  z | ʃ ʒ       |        | ç  ʝ   |         | χ   ʁ    | h       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | spirante      |        |            |       | ɹ    |           |        | j      |         |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | roulé         |        |            |       | r    |           |        |        |         |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | fric.-lat.    |        |            |       | ɬ    |           |        |        |         |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | spir.-lat.    |        |            |       | l    |           |        |        |         |          |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+----------+---------|
|   | semi-voyelles | w      |            |       |      |           |        |        |         |          |         |

** Accentuation
# Ajouter des exemples
L’accentuation des mots en langue divine porte sur l’avant-dernière voyelle racine si le mot racine dispose de deux syllabes ou plus, sur la voyelle racine unique sinon. L’accentuation des mots étant régulière, elle n’est pas marquée par l’orthographe et la translittération de la langue.
Pour ce qui est de l’accentuation des phrases, le ton est généralement tombant, avec le terme que le locuteur estime le plus important de la phrase bénéficiant d’une remontée du ton sur ce terme précisément. Si le locuteur estime que le terme est très important, alors il peut même le prononcer avec une voix de tête, voire étirer de manière exagérée la première syllabe racine du terme. Un verbe interrogatif bénéficie nécessairement de la remontée du ton de la phrase sur ce terme, tandis qu’une phrase exclamative voit son ton recommencer à descendre à partir de la même hauteur que celle du début de phrase. Une phrase affirmative continue la descente de ton jusqu’à la dernière syllabe racine qui bénéficie d’une accentuation.

** Romanisation et translittération
# Ajouter des exemples
La romanisation et la translittération d’une langue sont deux choses très différentes ; en effet, la première a pour but de représenter de façon grossière la prononciation de la langue avec l’alphabet latin, sans se soucier de l’orthographe exacte, tandis que la translittération a pour but de reproduire de manière précise l’orthographe de la langue transcrite, sans se soucier de savoir si le lecteur saura prononcer correctement la transcription s’il n’a pas été initié avant à la langue transcrite.

Pour moi le meilleur exemple que je puisse donner pour ce qui est de la différence entre romanisation et translittération est en Tibétain. Nous avons des termes Tibétain romanisés “dorje”, “chorten” ou encore “yak” en anglais dont une de leur translittération possible respective est “rdo rje”, “mchod brten” et “gyag”. Bien évidemment, toute personne n’ayant aucune notion de translittération du Tibétain et/ou de son orthographe peut être confuse quant à ce qu’ils viennent de lire, et c’est tout naturel : leur but est de savoir précisément comment écrire ces mots, et une personne sachant écrire en tibétain pourra, en ayant lu ces exemples, écrire les mots sans faute si je n’en ai pas fait non plus à la rédaction de cet ouvrage. Comme je l’ai indiqué, il s’agit dans cet exemple d’une romanisation anglophone ; en effet, la romanisation dépend de la langue du lecteur. Étant donné que ce dernier doit pouvoir se forger une idée de la prononciation du mot étranger, il faut utiliser les conventions de lecture de l’alphabet de sa propre langue afin d’approcher au mieux la prononciation originale. Ainsi, “dorje” en anglais pourrait être écrit « dordjé » en français, “chorten” pourrait être écrit « tchortène » (« yak » garde la même orthographe dans les deux langues, et est même dans les dictionnaires anglophones et francophones).

Ainsi, dans mon (ou mes ?) livre(s ?) qui s’adressera (s’adresseront ?) à un public général, j’utiliserai des romanisation de la langue divine si je souhaite que le lecteur ait une idée de la prononciation du mot ou de la phrase qu’il vient de rencontrer –et à l’inverse, si je souhaite être plus graphique, j’utiliserai soit la translittération, soit l’écriture native du Hjalpi’. Toujours est-il que dans cette référence grammaticale, je n’utiliserai que de la translittération (les graphèmes et lettres correspondantes furent décrites dans [[phon-consonnes][Consonnes]] et [[phon-voyelles][Voyelles]]), et ne ferai usage de la romanisation que dans ce chapitre où j’explique ci-dessous le processus de l’écriture du Hjalpi en romanisation.

Voici ci-dessous un tableau avec chaque phonème du Hjalpi’, sa translittération, et sa romanisation francophone. Pour un équivalent anglophone, se référer à la version anglophone de cet ouvrage si cette dernière existe.

#+CAPTION: Translittération des voyelles du Hjalpi’
| / | >       | >      |      |
|   | phonème | trans. | rom. |
|---+---------+--------+------|
|   | iː      | i      | i    |
|   | yː      | y      | u    |
|   | uː      | u      | ou   |
|   | ɪ       | í      | i    |
|   | ʏ       | ý      | u    |
|   | ʊ       | ú      | ou   |
|   | eː      | e      | é    |
|   | øː      | ò      | e    |
|   | oː      | o      | o    |
|   | ɛ       | é      | è    |
|   | œ       | ö      | eu   |
|   | ɔ       | ó      | au   |
|   | aː      | a      | a    |
|   | ɑ       | á      | a    |

#+CAPTION: Translittération des consonnes du Hjalpi’
| / | >       | >      |      | <> | >       | >      |      |
|   | phonème | trans. | rom. |    | phonème | trans. | rom. |
|---+---------+--------+------+----+---------+--------+------|
|   | p       | p      | p    |    | b       | b      | b    |
|   | t       | t      | t    |    | d       | d      | d    |
|   | ʈ       | ţ      | tr   |    | ɖ       | ḑ      | dr   |
|   | k       | k      | k    |    | ɡ       | g      | g    |
|   | f       | f      | f    |    | v       | v      | v    |
|   | θ       | þ      | th   |    | ð       | ð      | dh   |
|   | s       | s      | s    |    | z       | z      | z    |
|   | ʃ       | ß      | sh   |    | ʒ       | ź      | j    |
|   | ç       | š      | sh   |    | ʝ       | ž      | jh   |
|   | m       | m      | m    |    | n       | n      | n    |
|   | ŋ       | ň      | ng   |    | ʔ       | ’      | ’    |
|   | r       | r      | r    |    | h       | h      | h    |
|   | χ       | x      | rh   |    | ʁ       | r      | r    |
|   | ɬ       | ł      | lh   |    | ɹ       | r      | r    |
|   | l       | l      | l    |    | j       | j      | y    |
|   | w       | w      | w    |    |         |        |      |

* Phonologie dérivationnelle
Le Hjalpi’ est une langue riche en dérivation phonétiques du fait de sa grammaire agglutinative et fusionnelle. Les noms changent selon leur nombre, leur rôle au sein de la phrase (leur cas grammatical), les verbes s’accordent en genre et en nombre, selon l’objectivité, le mode ou l’un des nombreux temps de la phrase ou de la proposition. L’utilisation de chacun de ces éléments sera traité dans le chapitre traitant de la [[*Syntaxe][syntaxe]]. Le chapitre actuel servira principalement de référence condensée pour savoir comment accorder les divers éléments entre eux.

Ci-dessous se trouve une liste d’abréviations que l’on trouvera souvent dans les règles formelles :
- ~C~ = consonne
- ~V~ = voyelle
- ~N~ = nasale
- ~F~ = fricative
- ~P~ = consonne labiale
- ~L~ = voyelle longue
- ~S~ = voyelle courte
- ~#~ = limite d’un mot
- ~Ø~ = silencieux, muet, rien

** <<allophonie>>Allophonie

En Hjalpi’, il existe de nombreuses règles sur la modification de prononciation de phonèmes selon leur emplacement au sein d’un mot et leur environnement phonétique, donnant lieu à des allophones desdits phonèmes. Ces règles sont les dernières règles à s’appliquer sur la modification de prononciation des mots, les autres règles comme les [[deriv-accord-voy][accords des voyelles]] ou les [[deriv-accord-cons][accords des consonnes]] s’appliquant avant les règles d’allophonie. Ces règles s’appliquent dans leur ordre d’apparition ci-dessous.

*** Voyelles
Il existe relativement peu d’allophones parmi les voyelles de le Hjalpi’, cependant on peut en relever certains comme suit :
- La prononciation standard du « ń », comme mentionné ci-dessus dans [[cons-syll][Consonnes syllabiques]], est /n̩/. Cependant, cette voyelle peut également être prononcée /m̩/ si le /ń/ est précédé et/ou suivi par une consonne bilabiale, et il peut être palatalisé en /ɲ̩/ ou /m̩ʲ/ si le /ń/ est également adjacent à une des voyelles /i/ ou /í/, ou bien la consonne /j/ (notées ~I~).
 -  /n̩/ > [m̩] / _P
 -  /n̩/ > [m̩] / P_
 -  /n̩/ > [ɲ̩] / _I
 -  /n̩/ > [ɲ̩] / I_
 -  /n̩/ > [m̩ʲ] / P_ I
 -  /n̩/ > [m̩ʲ] / I_ P
- Le « ĺ » peut également être palatalisé en cas d’adjacence à une des voyelles /i/ ou /í/ ou bien la consonne /j/, et donc être prononcée /l̩ʲ/.
 -  /l̩/ > [l̩ʲ] / _I
- Une voyelle ou un groupe de voyelles placé devant une consonne nasale se nasalise.
 - V > [+nasal] / _N

*** Consonnes
Plusieurs de ces consonnes disposent d’allophones, c’est à dire de prononciations alternatives à la prononciation exacte mentionnée plus haut, sans que cela n’affecte le sens des mots ou le sens d’une phrase.
- La prononciation standard du /f/ et /v/ sont respectivement ~/f/~ et ~/v/~, cependant il arrive également qu’ils soient respectivement prononcés ~/p\/~ et ~/B/~ entre deux voyelles, ou en début de mot si immédiatement suivis d’une voyelle ou d’une semi-consonne (également notée ~V~).
 -  /f/ > [ɸ] / #_ V
 -  /f/ > [ɸ] / V_ V
 -  /v/ > [β] / #_ V
 -  /v/ > [β] / V_ V
- Le  /ɦ/ est considéré comme étant un allophone du  /h/. Cet allophone se produit entre deux voyelles, en début de mot immédiatement suivit d’une voyelle, entre une consonne voisée et une voyelle, ou une voyelle et une consonne voisée. En revanche, au contact du /i/, /í/ ou /j/ (notés ~I~), le  /h/ se palatalise en un  /ç/. Similairement, un  /ɦ/ obtenu grâce au premières règles ci-dessous change en  /ʝ/.
 -  /h/ > [ɦ] / #_ V
 -  /h/ > [ɦ] / V_ V
 -  /h/ > [ç] / _I
 -  /h/ > [ç] / I_
 -  [ɦ] > [ʝ] / _I
 -  [ɦ] > [ʝ] / I_
- Le /ŗ/ a pour prononciation standard le /ʁ/, cependant il est généralement prononcé /ʀ/ entre deux voyelles et/ou consonne voisée (notées ~V~).
 -  /ʁ/ > [ʀ] / V_ V
- Le /x/ est habituellement prononcé /χ/, cependant il est prononcé /x/ lorsqu’il est en contact avec une consonne fricative sourde (notée ~FS~).
 -  /χ/ > [x] / FS_
 -  /χ/ > [x] / _FS
- Une consonne nasale devient silencieuse si elle est précédée d’une voyelle et suivie d’une consonne ou d’un silence. Cela fait suite à la nasalisation de la voyelle précédente.
 - N > Ø / V_ #
 - N > Ø / V_ C
- Si deux consonnes fricatives toutes deux voisées ou sourdes se suivent successivement, même entre deux mots distincts, la première fricative devient silencieuse.
 - F > Ø / _F
- Si une consonne fricative voisée (notée ~FV~) est précédée par une fricative sourde (notée ~FS~), elle devient elle-même sourde. À l’inverse, si une fricative sourde est précédée par une fricative voisée, la première devient également voisée.
 - FS > [+voisée] / FV_
 - FV > [+sourde] / FS_

*** Exemples

- raòm ::  /raøm/ est prononcé [rãø̃]

** <<deriv-accord-voy>>Accord des voyelles

L’accord des voyelles a lieu principalement lors de la déclinaison d’un nom ou de la conjugaison d’un verbe, lors d’un cas où la juxtaposition d’une voyelle à une autre est obligatoire. Cela donne alors lieu à un accord des voyelles.

1. Les deux voyelles sont fusionnées en une diphtongue.
2. Si l’un des deux phonèmes est une consonne syllabique /ń/ ou /ĺ/, alors celle-ci reste inchangée.
3. Si la première voyelle est une diphtongue, alors le second phonème est remplacé par la seconde voyelle après que cette dernière ait été accordée en longueur à la longueur de premier phonème de la diphtongue.
4. Si la seconde voyelle était également une diphtongue, alors elle perd son second phonème.
5. Si le second phonème de la diphtongue est plus ouvert que le premier, alors il est refermé afin d’être au moins aussi fermé que le premier phonème.
6. Si le premier phonème de la diphtongue est une voyelle antérieure, alors elle devient son équivalent phonétique postérieur selon la table suivante :
| / | >                 |                 |
|   | phonème d’origine | nouveau phonème |
|---+-------------------+-----------------|
|   | u                 | y               |
|   | ú                 | ý               |
|   | o                 | ò               |
|   | ó                 | ö               |
|   | á                 | a               |

** <<deriv-accord-cons>>Accord des consonnes
** Phonotaxes
*** Attaque
*** Rime
**** Noyau syllabique
**** Coda

* Morphologie
** Noms
*** <<morpho-nom-genre>>Genre
Le Hjalpi’ est une langue riche en genres grammaticaux, étant donné qu’elle dispose de *neuf genres* différents
1. Genre divin : se réfère à toute personne considérée comme divine, que ce soit par les Divins ou par les mortels (humains comme non humains). Aucune distinction n’est faite selon leur sexe biologique. Les méduses, du fait d’être une icône divine, sont considérées étant également du genre divin. Il se réfère également à ce qui fait partie de leur domaine, que ce soit leurs Demeures ou leurs Œuvres majeures, tels que les Tours ou le Temps.
2. Genre mental : se réfère à tout élément non physique ou concept, comme des pensées ou des couleurs. Les lieux physiques et temporels sont également classifiés dans le genre mental. Bien que le temps en lui-même soit considéré comme étant du genre divin, les événements sont considérés comme étant des éléments mentaux.
3. Genre liquide : se réfère, comme son nom l’indique, à tout liquide, et en particulier à l’eau, mais ne couvre pas tous les fluides ; par exemple, l’air n’est pas considéré comme un liquide, malgré le fait que ce soit un fluide.
4. Genre masculin humain : se réfère à tout être humain ou semi-humain mâle, ou à un groupe à prédominance numérique ou de puissance masculine.
5. Genre féminin humain : se réfère à tout être humain ou semi-humain femelle, ou à un groupe à prédominance numérique ou de puissance féminine.
6. Genre neutre humain : se réfère à tout être humain ou semi-humain dont on ne connaît pas le sexe biologique, ou si un groupe n’a pas de prédominance numérique ou de puissance masculine ou féminine.
7. Genre animal : se réfère à tout être mortel n’étant pas un humain ou semi-humain et étant animé.
8. Genre végétal : se réfère à tout être mortel n’étant pas un humain ou semi-humain, ou membre d’animaux.
9. Genre inanimé : se réfère à tout être non-vivant n’étant pas inclus par les trois premiers genres.

Le genre est inclus sémantiquement dans chaque nom commun du Hjalpi’, en revanche la majorité des éléments rattachés au nom s’accorderont en genre, ainsi que les verbes suivant si le nom influe la conjugaison du verbe.

Le Hjalpi’ dispose également de *quatre sur-genres*, regroupant les genres en catégories qui sont utilisées dans certains contexte, comme pour la déclinaison ou la conjugaison des verbes.
1. Le sur-genre supérieur : rassemble les genres divin et mental
2. Le sur-genre humain : rassemble les genres humains (masculin, féminin et neutre)
3. Le sur-genre vivant : rassemble les genres du vivant non-humain (animal et végétal)
4. Le sur-genre inanimé : rassemble les genres liquide et inanimé

Une déclinaison des éléments humains neutres est possible, auquel cas on peut décliner ainsi l’élément dont on souhaite changer le genre :
| / | >        |             |
|   | genre    | déclinaison |
|---+----------+-------------|
|   | masculin | -e          |
|   | féminin  | -am         |

Ce genre de déclinaison est en général utilisé pour les mots se référant à un être humain dont le genre syntaxique est neutre, mais que l’humain référé est d’un genre connu. Par exemple, si l’on parle de plusieurs personnes de nombre inconnu (donc singulatif, voir les [[morpho-nom-nombre][Nombres]]) mais que la majorité des individus est de genre féminin, alors on déclinera /ðenmóíl/ (individu/personne) en /ðenmóílelam/ (personne.sf.5g). La déclinaison en féminin s’affixe à la déclinaison au singulatif du fait qu’il s’agit du groupe qui prend le genre féminin, indiquant que le groupe n’est pas uniquement mais majoritairement féminin. Si le groupe n’est composé que de femmes, alors /ðenmóíl/ se déclinera en /ðenmóílamel/ (personne.5g.sf).

*** <<morpho-nom-nombre>>Nombre
En plus d’avoir une riche quantité de genres, le Hjalpi’ dispose également de cinq nombres distincts qui se marquent par une déclinaison du nom ou de l’élément accordé en nombre (hormis le verbe).

| / | >          | >           |                                    |
|   | nombre     | déclinaison | description                        |
|---+------------+-------------+------------------------------------|
|   | singulier  | (aucune)    | élément unique                     |
|   | singulatif | -el         | ensemble d’éléments semblables     |
|   | duel       | -(a)t       | deux éléments semblables           |
|   | triel      | -(e)þ       | trois éléments semblables          |
|   | pluriel    | -(o)st      | quatre éléments semblables ou plus |

Le singulatif, comme décrit ci-dessus, est utilisé pour regrouper des éléments semblables et est une alternative au singulier ou pluriel dans le cas où l’élément dont il est question est indénombrable ou éligible au pluriel mais le locuteur n’a pas d’idée précise du nombre d’éléments présents dans le groupe.

Pour des raisons grammaticales il existe également un sur-nombre, le /super-singulier/ qui regroupe tous les nombres qui ne sont pas le pluriel. Le super-singulier est utile notamment pour les différentes déclinaisons possibles.

*** <<decl-morph-decl>>Déclinaisons

Les déclinaisons se présentent sous la forme de particules (préfixes, infixes et suffixes) à ajouter au mot racine. Voici un exemple d’utilisation. Notez que la partie entre parenthèse peut ne pas être spécifiée, auquel cas il faudra se référer à l’harmonisation des voyelles ou des consonnes selon le cas si une voyelle est accolée à une autre voyelle, de même pour les consonnes.
- V(C)- :: le préfixe est (ou fini par) une voyelle V, il se rajoute donc au début du mot racine. Si ce dernier commence avec une voyelle, la consonne C est rajoutée entre la voyelle V et le mot racine.
- C(V)- :: le préfixe est (ou fini par) une consonne, il se rajoute donc au début du mot racine. Si ce dernier commence avec une consonne, la voyelle (V) est rajoutée entre la consonne C et le mot racine.
- -C_{1}V(C_{2})- :: l’infixe commence par consonne, il se placera donc à la fin du mot racine, entre la dernière voyelle et la dernière consonne du mot racine. Si le mot racine se termine par une voyelle, l’ensemble C_{1}VC_{2} agira comme un suffixe.
- -(C_{1})VC_{2}- :: l’infixe commence par une voyelle, il se placera donc au début du mot racine, entre la première consonne et la première voyelle. Si le mot racine commence par une voyelle, l’ensemble C_{1}VC_{2} agira comme un préfixe.

Notez également que la ou les voyelles présentée dans le tableau s’accorde en ouverture et longueur avec la voyelle du mot racine sur laquelle porte l’accent. Ainsi, ajouts de voyelles sur /mén/ via des déclinaisons s’accorderont en voyelles longues et ouvertes. Si la juxtaposition de deux voyelles est obligatoire, se référer à [[deriv-accord-voy][l’accord des voyelles]] ci-dessus. Si la juxtaposition de deux consonnes est obligatoire, se référer à [[deriv-accord-cons][l’accord des consonnes]], idem pour [[deriv-accord-voy][l’accord des voyelles]].

Voici ci-dessous un tableau exposant la forme de chaque déclinaison selon le cas grammatical et le genre/nombre. Le numéro se réfère au numéro du genre tel que décrit dans [[morpho-nom-genre][Genre]], le super-singulier (tel que décrit dans [[morpho-nom-nombre][Nombre]]) est représenté par « s » et le pluriel par « p ». Bien que la déclinaison soit différente suivant la pluralité du nom et son genre, la déclinaison du nom se fait après l’avoir accordé en genre et en nombre afin d’assurer une certaine redondance de l’information, en particulier concernant le nombre, le super-singulier ne portant pas assez d’information selon le standard du Hjalpi’.
src_latex{\newpage}

| / | <>                   | >       | >        | >       | >       | >       | >       |
|   |                      | 1s      | 1p       | 2s      | 2p      | 3s      | 3p      |
|---+----------------------+---------+----------+---------+---------+---------+---------|
|   | abessif              | e(m)-   | e(ň)-    | e(n)-   | e(n)-   | e(l)-   | e(dl)-  |
|   | [[cas-abl][ablatif]]              | l(i)-   | l(e)-    | li(s)-  | le(ž)-  | l(i)-   | ĺ(ž)-   |
|   | [[cas-abs][absolutif]]            | -(ts)a  | -(ts)a   | -(tß)a  | -(tß)a  | -(ts)a  | -(ts)a  |
|   | [[cas-acc][accusatif]]            | -vo     | -vwo     | -vu     | -vwu    | -vo     | -vo     |
|   | [[cas-atemp][accusatif-temporel]]   | -źu     | -źu      | -źu     | -źu     | -źoy    | -źou    |
|   | [[cas-ade][adessif]]              | ix(a)-  | ix(e)-   | ix(a)-  | ix(e)-  | ix(a)-  | ix(e)-  |
|   | adverbial            | -ei     | -ey      | -ei     | -ei     | -ey     | -ey     |
|   | [[cas-all][allatif]]              | -li(ß)- | -li(ts)- | -li(ð)- | -li(ð)- | -li-    | -li-    |
|   | [[cas-ante][antessif]]             | vwo(n)- | vw(o)-   | v(o)-   | vw(o)-  | vwo-    | vo-     |
|   | [[cas-apu][apudessif]]            | þ(e)-   | ð(e)-    | ð(e)-   | ðe-     | þ(e)-   | ð(e)-   |
|   | [[cas-evit][aversif]]              | ł(e)-   | ł(e)-    | ła-     | ł(e)-   | ł(e)-   | ła-     |
|   | [[cas-ben][bénéfactif]]           | -at     | -et      | -at     | -at     | -at     | -aţ     |
|   | causal               | -(o)by  | -(o)bu   | -(u)by  | -(o)by  | -(ob)y  | -(b)y   |
|   | [[cas-com][comitatif]]            | -ðai-   | -ðei-    | -ðei-   | -ðai-   | -ðei-   | -ðey-   |
|   | comparatif           | -(oi)r  | -(oi)r   | -(oi)r  | -(oi)ţ  | -(oi)r  | -(oi)t  |
|   | [[cas-dat][datif]]                | -at-    | -et-     | -at-    | -at-    | -at-    | -aţ-    |
|   | [[cas-del][délatif]]              | ß(a)-   | ß(e)-    | ß(e)-   | ß(e)-   | ß(ai)-  | ß(a)-   |
|   | [[cas-dat][distributif]]          | xe(š)-  | xe(l)-   | xe(ž)-  | xe(l)-  | ŗe(š)-  | ŗe(ž)-  |
|   | [[cas-distemp][distributif-temporel]] | -be     | -be      | -ve     | -be     | -va     | -fe     |
|   | [[cas-ela][élatif]]               | -(a)ły  | -(e)ły   | -(a)ły  | -(a)łu  | -(e)ły  | -(e)ły  |
|   | équatif              | -(ń)t   | -(ń)t    | -(ń)t   | -(ĺ)t   | -(ń)st  | -(ń)ft  |
|   | [[cas-erg][ergatif]]              | -(u)jo  | -(y)jo   | -(í)jo  | -(é)jo  | -(u)jo  | -(u)jo  |
|   | [[cas-ess][essif]]                | -(þ)yd- | -(þ)yd-  | -(þ)ud- | -(þ)ud- | -(þ)yd- | -(þ)ud- |
|   | essif-formel         | -(ò)ţ   | -(ò)d    | -(o)d   | -(o)ḑ   | -(ò)d   | -(ò)ň   |
|   | essif-modal          | -(’)uix | -(’)uix  | -’yiŗ   | -(’)yiŗ | -(’)uŗ  | -(’)uiŗ |
|   | excessif             | -ex     | -ex      | -eŗ     | -ex     | -ix     | -ex     |
|   | [[cas-gen][génitif]]              | ţ(y)-   | ţ(u)-    | ţ(y)-   | ţ(y)-   | ţ(y)-   | ţ(yi)-  |
|   | identique            | -(e)tyr | -(a)tur  | -(a)tyr | -(e)tur | -(e)tur | -tyr    |
|   | [[cas-ill][illatif]]              | -(p)òn- | -(p)on-  | -(f)òn- | -(f)on- | -òn-    | -(p)òn- |
|   | [[cas-ine][inessif]]              | -(a)ŕo- | -(e)ŕo-  | -ŕo(n)- | -(ń)ŕo- | -(a)ŕo- | -ŕo-    |
|   | [[cas-init][initiatif]]            | -(a)kĺ  | -(k)ĺ    | -(e)kĺ  | -(a)kĺ  | -(k)ĺ   | -(k)ĺ   |
|   | [[cas-instructive][instructif]]           | -(e)ň   | -(e)ň    | -(a)ň   | -eň     | -(e)ň   | -(a)ň   |
|   | [[cas-instr][instrumental]]         | -(d)ĺ   | -(d)ĺ    | -(d)ĺ   | -(ḑ)ĺ   | -(d)ĺ   | -(ḑ)ĺ   |
|   | [[cas-intrt][intratif]]             | -fu(þ)- | -fu(ð)-  | -fu(ð)- | -fu(ð)- | -fy(þ)- | -fy(ð)- |
|   | [[cas-lat][latif]]                | -(l)a   | -(l)ei   | -(l)òĺ  | -(l)e   | -(l)au  | -(l)ĺ   |
|   | [[cas-limit][limitatif]]            | -(ò)mp  | -(e)mp   | -(ò)mp  | -(ò)mp  | -(ò)mp  | -(ò)mp  |
|   | [[cas-loc][locatif]]              | l(a)-   | l(e)-    | l(i)-   | l(e)-   | le(þ)-  | l(e)-   |
|   | nominal              | -(eu)s  | -(eu)ß   | -(eu)s  | -(eu)ßt | -(eu)st | -(eu)s  |
|   | [[cas-nom][nominatif]]            | p(a)-   | p(e)-    | p(a)-   | p(e)-   | p(a)-   | p(a)-   |
|   | [[cas-obl][oblique]]              | -(ŗ)eß  | -(ŗ)eßt  | -(ŗ)ef  | -(ŗ)eft | -(ŗ)eß  | -(x)eß  |
|   | orientatif           | f(o)-   | f(o)-    | f(u)-   | f(o)-   | þ(o)-   | f(o)-   |
|   | [[cas-ptv][partitif]]             | -’i(l)- | -’i(l)-  | -’y(l)- | -’u(l)- | -’i(l)- | -’i(l)- |
|   | [[cas-peg][pégatif]]              | ey-     | eu-      | ey-     | ey-     | eu-     | ei-     |
|   | [[cas-per][perlatif]]             | ž(u)-   | ž(y)-    | ž(u)-   | š(u)-   | š(y)-   | ž(u)-   |
|   | [[cas-pert][pertingent]]           | m(a)-   | m(a)-    | m(a)-   | m(e)-   | mj(a)-  | mj(e)-  |
|   | [[cas-poss][possessif]]            | -ţy     | -ţy      | -(i)ţy  | -ţy     | -(eu)ţ  | -(y)ţ   |
|   | [[cas-poste][postessif]]            | -(u)ß   | -(u)ßt   | -(y)ß   | -(y)ž   | -(u)š   | -(u)št  |
|   | [[cas-priv][privatif]]             | ei-     | ei-      | eń-     | ež-     | ei-     | éĺ-     |
|   | [[cas-prol][prolatif]]             | š(a)-   | š(a)-    | š(e)-   | š(ae)-  | ž(a)-   | š(ay)-  |
|   | révertif             | -ňo     | -ňò      | -ňò     | -ňò     | -ňe     | -ňò     |
|   | [[cas-sempl][semplatif]]            | -(ŗ)wo  | -(ŗ)wo   | -(ŗ)we  | -(ŗ)wo  | -(ŗ)wo  | -ŗwo    |
|   | [[cas-soc][sociatif]]             | t(o)-   | t(e)-    | t(o)-   | t(o)-   | ţ(o)-   | te-     |
|   | [[cas-sube][subessif]]             | ň(o)-   | ň(wo)-   | n(o)-   | n(wo)-  | ň(o)-   | ň(o)-   |
|   | [[cas-subl][sublatif]]             | -(i)ţ   | -(i)ţ    | -(e)ţ   | -(i)ḑ   | -(i)ţ   | -(i)nţ  |
|   | [[cas-supe][superessif]]           | tß(a)-  | tß(ań)-) | tß(ai)- | tßau-   | tß(e)-  | tß(a)-  |
|   | [[cas-temp][temporel]]             | -(i)ňni | -(i)ňni  | -(i)ňni | -(i)mi  | -(i)ňni | -(i)nji |
|   | [[cas-term][terminatif]]           | -(ae)n  | -(ae)ň   | -(þ)aen | -(ð)aen | -(þ)aeň | -(ae)m  |
|   | translatif           | -(i)n   | -(i)n    | -(y)n   | -(e)n   | -in     | -(i)n   |
|   | vocatif              | -wa     | -we      | -wa     | -wa     | -we     | -(d)wa  |

| / | <>                   | >       | >       | >        | >        | >        | >        |
|   |                      | 4s      | 4p      | 5s       | 5p       | 6s       | 6p       |
|---+----------------------+---------+---------+----------+----------+----------+----------|
|   | abessif              | e(ň)-   | e(t)-   | e(st)-   | e(ßt)-   | e(nt)-   | e(ňt)-   |
|   | [[cas-abl][ablatif]]              | li(ß)-  | li(ź)-  | li(ß)-   | li(ź)-   | li(s)-   | li(z)-   |
|   | [[cas-abs][absolutif]]            | -(t)a   | -(š)a   | -(p)a    | -(v)a    | -(st)a   | -(ž)a    |
|   | [[cas-acc][accusatif]]            | -(e)vo  | -(e)vo  | -(e)vo   | -(e)vo   | -(a)vo   | -(a)vo   |
|   | [[cas-atemp][accusatif-temporel]]   | -(a)źu  | -(e)źu  | -(u)źu   | -(ai)źu  | -(i)źu   | -(u)źu   |
|   | [[cas-ade][adessif]]              | iź(a)-  | iź(ei)- | iź(a)-   | iź(ei)-  | iź(a)-   | iź(ei)-  |
|   | adverbial            | -ei     | -ai     | -ai      | -ei      | -eu      | -ey      |
|   | [[cas-all][allatif]]              | -li(s)- | -li(ź)- | -li(z)-  | -li(š)-  | -li(x)-  | -li(x)-  |
|   | [[cas-ante][antessif]]             | we-     | w(e)-   | w(o)-    | w(e)-    | v(e)-    | v(wo)-   |
|   | [[cas-apu][apudessif]]            | þe(n)-  | þ(e)-   | v(e)-    | ve(n)-   | þ(e)-    | ð(e)-    |
|   | [[cas-evit][aversif]]              | ł(e)-   | ła-     | la-      | ł(e)-    | ła-      | ł(e)-    |
|   | [[cas-ben][bénéfactif]]           | -at     | -aţ     | -aţ      | -aţ      | -et      | -(v)et   |
|   | causal               | -(o)by  | -(o)by  | -(o)by   | -(o)by   | -(o)bu   | -(o)bu   |
|   | [[cas-com][comitatif]]            | -ðeń-   | -ðei-   | -ðei(n)- | -ðey-    | -ðei-    | -ðey-    |
|   | comparatif           | -(oi)t  | -(oi)ţ  | -oir     | -er      | -(oi)r   | -oit     |
|   | [[cas-dat][datif]]                | -at-    | -aţ-    | -aţ-     | -aţ-     | -et-     | -(v)et-  |
|   | [[cas-del][délatif]]              | š(a)-   | š(e)-   | ž(a)-    | ž(e)-    | ž(a)-    | ž(a)-    |
|   | [[cas-dat][distributif]]          | he(l)-  | he(l)-  | he(l)-   | he(l)-   | ha(l)-   | ha(l)-   |
|   | [[cas-distemp][distributif-temporel]] | -be     | -ba     | -ba      | -ve      | -ve      | -va      |
|   | élatif               | -(ł)y   | -(ł)y   | -(ł)y    | -(ł)yi   | -(ł)u    | -(ł)yi   |
|   | équatif              | -(ń)t   | -(ń)ḑ   | -(ń)ţ    | -(ń)t    | -(ĺ)ḑ    | -(ń)ţ    |
|   | [[cas-erg][ergatif]]              | -(ò)jo  | -(y)jo  | -(lj)o   | -(lj)o   | -(mj)o   | -(lj)o   |
|   | [[cas-ess][essif]]                | -(þ)yḑ- | -(þ)yḑ- | -(ð)yţ-  | -(ð)yţ-  | -(þ)ud-  | -(þ)ud-  |
|   | essif-temporel       | -(ţ)òd  | -(ţ)ed  | -(ţ)òd   | -òd      | -(ò)d    | ò(d)-    |
|   | essif-modal          | -(’)uŗ  | -(’)uŗ  | -’u      | -(’)yŗ   | -(’)yiŗ  | -(’)yŗ   |
|   | excessif             | -ex     | -eŕ     | -ex      | -aŗ      | -ex      | -eŗ      |
|   | [[cas-gen][génitif]]              | ţy-     | ţy-     | ţy(i)-   | ţy-      | ţ(eu)-   | ţo(y)-   |
|   | identique            | -tur    | -(e)tur | -(a)tur  | -(e)tur  | -tyr     | -tyr     |
|   | [[cas-ill][illatif]]              | -(s)òn- | -(s)en- | -(s)en-  | -(s)an-  | -(ps)òn- | -(ps)en- |
|   | [[cas-ine][inessif]]              | -(e)ŕo- | -(a)ŕo- | -(e)ŕo-  | -ŕo-     | -ŕo-     | -(a)ŕo-  |
|   | [[cas-init][initiatif]]            | -(e)kĺ  | -(e)kń  | -(a)kĺ   | -(ei)kń  | -akĺ     | -ekĺ     |
|   | [[cas-instructive][instructif]]           | -(e)ň   | -eň     | -aň      | -(e)ň    | -(ea)ň   | -(e)ň    |
|   | [[cas-instr][instrumental]]         | -(d)ĺ   | -(ţ)ĺ   | -(d)ĺ    | -ḑĺ      | -(d)ĺ    | -(d)ń    |
|   | [[cas-intrt][intratif]]             | -fu(þ)- | -fy-    | -fy(ð)-  | -fy(ð)-  | -fu(ð)-  | -þy(ð)-  |
|   | [[cas-lat][latif]]                | -(l)ń   | -(l)a   | -(l)a    | -le      | -la      | -la      |
|   | [[cas-limit][limitatif]]            | -(ò)mp  | -(ò)mp  | -(ò)mp   | -(ò)mp   | -(e)mp   | -(ò)mp   |
|   | [[cas-loc][locatif]]              | l(e)-   | l(e)-   | lj(a)-   | l(a)-    | ła-      | ł(a)-    |
|   | nominal              | -(eu)s  | -(eo)ß  | -eus     | -eušt    | -eus     | -(eu)ß   |
|   | [[cas-nom][nominatif]]            | pa(n)-  | pa(ń)-  | pń-      | pń-      | pa(m)-   | pa-      |
|   | [[cas-obl][oblique]]              | -(ŗ)ef  | -(ŗ)òß  | -(ŗ)ef   | -(ŗ)òß   | -(ŗ)ef   | -(ŗ)òß   |
|   | orientatif           | f(o)-   | v(o)-   | þ(o)-    | ð(o)-    | þ(o)-    | þo-      |
|   | [[cas-ptv][partitif]]             | -’i(l)- | -’il-   | -’il(y)- | -ili(’)- | -’i(ł)-  | -’e(ł)-  |
|   | [[cas-peg][pégatif]]              | ey-     | ei-     | ei-      | eu-      | ey-      | eu-      |
|   | [[cas-per][perlatif]]             | š(ui)-  | ž(ui)-  | š(eu)-   | š(ey)-   | š(oy)-   | ž(ou)-   |
|   | [[cas-pert][pertingent]]           | m(e)-   | m(e)-   | m(a)-    | m(e)-    | mj(ò)-   | mj(e)-   |
|   | [[cas-poss][possessif]]            | -eţy    | -eţy    | -(i)ţy   | -oţy     | -(e)uţ   | -(o)iţ   |
|   | [[cas-poste][postessif]]            | -(u)š   | -(u)ß   | -(u)ß    | -(u)þ    | -(u)ž    | -(y)š    |
|   | [[cas-priv][privatif]]             | ei-     | ae-     | eiḑ-     | ei-      | ei-      | ei-      |
|   | [[cas-prol][prolatif]]             | ša-     | š(e)-   | š(e)-    | ž(a)-    | š(e)-    | še-      |
|   | révertif             | -ňò     | -ňò     | -ňoe     | -ňò      | -ňò      | -ňe      |
|   | [[cas-sempl][semplatif]]            | -ŗwe    | -(ŗ)wo  | -ŗwo     | -(ŗ)wo   | -ŗwo     | -ŗwe     |
|   | [[cas-soc][sociatif]]             | t(o)-   | t(e)-   | ţe-      | t(o)-    | to-      | ţo-      |
|   | [[cas-sube][subessif]]             | nw(o)-  | n(we)-  | ň(e)-    | ň(o)-    | ne-      | ňe-      |
|   | [[cas-subl][sublatif]]             | -(i)fţ  | -(i)þţ  | -(e)nţ   | -(eu)ţ   | -(a)ţ    | -(i)nţ   |
|   | [[cas-supe][superessif]]           | ßt(e)-  | tß(ei)- | tß(e)-   | št(a)-   | ßt(a)-   | ßt(a)-   |
|   | [[cas-temp][temporel]]             | -(y)ňni | -(ň)ne  | -eňni    | -(i)mji  | -(i)ňni  | -(iň)ni  |
|   | [[cas-term][terminatif]]           | -(ae)n  | -aem    | -aeň     | -aem     | -(ae)nz  | ae(ň)-   |
|   | translatif           | -(i)n   | -(y)m   | -(i)ň    | -(i)n    | -(i)m    | -(i)n    |
|   | vocatif              | -wa     | -ja     | -je      | -v(w)e   | -va      | -ve      |


| / | <>                   | >       | >       | >        | >       | >         | >         |
|   |                      | 7s      | 7p      | 8s       | 8p      | 9s        | 9p        |
|---+----------------------+---------+---------+----------+---------+-----------+-----------|
|   | abessif              | e-      | e(s)-   | e-       | e(ňt)-  | e(mt)-    | e(ňt)-    |
|   | [[cas-abl][ablatif]]              | lń(d)-  | lń(d)-  | ĺ(z)-    | ĺ(z)-   | ĺ(v)-     | ĺ(v)-     |
|   | [[cas-abs][absolutif]]            | -(r)a   | -(r)a   | -(x)a    | -(š)a   | -(ŗ)a     | -(ž)a     |
|   | [[cas-acc][accusatif]]            | -(u)vo  | -(u)vo  | -vu      | -vu     | -vy       | -vy       |
|   | [[cas-atemp][accusatif-temporel]]   | -(o)źu  | -(o)źu  | -(o)źu   | -(o)źu  | -(o)źu    | -(o)źu    |
|   | [[cas-ade][adessif]]              | iź(a)-  | iź(ei)- | iŗ(a)-   | iŗ(a)-  | iŗ(e)-    | iŗ(e)-    |
|   | adverbial            | -ei     | -ei     | -ei      | -(r)ei  | -(ei)r    | -(ey)r    |
|   | [[cas-all][allatif]]              | -li(ŗ)- | -li(ŗ)- | -li(þt)- | -li(v)- | -(l)iþ-   | -(l)ið-   |
|   | [[cas-ante][antessif]]             | vw(o)-  | v(u)-   | v(u)-    | v(u)-   | vw(o)-    | vu-       |
|   | [[cas-apu][apudessif]]            | ð(ei)-  | ðe(m)-  | f(e)-    | fe-     | vei-      | fei-      |
|   | [[cas-evit][aversif]]              | ł(e)-   | ł(e)-   | ła-      | l(e)-   | ł(e)-     | ł(e)-     |
|   | [[cas-ben][bénéfactif]]           | -at     | -et     | -ast     | -aþ     | -at       | -et       |
|   | causal               | -(o)vu  | -(e)vy  | -(e)vy   | -(e)vy  | -vy       | -vy       |
|   | [[cas-com][comitatif]]            | -ðei-   | -ðei-   | -ðeu-    | -ðei-   | -ðeu-     | -ðeu-     |
|   | comparatif           | -(oi)r  | -(oi)r  | -or      | -(oi)r  | -oiŗ      | -(oi)ŗ    |
|   | [[cas-dat][datif]]                | -at-    | -et-    | -ast-    | -aþ-    | -at-      | -et-      |
|   | [[cas-del][délatif]]              | ß(eu)-  | ß(eu)-  | ß(a)-    | ß(a)-   | ßa(l)-    | ße(l)-    |
|   | [[cas-dat][distributif]]          | hei(l)- | hea(l)- | hea(l)-  | hea(l)- | še(l)-    | še(l)-    |
|   | [[cas-distemp][distributif-temporel]] | -(b)e   | -be     | -bei     | -(b)ei  | -be       | -be       |
|   | élatif               | -ły     | -(a)ły  | -(ł)ay   | -(ł)ey  | -(ł)ay    | -łay      |
|   | équatif              | -(ń)t   | -(ń)t   | -ńt      | -(ń)t   | -(ń)t     | -ńt       |
|   | [[cas-erg][ergatif]]              | -jo     | -jo     | -(o)jo   | -(e)jo  | -(u)jo    | -(u)jo    |
|   | [[cas-ess][essif]]                | -þy(d)- | -þy(d)- | -þy(d)-  | -þy(d)- | -(oi)þyd- | -(oi)þyd- |
|   | essif-temporel       | -òd     | -(ò)ns  | -òd      | -òts    | -(ò)ß     | -(ò)ßt    |
|   | essif-modal          | -(’)uŗ  | -(’)u   | -(’)u    | -(’)ust | -(’)uŗ    | -(’)uŗ    |
|   | excessif             | -ex     | -(e)x   | -(a)x    | -ex     | -eŕ       | -ex       |
|   | [[cas-gen][génitif]]              | ţy-     | ţ(u)-   | ţ(u)-    | ţu-     | ţ(y)-     | ţ(u)-     |
|   | identique            | -(e)tur | -(e)tur | -(t)ur   | -tur    | -(e)tur   | -(o)tur   |
|   | [[cas-ill][illatif]]              | -òn-    | -(v)òn- | -(ŕ)òn-  | -(ŕ)òn- | -(ŕ)òn-   | -(ŕ)en-   |
|   | [[cas-ine][inessif]]              | -(o)ŕo- | -(a)ŕo- | -(a)ŕo-  | -(u)ŕo- | -(e)ŕo-   | -(a)ŕo-   |
|   | [[cas-init][initiatif]]            | -(a)kĺ  | -(e)kń  | ak(ĺ)-   | k(ń)-   | -(k)ĺ     | -(k)ń     |
|   | [[cas-instructive][instructif]]           | -eň     | -eňt    | -(e)ňz   | -(e)ň   | -(e)ň     | -(e)ňt    |
|   | [[cas-instr][instrumental]]         | -(d)ĺ   | -(d)ĺ   | -(d)ń    | -(ḑ)ń   | -(d)ĺ     | -(d)ĺ     |
|   | [[cas-intrt][intratif]]             | -(f)yþ- | -fu-    | -fi(ŕ)-  | -fe(ŕ)- | -fu(ð)-   | -fu(þ)-   |
|   | [[cas-lat][latif]]                | -(a)la  | -(e)la  | -(l)e    | -(l)ai  | -(l)ae    | -la       |
|   | [[cas-limit][limitatif]]            | -(a)mp  | -(a)mp  | -(a)mp   | -(a)mp  | -(ò)mp    | -(ò)mp    |
|   | [[cas-loc][locatif]]              | l(au)-  | l(ai)-  | l(a)-    | la-     | ĺ-        | l(e)-     |
|   | nominal              | -(eu)s  | -(eu)ß  | -(eu)s   | -(ei)š  | -(eu)s    | -(eu)st   |
|   | [[cas-nom][nominatif]]            | pa(l)-  | pa(l)-  | pa(ß)-   | pe(ß)-  | pa-       | pa-       |
|   | [[cas-obl][oblique]]              | -(x)eß  | -(x)eß  | -(x)eß   | -(x)eß  | -(x)uiß   | -(x)oiß   |
|   | orientatif           | f(o)-   | f(u)-   | f(o)-    | vo-     | þo-       | fo-       |
|   | [[cas-ptv][partitif]]             | -’i(l)- | -gi(l)- | -’i(l)-  | -ki(l)- | -’i(l)-   | -’i(l)-   |
|   | [[cas-peg][pégatif]]              | eu-     | ey-     | ey-      | ey-     | ei-       | ey-       |
|   | [[cas-per][perlatif]]             | ž(u)-   | ž(e)-   | ž(u)-    | ž(u)-   | š(y)-     | ž(u)-     |
|   | [[cas-pert][pertingent]]           | m(e)-   | m(u)-   | m(a)-    | m(o)-   | m(e)-     | m(e)-     |
|   | [[cas-poss][possessif]]            | -(ţ)y   | -(e)ţy  | -iţy     | -ţy     | -yţ       | -iţ       |
|   | [[cas-poste][postessif]]            | -(u)ß   | -(u)ź   | -(y)ź    | -(y)ž   | -(y)tß    | -(y)ßt    |
|   | [[cas-priv][privatif]]             | ei-     | ei-     | ei-      | ei-     | eń-       | eń-       |
|   | [[cas-prol][prolatif]]             | š(a)-   | šei-    | še-      | š(a)-   | š(ey)-    | ž(e)-     |
|   | révertif             | -ňo     | -ňo     | -ňò      | -ňo     | -(ň)ò     | -ňo       |
|   | [[cas-sempl][semplatif]]            | -(ŗ)wo  | -(ŗ)wo  | -(ŗ)we   | -(ŗ)wo  | -(ŗ)wo    | -(ŗ)wo    |
|   | [[cas-soc][sociatif]]             | te-     | t(o)-   | t(o)-    | to-     | t(o)-     | t(o)-     |
|   | [[cas-sube][subessif]]             | ňe-     | ňo-     | nw(a)-   | n(wa)-  | n(a)-     | na-       |
|   | [[cas-subl][sublatif]]             | -(i)ţ   | -(i)ßţ  | -(i)šţ   | -(i)ţ   | -(r)iţ    | -iţ       |
|   | [[cas-supe][superessif]]           | tß(ao)- | tß(ae)- | tßa-     | ßta-    | ßt(e)-    | tß(a)-    |
|   | [[cas-temp][temporel]]             | -(i)ňni | -(i)ňni | -(e)ňni  | -(i)ňni | -(y)ňni   | -iňni     |
|   | [[cas-term][terminatif]]           | -(ae)n  | -(ae)n  | -(ae)m   | -ae     | -(ai)n    | -(ai)ň    |
|   | translatif           | -(i)n   | -(i)n   | -in      | -iň     | -iň       | -iň       |
|   | vocatif              | -wa     | -wa     | -wein    | -wa     | -wa       | -weŕ      |
src_latex{\newpage}

** Verbes
* Syntaxe
** Noms
*** Déclinaisons
Suivant le rôle du nom dans la phrase, il est possible de le décliner à l’un des nombreux cas grammaticaux qu’offre le Hjalpi’. Dans cette section, j’expliquerai simplement la signification brève de chacune de ces déclinaisons. Pour un détail de comment décliner les noms, veuillez vous référer au [[decl-morph-decl][chapitre dédié]]. Je regrouperai ici les déclinaison par catégorie. Chaque cas sera présenté de la manières suivante :
- Cas grammatical (/ABBRÉVIATION/) :: définition

**** Lieu
- <<cas-ade>>Cas adessif (/ADE/) :: indique un lieu adjacent à l’élément.
Exemple : iŗeménóst (ADE-maison-pl.) à côté des maisons

- <<cas-ante>>Cas antessif (/ANTE/) :: indique un lieu antérieur à l’élément.
Exemple : vwomén (ANTE-maison) avant la maison / devant la maison

- <<cas-apu>>Cas apudessif (/APU/) :: indique un lieu à côté, proche de l’élément. L’élément n’est pas adjacent au lieu, auquel cas il faudrait utiliser le cas adessif.
Exemple : veimén (APU-maison) à côté de la maison

- <<cas-ine>>Cas inessif (/INE/) :: indique un lieu à l’intérieur de l’élément.
Exemple : mérón (<INE>maison) dans la maison

- <<cas-intrt>>Cas intratif (/INTRT/) :: indique un lieu entre des éléments. L’élément décliné ne peut être singulier.
Exemple : ménatĺ (maison.duel.INTRT) entre deux maisons.

- <<cas-loc>>Cas locatif (/LOC/) :: indique que l’élément décliné est le lieu indiqué (usage général).
Exemple : ĺmén (LOC-maison) à la maison (sans précision)

- <<cas-pert>>Cas pertingent (/PERT/) :: indique un contact avec un lieu.
Exemple : memén (PERT-maison) en contact avec la maison

- <<cas-poste>>Cas postessif (/POSTE/) :: indique un lieu postérieur à l’élément.
Exemple : ménýßt (maison-POSTE) après la maison.

- <<cas-sube>>Cas subessif (/SUBE/) :: indique un lieu sous l’élément.
Exemple : namén (SUBE-maison) sous la maison

- <<cas-supe>>Cas superessif (/SUPE/) :: indique un lieu sous l’élément.
Exemple : ßtemén (SUPE-maison) sur la maison / sur le toit de la maison (impliqué)\\
\\
**** Mouvement depuis un élément
- <<cas-abl>>Cas ablatif (/ABL/) :: indique un déplacement s’éloignant de l’élément.
Exemple : Je pars de Ðbńo. (décision motivée par moi-même)
| wyhakéís                      | liÐbńovu     | né       |
| quitter(NOM prés-indic 1s2SG) | ABL-Ðbńo-ACC | 1s6G.NOM |

- <<cas-del>>Cas délatif (/DEL/) :: déplacement depuis la surface de l’élément.
Exemple : La mouche s’envola (volontairement) du livre (de l’extérieur du livre, sous entendu de sa couverture)
| proböléntí                                | ßaraòm    | paŗevir    |
| s’envoler-(NOM passé m p 3s3SG) | DEL-livre | NOM-mouche |

- <<cas-ela>>Cas élatif (/ELA/) :: déplacement depuis l’intérieur de l’élément.
Exemple : La mouche s’envola (volontairement) du livre (sous entendu depuis une page / l’intérieur du livre, le livré étant ouvert)
| proböléntí                      | raòmey    | paŗevir    |
| s’envoler-(NOM passé m p 3s3SG) | livre-ELA | NOM-mouche |

- <<cas-init>>Cas initiatif (/INIT/) :: indique le point de départ d’une action (cas général)
Exemple : Je voyage depuis Ðbńo (sous-entendu, Ðbńo était de point de départ du voyage)
| etrjáléís                     | Ðbńokĺ    | né       |
| voyager(NOM prés-indic 1s2SG) | Ðbńo-INIT | 1s6G.NOM |

**** Mouvement vers un élément
- <<cas-all>>Cas allatif (/ALL/) :: indique un mouvement vers les environs de l’élément (cas général), n’indique pas nécessairement de finalité ou de point précis.
Exemple : Je voyage vers Ðbńo (sans nécessairement aller à Ðbńo même).
| etrjáléís                     | Ðbńoðil   | né       |
| voyager(NOM prés-indic 1s2SG) | Ðbńo<ALL> | 1s6G.NOM |

- <<cas-ill>>Cas illatif (/ILL/) :: mouvement vers l’intérieur de l’élément, n’indique pas nécessairement de finalité.
Exemple : La mouche vole vers la maison (sous entendu, elle va y rentrer)
| eŕbölay                      | monén       | paŗevir    |
| voler-(NOM prés-indic 3s3SG) | <ILL>maison | NOM-mouche |

- <<cas-lat>>Cas latif (/LAT/) :: mouvement vers l’élément (cas général), n’indique pas nécessairement de finalité.
Exemple : Je pars de Notń pour Ðbńo.
| wyhakéís                      | liNotńvu     | Ðbńolòĺ  | né       |
| quitter(NOM prés-indic 1s2SG) | ABL-Notń-ACC | Ðbńo-LAT | 1s6G.NOM |

- <<cas-subl>>Cas sublatif (/SUBL/) :: mouvement vers la surface de l’élément.
Exemple : La mouche vole vers le livre. (sous-entendu, la couverture)
| eŕbölay                      | raòmiţ     | paŗevir    |
| voler-(NOM prés-indic 3s3SG) | livre-SUBL | NOM-mouche |

- <<cas-term>>Cas terminatif (/TERM/) :: le mouvement a pour but l’élément.
Exemple : Je voyage jusqu’à Ðbńo.
| etrjáléís                     | Ðbńoþaen  | né       |
| voyager(NOM prés-indic 1s2SG) | Ðbńo-TERM | 1s6G-NOM |

**** Déplacement via un élément
- <<cas-per>>Cas perlatif (/PER/) :: mouvement au travers ou le long de l’élément.
Exemple : Je voyage le long de la rivière.
| etrjáléís                     | šyłánt                 | né       |
| voyager(NOM prés-indic 1s2SG) | PERL-(rivière mineure) | 1s6G-NOM |

- <<cas-prol>>Cas prolatif (/PROL/) :: mouvement en utilisant l’élément ou sur sa surface.
Exemple : Je navigue sur l’océan côtier.
| ’elḑökay                       | šielt               | né       |
| naviguer(NOM prés-indic 1s2SG) | PROL-(océan côtier) | 1s6G-NOM |

**** Temps
- <<cas-atemp>>Cas accusatif-temporel (/ATEMP/) :: indication d’une durée de temps, peut remplacer l’accusatif d’une proposition nominative-accusative avec un verbe transitif.
Exemple : J’ai dormis sept heures.
| ’oherénté                    | heolí’            | pńtwánźu   | né       |
| dormir-(NOM passé m p 1s2SG) | heure(mesure)-GEN | sept-ATEMP | 1s6G-NOM |

- <<cas-ess>>Cas essif (/ESS/) :: l’élément indique la date où le moment où un événement se produit.
Exemple : Je dors habituellement à sept heures.
| ’oheroméis                   | hebéómi’  | pudńtwán  | né       |
| dormir(NOM prés-habit 1s2SG) | heure-GEN | <ESS>sept | 1s6G-NOM |

- <<cas-limit>>Cas limitatif (/LIMIT/) :: l’élément indique une limite dans le temps.
Exemple : Je dors habituellement jusqu’à sept heures.
| ’oheroméis                   | hebéómi’  | pńtwánòmp  | né       |
| dormir(NOM prés-habit 1s2SG) | heure-GEN | sept-LIMIT | 1s6G-NOM |

- <<cas-temp>>Cas temporel (/TEMP/) :: l’élément désigne un moment (cas général).
Exemple : à sept heures
| hebéómi’  | pńtwániňni |
| heure-GEN | sept-TEMP  |

- <<cas-distemp>>Cas distributif-temporel (/DISTEMP/) :: Similaire au [[cas-distributif][cas distributif]], montrant une répétition temporelle se produisant à chaque élément temporel décliné.

**** Alignement morphosyntaxique
- <<cas-abs>>Cas absolutif (/ABS/) :: indique le patient d’un verbe transitif ou le sujet d’un verbe intransitif dans une proposition ergative. S’oppose à l’[[cas-erg][ergatif]].
Exemple : J’ai brisé le vase. (action sous-entendue comme involontaire)
| néí      | nweţuŗa  | kĺnéínté                    |
| 1s6G.ERG | vase-ABS | briser(ERG passé m p 1s2SG) |

- <<cas-acc>>Cas accusatif (/ACC/) :: indique le patient d’un verbe transitif dans une proposition nominative. S’oppose au nominatif.
Exemple : J’ai brisé le vase. (action sous-entendue comme volontaire)
| kĺnénté                     | nweţuvy  | né       |
| briser(NOM passé m p 1s2SG) | vase-ACC | 1s6G.NOM |

- <<cas-erg>>Cas ergatif (/ERG/) :: indique l’agent d’un verbe transitif dans une proposition ergative. S’oppose à l’[[cas-abs][absolutif]]. Peut-être remplacé par le [[cas-peg][pégatif]].
Exemple : J’ai brisé le vase. (action sous-entendue comme involontaire)
| néí      | nweţuŗa  | kĺnéínté                          |
| 1s6G.ERG | vase-ABS | briser(ERG passé moy. pft. 1s2SG) |

- <<cas-instructive>>Cas instructif (/INSTRUCTIVE/) :: indique le moyen employé, répond à la question /comment ?/.
Exemple : J’ai brisé le vase en tombant. (comme je suis tombé, sous-entendu involontairement, j’ai brisé le vase)
| néí      | žybdinobyente                    | nweţuŗa  | kĺnéínté                          |
| 1s6G.ERG | tomber(ERG pas. moy. pft. 1s2SG) | vase-ABS | briser(ERG passé moy. pft. 1s2SG) |

- <<cas-instr>>Cas instrumental (/INSTR/) :: indique l’instrument utilisé, répond à la question /au moyen de quel objet ?/.
| néí      | pńtédń             | nweţuŗa  | kĺnéínté                          |
| 1s6G.ERG | pied.POSS-6s.INSTR | vase-ABS | briser(ERG passé moy. pft. 1s2SG) |

- <<cas-nom>>Cas nominatif (/NOM/) :: indique le sujet d’un verbe intransitif ou l’agent d’un verbe transitif dans une proposition nominative. S’oppose à l’[[cas-acc][accusatif]]. Peut-être remplacé par le [[cas-peg][pégatif]].
Exemple : J’ai brisé le vase. (action sous-entendue comme volontaire)
| kĺnénté                     | nweţuvy  | né       |
| briser(NOM passé m p 1s2SG) | vase-ACC | 1s6G.NOM |

- <<cas-obl>>Cas oblique (/OBL/) :: marque le verbe, indique la proposition comme étant une citation. Les sous-propositions n’ont pas besoin d’être marquée. Remplace l’[[cas-acc][accusatif]] dans les propositions nominatives, et l’[[cas-abs][absolutif]] dans les propositions ergatives.
Exemple : j’ai dis que j’ai cassé (involontairement) le vase.
| ŗeðénté                   | kĺnéntéŗòß                  | nweţuŗa  | né       |
| dire(NOM passé m p 1s2SG) | briser(NOM passé m p 1s2SG) | vase-ACC | 1s6G.NOM |

- <<cas-peg>>Cas pégatif (/PEG/) :: agent dans une proposition ayant un argument datif. Peut remplacer le [[cas-nom][nominatif]] et l’[[cas-erg][ergatif]].

**** Relation
- <<cas-evit>>Cas aversif (/EVIT/) :: indique que l’élément est évité ou craint.
Exemple : Je navigue sur l’océan côtier tout en évitant Notń.
| ’elḑökay                       | łaNotń    | šielt               | né       |
| naviguer(NOM prés-indic 1s2SG) | EVIT-Notń | PROL-(océan côtier) | 1s6G-NOM |

- <<cas-ben>>Cas bénéfactif (/BEN/) :: indique la personne ou le concept motivant une proposition d’un verbe d’action. S’il est omis à la première personne, on assume que le bénéfacteur est le sujet ou l’agent ; à la seconde ou à la troisième personne, on assume que le bénéfacteur est inconnu.
Exemple : Je navigue sur l’océan côtier (l’action est motivée par ou due à Mérian).
| Merianaţ   | ’elḑökay                       | šielt               | né       |
| Merian-BEN | naviguer(NOM prés-indic 1s2SG) | PROL-(océan côtier) | 1s6G-NOM |

- <<cas-com>>Cas comitatif (/COM/) :: indique un accompagnement par l’élément décliné, comparable au « avec » ou « et » en Français. L’action doit être partagée entre le sujet ou agent de la proposition et l’élément décliné, c’est à dire que l’élément est souvent un compagnon dans la situation (sans conotation positive ou négative).
Exemple : Je voyage le long de la rivière accompagné de Romur. (Romur et moi partageons l’expérience du voyage).
| etrjáléís                     | šyłánt                 | Romyðeńr   | né       |
| voyager(NOM prés-indic 1s2SG) | PERL-(rivière mineure) | <COM>Romyr | 1s6G-NOM |

- <<cas-dat>>Cas datif (/DAT/) :: élément recevant ou direction de l’action vers l’élément.
Exemple : Je crie (par colère) sur mon voisin.
| ţýbýmáý                     | ketipŕým    | né       |
| crier(NOM prés-indic 1s2SG) | <DAT>voisin | 1s6G-NOM |

- <<cas-distributif>>Cas Distributif (/DISTR/) :: Marque une distribution équitable entre les éléments déclinés. Comparable au cas [[cas-distemp][distributif-temporel]].

- <<cas-gen>>Cas génitif (/GEN/) :: montre une relation entre deux éléments, l’élément décliné définit l’élément situé immédiatement après. Attention, contrairement à certaines langues, le génitif de dénote pas la possession de l’élément ; pour cela, il faut utiliser le [[cas-poss][possessif]].

- <<cas-poss>>Cas possessif (/POSS/) :: marque l’élément comme le propriétaire de l’élément suivant immédiatement l’élément décliné. Il n’est pas utile de décliner l’élément (voire même de placer l’élément dans la phrase) si l’élément propriété est également décliné avec les déclinaisons possessives.

- <<cas-priv>>Cas prifatif (/PRIV/) :: indique un manque ou une absence de l’élément décliné. Ce manque n’a aucune conotation positive ou négative.

- <<cas-sempl>>Cas semplatif (/SEMPL/) :: indique une similitude entre le sujet/expérienceur ou l’agent de la proposition et le ou les éléments déclinés.

- <<cas-soc>>Cas sociatif (/SOC/) :: indique que la situation de la proposition s’est déroulée avec l’agent ou le sujet étant avec l’élément décliné. L’élément n’a pas à partager la situation avec l’agent/sujet.
Exemple : Je voyage le long de la rivière avec mes jumelles. (Les jumelles ne peuvent partager l’expérience dû au fait qu’elles soient inanimées et ne sont certainement pas mon moyen de voyage)
| etrjáléís                     | šyłánt                 | tovyelegot   | né       |
| voyager(NOM prés-indic 1s2SG) | PERL-(rivière mineure) | SOC-jumelles | 1s6G-NOM |

**** Sémantiques
- <<cas-ptv>>Cas partitif (/PTV/) :: s’utilise pour indiquer une quantité de l’élément donné s’il s’agit de désigner un sous-groupe, sans spécifier d’identité ou bien de marquer une partie uniquement de l’élément décliné.

* Champs sémantiques et pragmatismes
* Système d’écriture
src_latex{\newpage}
* <<glossaire>>Glossaire

- clef ::  /transcription large/ /élément de langage./ Définition(s)
Définition

Abréviations :
- 1 : genre divin
- 2 : genre mental
- 3 : genre liquide
- 4 : genre masculin
- 5 : genre féminin
- 6 : genre neutre
- 7 : genre animal
- 8 : genre végétal
- 9 : genre inanimé
- adj. : adjectif
- ind. : indénombrable
- n.X : nom du Xème genre
- pron. : pronom
- vi. : verbe intransitif
- vt : verbe transitif

** À trier
- kipŕým :: (n.6) voisin
- ŗeðyþ :: (vt.) dire
- vyelegot :: (n.9) jumelles (instrument)

** Actions physiques
- kĺnyþ ::  /kl̩.nyːθ/ (vt.) casser, briser
- ţýbýmýþ ::  /ʈʏ.bʏ.mʏθ/ (vi.) crier par colère, par rage
- žybdinyþ ::  /ʐyːb.diː.nyːθ/ (vi.) tomber
- ’oheryþ ::  /?o:.he:.ry:þ/ (vi.) dormir
** Amour
** Animaux
- nael ::  /nael/ (n.7) cheval
- ŗevír ::  /ʁeː.vɪr/ (n.7) mouche
** Art
- raòm ::  /raøm/ (n.9) livre
** Astronomie
- <<glos-béóm>>béóm ::  /bɛɔm/ (n.1) Soleil. Étymologie : /[[glos-b%C3%A9m][bém]]/ + /[[gloss-jaom][jaom]]/, astre du jour
- <<gloss-jaom>>jaom ::  /jaom/ (n.1) astre
** Bâtiments
- mén ::  /mɛn/ (n.9) maison (bâtiment)
** Commerce
** Conflits
** Conteneurs
** Corps
- gar ::  /ɡaːr/ (n.6) tête
- <<glos-pńt>>pńt ::  /pn̩t/ (n.6) main
- <<glos-wán>>wán ::  /waːn/ (n.6) pied
** Couleurs
- <<glos-ðúr>>ðúr ::  /ðʊr/ (adj.) argent (couleur)
** Dimensions
** Direction
- ňam ::  /ŋaːm/ (n.2) ouest
- watßúd ::  /waːt.ʃʊd/ (n.2) nord
- wémšal ::  /wɛm.çaːl/ (n.2) est (direction)
- zelðeg ::  /zeːl.ðeːɡ/ (n.2) sud
** Eau
- ánd ::  /ɑnd/ (n.3) rivière majeure, cours d’eau dans lequel s’est jeté une autre rivière, mais ammenée à se jeter elle-même dans un autre cours d’eau
- hanḑ ::  /haːnɖ/ (n.3) fleuve mineur, cours d’eau n’ayant aucun confluent se jetant directement dans la mer ou l’océan
- ielt ::  /ielt/ (n.3) océan côtier, vaste étendue d’eau au contact des côtes
- łánt ::  /ɬɑt/ (n.3) rivière mineure ou ruisseau, cours d’eau dans lequel ne s’est jeté aucun autre cours d’eau mais ammené à se jeter dans un autre cours d’eau
- omd ::  /oːmd/ (n.3) océan non-côtier, vaste étendue d’eau n’étant pas au contact des côtes
- vilţ ::  /viːlʈ/ (n.3) fleuve majeur, cours d’eau ayant reçu d’autre cours d’eau et se jetant directement dans la mer ou l’océan
- ’élḑ ::  /ʔɛlɖ/ (n.3) mer, petite étendue d’eau connectée à d’autres mers ou océans, ou région d’océan côtier
** Effort
** Éléments
** Émotions
- feŗan ::  /feː.ʁaːn/ (n.2) tristesse
** Évaluation
- ’eßtef ::  /ʔeːʃ.teːf/ (adj.) mauvais
** Événements
- gén ::  /ɡɛn/ (n.2) acte, action
** Existence
** Famille
- ánám ::  /ɑ.nɑm/ (n.6) parent
- mánám ::  /mɑ.nɑm/ (n.5) mère, maman
- pánám ::  /pɑ.nɑm/ (n.4) père, papa
** Forme
** Gouvernement
** Grammaire
- pöb ::  /pœb/ (pron. interrogatif) quoi, idée générale d’élément. Peut être décliné afin d’obtenir des questionnements plus précis.
*** Pronoms interrogatifs
**** Temps
- pejb ::  /pejb/ (pron. interr. essif) quand, à quel moment. /pöb/ décliné à l’essif.
- pöémp ::  /pœɛmp/ (pron. interrogatif limitatif) jusqu’à quand. /pöb/ décliné au limitatif.
- pövwó ::  /pœ.vwɔ/ (pron. interrogatif accusatif) sur quelle durée, pendent combien de temps. /pöb/ décliné à l’accusatif.

** Guerre
- wóúl ::  /wɔʊl/ (n.2) attaque
** Légal
** Lieux
** Lumière
** Mental
** Mesures
** Métaux
** Mouvement
- etrjálòm ::  /eːt.rjɑ.lʏθ/ (vi.) voyager
- eŕbölýþ ::  /eːɹ.bœ.lʏθ/ (vi.) voler (dans le airs)
- jĺšek ::  /jl̩.çeːk/ (n.9) chemin, voie
- probölýþ ::  /proː.bœ.lʏþ/ (vi.) s’envoler
Exemple : Proböléntí paŗevir. La mouche s’envola.
- wyhakòm ::  /wyː.haː.køːm/ (vt.) quitter, partir.
Exemple : Né liÐbńovu wyhakéís. Je pars de Ðbńo.
- ’elḑökýþ ::  /ʔeːlɖœkʏθ/ (vi.) naviguer
** Nature
** Nombres
- pńtwán ::  /pn̩twɑn/ (nbrc) sept. Étymologie : /[[glos-p%C5%84t][pńt]]/ + /[[glos-w%C3%A1n][wán]]/
** Nourriture
** Outils
** Parole
- vár ::  /vɑr/ (n.2) langue (linguistique), langage, parole
** Péchés
** Physique
** Possession
** Religion
- hjalp ::  /hjaːlp/ (n.1) dieu céleste
- melex ::  /meː.leːχ/ (n.1) dieu terrestre
** Savoir
- bóljòluþ ::  /bɔ.ljøː.luːθ/ (vt.) savoir
- wanmjöd ::  /waːn.mjœd/ savoir, connaissance
** Sensations
- feŗtef ::  /feːʁ.teːf/ (n.2) douleur mentale, dépression. Étymologie : /feŗan/ + /’eßtef/, une /tristesse mauvaise/
- núótöm ::  /nʊɔ.tœm/ (vt.) voir
** Sexe
** Société
** Substances
- lúb ::  /lʊb/ (n.9) air
** Temps
- <<glos-bém>>bém ::  /bɛm/ (n.2) jour (mesure de temps)
- hebéóm ::  /heːbɛɔm/ (n.2) heure (repère de temps). Étymologie : /[[glos-heol][heol]]/ + /[[glos-b%C3%A9%C3%B3m][béóm]]/ l’heure par le Soleil
- <<glos-heol>>heol ::  /heol/ (n.2) heure (mesure de temps)
- łail ::  /ɬail/ (n.2) année (mesure de temps)
- ţealnat ::  /ʈealnaːt/ (adj.) précision temporelle, précis.
*** Jours de la semaine
- ðúbém ::  /ðʊ.bɛm/ (n.2) septième jour de la semaine / jour d’agent. Étymologie : /[[glos-%C3%B0%C3%BAr][ðúr]]/ + /[[glos-b%C3%A9m][bém]]/
** Travail
** Végétaux
** Vêtements
** Vie et santé
- ðenmóíl ::  /ðeːn.mɔɪl/ (n.6) personne, individu
