#+TITLE: Grammaire du Hjalpi’
#+INCLUDE: "../headers.org"
src_latex{\newpage}

* Introduction
Le Hjalpi’ est la langue parlée par les dieux dans l’univers de mon roman. La langue dont je présente ci-dessous la grammaire n’est cependant pas réellement la langue divine mais la représente ; en effet, le Hjalpi’ a été imaginée comme étant bien trop complexe pour être entièrement apprise par un humain, l’élaboration de phrases simples requière quelques années d’études déjà. Bien évidemment, il est impossible pour un humain de créer une telle langue, mais je reste toujours dans cette optique de création de langue complexe, et le résultat me paraîtra complexe mais il se peut que pour certains (du fait des langues qu’ils maîtrisent déjà) n’aient pas cette impression.

Cette langue sera également utilisée pour créer d’autres langues qui auront évolué depuis la langue divine en des langues (me paraissant) beaucoup plus simples afin de créer des langues pour les mortels.

* Phonologie
** Voyelles
Le Hjalpi’ dispose d’un inventaire de voyelle très large comparé à la majorité des langues existantes dans notre monde, avec dix-sept voyelles simples, et quelques autres diphtongues (discutées plus bas dans [[*Diphtongues][Diphtongues]]). Voici la liste des voyelles utilisées dans le Hjalpi’ :

| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | i / y       | u            |
|   | pré-fermées | í / ý       | ú            |
|   | mi-fermées  | e / ò       | o            |
|   | mi-ouvertes | é / ö       | ó            |
|   | ouvertes    | a           | á            |

Le Hjalpi’ dispose également de deux consonnes syllabiques, le /ń/ et le /ĺ/, qui sont respectivement le /n/ et le /l/ prononcés comme des voyelles. Voici ci-dessous le même tableau, avec chaque voyelle remplacée par sa valeur phonétique en X-SAMPA :

| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | ~i:~ / ~y:~ | ~u:~         |
|   | pré-fermées | ~I~ / ~Y~   | ~U~          |
|   | mi-fermées  | ~e:~ / ~2:~ | ~o:~         |
|   | mi-ouvertes | ~E~ / ~9~   | ~O~          |
|   | ouvertes    | ~a:~        | ~A~          |



Avec le /ń/ et le /ĺ/ ayant respectivement pour valeur ~n=~ et ~l=~.

On peut remarquer que, à l’exception de /ǒ/, /ń/ et /ĺ/, toutes les voyelles ont un couple ouverte-courte/fermée-longue. Dans les mots racine (c’est à dire non altérés par une quelconque règle grammaticale), la distinction revêt une importance capitale, porteuse de sens et de distinction de certains mots entre eux. Ainsi, /þran/ n’aura pas la même signification que /þrán/. En revanche, comme on le verra plus tard, les addition grammaticales verront leurs voyelles s’accorder avec les voyelles du mot racine en ouverture-longueur.

*** Voyelles courtes

- ~/A/~ : á
Le /á/ est une voyelle ressemblant au « â » que l’on retrouve en français dans des mots tels que « pâte ». Il s’agit de la voyelle ouverte antérieure non-arrondie.

- ~/9/~ : ö
Il s’agit ici du son « eu » tel qu’on le retrouve en français tel que dans le mot « neuf ».

- ~/I/~ : í
Cette voyelle est une voyelle se situant entre le son « i » et le son « e » ; on peut le retrouver en anglais dans des mots tels que « hit » ou « this ». Il s’agit de la voyelle pré-fermée antérieure non-arrondie.

- ~/E/~ : é
Nous avons ici la voyelle « è » que l’on retrouve en français par exemple dans le mot « cette ».

- ~/O/~ : ó
Il s’agit du « o » ouvert, que l’on retrouve en français dans le mot « sort » par exemple.

- ~/Y/~ : ý
Cette voyelle est un équivalent du « u » français ouvert, que l’on peut retrouver en Allemand comme dans « Müller » par exemple. Il s’agit de la voyelle antérieure pré-fermée arrondie.

- ~/U/~ : ú
Cette voyelle est un équivalent du « ou » Français ouvert, telle que l’on peut la retrouver dans le mot « book » en Anglais britannique.

*** Voyelles longues
- ~/a:/~ : a
Cette voyelle est le « a » que l’on peut retrouver dans le français tel que dans « patte », à la différence que le « a » de le Hjalpi’ est prononcé un peu plus longuement que le « a » français.

- ~/2:/~ : ò
Cette voyelle est la même que le « eu » français que l’on retrouve dans le mot « deux », à la différence que le « ò » divin est prononcé un peu plus longuement que le « eu » français.

- ~/i:/~ : i
Cette voyelle est la même que le « i » français, à la différence que le « i » de le Hjalpi’ est prononcé un peu plus longuement que le « i » français.

- ~/e:/~ : e
Cette voyelle est la même que le « é » français, à la différence que le « i » de le Hjalpi’ est prononcé un peu plus longuement que le « i » français.

- ~/o:/~ : o
Cette voyelle est la même que le « o » français comme dans « eau », à la différence que le « o » de le Hjalpi’ est prononcé un peu plus longuement que le « o » français.

- ~/y:/~ : y
Cette voyelle est la même que le « u » français, à la différence que le « u » de le Hjalpi’ est prononcé un peu plus longuement que le « u » français.

- ~/u:/~ : u
Cette voyelle est la même que le « ou » français, à la différence que le « ou » de le Hjalpi’ est prononcé un peu plus longuement que le « ou » français.
*** Consonnes syllabiques
- ~/n=/~ : ń
Le « ń » est la consonne « n » (la même que le « n » standard français), mais considérée et prononcée comme une voyelle, tel qu’on peut l’entendre dans certains mots anglais comme dans « button » qui peut être prononcé ~/bVtn=/~.

- ~/l=/~ : ĺ
Le « ĺ » est la consonne « l » (la même que le « l » français), mais considérée et prononcée comme une voyelle, tel qu’on peut l’entendre dans certains mots anglais comme dans « bottle » qui peut être prononcé ~/bOtl=/~, avec le ~/U/~ qui est omis et le ~/l/~ devenant syllabique.

*** Diphtongues

*** Allophones
Il existe relativement peu d’allophones parmi les voyelles de le Hjalpi’, cependant on peut en relever certains comme suit :
- La prononciation standard du « ń », comme mentionné ci-dessus dans src_latex{\newline} [[Consonnes syllabiques][Consonnes syllabiques]], est ~/n=/~. Cependant, cette voyelle peut également être prononcée ~/m=/~ si le « ń » est précédé et/ou suivi par une consonne bilabiale, et il peut être palatalisé en ~/J=/~ ou ~/m'/~ si le « ń » est adjacent à une des voyelles /i/ ou /í/, ou bien la consonne /j/.
~/n=/>[m=]/_p,b,w~
~/n=/>[J=]/_i,í,j~
- Le « ĺ » peut également être palatalisé en cas d’adjacence à une des voyelles /i/ ou /í/ ou bien la consonne /j/, et donc être prononcée ~/l'=/~.
~/l=/>[l'=]/_i,í,j~

** Consonnes
En plus d’un important inventaire de voyelle, le Hjalpi’ dispose également d’un inventaire de consonnes assez important. Voici ci-dessous lesdites consonnes :

| / | >    |   | > |    | > |   | > |   | > |    | > |   | > |   | > |   | > |    | > |    | > |   | > |
|   |      | b |   | ld |   | d |   | a |   | pa |   | r |   | p |   | v |   | uv |   | ph |   | g |   |
|---+------+---+---+----+---+---+---+---+---+----+---+---+---+---+---+---+---+----+---+----+---+---+---|
|---+------+---+---+----+---+---+---+---+---+----+---+---+---+---+---+---+---+----+---+----+---+---+---|
|   | pl   | p | b |    |   |   |   | t | d |    |   | ť | ď |   |   | k | g |    |   |    |   | ' |   |
|---+------+---+---+----+---+---+---+---+---+----+---+---+---+---+---+---+---+----+---+----+---+---+---|
|   | n    |   | m |    |   |   |   |   | n |    |   |   |   |   |   |   | ň |    |   |    |   |   |   |
|---+------+---+---+----+---+---+---+---+---+----+---+---+---+---+---+---+---+----+---+----+---+---+---|
|   | t    |   |   |    |   |   |   |   | r |    |   |   |   |   |   |   |   |    |   |    |   |   |   |
|---+------+---+---+----+---+---+---+---+---+----+---+---+---+---+---+---+---+----+---+----+---+---+---|
|   | afr  |   |   | f  | v | þ | ð | s | z | ß  | ź |   |   | š | ž |   |   | x  | ŗ |    |   | h |   |
|---+------+---+---+----+---+---+---+---+---+----+---+---+---+---+---+---+---+----+---+----+---+---+---|
|   | lafr |   |   |    |   |   |   | ł |   |    |   |   |   |   |   |   |   |    |   |    |   |   |   |
|---+------+---+---+----+---+---+---+---+---+----+---+---+---+---+---+---+---+----+---+----+---+---+---|
|   | apr  |   |   |    |   |   |   | ŕ |   |    |   |   |   |   | j |   |   |    |   |    |   |   |   |
|---+------+---+---+----+---+---+---+---+---+----+---+---+---+---+---+---+---+----+---+----+---+---+---|
|   | lapr |   |   |    |   |   |   | l |   |    |   |   |   |   |   |   |   |    |   |    |   |   |   |
|---+------+---+---+----+---+---+---+---+---+----+---+---+---+---+---+---+---+----+---+----+---+---+---|
|   | sv   | w |   |    |   |   |   |   |   |    |   |   |   |   |   |   |   |    |   |    |   |   |   |

Abréviations :
| b  | bilabial        |   | pl   | plosif             |
| ld | labio-dental    |   | n    | nasal              |
| d  | dental          |   | t    | trill              |
| a  | alvéolaire      |   | sv   | semi-voyelle       |
| pa | post-alvéolaire |   | afr  | fricatif           |
| r  | rétroflexe      |   | lafr | fricatif latéral   |
| v  | velaire         |   | apr  | aproximant         |
| uv | uvulaire        |   | lapr | aproximant latéral |
| ph | pharyngal       |   |      |                    |
| g  | glottal         |   |      |                    |

- ~/p/~ : P p
- ~/b/~ : B b
- ~/t/~ : T t
- ~/d/~ : D d
- ~/t`/~ : Ţ ţ
- ~/d`/~ : Ḑ ḑ
- ~/k/~ : K k
- ~/g/~ : G g
- ~/?/~ : ' '
- ~/m/~ : M m
- ~/n/~ : N n
- ~/N/~ : Ň ň
- ~/r/~ : R r
- ~/f/~ : F f
- ~/v/~ : V v
- ~/T/~ : Þ þ
- ~/D/~ : Ð ð
- ~/s/~ : S s
- ~/z/~ : Z z
- ~/S/~ : ẞ ß
- ~/C/~ : Š š
- ~/j\/~ : Ž ž
- ~/X/~ : X x
- ~/R/~ : Ŗ ŗ
- ~/h/~ : H h
- ~/K/~ : Ł ł
- ~/r\/~ : Ŕ ŕ
- ~/j/~ : J j
- ~/l/~ : L l
- ~/w/~ : W w

*** Allophones
Plusieurs de ces consonnes disposent d’allophones, c’est à dire de prononciations alternatives à la prononciation exacte mentionnée plus haut, sans que cela n’affecte le sens des mots ou le sens d’une phrase.
- La prononciation standard du /f/ et /v/ sont respectivement ~/f/~ et ~/v/~, cependant il arrive également qu’ils soient respectivement prononcés ~/p\/~ et ~/B/~ entre deux voyelles.
~/f/>[p\]/V_V~
~/v/>[B]/V_V~
- Le ~/h\/~ est considéré comme étant un allophone du /h/, dont la prononciation standard est le ~/h/~. Cet allophone se produit entre deux voyelles et entre une consonne voisée et une voyelle ou une voyelle et une consonne voisée.
~/h/>[h\]/V_V~ (~V~ signifiant ici « voyelle » ou « consonne voisée »)
- Le /ŗ/ a pour prononciation standard le /R/, cependant il est généralement prononcé ~/R\/~ entre deux voyelles.
~/R/>[R\]/V_V~
- Le /x/ est habituellement prononcé /X/, cependant il est prononcé /x/ lorsqu’il est en contact avec une consonne fricative sourde autre que le /h/ et le /ŗ/.
~/X/>[x]/F_~
~/X/>[x]/_F~ (~F~ représentant toute fricative sourde autre que le /h/ et le /ŗ/)

** Accentuation

L’accentuation des mots en langue divine porte sur l’avant-dernière voyelle racine si le mot racine dispose de deux syllabes ou plus, sur la voyelle racine unique sinon. L’accentuation des mots étant régulière, elle n’est pas marquée par l’orthographe et la translittération de la langue.
Pour ce qui est de l’accentuation des phrases, le ton est généralement tombant, avec le terme que le locuteur estime le plus important de la phrase bénéficiant d’une remontée du ton sur ce terme précisément. Si le locuteur estime que le terme est très important, alors il peut même le prononcer avec une voix de tête, voire étirer de manière exagérée la première syllabe racine du terme. Un verbe interrogatif bénéficie nécessairement de la remontée du ton de la phrase sur ce terme, tandis qu’une phrase exclamative voit son ton recommencer à descendre à partir de la même hauteur que celle du début de phrase. Une phrase affirmative continue la descente de ton jusqu’à la dernière syllabe racine qui bénéficie d’une accentuation.

** Romanisation et translittération
La romanisation et la translittération d’une langue sont deux choses très différentes ; en effet, la première a pour but de représenter de façon grossière la prononciation de la langue avec l’alphabet latin, sans se soucier de l’orthographe exacte, tandis que la translittération a pour but de reproduire de manière précise l’orthographe de la langue transcrite, sans se soucier de savoir si le lecteur saura prononcer correctement la transcription s’il n’a pas été initié avant à la langue transcrite.

Pour moi le meilleur exemple que je puisse donner pour ce qui est de la différence entre romanisation et translittération est en Tibétain. Nous avons des termes Tibétain romanisés “dorje”, “chorten” ou encore “yak” en anglais dont une de leur translittération possible respective est “rdo rje”, “mchod brten” et “gyag”. Bien évidemment, toute personne n’ayant aucune notion de translittération du Tibétain et/ou de son orthographe peut être confuse quant à ce qu’ils viennent de lire, et c’est tout naturel : leur but est de savoir précisément comment écrire ces mots, et une personne sachant écrire en tibétain pourra, en ayant lu ces exemples, écrire les mots sans faute si je n’en ai pas fait non plus à la rédaction de cet ouvrage. Comme je l’ai indiqué, il s’agit dans cet exemple d’une romanisation anglophone ; en effet, la romanisation dépend de la langue du lecteur. Étant donné que ce dernier doit pouvoir se forger une idée de la prononciation du mot étranger, il faut utiliser les conventions de lecture de l’alphabet de sa propre langue afin d’approcher au mieux la prononciation originale. Ainsi, “dorje” en anglais pourrait être écrit « dordjé » en français, “chorten” pourrait être écrit « tchortène » (« yak » garde la même orthographe dans les deux langues, et est même dans les dictionnaires anglophones et francophones).

Ainsi, dans mon (ou mes ?) livre(s ?) qui s’adressera (s’adresseront ?) à un public général, j’utiliserai des romanisation de la langue divine si je souhaite que le lecteur ait une idée de la prononciation du mot ou de la phrase qu’il vient de rencontrer –et à l’inverse, si je souhaite être plus graphique, j’utiliserai soit la translittération, soit l’écriture native du Hjalpi’. Toujours est-il que dans cette référence grammaticale, je n’utiliserai que de la translittération (les graphèmes et lettres correspondantes furent décrites dans [[Consonnes][Consonnes]] et [[Voyelles][Voyelles]]), et ne ferai usage de la romanisation que dans ce chapitre où j’explique ci-dessous le processus de l’écriture du Hjalpi en romanisation.

Voici ci-dessous un tableau avec chaque phonème du Hjalpi’, sa translittération, et sa romanisation francophone. Pour un équivalent anglophone, se référer à la version anglophone de cet ouvrage si celle-ci existe.

| / | >       | >      |      |
|   | phonème | trans. | rom. |
|---+---------+--------+------|
|   | ~i:~    | i      | i    |
|   | ~y:~    | y      | u    |
|   | ~u:~    | u      | ou   |
|   | ~I~     | í      | i    |
|   | ~Y~     | ý      | u    |
|   | ~U~     | ú      | ou   |
|   | ~e:~    | e      | é    |
|   | ~2:~    | ò      | e    |
|   | ~o:~    | o      | o    |
|   | ~E~     | é      | è    |
|   | ~9~     | ö      | eu   |
|   | ~O~     | ó      | au   |
|   | ~a:~    | a      | a    |
|   | ~A~     | á      | a    |

* Noms
** Genres
Le Hjalpi’ dispose d’un système de genre composé de neuf éléments :
1. divin : se réfère à toute personne considérée comme divine, que ce soit par les Divins ou par les mortels (humains comme non humains). Aucune distinction n’est faite selon leur sexe biologique. Les méduses, du fait d’être une icône divine, sont considérées étant également du genre divin.
2. mental : se réfère à tout élément non physique ou concept, comme des pensées ou un événement. Les lieux physiques et temporels sont également classifiés dans le genre mental.
3. liquide : se réfère, comme son nom l’indique, à tout liquide, et en particulier à l’eau, mais ne couvre pas tous les fluides (l’air n’est pas considéré comme un liquide, malgré le fait que ce soit un fluide).
4. masculin : se réfère à tout mâle biologique humain ou semi-humain.
6. féminin : se réfère à toute femelle biologique humaine ou semi-humaine.
7. neutre : se réfère à groupe d’humain et/ou de semi-humains, ou bien à un humain ou semi-humain dont le sexe biologique est inconnu du locuteur. Se réfère aussi à tout membre du corps humain.
8. animal : se réfère à tout être mortel n’étant pas un humain ou semi-humain, ou membre d’animaux.
9. végétal : se réfère à toute plante ou végétal.
10. inanimé : se réfère à tout élément minéral ou physique ne rentrant pas dans les catégories précédentes.

Le genre est intrinsèque à tout nom, en revanche la majorité des éléments grammaticaux (comme les noms démonstratifs, pronoms, déclinaisons) et les verbes entre autres s’accordent en genre.

** Nombre
Le Hjalpi’ dispose d’un système de nombre des noms plutôt évolué, avec un total de cinq nombres :

| / | >          | >           |                                               |
|   | nombre     | déclinaison | description                                   |
|---+------------+-------------+-----------------------------------------------|
|   | singulier  | /           | un élément unique                             |
|   | singulatif | -(e)l       | un groupe indénombrable d’éléments semblables |
|   | duel       | -(a)t       | deux éléments                                 |
|   | triel      | -(e)þ       | trois éléments                                |
|   | pluriel    | -(o)st      | quatre éléments ou plus                       |

À moins d’une contre-indication dans le dictionnaire, les noms ne portent pas en eux de nombre de façon intrinsèque, mais peuvent porter leur propriété de dénombrable ou non. Dans tous les cas, *le nombre par défaut n’est pas marqué sur le nom*, les autres si, et son marquage est prioritaire sur toute autre modification grammaticale du mot racine.

Un nom dénombrable a pour nombre par défaut le singulier. Tout nom dénombrable peut également être mis à l’indénombrable via le singulatif si on ne connais pas le nombre d’éléments de ce nom dont il est question. En revanche, dès que l’on peut mettre un nombre sur la quantité d’éléments, même s’il n’est qu’approximatif voire même faux, le mot se met au duel en cas de deux éléments, au triel pour trois éléments et au pluriel pour quatre éléments ou plus. Les mots indénombrables ne connaissent que le singulatif et ne peuvent être mis à un autre nombre.

Le singulier, le singulatif, le duel et le triel sont parfois regroupé dans le super-singulier pour certaines utilisations grammaticales, le pluriel restant à part.
Comme précisé ci-dessus, le singulatif permet de regrouper des éléments semblables non dénombrés. Ainsi, « du sucre » ou « des arbres » sera au nombre singulatif.

* Cas grammaticaux
Le Hjalpi’ est une langue très riche en cas grammaticaux et en déclinaisons. Cela lui permet ainsi d’exprimer une grande précision dans un nombre minimal de mots, et lui donne également une grande liberté quant à l’ordre des mots dans la phrase. En revanche, cela implique également un système complexe de déclinaisons qu'il faut mémoriser.

Les déclinaisons se présentent sous la forme de particules (préfixes, infixes et suffixes) à ajouter au mot racine. Voici un exemple d’utilisation. Notez que la partie entre parenthèse peut ne pas être spécifiée, auquel cas il faudra se référer à l’harmonisation des voyelles ou des consonnes selon le cas si une voyelle est accolée à une autre voyelle, de même pour les consonnes.
+ V(C)- :: le préfixe est (ou fini par) une voyelle V, il se rajoute donc au début du mot racine. Si ce dernier commence avec une voyelle, la consonne C est rajoutée entre la voyelle V et le mot racine.
+ C(V)- :: le préfixe est (ou fini par) une consonne, il se rajoute donc au début du mot racine. Si ce dernier commence avec une consonne, la voyelle (V) est rajoutée entre la consonne C et le mot racine.
+ -C_{1}V(C_2)- :: l’infixe commence par consonne, il se placera donc à la fin du mot racine, entre la dernière voyelle et la dernière consonne du mot racine. Si le mot racine se termine par une voyelle, l’ensemble C_{1}VC_2 agira comme un suffixe.
+ -(C_{1})VC_2- :: l’infixe commence par une voyelle, il se placera donc au début du mot racine, entre la première consonne et la première voyelle. Si le mot racine commence par une voyelle, l’ensemble C_{1}VC_2 agira comme un préfixe.
+ -(C)V :: le suffixe est (ou commence par) une voyelle, il se placera donc à la fin du mot racine. Si ce dernier se termine par une voyelle, la consonne C sera ajoutée entre le mot racine et le suffixe.
+ -(V)C :: le suffixe est (ou commence par) une consonne, il se placera donc à la fin du mot racine. Si ce dernier se termine par une consonne, la voyelle V sera ajoutée entre le mot racine et le suffixe.

Notez également que la ou les voyelles présentée dans le tableau s’accorde en ouverture et longueur avec la voyelle du mot racine sur laquelle porte l’accent. Ainsi, ajouts de voyelles sur /mén/ via des déclinaisons s’accorderont en voyelles longues et ouvertes.

Voici ci-dessous un tableau exposant la forme de chaque déclinaison selon le cas grammatical et le genre/nombre. Le numéro se réfère au numéro du genre tel que décrit dans [[*Genres][Genres]], le super-singulier (tel que décrit dans [[*Nombre][Nombre]]) est représenté par « s » et le pluriel par « p ».

| / | <>                   | >       | >        | >       | >       | >       | >       |
|   |                      | 1s      | 1p       | 2s      | 2p      | 3s      | 3p      |
|---+----------------------+---------+----------+---------+---------+---------+---------|
|   | [[*Abessif][abessif]]              | e(m)-   | e(ň)-    | e(n)-   | e(n)-   | e(l)-   | e(dl)-  |
|   | [[*Ablatif][ablatif]]              | l(i)-   | l(e)-    | li(s)-  | le(ž)-  | l(i)-   | ĺ(ž)-   |
|   | [[*Absolutif][absolutif]]            | -(ts)a  | -(ts)a   | -(tß)a  | -(tß)a  | -(ts)a  | -(ts)a  |
|   | [[*Accusatif][accusatif]]            | -vo     | -vwo     | -vu     | -vwu    | -vo     | -vo     |
|   | [[*Accusatif temporel][accusatif temporel]]   | -źu     | -źu      | -źu     | -źu     | -źoy    | -źou    |
|   | [[*Adessif][adessif]]              | ix(a)-  | ix(e)-   | ix(a)-  | ix(e)-  | ix(a)-  | ix(e)-  |
|   | adverbial            |         |          |         |         |         |         |
|   | agentif              |         |          |         |         |         |         |
|   | [[*Allatif][allatif]]              | -li(ß)- | -li(ts)- | -li(ð)- | -li(ð)- | -li-    | -li-    |
|   | antessif             |         |          |         |         |         |         |
|   | apudessif            |         |          |         |         |         |         |
|   | aversif              |         |          |         |         |         |         |
|   | [[*Causal][causal]]               | -(o)by  | -(o)bu   | -(u)by  | -(o)by  | -(ob)y  | -(b)y   |
|   | comitatif            |         |          |         |         |         |         |
|   | comparatif           |         |          |         |         |         |         |
|   | datif                |         |          |         |         |         |         |
|   | [[*Distributif][distributif]]          | xe(l)-  | xe(l)-   | xe(l)-  | xe(l)-  | ŗe(j)-  | ŗe(j)-  |
|   | distributif-temporel |         |          |         |         |         |         |
|   | [[*Délatif][délatif]]              | ß(a)-   | ß(e)-    | ß(e)-   | ß(e)-   | ß(ai)-  | ß(a)-   |
|   | [[*Élatif][élatif]]               | -(a)ły  | -(e)ły   | -(a)ły  | -(a)łu  | -(e)ły  | -(e)ły  |
|   | équatif              |         |          |         |         |         |         |
|   | [[*Ergatif][ergatif]]              | -(u)jo  | -(y)jo   | -(í)jo  | -(é)jo  | -(u)jo  | -(u)jo  |
|   | ergatif-génitif      |         |          |         |         |         |         |
|   | [[*Essif][essif]]                | -(þ)yd- | -(þ)yd-  | -(þ)ud- | -(þ)ud- | -(þ)yd- | -(þ)ud- |
|   | [[*Essif-formel][essif-formel]]         | -(ò)ţ   | -(ò)d    | -(o)d   | -(o)ḑ   | -(ò)d   | -(ò)ň   |
|   | [[*Essif-modal][essif-modal]]          | -(’)uix | -(’)uix  | -’yiŗ   | -(’)yiŗ | -(’)uŗ  | -(’)uiŗ |
|   | excessif             |         |          |         |         |         |         |
|   | génitif              |         |          |         |         |         |         |
|   | identique            |         |          |         |         |         |         |
|   | [[*Illatif][illatif]]              | -(p)òn- | -(p)on-  | -(f)òn- | -(f)on- | -òn-    | -(p)òn- |
|   | inessif              |         |          |         |         |         |         |
|   | initiatif            |         |          |         |         |         |         |
|   | instructif           |         |          |         |         |         |         |
|   | instrumental         |         |          |         |         |         |         |
|   | intratif             |         |          |         |         |         |         |
|   | latif                |         |          |         |         |         |         |
|   | limitatif            |         |          |         |         |         |         |
|   | locatif              |         |          |         |         |         |         |
|   | nominal              |         |          |         |         |         |         |
|   | [[*Nominatif][nominatif]]            | p(a)-   | p(e)-    | p(a)-   | p(e)-   | p(a)-   | p(a)-   |
|   | [[*Oblique][oblique]]              | -(ŗ)eß  | -(ŗ)eßt  | -(ŗ)ef  | -(ŗ)eft | -(ŗ)eß  | -(x)eß  |
|   | orientatif           |         |          |         |         |         |         |
|   | partitif             |         |          |         |         |         |         |
|   | pégatif              |         |          |         |         |         |         |
|   | perlatif             |         |          |         |         |         |         |
|   | pertingent           |         |          |         |         |         |         |
|   | postessif            |         |          |         |         |         |         |
|   | privatif             |         |          |         |         |         |         |
|   | prolatif             |         |          |         |         |         |         |
|   | révertif             |         |          |         |         |         |         |
|   | semplatif            |         |          |         |         |         |         |
|   | sociatif             |         |          |         |         |         |         |
|   | subessif             |         |          |         |         |         |         |
|   | sublatif             |         |          |         |         |         |         |
|   | superessif           |         |          |         |         |         |         |
|   | temporel             |         |          |         |         |         |         |
|   | terminatif           |         |          |         |         |         |         |
|   | translatif           |         |          |         |         |         |         |
|   | vocatif              |         |          |         |         |         |         |

| / | <>                   | >       | >       | >       | >       | >        | >        |
|   |                      | 4s      | 4p      | 5s      | 5p      | 6s       | 6p       |
|---+----------------------+---------+---------+---------+---------+----------+----------|
|   | [[*Abessif][abessif]]              | e(ň)-   | e(t)-   | e(st)-  | e(ßt)-  | e(nt)-   | e(ňt)-   |
|   | [[*Ablatif][ablatif]]              | li(ß)-  | li(ź)-  | li(ß)-  | li(ź)-  | li(s)-   | li(z)-   |
|   | [[*Absolutif][absolutif]]            | -(t)a   | -(š)a   | -(p)a   | -(v)a   | -(st)a   | -(ž)a    |
|   | [[*Accusatif][accusatif]]            | -(e)vo  | -(e)vo  | -(e)vo  | -(e)vo  | -(a)vo   | -(a)vo   |
|   | [[*Accusatif temporel][accusatif temporel]]   | -(a)źu  | -(e)źu  | -(u)źu  | -(ai)źu | -(i)źu   | -(u)źu   |
|   | [[*Adessif][adessif]]              | iź(a)-  | iź(ei)- | iź(a)-  | iź(ei)- | iź(a)-   | iź(ei)-  |
|   | adverbial            |         |         |         |         |          |          |
|   | agentif              |         |         |         |         |          |          |
|   | [[*Allatif][allatif]]              | -li(s)- | -li(ź)- | -li(z)- | -li(š)- | -li(x)-  | -li(x)-  |
|   | antessif             |         |         |         |         |          |          |
|   | apudessif            |         |         |         |         |          |          |
|   | aversif              |         |         |         |         |          |          |
|   | [[*Causal][causal]]               | -(o)by  | -(o)by  | -(o)by  | -(o)by  | -(o)bu   | -(o)bu   |
|   | comitatif            |         |         |         |         |          |          |
|   | comparatif           |         |         |         |         |          |          |
|   | datif                |         |         |         |         |          |          |
|   | [[*Distributif][distributif]]          | he(l)-  | he(l)-  | he(l)-  | he(l)-  | ha(l)-   | ha(l)-   |
|   | distributif-temporel |         |         |         |         |          |          |
|   | [[*Délatif][délatif]]              | š(a)-   | š(e)-   | ž(a)-   | ž(e)-   | ž(a)-    | ž(a)-    |
|   | [[*Élatif][élatif]]               | -(ł)y   | -(ł)y   | -(ł)y   | -(ł)yi  | -(ł)u    | -(ł)yi   |
|   | équatif              |         |         |         |         |          |          |
|   | [[*Ergatif][ergatif]]              | -(ò)jo  | -(y)jo  | -(lj)o  | -(lj)o  | -(mj)o   | -(lj)o   |
|   | ergatif-génitif      |         |         |         |         |          |          |
|   | [[*Essif][essif]]                | -(þ)yḑ- | -(þ)yḑ- | -(ð)yţ- | -(ð)yţ- | -(þ)ud-  | -(þ)ud-  |
|   | [[*Essif-formel][essif-formel]]         | -(ţ)òd  | -(ţ)ed  | -(ţ)òd  | -òd     | -(ò)d    | ò(d)-    |
|   | [[*Essif-modal][essif-modal]]          | -(’)uŗ  | -(’)uŗ  | -’u     | -(’)yŗ  | -(’)yiŗ  | -(’)yŗ   |
|   | excessif             |         |         |         |         |          |          |
|   | génitif              |         |         |         |         |          |          |
|   | identique            |         |         |         |         |          |          |
|   | [[*Illatif][illatif]]              | -(s)òn- | -(s)en- | -(s)en- | -(s)an- | -(ps)òn- | -(ps)en- |
|   | inessif              |         |         |         |         |          |          |
|   | initiatif            |         |         |         |         |          |          |
|   | instructif           |         |         |         |         |          |          |
|   | instrumental         |         |         |         |         |          |          |
|   | intratif             |         |         |         |         |          |          |
|   | latif                |         |         |         |         |          |          |
|   | limitatif            |         |         |         |         |          |          |
|   | locatif              |         |         |         |         |          |          |
|   | nominal              |         |         |         |         |          |          |
|   | [[*Nominatif][nominatif]]            | pa(n)-  | pa(ń)-  | pń-     | pń-     | pa(m)-   | pa-      |
|   | [[*Oblique][oblique]]              | -(ŗ)ef  | -(ŗ)òß  | -(ŗ)ef  | -(ŗ)òß  | -(ŗ)ef   | -(ŗ)òß   |
|   | orientatif           |         |         |         |         |          |          |
|   | partitif             |         |         |         |         |          |          |
|   | pégatif              |         |         |         |         |          |          |
|   | perlatif             |         |         |         |         |          |          |
|   | pertingent           |         |         |         |         |          |          |
|   | postessif            |         |         |         |         |          |          |
|   | privatif             |         |         |         |         |          |          |
|   | prolatif             |         |         |         |         |          |          |
|   | révertif             |         |         |         |         |          |          |
|   | semplatif            |         |         |         |         |          |          |
|   | sociatif             |         |         |         |         |          |          |
|   | subessif             |         |         |         |         |          |          |
|   | sublatif             |         |         |         |         |          |          |
|   | superessif           |         |         |         |         |          |          |
|   | temporel             |         |         |         |         |          |          |
|   | terminatif           |         |         |         |         |          |          |
|   | translatif           |         |         |         |         |          |          |
|   | vocatif              |         |         |         |         |          |          |


| / | <>                   | >       | >       | >        | >       | >         | >         |
|   |                      | 7s      | 7p      | 8s       | 8p      | 9s        | 9p        |
|---+----------------------+---------+---------+----------+---------+-----------+-----------|
|   | [[*Abessif][abessif]]              | e-      | e(s)-   | e-       | e(ňt)-  | e(mt)-    | e(ňt)-    |
|   | [[*Ablatif][ablatif]]              | lń(d)-  | lń(d)-  | ĺ(z)-    | ĺ(z)-   | ĺ(v)-     | ĺ(v)-     |
|   | [[*Absolutif][absolutif]]            | -(r)a   | -(r)a   | -(x)a    | -(š)a   | -(ŗ)a     | -(ž)a     |
|   | [[*Accusatif][accusatif]]            | -(u)vo  | -(u)vo  | -vu      | -vu     | -vy       | -vy       |
|   | [[*Accusatif temporel][accusatif temporel]]   | -(o)źu  | -(o)źu  | -(o)źu   | -(o)źu  | -(o)źu    | -(o)źu    |
|   | [[*Adessif][adessif]]              | iź(a)-  | iź(ei)- | iŗ(a)-   | iŗ(a)-  | iŗ(e)-    | iŗ(e)-    |
|   | adverbial            |         |         |          |         |           |           |
|   | agentif              |         |         |          |         |           |           |
|   | [[*Allatif][allatif]]              | -li(ŗ)- | -li(ŗ)- | -li(þt)- | -li(v)- | -(l)iþ-   | -(l)ið-   |
|   | antessif             |         |         |          |         |           |           |
|   | apudessif            |         |         |          |         |           |           |
|   | aversif              |         |         |          |         |           |           |
|   | [[*Causal][causal]]               | -(o)vu  | -(e)vy  | -(e)vy   | -(e)vy  | -vy       | -vy       |
|   | comitatif            |         |         |          |         |           |           |
|   | comparatif           |         |         |          |         |           |           |
|   | datif                |         |         |          |         |           |           |
|   | [[*Distributif][distributif]]          | hei(l)- | hea(l)- | hea(l)-  | hea(l)- | še(l)-    | še(l)-    |
|   | distributif-temporel |         |         |          |         |           |           |
|   | [[*Délatif][délatif]]              | ß(eu)-  | ß(eu)-  | ß(a)-    | ß(a)-   | ßa(l)-    | ße(l)-    |
|   | [[*Élatif][élatif]]               | -ły     | -(a)ły  | -(ł)ay   | -(ł)ey  | -(ł)ay    | -łay      |
|   | équatif              |         |         |          |         |           |           |
|   | [[*Ergatif][ergatif]]              | -jo     | -jo     | -(o)jo   | -(e)jo  | -(u)jo    | -(u)jo    |
|   | ergatif-génitif      |         |         |          |         |           |           |
|   | [[*Essif][essif]]                | -þy(d)- | -þy(d)- | -þy(d)-  | -þy(d)- | -(oi)þyd- | -(oi)þyd- |
|   | [[*Essif-formel][essif-formel]]         | -òd     | -(ò)ns  | -òd      | -òts    | -(ò)ß     | -(ò)ßt    |
|   | [[*Essif-modal][essif-modal]]          | -(’)uŗ  | -(’)u   | -(’)u    | -(’)ust | -(’)uŗ    | -(’)uŗ    |
|   | excessif             |         |         |          |         |           |           |
|   | génitif              |         |         |          |         |           |           |
|   | identique            |         |         |          |         |           |           |
|   | [[*Illatif][illatif]]              | -òn-    | -(v)òn- | -(ŕ)òn-  | -(ŕ)òn- | -(ŕ)òn-   | -(ŕ)en-   |
|   | inessif              |         |         |          |         |           |           |
|   | initiatif            |         |         |          |         |           |           |
|   | instructif           |         |         |          |         |           |           |
|   | instrumental         |         |         |          |         |           |           |
|   | intratif             |         |         |          |         |           |           |
|   | latif                |         |         |          |         |           |           |
|   | limitatif            |         |         |          |         |           |           |
|   | locatif              |         |         |          |         |           |           |
|   | nominal              |         |         |          |         |           |           |
|   | [[*Nominatif][nominatif]]            | pa(l)-  | pa(l)-  | pa(ß)-   | pe(ß)-  | pa-       | pa-       |
|   | [[*Oblique][oblique]]              | -(x)eß  | -(x)eß  | -(x)eß   | -(x)eß  | -(x)uiß   | -(x)oiß   |
|   | orientatif           |         |         |          |         |           |           |
|   | partitif             |         |         |          |         |           |           |
|   | pégatif              |         |         |          |         |           |           |
|   | perlatif             |         |         |          |         |           |           |
|   | pertingent           |         |         |          |         |           |           |
|   | postessif            |         |         |          |         |           |           |
|   | privatif             |         |         |          |         |           |           |
|   | prolatif             |         |         |          |         |           |           |
|   | révertif             |         |         |          |         |           |           |
|   | semplatif            |         |         |          |         |           |           |
|   | sociatif             |         |         |          |         |           |           |
|   | subessif             |         |         |          |         |           |           |
|   | sublatif             |         |         |          |         |           |           |
|   | superessif           |         |         |          |         |           |           |
|   | temporel             |         |         |          |         |           |           |
|   | terminatif           |         |         |          |         |           |           |
|   | translatif           |         |         |          |         |           |           |
|   | vocatif              |         |         |          |         |           |           |
src_latex{\newpage}
Ci-dessous, chaque cas grammatical sera expliqué ainsi que son utilisation dans le Hjalpi’.

** Lieu
*** Adessif
Le cas adessif est utilisé pour exprimer un lieu adjacent au nom décliné. Exemples :
- /ixÐbńo/ : à côté de Dbńo
- /íŗmén/ : près de la maison

** Déplacement depuis un point
*** Ablatif
Afin de décrire un déplacement depuis un point dans un lieu ouvert, le cas ablatif peut être utilisé pour décliner ledit point pour le marquer en tant que tel. Exemples :
- /ĺmén/ : depuis l’extérieur de la maison
- /liÐbńo/ : depuis l’extérieur de Ðbńo, depuis l’extérieur de la ville

*** Délatif
Le cas délatif exprime un déplacement ou mouvement depuis la surface d’un lieu ou d’un objet.
- /ßémén/ : depuis le toit de la maison
- /ßeraòmm/ : depuis la couverture du livre / depuis la surface d’un livre ouvert

*** Élatif
Le cas élatif exprime un mouvement ou la provenance de quelque chose depuis l’intérieur du lieu ou de l’objet décliné.
- /ménay/ : depuis l’intérieur de la maison
- /nareły/ : depuis la rivière (sous-entendu dans l’eau)

Cas intéressant, l’élatif peut également être utilisé pour ce qui est des citations de livres ou tout autre support écrit. Ainsi, on peut utiliser /raòmay/ (« depuis l’intérieur du livre ») pour citer un passage du livre dont il est question.
** Déplacement vers un point
*** Allatif
L’allatif permet de marquer le lieu ou le point sur lequel se produit un mouvement. /Attention à l’irrégularité du placement de la déclinaison pour le genre inanimé !/ Exemple :
- /riþaòm/ : un déplacement ou un mouvement se fait sur un livre

*** Illatif
L’illatif permet de marquer le lieu à l’intérieur du quel s’effectue un mouvement ou déplacement. Exemple :
- /ménén/ : à l’intérieur de la maison
- /nònarat/ : dans deux rivière

** Déplacement via un point
** Temporalité
*** Accusatif temporel
Le cas accusatif, dans un contexte de temporalité, sert à désigner une durée de temps. À ne pas confondre avec le cas [[*Accusatif][accusatif]] d’alignement morphosyntaxique.
- J’ai dormi *durant sept heures*.
*** Essif-temporel
L’essif-temporel se comporte et se décline exactement comme l’[[*Essif][essif]], mais sert dans ce cas à déterminer une date ou un temps durant lequel une action se déroule.
- /ðúdúbém/ : lors du septième jour de la semaine

** Alignement Morphosyntaxique
*** Absolutif
*Ergatif* Le cas absolutif marque de sujet des verbes transitif et l’objet des verbes intransitif (le patient) dans une phrase ou dans une proposition ergative. En opposition au cas [[*Ergatif][ergatif]], il peut être également assumé par les cas [[*Accusatif][accusatif]] ou [[*Nominatif][nominatif]] dans les phrases ou propositions nominatives.
- *Je* dors.
- Je lis *un livre*.

*** Accusatif
*Nominatif* L’accusatif permet de marquer l’objet d’un verbe transitif (le patient) dans les phrases ou propositions nominatives, et s’oppose au cas [[*Nominatif][nominatif]]. L’accusatif peut être assumé par le cas [[*Absolutif][absolutif]] dans les phrases ergatives.
- Je lis *un livre*.

*** Ergatif
Le cas ergatif marque le sujet des verbes transitifs (l’agent) dans une phrase ou proposition ergative et s’oppose à l’[[*Absolutif][absolutif]]. Il peut être assumé par le cas [[*Nominatif][nominatif]] dans les phrases ou propositions nominatives.
- *Je* lis un livre.

*** Nominatif
Le cas nominatif marque le sujet des verbes transitifs et intransitifs (l’agent) dans une phrase ou proposition nominative, et s’oppose au cas [[*Accusatif][accusatif]]. Il peut être assumé par les cas [[*Ergatif][ergatif]] et [[*Absolutif][absolutif]] dans les phrases ou propositions ergatives.
- *Je* dors.
- *Je* lis un livre.

*** Oblique
Le cas oblique sert à citer l’élément décliné, mettant le terme décliné à l’oblique comme entre guillemets. L’oblique peut également se marquer après le verbe d’une phrase ou proposition afin de marquer la citation, tel que la particule « to » en japonais ou « zhes » en tibétain. Dans le dernier cas, le verbe ne sera pas décliné, mais on lui accolera la particule « ŗeß ».
- Elle m’a dit *« je viens demain »*.
- Il m’a dit *qu’il l’a vu hier*.
- Ce n’était pas un *« accident »*, comme il le dit.

** Relation
*** Causal
Le cas causal permet de marquer la raison de l’action exprimée par le verbe principal de la phrase ou de la proposition (similaire à la particule grammaticale « kara » en japonais). Exemples :
- /hjalpi’váruby/ : du fait de la langue Hjalpi’
- /pánámóbý/ : du fait du père

*** Distributif
Le cas distributif indique une distribution égale entre les éléments déterminés. En français, il s’agit l’équivalent du « par » comme dans « il n’y a *par commune* qu’une seule mairie ».
- /šereòm/ : par livre
- /háðenmóíl/ : par individu

** Sémantique
** État
*** Abessif
Le cas abessif est un cas grammatical exprimant l’absence de l’élément décliné. L’équivalent en français est « sans X ». Exemple dans quelques langues naturelles :
- « sans parler »
- « excepté » (sans prendre dans le nombre)

*** Essif
L’essif exprime un état temporaire ou une qualité temporaire. Il s’agit du cas général pouvant se spécialiser en [[*Essif-formel][essif-formel]] pour déterminer une qualité, ou en [[*Essif-modal][essif-modal]] pour un état. Il peut également être utilisé pour des questions temporelles, voir [[*Essif-temporel][Essif-temporel]].
- /hjydalpel/ : en qualité de dieux, en tant que dieux (/hjalp/ étant au singulatif)
- /moiþydén/ : en tant que maison

*** Essif-formel
L’essif-formel est une spécialisation de l’[[*Essif][essif]] permettant d’exprimer une qualité physique.

*** Essif-modal
L’essif-formel est une spécialisation de l’[[*Essif][essif]] permettant d’exprimer l’état du sujet ou de l’agent (dans les phrases ou propositions nominatives), ou le sujet ou le patient (dans les phrases ou propositions ergatives).

* Adjectifs
* Adverbes
* Verbes
* Pronoms et déterminants
* Nombres
** Nombres Cardinaux
** Nombres Ordinaux
* Interjections
* Interrogation
* Syntaxe

#  LocalWords:  super-singulier non-arrondie pré-fermée Ðbńo
