#+TITLE: Grammaire du Hjalpi’
#+INCLUDE: "../headers.org"

* Introduction
Le Hjalpi’ est la langue parlée par les dieux dans l’univers de mon roman. La langue dont je présente ci-dessous la grammaire n’est cependant pas réellement la langue divine mais la représente ; en effet, le Hjalpi’ a été imaginée comme étant bien trop complexe pour être entièrement apprise par un humain, l’élaboration de phrases simples requière quelques années d’études déjà. Bien évidemment, il est impossible pour un humain de créer une telle langue, mais je reste toujours dans cette optique de création de langue complexe, et le résultat me paraîtra complexe mais il se peut que pour certains (du fait des langues qu’ils maîtrisent déjà) n’aient pas cette impression.

Cette langue sera également utilisée pour créer d’autres langues qui auront évolué depuis la langue divine en des langues (me paraissant) beaucoup plus simples afin de créer des langues pour les mortels.

Cette grammaire suppose que ses lecteurs ont un minimum de connaissances linguistiques de par sa nature de grammaire de référence, et n’est donc pas adaptée à un apprentissage de la langue et aux personnes sans connaissances linguistiques. Pour ces personnes, un autre ouvrage sera écrit afin de permettre l’apprentissage du Hjalpi’ sans nécessité de prérequis linguistiques.

** Abréviations utilisées
Dans cet ouvrage seront souvent utilisés des gloses afin de noter le détail grammatical de phrases ou de termes, et ces dernières emploient quasiment systématiquement des abréviations pour les termes grammaticaux. Voici donc la liste alphabétique de ces abréviations et de leur significations :

src_latex{\begin{multicols}{2}}

- 1DU :: première personne exclusive duel
- 1IDU :: première personne inclusive duel
- 1IPL :: première personne inclusive pluriel
- 1IS :: première personne inclusive singulier
- 1ISGV :: première personne inclusive singulatif
- 1ITRI :: première personne inclusive triel
- 1PL :: première personne exclusive pluriel
- 1S :: première personne exclusive singulier
- 1SGV :: première personne exclusive singulatif
- 1TRI :: première personne exclusive triel
- 2DU :: seconde personne duel
- 2PL :: seconde personne pluriel
- 2S :: seconde personne singulier
- 2SGV :: seconde personne singulatif
- 2TRI :: seconde personne triel
- 3DU :: troisième personne duel
- 3PL :: troisième personne pluriel
- 3S :: troisième personne singulier
- 3SGV :: troisième personne singulatif
- 3TRI :: troisième personne triel
- ABE :: [[cas-abe][abessif]] ([[decl-morph-decl][cas]])
- ABL :: [[cas-abl][ablatif]] ([[decl-morph-decl][cas]])
- ABS :: [[cas-abs][absolutif]] ([[decl-morph-decl][cas]])
- ABST :: abstrait ([[morpho-nom-genre][genre]])
- ACC :: [[cas-acc][accusatif]] ([[decl-morph-decl][cas]])
- ACC.TEMP :: [[cas-atemp][accusatif-temporel]] ([[decl-morph-decl][cas]])
- ADE :: [[cas-ade][adessif]] ([[decl-morph-decl][cas]])
- ADV :: [[cas-adv][adverbial]] ([[decl-morph-decl][cas]])
- ALL :: [[cas-all][allatif]] ([[decl-morph-decl][cas]])
- ANML :: animal ([[morpho-nom-genre][genre]])
- ANTE :: [[cas-ante][antessif]] ([[decl-morph-decl][cas]])
- ANTIP :: antipassif ([[verbes-valence][voix]])
- APUD :: [[cas-apud][apudessif]] ([[decl-morph-decl][cas]])
- ATL :: atélique ([[verbes-aspects][aspect]])
- AVRS :: [[cas-avrs][aversif]] ([[decl-morph-decl][cas]])
- BEN :: [[cas-ben][bénéfactif]] ([[decl-morph-decl][cas]])
- CAUS :: [[cas-caus][causal]] ([[decl-morph-decl][cas]])
- COM :: [[cas-com][comitatif]] ([[decl-morph-decl][cas]])
- COMP :: [[cas-comp][comparatif]] ([[decl-morph-decl][cas]])
- COND :: [[mode-cond][conditionnel]] ([[verbes-modes][mode]])
- DAT :: [[cas-dat][datif]] ([[decl-morph-decl][cas]])
- DEF.ART :: article défini ([[noms-articles][article]])
- DEL :: [[cas-del][délatif]] ([[decl-morph-decl][cas]])
- DISTR :: [[cas-distributif][distributif]] ([[decl-morph-decl][cas]])
- DISTR.TEMP :: [[cas-distemp][distributif-temporel]] ([[decl-morph-decl][cas]])
- DU :: duel ([[morpho-nom-nombre][nombre]])
- ELA :: [[cas-ela][élatif]] ([[decl-morph-decl][cas]])
- ENERG :: [[mode-energ][énergétique]] ([[verbes-modes][mode]])
- EQU :: [[cas-equ][équatif]] ([[decl-morph-decl][cas]])
- ERG :: [[cas-erg][ergatif]] ([[decl-morph-decl][cas]])
- ESS :: [[cas-ess][essif]] ([[decl-morph-decl][cas]])
- ESSFRM :: [[cas-essfrm][essif-formel]] ([[decl-morph-decl][cas]])
- ESSMOD :: [[cas-essmod][essif modal]] ([[decl-morph-decl][cas]])
- EXESS :: [[cas-exess][exessif]] ([[decl-morph-decl][cas]])
- F :: féminin ([[morpho-nom-genre][genre]])
- FANT :: futur antérieur ([[verbes-temps][temps]])
- FDIS :: futur distant ([[verbes-temps][temps]])
- FNEA :: futur proche ([[verbes-temps][temps]])
- FPTR :: futur postérieur ([[verbes-temps][temps]])
- FUT :: futur moyen ([[verbes-temps][temps]])
- GEN :: [[cas-gen][génitif]] ([[decl-morph-decl][cas]])
- GRV :: [[mode-grv][gérondif]] ([[verbes-modes][mode]])
- HP :: [[mode-hp][hypothétique]] ([[verbes-modes][mode]])
- HUM :: sur-genre humain ([[morpho-nom-genre][genre]])
- ILL :: [[cas-ill][illatif]] ([[decl-morph-decl][cas]])
- IMP :: [[mode-imp][impératif]] ([[verbes-modes][mode]])
- IN :: inanimé ([[nom-sur-genre][sur-genre]])
- INAN :: inanimé ([[morpho-nom-genre][genre]])
- IND :: [[mode-ind][indicatif]] ([[verbes-modes][mode]])
- INDF.ART :: article indéfini ([[noms-articles][article]])
- INE :: [[cas-ine][inessif]] ([[decl-morph-decl][cas]])
- INF :: [[mode-inf][infinitif]] ([[verbes-modes][mode]])
- INITI :: [[cas-initi][initiatif]] ([[decl-morph-decl][cas]])
- INS :: [[cas-instr][instrumental]] ([[decl-morph-decl][cas]])
- INSC :: [[cas-insc][instructif]] ([[decl-morph-decl][cas]])
- IPFV :: imperfectif ([[verbes-aspects][aspect]])
- ITRT :: [[cas-itrt][intratif]] ([[decl-morph-decl][cas]])
- LAT :: [[cas-lat][latif]] ([[decl-morph-decl][cas]])
- LIQ :: liquide ([[morpho-nom-genre][genre]])
- LMT :: [[cas-lmt][limitatif]] ([[decl-morph-decl][cas]])
- LOC :: [[cas-loc][locatif]] ([[decl-morph-decl][cas]])
- M :: masculin ([[morpho-nom-genre][genre]])
- N :: neutre ([[morpho-nom-genre][genre]])
- NHUM :: sur-genre non-humain
- NOM :: [[cas-nom][nominatif]] ([[decl-morph-decl][cas]])
- NOMIN :: [[cas-nomin][nominal]] ([[decl-morph-decl][cas]])
- OBL :: [[cas-obl][oblique]] ([[decl-morph-decl][cas]])
- OBJS :: objectif fort ([[verbes-modes][certaineté]])
- OBJW :: objectif faible ([[verbes-modes][certaineté]])
- OPT :: [[mode-opt][optatif]] ([[verbes-modes][mode]])
- ORI :: [[cas-ori][orientatif]] ([[decl-morph-decl][cas]])
- PAS :: passé moyen ([[verbes-temps][temps]])
- PASS :: passif ([[verbes-valence][voix]])
- PCP :: [[mode-pcp][participe]] ([[verbes-modes][mode]])
- PDIS :: passé distant ([[verbes-temps][temps]])
- PEG :: [[cas-peg][pégatif]] ([[decl-morph-decl][cas]])
- PER :: [[cas-per][perlatif]] ([[decl-morph-decl][cas]])
- PERT :: [[cas-pert][pertingent]] ([[decl-morph-decl][cas]])
- PFV :: perfectif ([[verbes-aspects][aspect]])
- PL :: pluriel ([[morpho-nom-nombre][nombre]])
- PLNT :: végétal ([[morpho-nom-genre][genre]])
- PNEA :: passé proche ([[verbes-temps][temps]])
- POSS :: [[cas-poste][possessif]] ([[decl-morph-decl][cas]])
- POSTE :: [[cas-poste][postessif]] ([[decl-morph-decl][cas]])
- POT :: [[mode-pot][potentiel]] ([[verbes-modes][mode]])
- PRES :: présent ([[verbes-temps][temps]])
- PROG :: progressif ([[verbes-aspects][aspect]])
- PROL :: [[cas-prol][prolatif]] ([[decl-morph-decl][cas]])
- PRV :: [[cas-prv][privatif]] ([[decl-morph-decl][cas]])
- PTV :: [[cas-ptv][partitif]] ([[decl-morph-decl][cas]])
- Q :: [[mode-q][interrogatif]] ([[verbes-modes][mode]])
- S :: singulier ([[morpho-nom-nombre][nombre]])
- SAC :: sacré ([[morpho-nom-genre][genre]])
- SBJS :: subjectif fort ([[verbes-modes][certaineté]])
- SBJV :: [[mode-sbjv][subjonctif]] ([[verbes-modes][mode]])
- SBJW :: subjectif faible ([[verbes-modes][certaineté]])
- SEMPL :: [[cas-sempl][semplatif]] ([[decl-morph-decl][cas]])
- SGV :: singulatif ([[morpho-nom-nombre][nombre]])
- SIM :: [[cas-sim][identique]] ([[decl-morph-decl][cas]])
- SOC :: [[cas-soc][sociatif]] ([[decl-morph-decl][cas]])
- SPIR :: spirituel ([[nom-sur-genre][sur-genre]])
- SS :: super-singulier ([[morpho-nom-nombre][nombre]])
- SUBE :: [[cas-sube][subessif]] ([[decl-morph-decl][cas]])
- SUBL :: [[cas-subl][sublatif]] ([[decl-morph-decl][cas]])
- SUPE :: [[cas-supe][superessif]] ([[decl-morph-decl][cas]])
- TEMP :: [[cas-temp][temporel]] ([[decl-morph-decl][cas]])
- TERM :: [[cas-term][terminatif]] ([[decl-morph-decl][cas]])
- TRANSL :: [[cas-transl][translatif]] ([[decl-morph-decl][cas]])
- TRI :: triel ([[morpho-nom-nombre][nombre]])
- VOC :: [[cas-voc][vocatif]] ([[decl-morph-decl][cas]])

src_latex{\end{multicols}}

* Sons et système d’écriture
** Phonologie
Dans cet ouvrage, j’utiliserai principalement la translittération des mots, expressions et phrases du Hjalpi’ pour illustrer mes propos, exemples et explications de la grammaire de cette langue. Toutefois, il est important de savoir comment correctement prononcer le Hjalpi’, et pour cela j’utiliserai l’alphabet phonétique international afin de retranscrire la prononciation correcte du Hjalpi’. Il est important de relever les deux styles différents de transcription phonétique qui seront utilisés dans cet ouvrage :
-  /transcription large/ :: ce type de transcription ne prend pas en compte les divers cas d’allophonie présents en Hjalpi’ et retranscrit individuellement chaque symbole ayant une signification phonétique dans son orthographe translittérée.
- [transcription rapprochée] :: ce style de transcription prend en compte les changements de prononciation dû aux modifications entre phonèmes. Cela représente donc la prononciation réelle des locuteurs, qui n’est pas représentée de manière exacte par la translittération du Hjalpi’.

Généralement, j’utiliserai la transcription large lorsque j’aurai besoin de transcrire de façon phonétique des éléments de langage, à moins que je souhaite que vous, le lecteur, portiez votre attention sur un élément particulier de la prononciation de la langue divine, auquel cas j’userai de la transcription rapprochée, comme lors de la discussion sur l’[[allophonie][allophonie]]. La prononciation des mots du [[glossaire][glossaire]] sera notée en transcription large.

*** <<phon-consonnes>>Consonnes
En plus d’un important inventaire de voyelle, le Hjalpi’ dispose également d’un inventaire de consonnes relativement important. Voici ci-dessous lesdites consonnes :

#+CAPTION: Consonnes du Hjalpi’
| / | >             | >      | >          | >     | >    | >         | >      | >      | >       | >     | >       |
|   |               | bilab. | lab.-dent. | dent. | alv. | pal.-alv. | rétro. | palat. | vélaire | uvul. | glottal |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | nasal         | m      |            |       | n    |           |        |        | ng      |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | occlusif      | p b    |            |       | t d  |           | ŧ đ    |        | k g     |       | '       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | fricatif      |        | f v        | þ ð   | s z  | sh zh     |        | ch jh  |         | qh rh | h       |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | spirante      |        |            |       | ŕ    |           |        | j      |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | roulé         |        |            |       | r    |           |        |        |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | fric.-lat.    |        |            |       | lh   |           |        |        |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | spir.-lat.    |        |            |       | l    |           |        |        |         |       |         |
|---+---------------+--------+------------+-------+------+-----------+--------+--------+---------+-------+---------|
|   | semi-voyelles | w      |            |       |      |           |        |        |         |       |         |

#+CAPTION: Consonnes du Hjalpi’ (IPA)
| / | >             | >       | >          | >     | >        | >         | >      | >      | >       | >     | >       |
|   |               | bilab.  | lab.-dent. | dent. | alv.     | pal.-alv. | rétro. | palat. | vélaire | uvul. | glottal |
|---+---------------+---------+------------+-------+----------+-----------+--------+--------+---------+-------+---------|
|---+---------------+---------+------------+-------+----------+-----------+--------+--------+---------+-------+---------|
|   | nasal         | m [m̩ʲ]  |            |       | n n̩      |           |        | [ɲ̩]    | ŋ       |       |         |
|---+---------------+---------+------------+-------+----------+-----------+--------+--------+---------+-------+---------|
|   | occlusif      | p  b    |            |       | t  d     |           | ʈ  ɖ   |        | k  ɡ    |       | ʔ       |
|---+---------------+---------+------------+-------+----------+-----------+--------+--------+---------+-------+---------|
|   | fricatif      | [ɸ] [β] | f   v      | θ  ð  | s  z     | ʃ ʒ       |        | ç  ʝ   | [x] [ɣ] | χ   ʁ | h [ɦ]   |
|---+---------------+---------+------------+-------+----------+-----------+--------+--------+---------+-------+---------|
|   | spirante      |         |            |       | ɹ        |           |        | j      |         |       |         |
|---+---------------+---------+------------+-------+----------+-----------+--------+--------+---------+-------+---------|
|   | roulé         |         |            |       | r        |           |        |        |         |       |         |
|---+---------------+---------+------------+-------+----------+-----------+--------+--------+---------+-------+---------|
|   | fric.-lat.    |         |            |       | ɬ        |           |        |        |         |       |         |
|---+---------------+---------+------------+-------+----------+-----------+--------+--------+---------+-------+---------|
|   | spir.-lat.    |         |            |       | l l̩ [l̩ʲ] |           |        |        |         |       |         |
|---+---------------+---------+------------+-------+----------+-----------+--------+--------+---------+-------+---------|
|   | semi-voyelles | w       |            |       |          |           |        |        |         |       |         |

Les consonnes entre crochet sont des allophones d’autres phonèmes, tel qu’expliqué dans [[allophonie][Allophonie]]. Il est aussi à noter que les consonnes /n̩/ et /l̩/ sont toutes deux des consonnes dites syllabiques et appartenant donc aux [[phon-voyelles][voyelles]].

*** <<phon-voyelles>>Voyelles
Le Hjalpi’ dispose d’un inventaire de voyelle très large comparé à la majorité des langues existantes dans notre monde, avec dix-sept voyelles simples, et quelques autres diphtongues (discutées plus bas dans [[phon-diphtongues][Diphtongues]]). Voici la liste des voyelles utilisées dans le Hjalpi’ :

#+CAPTION: Voyelles du Hjalpi’
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | i / y       | u            |
|   | pré-fermées | ì / ĩ / ů   | ù / ũ        |
|   | mi-fermées  | e / ø       | o            |
|   | mi-ouvertes | è / œ       | ò            |
|   | ouvertes    | a           | å / ã        |

Le Hjalpi’ dispose également de deux consonnes syllabiques, le /ń/ et le /ĺ/, qui sont respectivement le /n/ et le /l/ prononcés comme des voyelles. Voici ci-dessous le même tableau, avec chaque voyelle remplacée par sa valeur phonétique en IPA :

#+CAPTION: Voyelles du Hjalpi’ (IPA)
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | iː / yː     | uː           |
|   | pré-fermées | ɪ / ɪ̃ / ʏ   | ʊ / ʊ̃        |
|   | mi-fermées  | eː / øː     | oː           |
|   | mi-ouvertes | ɛ / œ       | ɔ            |
|   | ouvertes    | aː          | ɑ / ɑ̃        |

Avec le /ń/ et le /ĺ/ ayant respectivement pour valeur /n̩/ et /l̩/.

On peut remarquer que, à l’exception de /ĩ/, /ũ/, /ã/, /ń/ et /ĺ/, toutes les voyelles ont un couple ouverte courte vs. fermée longue. Dans les mots racine (c’est à dire non altérés par une quelconque règle grammaticale), la distinction revêt une importance capitale, porteuse de sens et de distinction de certains mots entre eux. Ainsi, /þran/ [θraːn] n’aura pas la même signification que /þrån/  [θrɑn] (pour l’explication de la prononciation, voir [[allophonie][l’allophonie]]). En revanche, comme on le verra plus tard, les addition grammaticales verront leurs voyelles s’accorder avec les voyelles du mot racine en ouverture/longueur.

**** Voyelles courtes
 - /ɑ/ å :: Le /å/ est une voyelle ressemblant au « â » que l’on retrouve en français dans des mots tels que « pâte ».

 -  /ɑ̃/ ã :: Le /ã/ est l’équivalent nasal de la lettre /å/, que l’on retrouve souvent en français avec la graphie « an » ou « en », comme dans « pendant ».

 -  /œ/ œ :: Il s’agit ici du son « eu » tel qu’on le retrouve en français tel que dans le mot « neuf ».

 -  /ɪ/ ì :: Cette voyelle est une voyelle se situant entre le son « i » et le son « e » ; on peut le retrouver en anglais dans des mots tels que « hit » ou « this ».

 - /ɪ̃/ ĩ :: Il s’agit de la même voyelle que le /ì/ à la différence près que celle-ci est nasalisée. On la retrouve à quelques occasions en anglais en tant qu’allophone comme dans le terme « women » [wɪ̃mə̃n].

 -  /ɛ/ è :: Nous avons ici la voyelle « è » que l’on retrouve en français par exemple dans le mot « cette ».

 -  /ɔ/ ø :: Il s’agit du « o » ouvert, que l’on retrouve en français dans le mot « sort » par exemple.

 -  /ʏ/ ů :: Cette voyelle est un équivalent du « u » français ouvert, que l’on peut retrouver en Allemand comme dans « Müller » par exemple.

 -  /ʊ/ ù :: Cette voyelle est un équivalent du « ou » Français ouvert, telle que l’on peut la retrouver dans le mot « book » en Anglais britannique.

 -  /ʊ̃/ ũ :: Il s’agit du /ù/ nasalisé. Cette voyelle peut notamment se retrouver dans la langue africaine Guéré.

**** Voyelles longues
-  /aː/ a :: Cette voyelle est le « a » que l’on peut retrouver dans le français tel que dans « patte », à la différence que le « a » de le Hjalpi’ est prononcé un peu plus longuement que le « a » français.

-  /øː/ ø :: Cette voyelle est la même que le « eu » français que l’on retrouve dans le mot « deux », à la différence que le « ø » divin est prononcé un peu plus longuement que le « eu » français.

-  /iː/ i :: Cette voyelle est la même que le « i » français, à la différence que le « i » de le Hjalpi’ est prononcé un peu plus longuement que le « i » français.

-  /eː/ e :: Cette voyelle est la même que le « é » français, à la différence que le « i » de le Hjalpi’ est prononcé un peu plus longuement que le « i » français.

-  /oː/ o :: Cette voyelle est la même que le « o » français comme dans « eau », à la différence que le « o » de le Hjalpi’ est prononcé un peu plus longuement que le « o » français.

-  /yː/ y :: Cette voyelle est la même que le « u » français, à la différence que le « u » de le Hjalpi’ est prononcé un peu plus longuement que le « u » français.

-  /uː/ u :: Cette voyelle est la même que le « ou » français, à la différence que le « ou » de le Hjalpi’ est prononcé un peu plus longuement que le « ou » français.

**** <<cons-syll>>Consonnes syllabiques
-  /n̩/ ń :: Le « ń » est la consonne « n » (la même que le « n » standard français), mais considérée et prononcée comme une voyelle, tel qu’on peut l’entendre dans certains mots anglais comme dans « button » qui peut être prononcé  /bʌtn̩/.

-  /l̩/ ĺ :: Le « ĺ » est la consonne « l » (la même que le « l » français), mais considérée et prononcée comme une voyelle, tel qu’on peut l’entendre dans certains mots anglais comme dans « bottle » qui peut être prononcé  /bɔtl̩/, avec le /ʊ/ qui est omis et le  /l/ devenant syllabique.

**** <<phon-diphtongues>>Diphtongues

*** Accentuation
L’accentuation des mots en langue divine porte sur l’avant-dernière voyelle racine si le mot racine dispose de deux syllabes ou plus, sur la voyelle racine unique sinon. L’accentuation des mots étant régulière, elle n’est pas marquée par l’orthographe et la translittération de la langue.
Pour ce qui est de l’accentuation des phrases, le ton est généralement tombant, avec le terme que le locuteur estime le plus important de la phrase bénéficiant d’une remontée du ton sur ce terme précisément. Si le locuteur estime que le terme est très important, alors il peut même le prononcer avec une voix de tête, voire étirer de manière exagérée la première syllabe racine du terme. Un verbe interrogatif bénéficie nécessairement de la remontée du ton de la phrase sur ce terme, tandis qu’une phrase exclamative voit son ton recommencer à descendre à partir de la même hauteur que celle du début de phrase. Une phrase affirmative continue la descente de ton jusqu’à la dernière syllabe racine qui bénéficie d’une accentuation.

*** Romanisation et translittération
La romanisation et la translittération d’une langue sont deux choses très différentes ; en effet, la première a pour but de représenter de façon grossière la prononciation de la langue avec l’alphabet latin, sans se soucier de l’orthographe exacte, tandis que la translittération a pour but de reproduire de manière précise l’orthographe de la langue transcrite, sans se soucier de savoir si le lecteur saura prononcer correctement la transcription s’il n’a pas été initié avant à la langue transcrite.

Pour moi le meilleur exemple que je puisse donner pour ce qui est de la différence entre romanisation et translittération est en Tibétain. Nous avons des termes Tibétain romanisés “dorje”, “chorten” ou encore “yak” en anglais dont une de leur translittération possible respective est “rdo rje”, “mchod brten” et “gyag”. Bien évidemment, toute personne n’ayant aucune notion de translittération du Tibétain et/ou de son orthographe peut être confuse quant à ce qu’ils viennent de lire, et c’est tout naturel : leur but est de savoir précisément comment écrire ces mots, et une personne sachant écrire en tibétain pourra, en ayant lu ces exemples, écrire les mots sans faute si je n’en ai pas fait non plus à la rédaction de cet ouvrage. Comme je l’ai indiqué, il s’agit dans cet exemple d’une romanisation anglophone ; en effet, la romanisation dépend de la langue du lecteur. Étant donné que ce dernier doit pouvoir se forger une idée de la prononciation du mot étranger, il faut utiliser les conventions de lecture de l’alphabet de sa propre langue afin d’approcher au mieux la prononciation originale. Ainsi, “dorje” en anglais pourrait être écrit « dordjé » en français, “chorten” pourrait être écrit « tchortène » (« yak » garde la même orthographe dans les deux langues, et est même dans les dictionnaires anglophones et francophones).

Ainsi, dans mon (ou mes ?) livre(s ?) qui s’adressera (s’adresseront ?) à un public général, j’utiliserai des romanisation de la langue divine si je souhaite que le lecteur ait une idée de la prononciation du mot ou de la phrase qu’il vient de rencontrer –et à l’inverse, si je souhaite être plus graphique, j’utiliserai soit la translittération, soit l’écriture native du Hjalpi’. Toujours est-il que dans cette référence grammaticale, je n’utiliserai que de la translittération (les graphèmes et lettres correspondantes furent décrites dans [[phon-consonnes][Consonnes]] et [[phon-voyelles][Voyelles]]), et ne ferai usage de la romanisation que dans ce chapitre où j’explique ci-dessous le processus de l’écriture du Hjalpi en romanisation.

Voici ci-dessous un tableau avec chaque phonème du Hjalpi’, sa translittération, et sa romanisation francophone. Pour un équivalent anglophone, se référer à la version anglophone de cet ouvrage si cette dernière existe.
src_latex{\newpage}
| / | >       | >      |      |
|   | phonème | trans. | rom. |
|---+---------+--------+------|
|   | iː      | i      | i    |
|   | yː      | y      | u    |
|   | uː      | u      | ou   |
|   | ɪ       | ì      | i    |
|   | ʏ       | ů      | u    |
|   | ʊ       | ù      | ou   |
|   | eː      | e      | é    |
|   | øː      | ø      | e    |
|   | oː      | o      | o    |
|   | ɛ       | è      | è    |
|   | œ       | œ      | eu   |
|   | ɔ       | ò      | au   |
|   | aː      | a      | a    |
|   | ɑ       | å      | a    |

| / | >       | >      |      | <> | >       | >      |      |
|   | phonème | trans. | rom. |    | phonème | trans. | rom. |
|---+---------+--------+------+----+---------+--------+------|
|   | p       | p      | p    |    | b       | b      | b    |
|   | t       | t      | t    |    | d       | d      | d    |
|   | ʈ       | ŧ      | tr   |    | ɖ       | đ      | dr   |
|   | k       | k      | k    |    | ɡ       | g      | g    |
|   | f       | f      | f    |    | v       | v      | v    |
|   | θ       | þ      | th   |    | ð       | ð      | dh   |
|   | s       | s      | s    |    | z       | z      | z    |
|   | ʃ       | sh     | sh   |    | ʒ       | zh     | j    |
|   | ç       | ch     | ch   |    | ʝ       | jh     | jh   |
|   | m       | m      | m    |    | n       | n      | n    |
|   | ŋ       | ng     | ng   |    | ʔ       | ’      | ’    |
|   | r       | r      | r    |    | h       | h      | h    |
|   | χ       | qh     | qh   |    | ʁ       | rh     | rh   |
|   | ɬ       | lh     | lh   |    | ɹ       | ŕ      | r    |
|   | l       | l      | l    |    | j       | j      | y    |
|   | w       | w      | w    |    |         |        |      |
** Phonotaxes
*** Attaque
*** Rime
**** Noyau syllabique
**** Coda

** Phonologie dérivationnelle
Ci-dessous se trouve une liste d’abréviations que l’on trouvera souvent dans les règles formelles :
- ~#~ = limite d’un mot
- ~Ø~ = silencieux / muet
- ~C~ = consonne
- ~F~ = consonne fricative
- ~N~ = consonne nasale
- ~P~ = consonne labiale
- ~S~ = consonne plosive
- ~V~ = voyelle
- ~L~ = voyelle longue
- ~S~ = voyelle courte

*** <<allophonie>>Allophonie
En Hjalpi’, il existe de nombreuses règles sur la modification de prononciation de phonèmes selon leur emplacement au sein d’un mot et leur environnement phonétique, donnant lieu à des allophones desdits phonèmes. Ces règles sont les dernières règles à s’appliquer sur la modification de prononciation des mots, les autres règles comme les [[deriv-accord-voy][accords des voyelles]] ou les [[deriv-accord-cons][accords des consonnes]] s’appliquant avant les règles d’allophonie. Ces règles s’appliquent dans leur ordre d’apparition ci-dessous. Attention, la consonne /’/ (/ʔ/ ) est considérée comme étant transparente pour ce qui est de l’allophonie, ainsi les règles suivantes s’appliquent comme si cette consonne était inexistante et insonore.

**** Voyelles
Il existe relativement peu d’allophones parmi les voyelles de le Hjalpi’, cependant on peut en relever certains comme suit :
- La prononciation standard du « ń », comme mentionné ci-dessus dans [[cons-syll][Consonnes syllabiques]], est /n̩/. Cependant, cette voyelle se prononce [m̩] si le /ń/ est précédé ou suivi par une consonne bilabiale, il se palatalise en [ɲ̩] si le /ń/ est également adjacent à une des voyelles /i/ ou /ì/, ou bien la consonne /j/, et si les deux cas sont vérifiés vrais en même temps, le /ń/ sera prononcé [m̩ʲ].
 - /n̩/ > [m̩] / P_  | _ P
 - /n̩/ > [ɲ̩] / {iː,ɪ,j}_  | _ {iː,ɪ,j}
 - /n̩/ > [m̩ʲ] / P_ {iː,ɪ,j} | {iː,ɪ,j}_ P
| wańmjœd     | /wan̩.mjœd/       | [wam̩.mjœd]       |
| letńja      | /leː.tn̩.jaː/     | [leː.tɲ̩.jaː]     |
| rhepń ìltìþ | /ʁeː.pn̩.ɪl.tɪθ/  | [ʁeː.pm̩ʲ.ɪl.tɪθ] |
- Le « ĺ » également se palataliseen cas d’adjacence à une des voyelles /i/ ou /ì/ ou bien la consonne /j/, et donc se prononce [l̩ʲ] dans ce cas.
 - /l̩/ > [l̩ʲ] / {iː,ɪ,j}_  | _ {iː,ɪ,j}
| jĺchek | /jl̩.çeːk/  | [jl̩ʲ.çeːk] |

**** Consonnes
Plusieurs de ces consonnes disposent d’allophones, c’est à dire de prononciations alternatives à la prononciation exacte mentionnée plus haut, sans que cela n’affecte le sens des mots ou le sens d’une phrase.
- La prononciation standard du /f/ et /v/ sont respectivement ~/f/~ et ~/v/~, cependant il arrive également qu’ils soient respectivement prononcés ~/ɸ/~ et ~/β/~ entre deux voyelles, ou en début de mot si immédiatement suivis d’une voyelle ou d’une semi-consonne (également notée ~V~).
  - /f/ > [ɸ] / {#,V}_ V
  - /v/ > [β] / {#,V}_ V
| fenrũd   | /feːn.rʊ̃d/      | [ɸeːn.rʊ̃d]    |
| vyelogot | /vye.loː.ɡoːt/  | [βye.loː.ɡoːt] |
- Le  /ɦ/ est considéré comme étant un allophone du  /h/. Cet allophone se produit entre deux voyelles, en début de mot immédiatement suivit d’une voyelle, entre une consonne voisée et une voyelle, ou une voyelle et une consonne voisée. En revanche, au contact du /i/, /ì/ ou /j/, le  /h/ se palatalise en un  /ç/. Similairement, un  /ɦ/ obtenu grâce au premières règles ci-dessous change en  /ʝ/.
  - /h/ > [ɦ] / {#,V}_ V
  - /h/ > [ç] / _ {i,ɪ,j} | {i,ɪ,j}_ 
  - [ɦ] > [ʝ] / _ {i,ɪ,j} | {i,ɪ,j}_ 
| wyhakuþ | /wyː.haː.kyːθ/  | [wyː.ɦaː.kyːθ] |
| hjalp   | /hjalp/         | [çjalp]        |
| nehja   | /neː.hjaː/      | [neː.ʝja]      |
- Le /x/ et le /rh/ sont habituellement prononcés /χ/ et /ʁ/ respectivement, cependant ils sont avancés en consonnes velaires /x/  et /ɣ/ respectivement lorsqu’ils sont en contact avec une consonne fricative.
  - /{χ,ʁ}/ > [+vélaire] / F_  | _ F
| naqhfèn        | /naːχ.fɛnd/             | [naːx.fɛnd]            |
| ŧeleþ qhuljů   | /ʈeː.leːθ.χuː.ljʏ/      | [ʈeː.leːθ.xuː.ljʏ]     |
| elekorh þurènt | /eː.leː.koːɣ.θyː.rɛnt/  | [eː.leː.koːɣ.θyː.rɛnt] |
| đùvùzh rhev    | /ɖʊ.vʊʒ.ʁev/            | [ɖʊ.vʊʒ.ɣev]           |
- Si une consonne fricative voisée est précédée par une fricative sourde, elle devient elle-même sourde. À l’inverse, si une fricative sourde est précédée par une fricative voisée, la première devient également voisée.
  - F[-son] > [+son] / F[+son]_ 
  - F[+son] > [-son] / F[-son]_ 
| echvènd  | /eːç.vɛnd/  | [eːç̬.vɛnd] |
| auzshèìd | /auz.ʃɛɪd/  | [auz̥.ʃɛɪd] |
- Si deux plosives se suivent, la première a une désocclusion inaudible.
  - S > [-release] / _ S
| edtĩ | /ed.tɪ̃/  | [eːd̚.tɪ̃] |

*** <<deriv-accord-voy>>Accord des voyelles
L’accord des voyelles a lieu principalement lors de la déclinaison d’un nom ou de la conjugaison d’un verbe, lors d’un cas où la juxtaposition d’une voyelle à une autre est obligatoire. Cela donne alors lieu à un accord des voyelles.

1. Les deux voyelles sont fusionnées en une diphtongue.
2. Si l’un des deux phonèmes est une consonne syllabique /ń/ ou /ĺ/, alors celle-ci reste inchangée.
3. Si la première voyelle est une diphtongue, alors le second phonème est remplacé par la seconde voyelle après que cette dernière ait été accordée en longueur à la longueur de premier phonème de la diphtongue.
4. Si la seconde voyelle était également une diphtongue, alors elle perd son second phonème.
5. Si le second phonème de la diphtongue est plus ouvert que le premier, alors il est refermé afin d’être au moins aussi fermé que le premier phonème.
6. Si le premier phonème de la diphtongue est une voyelle antérieure, alors elle devient son équivalent phonétique postérieur selon la table suivante :
| / | >                 |                 |
|   | phonème d’origine | nouveau phonème |
|---+-------------------+-----------------|
|   | u                 | y               |
|   | ù                 | ů               |
|   | o                 | ø               |
|   | ø                 | œ               |
|   | å                 | a               |

*** <<deriv-accord-cons>>Accord des consonnes

** Système d’écriture

* Éléments de la phrase
** <<noms>>Noms
*** <<noms-articles>>Articles
*** <<morpho-nom-genre>>Genre
Le Hjalpi’ est une langue riche en genres grammaticaux, étant donné qu’elle dispose de *neuf genres* différents
1. Genre divin (/SAC/) : se réfère à toute personne considérée comme divine, que ce soit par les Divins ou par les mortels (humains comme non humains). Aucune distinction n’est faite selon leur sexe biologique. Les méduses, du fait d’être une icône divine, sont considérées étant également du genre divin. Il se réfère également à ce qui fait partie de leur domaine, que ce soit leurs Demeures ou leurs Œuvres majeures, tels que les Tours ou le Temps.
2. Genre abstrait (/ABST/) : se réfère à tout élément non physique ou concept, comme des pensées ou des couleurs. Les lieux physiques et temporels sont également classifiés dans le genre mental. Bien que le temps en lui-même soit considéré comme étant du genre divin, les événements sont considérés comme étant des éléments mentaux.
3. Genre liquide (/LIQ/) : se réfère, comme son nom l’indique, à tout liquide, et en particulier à l’eau, mais ne couvre pas tous les fluides ; par exemple, l’air n’est pas considéré comme un liquide, malgré le fait que ce soit un fluide.
4. Genre masculin (/M/) : se réfère à tout être humain ou semi-humain mâle, ou à un groupe à prédominance numérique ou de puissance masculine.
5. Genre féminin (/F/) : se réfère à tout être humain ou semi-humain femelle, ou à un groupe à prédominance numérique ou de puissance féminine.
6. Genre neutre (/N/) : se réfère à tout être humain ou semi-humain dont on ne connaît pas le sexe biologique, ou si un groupe n’a pas de prédominance numérique ou de puissance masculine ou féminine.
7. Genre animal (/ANML/) : se réfère à tout être mortel n’étant pas un humain ou semi-humain et étant animé.
8. Genre végétal (/PLNT/) : se réfère à tout être mortel n’étant pas un humain ou semi-humain, ou membre d’animaux.
9. Genre inanimé (/INAN/) : se réfère à tout être non-vivant n’étant pas inclus par les trois premiers genres.

Le genre est inclus sémantiquement dans chaque nom commun du Hjalpi’, en revanche la majorité des éléments rattachés au nom s’accorderont en genre, ainsi que les verbes suivant si le nom influe la conjugaison du verbe.

<<nom-sur-genre>>Le Hjalpi’ dispose également de *quatre sur-genres*, regroupant les genres en catégories qui sont utilisées dans certains contexte, comme pour la déclinaison ou la conjugaison des verbes.
1. Le sur-genre spirituel (/SPIR/) : rassemble les genres divin et mental
2. Le sur-genre humain (/HUM/) : rassemble les genres humains (masculin, féminin et neutre)
3. Le sur-genre non-humain (/NHUM/) : rassemble les genres du vivant non-humain (animal et végétal)
4. Le sur-genre inanimé (/IN/) : rassemble les genres liquide et inanimé

Une déclinaison des éléments humains neutres est possible, auquel cas on peut décliner ainsi l’élément dont on souhaite changer le genre :
| / | >        |             |
|   | genre    | déclinaison |
|---+----------+-------------|
|   | masculin | -e          |
|   | féminin  | -am         |

Ce genre de déclinaison est en général utilisé pour les mots se référant à un être humain dont le genre syntaxique est neutre, mais que l’humain référé est d’un genre connu. Par exemple, si l’on parle de plusieurs personnes de nombre inconnu (donc singulatif, voir les [[morpho-nom-nombre][Nombres]]) mais que la majorité des individus est de genre féminin, alors on déclinera /ðenmøìl/ (individu/personne) en /ðenmøìlelam/ (personne.sf.5g). La déclinaison en féminin s’affixe à la déclinaison au singulatif du fait qu’il s’agit du groupe qui prend le genre féminin, indiquant que le groupe n’est pas uniquement mais majoritairement féminin. Si le groupe n’est composé que de femmes, alors /ðenmøìl/ se déclinera en /ðenmøìlamel/ (personne.5g.sf).

Il est également possible de changer le genre d’un sujet de phrase (agent nominatif, patient ergatif ou expérienceur) en accordant le reste de la phrase suivant le genre que l’on veut lui donner. Ainsi, pour déifier le chat de la phrase « Ce chat se comporte comme un dieu céleste », on peut dire :
| se.comporter-1S.SPIR.IND | dieu.celeste-EQU | chat-ERG | ce.1S |

*** <<morpho-nom-nombre>>Nombre
En plus d’avoir une riche quantité de genres, le Hjalpi’ dispose également de cinq nombres distincts qui se marquent par une déclinaison du nom ou de l’élément accordé en nombre (hormis le verbe).

| / | >          | >           |                                    |
|   | nombre     | déclinaison | description                        |
|---+------------+-------------+------------------------------------|
|   | singulier  | (aucune)    | élément unique                     |
|   | singulatif | -el         | ensemble d’éléments semblables     |
|   | duel       | -(a)t       | deux éléments semblables           |
|   | triel      | -(e)þ       | trois éléments semblables          |
|   | pluriel    | -(o)st      | quatre éléments semblables ou plus |

Le singulatif, comme décrit ci-dessus, est utilisé pour regrouper des éléments semblables et est une alternative au singulier ou pluriel dans le cas où l’élément est indénombrable ou éligible au pluriel mais le locuteur n’a pas d’idée précise du nombre d’éléments présents dans le groupe (exemples en français : « de la farine », « des gens »).

Pour des raisons grammaticales il existe également un sur-nombre, le *super-singulier* qui regroupe tous les nombres qui ne sont pas le pluriel. Le super-singulier est utile notamment pour les déclinaisons qui distinguent uniquement le super-singulier et le pluriel.

** <<pronoms>>Pronoms

*Note : en construction*

Nominatif :
| /     | <    |      |      |      |       |      |      |      |      |
|       | SAC  | ABST | LIQ  | M    | F     | N    | ANML | PLNT | INAN |
|-------+------+------+------+------+-------+------+------+------+------|
| 1S    | lhè  | /    | jhò  | ngè  | njè   | nè   | /    | /    | /    |
| 1iS   | lhò  | /    | chò  | nwœ  | nje   | nå   | /    | /    | /    |
| 2S    | lhy  | ty   | jhy  | ngœ  | njy   | ny   | fay  | ly   | rhy  |
| 3S    | lhã  | tã   | jhã  | nwã  | nã    | mã   | vã   | ŕã   | qhã  |
| 1SGV  | lèqh | tèþ  | chòþ | ngèl | njèm  | nèl  | vèn  | lèsh | qhèŕ |
| 1iSGV | lòqh | tòch | chœð | lwœ  | ljè   | la   | fòl  | rò   | lèrh |
| 2SGV  | lhyl | tych | shyl | nyel | njym  | nĩ   | þyl  | ŕyl  | rhyl |
| 3SGV  | lãqh | tãþ  | zhãl | ngãl | njũl  | mãl  | fãl  | lã   | qhãl |
| 1DU   | tlhè | /    | shtè | nœt  | nœt   | nœt  | /    | /    | /    |
| 1iDU  | tlhò | /    | chtè | ngœt | njò   | ètń  | /    | /    | /    |
| 2DU   | lhůŧ | typ  | zhyt | tyng | njyd  | ůtń  | fãŧ  | lyđ  | trhy |
| 3DU   | lhãt | ŧãn  | zhãt | ngãd | njãt  | ngã  | tãv  | ŕãt  | qhã  |
| 1TRI  | èlþ  | /    | þò   | èmð  | njènt | ngjè | /    | /    | /    |
| 1iTRI | lhòð | /    | ðœ   | œnð  | njeþ  | ngøl | /    | /    | /    |
| 2TRI  |      |      |      |      |       |      |      |      |      |
| 3TRI  |      |      |      |      |       |      |      |      |      |
| 1PL   |      | /    |      |      |       |      | /    | /    | /    |
| 1iPL  |      | /    |      |      |       |      | /    | /    | /    |
| 2PL   |      |      |      |      |       |      |      |      |      |
| 3PL   |      |      |      |      |       |      |      |      |      |

Accusatif :
| /     | <   |      |     |   |   |   |      |      |      |
|       | SAC | ABST | LIQ | M | F | N | ANML | PLNT | INAN |
|-------+-----+------+-----+---+---+---+------+------+------|
| 1S    |     | /    |     |   |   |   | /    | /    | /    |
| 1iS   |     | /    |     |   |   |   | /    | /    | /    |
| 2S    |     |      |     |   |   |   |      |      |      |
| 3S    |     |      |     |   |   |   |      |      |      |
| 1SGV  |     | /    |     |   |   |   | /    | /    | /    |
| 1iSGV |     | /    |     |   |   |   | /    | /    | /    |
| 2SGV  |     |      |     |   |   |   |      |      |      |
| 3SGV  |     |      |     |   |   |   |      |      |      |
| 1DU   |     | /    |     |   |   |   | /    | /    | /    |
| 1iDU  |     | /    |     |   |   |   | /    | /    | /    |
| 2DU   |     |      |     |   |   |   |      |      |      |
| 3DU   |     |      |     |   |   |   |      |      |      |
| 1TRI  |     | /    |     |   |   |   | /    | /    | /    |
| 1iTRI |     | /    |     |   |   |   | /    | /    | /    |
| 2TRI  |     |      |     |   |   |   |      |      |      |
| 3TRI  |     |      |     |   |   |   |      |      |      |
| 1PL   |     | /    |     |   |   |   | /    | /    | /    |
| 1iPL  |     | /    |     |   |   |   | /    | /    | /    |
| 2PL   |     |      |     |   |   |   |      |      |      |
| 3PL   |     |      |     |   |   |   |      |      |      |

Ergatif :
| /     | <   |      |     |   |   |     |      |      |      |
|       | SAC | ABST | LIQ | M | F | N   | ANML | PLNT | INAN |
|-------+-----+------+-----+---+---+-----+------+------+------|
| 1S    |     | /    |     |   |   | nèì | /    | /    | /    |
| 1iS   |     | /    |     |   |   |     | /    | /    | /    |
| 2S    |     |      |     |   |   |     |      |      |      |
| 3S    |     |      |     |   |   |     |      |      |      |
| 1SGV  |     | /    |     |   |   |     | /    | /    | /    |
| 1iSGV |     | /    |     |   |   |     | /    | /    | /    |
| 2SGV  |     |      |     |   |   |     |      |      |      |
| 3SGV  |     |      |     |   |   |     |      |      |      |
| 1DU   |     | /    |     |   |   |     | /    | /    | /    |
| 1iDU  |     | /    |     |   |   |     | /    | /    | /    |
| 2DU   |     |      |     |   |   |     |      |      |      |
| 3DU   |     |      |     |   |   |     |      |      |      |
| 1TRI  |     | /    |     |   |   |     | /    | /    | /    |
| 1iTRI |     | /    |     |   |   |     | /    | /    | /    |
| 2TRI  |     |      |     |   |   |     |      |      |      |
| 3TRI  |     |      |     |   |   |     |      |      |      |
| 1PL   |     | /    |     |   |   |     | /    | /    | /    |
| 1iPL  |     | /    |     |   |   |     | /    | /    | /    |
| 2PL   |     |      |     |   |   |     |      |      |      |
| 3PL   |     |      |     |   |   |     |      |      |      |

Absolutif :
| /     | <   |      |     |   |   |   |      |      |      |
|       | SAC | ABST | LIQ | M | F | N | ANML | PLNT | INAN |
|-------+-----+------+-----+---+---+---+------+------+------|
| 1S    |     | /    |     |   |   |   | /    | /    | /    |
| 1iS   |     | /    |     |   |   |   | /    | /    | /    |
| 2S    |     |      |     |   |   |   |      |      |      |
| 3S    |     |      |     |   |   |   |      |      |      |
| 1SGV  |     | /    |     |   |   |   | /    | /    | /    |
| 1iSGV |     | /    |     |   |   |   | /    | /    | /    |
| 2SGV  |     |      |     |   |   |   |      |      |      |
| 3SGV  |     |      |     |   |   |   |      |      |      |
| 1DU   |     | /    |     |   |   |   | /    | /    | /    |
| 1iDU  |     | /    |     |   |   |   | /    | /    | /    |
| 2DU   |     |      |     |   |   |   |      |      |      |
| 3DU   |     |      |     |   |   |   |      |      |      |
| 1TRI  |     | /    |     |   |   |   | /    | /    | /    |
| 1iTRI |     | /    |     |   |   |   | /    | /    | /    |
| 2TRI  |     |      |     |   |   |   |      |      |      |
| 3TRI  |     |      |     |   |   |   |      |      |      |
| 1PL   |     | /    |     |   |   |   | /    | /    | /    |
| 1iPL  |     | /    |     |   |   |   | /    | /    | /    |
| 2PL   |     |      |     |   |   |   |      |      |      |
| 3PL   |     |      |     |   |   |   |      |      |      |

Pégatif :
| /     | <   |      |     |   |   |   |      |      |      |
|       | SAC | ABST | LIQ | M | F | N | ANML | PLNT | INAN |
|-------+-----+------+-----+---+---+---+------+------+------|
| 1S    |     | /    |     |   |   |   | /    | /    | /    |
| 1iS   |     | /    |     |   |   |   | /    | /    | /    |
| 2S    |     |      |     |   |   |   |      |      |      |
| 3S    |     |      |     |   |   |   |      |      |      |
| 1SGV  |     | /    |     |   |   |   | /    | /    | /    |
| 1iSGV |     | /    |     |   |   |   | /    | /    | /    |
| 2SGV  |     |      |     |   |   |   |      |      |      |
| 3SGV  |     |      |     |   |   |   |      |      |      |
| 1DU   |     | /    |     |   |   |   | /    | /    | /    |
| 1iDU  |     | /    |     |   |   |   | /    | /    | /    |
| 2DU   |     |      |     |   |   |   |      |      |      |
| 3DU   |     |      |     |   |   |   |      |      |      |
| 1TRI  |     | /    |     |   |   |   | /    | /    | /    |
| 1iTRI |     | /    |     |   |   |   | /    | /    | /    |
| 2TRI  |     |      |     |   |   |   |      |      |      |
| 3TRI  |     |      |     |   |   |   |      |      |      |
| 1PL   |     | /    |     |   |   |   | /    | /    | /    |
| 1iPL  |     | /    |     |   |   |   | /    | /    | /    |
| 2PL   |     |      |     |   |   |   |      |      |      |
| 3PL   |     |      |     |   |   |   |      |      |      |

Datif :
| /     | <   |      |     |   |   |   |      |      |      |
|       | SAC | ABST | LIQ | M | F | N | ANML | PLNT | INAN |
|-------+-----+------+-----+---+---+---+------+------+------|
| 1S    |     | /    |     |   |   |   | /    | /    | /    |
| 1iS   |     | /    |     |   |   |   | /    | /    | /    |
| 2S    |     |      |     |   |   |   |      |      |      |
| 3S    |     |      |     |   |   |   |      |      |      |
| 1SGV  |     | /    |     |   |   |   | /    | /    | /    |
| 1iSGV |     | /    |     |   |   |   | /    | /    | /    |
| 2SGV  |     |      |     |   |   |   |      |      |      |
| 3SGV  |     |      |     |   |   |   |      |      |      |
| 1DU   |     | /    |     |   |   |   | /    | /    | /    |
| 1iDU  |     | /    |     |   |   |   | /    | /    | /    |
| 2DU   |     |      |     |   |   |   |      |      |      |
| 3DU   |     |      |     |   |   |   |      |      |      |
| 1TRI  |     | /    |     |   |   |   | /    | /    | /    |
| 1iTRI |     | /    |     |   |   |   | /    | /    | /    |
| 2TRI  |     |      |     |   |   |   |      |      |      |
| 3TRI  |     |      |     |   |   |   |      |      |      |
| 1PL   |     | /    |     |   |   |   | /    | /    | /    |
| 1iPL  |     | /    |     |   |   |   | /    | /    | /    |
| 2PL   |     |      |     |   |   |   |      |      |      |
| 3PL   |     |      |     |   |   |   |      |      |      |

Causatif :
| /     | <   |      |     |   |   |   |      |      |      |
|       | SAC | ABST | LIQ | M | F | N | ANML | PLNT | INAN |
|-------+-----+------+-----+---+---+---+------+------+------|
| 1S    |     | /    |     |   |   |   | /    | /    | /    |
| 1iS   |     | /    |     |   |   |   | /    | /    | /    |
| 2S    |     |      |     |   |   |   |      |      |      |
| 3S    |     |      |     |   |   |   |      |      |      |
| 1SGV  |     | /    |     |   |   |   | /    | /    | /    |
| 1iSGV |     | /    |     |   |   |   | /    | /    | /    |
| 2SGV  |     |      |     |   |   |   |      |      |      |
| 3SGV  |     |      |     |   |   |   |      |      |      |
| 1DU   |     | /    |     |   |   |   | /    | /    | /    |
| 1iDU  |     | /    |     |   |   |   | /    | /    | /    |
| 2DU   |     |      |     |   |   |   |      |      |      |
| 3DU   |     |      |     |   |   |   |      |      |      |
| 1TRI  |     | /    |     |   |   |   | /    | /    | /    |
| 1iTRI |     | /    |     |   |   |   | /    | /    | /    |
| 2TRI  |     |      |     |   |   |   |      |      |      |
| 3TRI  |     |      |     |   |   |   |      |      |      |
| 1PL   |     | /    |     |   |   |   | /    | /    | /    |
| 1iPL  |     | /    |     |   |   |   | /    | /    | /    |
| 2PL   |     |      |     |   |   |   |      |      |      |
| 3PL   |     |      |     |   |   |   |      |      |      |

Possessif :
| /     | <   |      |     |   |   |   |      |      |      |
|       | SAC | ABST | LIQ | M | F | N | ANML | PLNT | INAN |
|-------+-----+------+-----+---+---+---+------+------+------|
| 1S    |     | /    |     |   |   |   | /    | /    | /    |
| 1iS   |     | /    |     |   |   |   | /    | /    | /    |
| 2S    |     |      |     |   |   |   |      |      |      |
| 3S    |     |      |     |   |   |   |      |      |      |
| 1SGV  |     | /    |     |   |   |   | /    | /    | /    |
| 1iSGV |     | /    |     |   |   |   | /    | /    | /    |
| 2SGV  |     |      |     |   |   |   |      |      |      |
| 3SGV  |     |      |     |   |   |   |      |      |      |
| 1DU   |     | /    |     |   |   |   | /    | /    | /    |
| 1iDU  |     | /    |     |   |   |   | /    | /    | /    |
| 2DU   |     |      |     |   |   |   |      |      |      |
| 3DU   |     |      |     |   |   |   |      |      |      |
| 1TRI  |     | /    |     |   |   |   | /    | /    | /    |
| 1iTRI |     | /    |     |   |   |   | /    | /    | /    |
| 2TRI  |     |      |     |   |   |   |      |      |      |
| 3TRI  |     |      |     |   |   |   |      |      |      |
| 1PL   |     | /    |     |   |   |   | /    | /    | /    |
| 1iPL  |     | /    |     |   |   |   | /    | /    | /    |
| 2PL   |     |      |     |   |   |   |      |      |      |
| 3PL   |     |      |     |   |   |   |      |      |      |

Sociatif :
| /     | <   |      |     |   |   |   |      |      |      |
|       | SAC | ABST | LIQ | M | F | N | ANML | PLNT | INAN |
|-------+-----+------+-----+---+---+---+------+------+------|
| 1S    |     | /    |     |   |   |   | /    | /    | /    |
| 1iS   |     | /    |     |   |   |   | /    | /    | /    |
| 2S    |     |      |     |   |   |   |      |      |      |
| 3S    |     |      |     |   |   |   |      |      |      |
| 1SGV  |     | /    |     |   |   |   | /    | /    | /    |
| 1iSGV |     | /    |     |   |   |   | /    | /    | /    |
| 2SGV  |     |      |     |   |   |   |      |      |      |
| 3SGV  |     |      |     |   |   |   |      |      |      |
| 1DU   |     | /    |     |   |   |   | /    | /    | /    |
| 1iDU  |     | /    |     |   |   |   | /    | /    | /    |
| 2DU   |     |      |     |   |   |   |      |      |      |
| 3DU   |     |      |     |   |   |   |      |      |      |
| 1TRI  |     | /    |     |   |   |   | /    | /    | /    |
| 1iTRI |     | /    |     |   |   |   | /    | /    | /    |
| 2TRI  |     |      |     |   |   |   |      |      |      |
| 3TRI  |     |      |     |   |   |   |      |      |      |
| 1PL   |     | /    |     |   |   |   | /    | /    | /    |
| 1iPL  |     | /    |     |   |   |   | /    | /    | /    |
| 2PL   |     |      |     |   |   |   |      |      |      |
| 3PL   |     |      |     |   |   |   |      |      |      |

Vocatif :
| /     | <   |      |     |   |   |   |      |      |      |
|       | SAC | ABST | LIQ | M | F | N | ANML | PLNT | INAN |
|-------+-----+------+-----+---+---+---+------+------+------|
| 1S    |     | /    |     |   |   |   | /    | /    | /    |
| 1iS   |     | /    |     |   |   |   | /    | /    | /    |
| 2S    |     |      |     |   |   |   |      |      |      |
| 3S    |     |      |     |   |   |   |      |      |      |
| 1SGV  |     | /    |     |   |   |   | /    | /    | /    |
| 1iSGV |     | /    |     |   |   |   | /    | /    | /    |
| 2SGV  |     |      |     |   |   |   |      |      |      |
| 3SGV  |     |      |     |   |   |   |      |      |      |
| 1DU   |     | /    |     |   |   |   | /    | /    | /    |
| 1iDU  |     | /    |     |   |   |   | /    | /    | /    |
| 2DU   |     |      |     |   |   |   |      |      |      |
| 3DU   |     |      |     |   |   |   |      |      |      |
| 1TRI  |     | /    |     |   |   |   | /    | /    | /    |
| 1iTRI |     | /    |     |   |   |   | /    | /    | /    |
| 2TRI  |     |      |     |   |   |   |      |      |      |
| 3TRI  |     |      |     |   |   |   |      |      |      |
| 1PL   |     | /    |     |   |   |   | /    | /    | /    |
| 1iPL  |     | /    |     |   |   |   | /    | /    | /    |
| 2PL   |     |      |     |   |   |   |      |      |      |
| 3PL   |     |      |     |   |   |   |      |      |      |

** <<adjectifs>>Adjectifs
** <<adverbes>>Adverbes
** <<verbes>>Verbes
*** <<verbes-temps>>Temps
Il existe techniquement sept temps en Hjalpi’, considérés tous comme étant distincts les uns des autres :
- Le *passé lointain* et le *futur lointain* sont associés à des temps à échelle d’une civilisation et au delà de temps à échelle d’une vie humaine. Ainsi, si un événement quelconque est mentionné comme s’étant passé il y a plus d’une soixantaine d’années, les locuteurs du Hjalpi’ s’y référeront au moyen du passé lointain, et à l’inverse, un événement qui se produira dans un siècle sera référé au moyen du futur lointain.
- Le *passé moyen* et le *futur moyen*, plus souvent appelés respectivement *passé* et *futur*, se réfèrent à des événements à échelle d’une vie humaine, c’est à dire à plus ou moins une soixantaine d’années dans le passé ou dans le futur.
- Les deux temps précédents n’empiètent cependant pas sur le *passé proche* et le *futur proche*, qui se réfèrent à des événements se produisant de deux jours dans le passé à deux jours dans le futur. Ils sont aussi utilisés pour des événements imminents ou venant de se produire.
- Le *présent* se réfère quand à lui à des événements ayant cours au moment de la locution et, contrairement au français, ne peut se référer à un autre temps, comme le futur immédiat.

Chacun de ces temps se marquent via la conjugaison des verbes.

Il y a également deux temps utilisés uniquement par les dieux (célestes comme terrestres) qui sont le *passé divin* et le *futur divin*, chacun ayant pour limite la création du monde et sa fin avec lesquels ils se réfèrent à des événements dans des temps plus lointains que ceux situés dans la même ère civilisée que le locuteur, c’est à dire des événements se produisant à environ dix mille ans du temps de locution. Ces temps divins se marquent par une double conjugaison du verbe au temps lointain correspondant. Les mortels n’ayant pas la même notion du temps que les divins utiliseront à la place les temps lointains, à l’exception d’universitaires ayant eu le privilège d’avoir pu converser avec un divin, l’impact du contact avec ces derniers permettant un changement radical de la vision des mortels dans la vision du monde. Cependant, l’utilisation des temps divins reste tout de même rare même parmi ces universitaires et est considéré comme étant plutôt pédant lorsqu’il est utilisé par un mortel.

Dans le Hjalpi’, le temps est visualisé comme une pluie tombante, ou plutôt comme le cycle de l’éther avec le ciel représentant le passé lointain, tombant jusqu’à l’arrière de la tête du locuteur (passé moyen), allant sur son épaule droite (passé proche), dans la tête du locuteur (présent), sur son épaule gauche (futur proche), devant son visage (futur moyen) puis dans le sol (futur lointain). On peut voir dans cette visualisation du temps que les dieux sont considérés comme étant les êtres à l’origine du monde, résidants dans les cieux, et leur bénédiction tombant sur les mortels et passant en eux avant qu’ils fassent face au futur qui va se joindre au sol et au monde, comme ce à quoi chaque mortel est destiné. Pour les divins, cette visualisation commence aux confins de l’espace, en dehors de l’univers d’où vient le Dieu Créateur, représentant lui-même le passé pour les divins, et le futur divin se situant au centre du monde où résident les flammes qui y mettront fin lors de l’arrivée de la fin des temps.

**** Temps antérieurs
Chaque passé dispose d’un *passé antérieur* se référant à une date antérieure au narratif. Cette conjugaison se faisant à l’aide d’un auxilliaire, la conjugaison déterminera le passé relatif au temps de narration, le participe du verbe indiquant le temps d’origine. Aussi connu sous le nom de *plus-que-parfait*. Un équivalent existe également pour les événements antérieurs à un futur de narration : le *futur antérieur*, applicable de la même façon à tous les futurs.

**** Temps postérieurs
Inversement, le *passé postérieur* permet d’exprimer une situation future au passé d’énonciation, de même que le *futur postérieur*. Leur marque se porte également sur l’auxilliaire et le participe du verbe racine.

*** <<verbes-aspects>>Aspects

Bien que le choix du temps nous permet de situer dans ce dernier quand un état ou une action se produit, nous n’avons aucune idée, uniquement avec cette information, de la façon avec laquelle cette action ou cet état se réfère à ce temps ; est-ce une action qui s’étale dans le temps ou est-ce instantané, considérons-nous cet événement ou cet état comme un processus ou comme un événement ? Ces nuances et subtilités sont apportées par les aspects que nous traiterons ci-dessous.

Tableaux ci-dessous juste pour moi le temps de la construction de ce chapitre.

FDIS :
| /     | <   | <    | <   | <    |
|       | PFV | IPFV | HAB | PROG |
|-------+-----+------+-----+------|
| DISC  | X   | X    | X   | X    |
| PERF  |     |      |     |      |
| PERP  |     |      | X   | X    |
| INCEP |     |      | X   | X    |
| TERM  |     |      | X   | X    |
| PUNCT |     | X    |     | X    |
| DUR   |     |      |     |      |
| ITER  |     |      | X   |      |
| HAB   |     |      | X   | X    |
| PROG  |     |      |     | X    |

FUT :
| /     | <   | <    | <   | <    |
|       | PFV | IPFV | HAB | PROG |
|-------+-----+------+-----+------|
| DISC  | X   | X    | X   | X    |
| PERF  |     |      |     |      |
| PERP  |     |      | X   | X    |
| INCEP |     |      | X   | X    |
| TERM  |     |      | X   | X    |
| PUNCT |     | X    |     | X    |
| DUR   |     |      |     |      |
| ITER  |     |      | X   |      |
| HAB   |     |      | X   | X    |
| PROG  |     |      |     | X    |

FNEA :
| /     | <   | <    | <   | <    |
|       | PFV | IPFV | HAB | PROG |
|-------+-----+------+-----+------|
| DISC  | X   | X    | X   | X    |
| PERF  |     |      |     |      |
| PERP  |     |      | X   | X    |
| INCEP |     |      | X   | X    |
| TERM  |     |      | X   | X    |
| PUNCT | X   | X    | X   | X    |
| DUR   | X   | X    | X   | X    |
| ITER  |     |      | X   |      |
| HAB   |     |      | X   | X    |
| PROG  |     |      |     | X    |

PRES :
| /     | <   | <    | <   | <    |
|       | PFV | IPFV | HAB | PROG |
|-------+-----+------+-----+------|
| DISC  | X   | X    | X   | X    |
| PERF  | X   | X    | X   | X    |
| PERP  | X   |      | X   | X    |
| INCEP | X   |      | X   | X    |
| TERM  | X   |      | X   | X    |
| PUNCT | X   | X    |     | X    |
| DUR   | X   |      |     |      |
| ITER  | X   |      | X   |      |
| HAB   | X   |      | X   | X    |
| PROG  | X   |      |     | X    |

PNEA :
| /     | <   | <    | <   | <    |
|       | PFV | IPFV | HAB | PROG |
|-------+-----+------+-----+------|
| DISC  |     |      |     |      |
| PERF  |     |      |     |      |
| PERP  |     |      |     |      |
| INCEP |     |      |     |      |
| TERM  |     |      |     |      |
| PUNCT | X   | X    | X   | X    |
| DUR   | X   | X    | X   | X    |
| ITER  |     |      | X   |      |
| HAB   |     |      | X   | X    |
| PROG  |     |      |     | X    |

PAS :
| /     | <   | <    | <   | <    |
|       | PFV | IPFV | HAB | PROG |
|-------+-----+------+-----+------|
| DISC  |     |      |     |      |
| PERF  |     |      |     |      |
| PERP  |     |      |     |      |
| INCEP |     |      |     |      |
| TERM  |     |      |     |      |
| PUNCT |     | X    |     | X    |
| DUR   |     |      |     |      |
| ITER  |     |      | X   |      |
| HAB   |     |      | X   | X    |
| PROG  |     |      |     | X    |

PDIS :
| /     | <   | <    | <   | <    |
|       | PFV | IPFV | HAB | PROG |
|-------+-----+------+-----+------|
| DISC  |     |      |     |      |
| PERF  |     |      |     |      |
| PERP  |     |      |     |      |
| INCEP |     |      |     |      |
| TERM  |     |      |     |      |
| PUNCT |     | X    |     | X    |
| DUR   |     |      |     |      |
| ITER  |     |      | X   |      |
| HAB   |     |      | X   | X    |
| PROG  |     |      |     | X    |


**** Perfectif (PFV) et imperfectif (IPFV) (aspects primaires)

Le perfectif et l’imperfectif permettent une distinction fondamentale en Hjalpi’ sur l’action ou le verbe dont il est question, et leur présence dans le verbe est obligatoire ; un verbe est soit perfectif soit imperfectif. Il s’agit d’aspects primaires, donc pouvant être utilisés seuls dans un verbe, ainsi un verbe peut être uniquement perfectif ou imperfectif. Cela implique également que l’on peut leur rajouter un second aspect, appelé « sous-aspect ».

Un verbe imperfectif considérera l’événement ou l’état comme étant un processus, doté d’un début, d’une continuation et d’une fin. Il est généralement utilisé afin de mettre en place le décors et le contexte d’un autre événement ou état qui sera généralement perfectif. À l’inverse, le perfectif permet de considérer l’événement comme étant un objet étant un point unique que l’on pourra comparer avec d’autres objets similaires. Pour un exemple, comparez en français « Henri IV régnais vingt et un ans » à « Henri IV régna vingt et un ans ». La première phrase permet une introduction à ce qu’il s’est passé durant le reigne d’Henri IV, alors que la seconde permet plutôt de comparer le reigne du souverain en lui-même à celui d’un autre.

L’imperfectif est l’aspect par défaut de tous les verbes, peu importe le temps, tandis que le perfectif doit être marqué au passé ou au futur ; il ne peut également pas être utilisé dans le temps présent.

**** Habituel (HAB) (aspect médian)

L’aspect habituel marque la caractéristique habituelle, normale du verbe. Cet aspect est un aspect médian, ce qui signifie qu’il peut agir soit en tant qu’aspect primaire, soit en tant que sous-aspect.

**** Progressif (PROG) (aspect médian)

Le progressif marque une action comme étant en cours d’exécution ou un état actuel inhabituel.

**** Discontinu (DISC) (sous-aspect)

Le discontinu est un sous-aspect ; cela implique qu’il ne peut être utilisé qu’en conjonction avec un aspect primaire ou médian. Le discontinu indique que l’événement ou l’état décrit par le verbe n’a plus d’impact sur les temps suivants.

Cet aspect ne peut être utilisé qu’avec les temps passés.

**** Parfait (PERF) et Parfait de Persistance (PERP) (sous-aspect)

Le parfait indique que l’état ou l’événement indiqué via le verbe a une incidence sur le temps présent. Par définition, il ne peut donc pas être utilisé au présent.

Le parfait de persistance indique que l’état ou l’événement est toujours d’actualité au temps présent. Il n’est compatible qu’avec les temps passés.

**** Inceptif (INCEP) et Terminatif (TERM) (sous-aspect)

L’inceptif marque le début d’un état ou d’un événement au moyen du verbe, tandis que le terminatif indique leur fin. Ainsi, « voler » (dans le sens de planer) à l’inceptif peut prendre pour signification « décoller » tandis qu’au terminatif il prendra le sens de « atterrir », avec à chaque fois l’accent mis sur l’action de voler en soit.

**** Ponctuel (PUNCT) et Duratif (DUR) (sous-aspect)
Le ponctuel permet d’indiquer qu’un état ou un événement était court et s’est produit une seule fois, ou bien, il n’est question que d’une seule occurence de l’état ou de l’événement.

À l’inverse, le duratif permet d’indiquer que l’état ou l’événement se prolonge dans le temps.

**** Itératif (ITER) (sous-aspect)

L’itératif et le fréquentatif, bien que similaires, ont une fonction bien différente et définie. L’itératif permet d’indiquer une action répétée à intervals réguliers. Ainsi, pour dire « frapper à la porte » il faudra utiliser le verbe « frapper » (qui n’implique qu’un seul coup) qui aura pour aspect l’itératif. Exemple : « Je frappe à la porte »
| frapper-1S.HUM.PRES.ITER.NOM | <DAT>porte-ACC | 1S.M.NOM |

*** <<verbes-modes>>Modes
<<verbe-cert>>Avant de commencer à se renseigner sur les modes, il faut savoir que le Hjalpi’ dispose d’un concept de certaineté et est omniprésent dans les verbes. En effet, la véracité et vérifiabilité des dires du locuteur est très importante pour les divins, et ce premier doit en toutes circonstances statuer de l’état de ses affirmations, et cela se fait via la conjugaison du verbe. Il existe quatre niveaux de certaineté :
- certaineté objective forte :: Le locuteur fait part d’une vérité objective vérifiée par lui-même ou dont il est certain sans qu’il s’agisse nécessairement d’une vérité générale ou absolue. Ainsi, on peut affirmer avec une objectivité faible « J’habite au quatrième étage de mon immeuble », j’affirme que cela est vrai et objectif sans pour autant que ce soit une vérité générale (je n’y habiterai pas toujours, et ce n’est pas une connaissance commune non plus).
- certaineté objective faible :: Le locuteur affirme que sa proposition est vraie sans nécessairement avoir personnellement vérifié cette affirmation par lui-même, mais il implique que cela est une vérité générale ou absolue. Par exemple, dans notre monde, la phrase « Il y a des yaks au Tibet » serait une phrase à certaineté objective forte, il s’agit d’une vérité générale qui ne sera normalement pas remise en question.
- certaineté subjective forte :: Le locuteur émet une opinion qui peut être partagée ou non avec son interlocuteur. Par exemple, un parisien pourra dire en subjectivité forte à un autre parisien qu’il fait froid lorsqu’en plein milieu de l’hiver il fait -5°C à Paris, ce avec quoi l’autre parisien pourrait être d’accord, en revanche un Canadien, un Russe ou un habitant des pays Scandinaves pourra montrer son désaccord ; ici l’interlocuteur peut vérifier ce que le locuteur a énoncé comme étant vrai ou faux, mais la conclusion sera uniquement subjective et n’invalidera donc pas nécessairement l’énoncée initiale. Le locuteur peut permettre de partager également des informations dont le locuteur est relativement sûr mais pas entièrement, l’empêchant d’utiliser une certaineté objective.
- certaineté subjective faible :: Le locuteur émet une opinion qui lui est propre et qui ne peut être partagé par son interlocuteur. Ce degré de certaineté est utilisé pour partager des opinions qui ont un caractère uniquement personnel et donc invérifiable par quelqu’un d’autre que le locuteur. Par exemple, si le locuteur dit « Je n’aime pas la menthe », il le dira avec une subjectivité relative et il est donc impossible pour un interlocuteur de vérifier ou non s’il s’agit de la vérité. Cela peut être aussi utilisé pour partager une information dont le locuteur n’est pas sûr, ou bien pour partager des souvenirs dont le locuteur peut se permettre de douter.

Il est tout à fait possible pour le locuteur d’utiliser volontairement un degré de certaineté erroné afin d’appuyer le message de sa phrase, d’y mettre une emphase. Par exemple, quelqu’un qui parle d’un restaurant huppé dans la ville à son ami qui vient d’arriver peut tout à fait lui dire que ce restaurant est excellent tout en utilisant l’objectif fort afin de sous entendre qu’il s’agit d’une opinion largement partagée, voire même d’une vérité générale dans la ville. À contrario, un locuteur qui doute d’une vérité générale utilisera une subjectivité relative afin de démettre cette vérité générale vers une simple opinion ; c’est ce qu’aurais pu faire Galilée avec la phrase « la Terre est plate », remettant ainsi en doute cette vérité générale de l’époque (qui, par ailleurs, n’était crue que par le bas peuple, les personnes cultivées savaient que la Terre est ronde). Cependant, attention à l’abus d’utilisation erronée du degré de subjectivité, les personnes qui en abusent sont souvent vus comme étant des hypocrites ou des manipulateurs par leurs pairs.

Les modes que nous verrons ci-dessous ont chacun une degré de certaineté par défaut qui n’est pas marqué à la conjugaison du verbe. Cependant, pour certains modes il est possible de changer de façon explicite ce degré de certaineté ; nous verrons cela au cas par cas ci-dessous. Le mode par défaut des verbes (et donc qui n’est pas marqué) est l’indicatif.

**** <<mode-ind>>Indicatif /IND/
Le mode indicatif est un mode dit « réel », cela signifie donc qu’il est utilisé afin de décrire des événements s’étant déjà produit, se produisant ou allant se produire, ou bien leur négation. Pour faire court, on dit donc que le mode indicatif permet de réaliser des phrases déclaratives. L’indicatif ne supporte que les degrés de certaineté faible, le degré de certaineté par défaut étant l’objectif faible ; le subjectif faible doit donc être marqué explicitement à la conjugaison.

Exemple : Il y a des yaks au Tibet (connaissance générale, mais je n’en suis pas témoin direct)
| yak-SGV-ABS | LOC-Tibet | existe-3SGV.IN.ERG |

**** <<mode-energ>>Énergétique /ENERG/
Ce mode est un mode très similaire à [[mode-ind][l’indicatif]] à la différence près des degrés de certaineté supportés. En effet, l’énergique supporte les degrés de certaineté forts, que l’indicatif ne supporte pas. Mis à part cette différence de degré de certaineté et de conjugaison de l’indicatif et de l’énergique, leur utilisation est identique. Le degré de certaineté par défaut de l’énergique est l’objectif fort, le subjectif fort doit donc être marqué à la conjugaison.

Exemple : Il y a des montagnes en France (connaissance générale et j’ai constaté par moi-même que c’est effectivement le cas)
| montagne-SGV-ERG | LOC-France | existe-3SGV.IN.ERG.ENERG |

**** <<mode-sbjv>>Subjonctif /SBJV/
Le mode subjonctif est généralement utilisé pour les événements imaginaires ou hypothétiques qui ne conviennent pas aux autres modes.

**** <<mode-cond>>Conditionnel /COND/
Le conditionnel permet d’exprimer un événement qui ne peut se produire selon certaines conditions exprimées dans la partie oblique de la phrase. Ces conditions peuvent être inclusives ou exclusives, auquel cas ils seront présentés ensemble séparés par les conjonctions de coordination adéquates.

Exemple : Je mangerai des pommes si j’en achète.
| manger-1S.HUM.NOM.COND.FNEA | pomme-SGV-ACC | acheter-1S.2SG.NOM.PRES | pomme-SGV-ACC | 1s.N.NOM |

**** <<mode-opt>>Optatif /OPT/

**** <<mode-imp>>Impératif /IMP/
L’impératif est un mode permettant de donner des ordres.

**** <<mode-pot>>Potentiel /POT/
Le potentiel est un mode indiquant la capacité à effectuer une action. Ainsi, une phrase telle que « Je peux parler en Hjalpi’ » en français se traduit par :
| parler-1S.HUM.ERG.POTENT | dieu.céleste-GEN-ABS | 1S.N.ERG |
Remarquez ici l’usage de l’ergatif, en Hjalpi’ le fait de disposer d’une capacité est considéré comme étant une situation passive ; en revanche, acquérir cette capacité peut être soit actif (utilisation donc du nominatif) soit passif (utilisation de l’ergatif).

Le degré de certaineté par défaut du potentiel est le subjectif fort.

**** <<mode-hp>>Hypothétique /HP/

**** <<mode-q>>Interrogatif /Q/

**** <<mode-grv>>Gérondif /GRV/

**** <<mode-pcp>>Participe /PCP/

**** <<mode-inf>>Infinitif /INF/

**** <<mode-cert>>Changer la certaineté d’un mode

*** <<verbes-valence>>Valence du verbe
La valence d’un verbe est le nombre d’arguments que ce dernier peut prendre. Les verbes intransitifs prennent au moins en argument un expérienceur, les verbes transitifs prennent au moins un agent et un patient. Si le verbe est également un verbe d’action, il prendra également en argument un bénéfactaire, bien qu’il soit souvent omis s’il est inconnu (ce qui est souvent le cas lorsque le locuteur ne parle pas à la première personne) ou s’il est identique avec l’expérienceur, l’agent nominatif ou le patient ergatif. Il est d’ailleurs également possible d’élipser l’agent nominatif ou le patient ergatif d’une phrase si le contexte permet aux locuteurs de les déduire aisément. En français cela donnerait quelque chose comme ceci : « Tu sais ce qu’a fait Éreþ hier ? A couru pendant quatre heures d’affilées pour Tama ».

Il est également possible de réduire ou d’augmenter la valence d’un verbe selon plusieurs procédés décrits ci-dessous.

**** Passif et antipassif
La voix passive et anti-passife permet d’ellipser un élément cœur de la proposition si le contexte le rend suffisamment évident. Il est également possible de transformer un verbe en un adjectif au patient, permettant d’ellipser l’agent dans certains cas, notamment : l’agent était un pronom impersonnel. Par exemple, en français à la palce de dire « on boit de la bière ici » on peut dire « la bière est bue ici ».

Le passif et l’antipassif permettent également l’inversion de l’agent et du patient, permettant d’ellipser l’agent dans les phrases nominatives et le patient dans les phrases ergatives.

**** Réflexif
La voix réflexive permet d’unifier l’agent et le patient d’une phrase et permet effectivement d’élipser le patient nominatif ou l’agent ergatif en modifiant le verbe de verbe transitif à verbe intransitif via une inflexion de la racine dudit verbe.

**** Réciproque
La voix réciproque permet quant à elle d’exprimer une action à double-sens entre l’agent et le patient, promouvant ce dernier en agent de la phrase nominative ou l’agent en patient d’une phrase ergative. Cela perrmet ainsi d’ignorer le patient ou l’agent de la phrase selon le cas. Le réciproque à l’instar du réflexif se marque par une inflexion de la racine du verbe.

**** Causatif
Le causatif ajoute un argument au verbe : l’élémant causant l’événement. Dans la phrase « Tama a fait se lever le soldat », Tama est responsable du fait que le soldat se soit levé, ainsi le verbe gagnee l’aspect causatif en plus de son aspect réflexif.

*** <<impersonnalité>>Impersonnalité
# 1excl.singulier

** <<decl-morph-decl>>Déclinaisons
Suivant le rôle du nom dans la phrase, il est possible de le décliner à l’un des nombreux cas grammaticaux qu’offre le Hjalpi’. Dans cette section, j’expliquerai simplement la signification brève de chacune de ces déclinaisons. Pour un détail de comment décliner les noms, veuillez vous référer au [[decl-morph-decl][chapitre dédié]]. Je regrouperai ici les déclinaison par catégorie. Chaque cas sera présenté de la manières suivante :
- Cas grammatical (/ABBRÉVIATION/) :: définition
| morphologie |
Exemple en français
| exemple | en Hjalpi’  |
| détail  | grammatical |

Les déclinaisons se présentent sous la forme de particules (préfixes, infixes et suffixes) à ajouter au mot racine. Notez que la partie entre parenthèse peut ne pas être spécifiée, auquel cas il faudra se référer à l’harmonisation des voyelles ou des consonnes selon le cas si une voyelle est accolée à une autre voyelle, de même pour les consonnes.
- V(C)- :: le préfixe est (ou fini par) une voyelle V, il se rajoute donc au début du mot racine. Si ce dernier commence avec une voyelle, la consonne C est rajoutée entre la voyelle V et le mot racine.
- C(V)- :: le préfixe est (ou fini par) une consonne, il se rajoute donc au début du mot racine. Si ce dernier commence avec une consonne, la voyelle (V) est rajoutée entre la consonne C et le mot racine.
- -C_{1}V(C_{2})- :: l’infixe commence par consonne, il se placera donc à la fin du mot racine, entre la dernière voyelle et la dernière consonne du mot racine. Si le mot racine se termine par une voyelle, l’ensemble C_{1}VC_{2} agira comme un suffixe.
- -(C_{1})VC_{2}- :: l’infixe commence par une voyelle, il se placera donc au début du mot racine, entre la première consonne et la première voyelle. Si le mot racine commence par une voyelle, l’ensemble C_{1}VC_{2} agira comme un préfixe.
Notez que la déclinaison se produit avant l’accord en genre et en nombre de l’élément décliné, et après application de [[deriv-accord-voy][l’accord des voyelles]] et de [[deriv-accord-cons][l’accord des consonnes]] de l’élément. Notez également que la ou les voyelles présentée dans les tableaux s’accorde en ouverture et longueur avec la voyelle du mot racine sur laquelle porte l’accent. Ainsi, ajouts de voyelles sur /mén/ via des déclinaisons s’accorderont en voyelles longues et ouvertes. Si la juxtaposition de deux voyelles est obligatoire, se référer à [[deriv-accord-voy][l’accord des voyelles]] ci-dessus. Si la juxtaposition de deux consonnes est obligatoire, se référer à [[deriv-accord-cons][l’accord des consonnes]], idem pour [[deriv-accord-voy][l’accord des voyelles]].

Le nombre représente le [[morpho-nom-genre][genre]] de l’élément décliné, le /s/ et le /p/ représentent respectivement le super-singulier et le pluriel, comme décrits dans les [[morpho-nom-nombre][nombres des noms]].

*** Lieu
- <<cas-ade>>Cas adessif (/ADE/) :: indique un lieu adjacent à l’élément.
| 1s      | 1p      | 2s       | 2p      | 3s       | 3p      | 4s      | 4p       | 5s      | 5p       |
| iqh(a)- | iqh(e)- | iqh(a)-  | iqh(e)- | iqh(a)-  | iqh(e)- | izh(a)- | izh(ei)- | izh(a)- | izh(ei)- |
|         | 6s      | 6p       | 7s      | 7p       | 8s      | 8p      | 9s       | 9p      |          |
|         | izh(a)- | izh(ei)- | izh(a)- | izh(ei)- | irh(a)- | irh(a)- | irh(e)-  | irh(e)- |          |
Exemple : La rivière (majeure) est à côté des maisons.
| åndjo-tsha          | irh-mèn-èl            | revean-is                                |
| rivière.majeure-ACC | ADE-maison-singulatif | être.objectif.fort-3S.LIQ.NOM.PRES.ENERG |

- <<cas-ante>>Cas antessif (/ANTE/) :: indique un lieu antérieur à l’élément.
| 1s      | 1p     | 2s     | 2p     | 3s    | 3p    | 4s    | 4p     | 5s    | 5p    |
| vwo(n)- | vw(o)- | v(o)-  | vw(o)- | vwo-  | vo-   | we-   | w(e)-  | w(o)- | w(e)- |
|         | 6s     | 6p     | 7s     | 7p    | 8s    | 8p    | 9s     | 9p    |       |
|         | v(e)-  | v(wo)- | vw(o)- | v(u)- | v(u)- | v(u)- | vw(o)- | vu-   |       |
Exemple : vwomèn (ANTE-maison) avant la maison / devant la maison

- <<cas-apud>>Cas apudessif (/APUD/) :: indique un lieu à côté, proche de l’élément. L’élément n’est pas adjacent au lieu, auquel cas il faudrait utiliser le cas adessif.
| 1s    | 1p    | 2s    | 2p     | 3s     | 3p    | 4s     | 4p    | 5s    | 5p     |
| þ(e)- | ð(e)- | ð(e)- | ðe-    | þ(e)-  | ð(e)- | þe(n)- | þ(e)- | v(e)- | ve(n)- |
|       | 6s    | 6p    | 7s     | 7p     | 8s    | 8p     | 9s    | 9p    |        |
|       | þ(e)- | ð(e)- | ð(ei)- | ðe(m)- | f(e)- | fe-    | vei-  | fei-  |        |
Exemple : veimèn (APUD-maison) à côté de la maison

- <<cas-ine>>Cas inessif (/INE/) :: indique un lieu à l’intérieur de l’élément.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p      | 5s      | 5p   |
| -(a)ŕo- | -(e)ŕo- | -ŕo(n)- | -(ń)ŕo- | -(a)ŕo- | -ŕo-    | -(e)ŕo- | -(a)ŕo- | -(e)ŕo- | -ŕo- |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s      | 9p      |      |
|         | -ŕo-    | -(a)ŕo- | -(o)ŕo- | -(a)ŕo- | -(a)ŕo- | -(u)ŕo- | -(e)ŕo- | -(a)ŕo- |      |
Exemple : mèrøn (<INE>maison) dans la maison

- <<cas-itrt>>Cas intratif (/ITRT/) :: indique un lieu entre des éléments. L’élément décliné ne peut être singulier.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p      | 5s      | 5p      |
| -fu(þ)- | -fu(ð)- | -fu(ð)- | -fu(ð)- | -fy(þ)- | -fy(ð)- | -fu(þ)- | -fy-    | -fy(ð)- | -fy(ð)- |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s      | 9p      |         |
|         | -fu(ð)- | -þy(ð)- | -(f)yþ- | -fu-    | -fi(ŕ)- | -fe(ŕ)- | -fu(ð)- | -fu(þ)- |         |
Exemple : mènåfùt (maison.duel.ITRT) entre deux maisons.

- <<cas-loc>>Cas locatif (/LOC/) :: indique que l’élément décliné est le lieu indiqué (usage général).
| 1s    | 1p    | 2s     | 2p     | 3s     | 3p    | 4s    | 4p    | 5s     | 5p    |
| l(a)- | l(e)- | l(i)-  | l(e)-  | le(þ)- | l(e)- | l(e)- | l(e)- | lj(a)- | l(a)- |
|       | 6s    | 6p     | 7s     | 7p     | 8s    | 8p    | 9s    | 9p     |       |
|       | lha-  | lh(a)- | l(au)- | l(ai)- | l(a)- | la-   | ĺ-    | l(e)-  |       |
Exemple : Il est à la maison (sans précision du lieu précis)
| øt       | ĺ-mèn-å        | nesh-øis                       |
| 3S.N.ERG | LOC-maison-ABS | être.subj.fort-3S.HUM.ERG.PRES |

- <<cas-pert>>Cas pertingent (/PERT/) :: indique un contact avec un lieu.
| 1s    | 1p     | 2s     | 2p    | 3s     | 3p     | 4s    | 4p    | 5s    | 5p    |
| m(a)- | m(a)-  | m(a)-  | m(e)- | mj(a)- | mj(e)- | m(e)- | m(e)- | m(a)- | m(e)- |
|       | 6s     | 6p     | 7s    | 7p     | 8s     | 8p    | 9s    | 9p    |       |
|       | mj(ø)- | mj(e)- | m(e)- | m(u)-  | m(a)-  | m(o)- | m(e)- | m(e)- |       |
Exemple : memèn (PERT-maison) en contact avec la maison

- <<cas-poste>>Cas postessif (/POSTE/) :: indique un lieu postérieur à l’élément.
Exemple : ménůsht (maison-POSTE) après la maison.
| 1s     | 1p      | 2s     | 2p     | 3s     | 3p      | 4s     | 4p      | 5s      | 5p    |
| -(u)sh | -(u)sht | -(y)sh | -(y)jh | -(u)ch | -(u)cht | -(u)ch | -(u)sh  | -(u)sh  | -(u)þ |
|        | 6s      | 6p     | 7s     | 7p     | 8s      | 8p     | 9s      | 9p      |       |
|        | -(u)jh  | -(y)ch | -(u)sh | -(u)zh | -(y)zh  | -(y)jh | -(y)tsh | -(y)sht |       |

- <<cas-sube>>Cas subessif (/SUBE/) :: indique un lieu sous l’élément.
| 1s     | 1p      | 2s    | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p     |
| ng(o)- | ng(wo)- | n(o)- | n(wo)- | ng(o)- | ng(o)- | nw(o)- | n(we)- | ng(e)- | ng(o)- |
|        | 6s      | 6p    | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |        |
|        | ne-     | nge-  | nge-   | ngo-   | nw(a)- | n(wa)- | n(a)-  | na-    |        |
Exemple : namèn (SUBE-maison) sous la maison

- <<cas-supe>>Cas superessif (/SUPE/) :: indique un lieu sous l’élément.
| 1s      | 1p       | 2s       | 2p       | 3s       | 3p      | 4s      | 4p       | 5s      | 5p      |
| tsh(a)- | tsh(ań)- | tsh(ai)- | tshau-   | tsh(e)-  | tsh(a)- | sht(e)- | tsh(ei)- | tsh(e)- | cht(a)- |
|         | 6s       | 6p       | 7s       | 7p       | 8s      | 8p      | 9s       | 9p      |         |
|         | sht(a)-  | sht(a)-  | tsh(ao)- | tsh(ae)- | tsha-   | shta-   | sht(e)-  | tsh(a)- |         |
Exemple : shtemèn (SUPE-maison) sur la maison / sur le toit de la maison (impliqué)

*** Mouvement depuis un élément
- <<cas-abl>>Cas ablatif (/ABL/) :: indique un déplacement s’éloignant de l’élément.
| 1s    | 1p     | 2s     | 2p      | 3s     | 3p     | 4s      | 4p      | 5s      | 5p      |
| l(i)- | l(e)-  | li(s)- | le(jh)- | l(i)-  | ĺ(jh)- | li(sh)- | li(zh)- | li(sh)- | li(zh)- |
|       | 6s     | 6p     | 7s      | 7p     | 8s     | 8p      | 9s      | 9p      |         |
|       | li(s)- | li(z)- | lń(d)-  | lń(d)- | ĺ(z)-  | ĺ(z)-   | ĺ(v)-   | ĺ(v)-   |         |
Exemple : Je pars de Ðbńo. (décision motivée par moi-même)
| wyhak-èìs               | li-Ðbńo-vu   | nè       |
| quitter-1S.HUM.NOM.PRES | ABL-Ðbńo-ACC | 1S.N.NOM |

- <<cas-del>>Cas délatif (/DEL/) :: déplacement depuis la surface de l’élément.
| 1s     | 1p     | 2s     | 2p      | 3s      | 3p     | 4s     | 4p      | 5s      | 5p     |
| sh(a)- | sh(e)- | sh(e)- | sh(e)-  | sh(ai)- | sh(a)- | ch(a)- | ch(e)-  | jh(a)-  | jh(e)- |
|        | 6s     | 6p     | 7s      | 7p      | 8s     | 8p     | 9s      | 9p      |        |
|        | jh(a)- | jh(a)- | sh(eu)- | sh(eu)- | sh(a)- | sh(a)- | sha(l)- | she(l)- |        |
Exemple : La mouche s’envola (volontairement) du livre (de l’extérieur du livre, sous entendu de sa couverture)
| probœl-èntì                | sha-raøm  | pa-rhevir  |
| s’envoler-3S.NHUM.NOM.PNEA | DEL-livre | NOM-mouche |

- <<cas-ela>>Cas élatif (/ELA/) :: déplacement depuis l’intérieur de l’élément.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p      | 5s     | 5p      |
| -(a)lhy | -(e)lhy | -(a)lhy | -(a)lhu | -(e)lhy | -(e)lhy | -(lh)y  | -(lh)y  | -(lh)y | -(lh)yi |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s      | 9p     |         |
|         | -(lh)u  | -(lh)yi | -lhy    | -(a)lhy | -(lh)ay | -(lh)ey | -(lh)ay | -lhay  |         |
Exemple : La mouche s’envola (volontairement) du livre (sous entendu depuis une page / l’intérieur du livre, le livré étant ouvert)
| probœl-èntì                    | raøm-ey   | pa-rhevir  |
| s’envoler-3S.NHUM.NOM.PNEA.PFV | livre-ELA | NOM-mouche |

- <<cas-initi>>Cas initiatif (/INITI/) :: indique le point de départ d’une action (cas général)
| 1s     | 1p    | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p      |
| -(a)kĺ | -(k)ĺ | -(e)kĺ | -(a)kĺ | -(k)ĺ  | -(k)ĺ  | -(e)kĺ | -(e)kń | -(a)kĺ | -(ei)kń |
|        | 6s    | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |         |
|        | -akĺ  | -ekĺ   | -(a)kĺ | -(e)kń | ak(ĺ)- | k(ń)-  | -(k)ĺ  | -(k)ń  |         |
Exemple : Je voyage depuis Ðbńo (sous-entendu, Ðbńo était de point de départ du voyage)
| etrjål-èìs              | Ðbńo-kĺ    | nè       |
| voyager-1S.HUM.NOM.PRES | Ðbńo-INITI | 1S.N.NOM |

*** Mouvement vers un élément
- <<cas-all>>Cas allatif (/ALL/) :: indique un mouvement vers les environs de l’élément (cas général), n’indique pas nécessairement de finalité ou de point précis.
| 1s       | 1p       | 2s      | 2p       | 3s       | 3p       | 4s      | 4p       | 5s      | 5p       |
| -li(sh)- | -li(ts)- | -li(ð)- | -li(ð)-  | -li-     | -li-     | -li(s)- | -li(zh)- | -li(z)- | -li(ch)- |
|          | 6s       | 6p      | 7s       | 7p       | 8s       | 8p      | 9s       | 9p      |          |
|          | -li(x)-  | -li(x)- | -li(rh)- | -li(rh)- | -li(þt)- | -li(v)- | -(l)iþ-  | -(l)ið- |          |
Exemple : Je voyage vers Ðbńo (sans nécessairement aller à Ðbńo même).
| etrjål-èìs              | Ðbńo-lið | nè       |
| voyager-1S.HUM.NOM.PRES | Ðbńo-ALL | 1S.N.NOM |

- <<cas-ill>>Cas illatif (/ILL/) :: mouvement vers l’intérieur de l’élément, n’indique pas nécessairement de finalité.
| 1s      | 1p       | 2s       | 2p      | 3s      | 3p      | 4s      | 4p      | 5s      | 5p      |
| -(p)øn- | -(p)on-  | -(f)øn-  | -(f)on- | -øn-    | -(p)øn- | -(s)øn- | -(s)en- | -(s)en- | -(s)an- |
|         | 6s       | 6p       | 7s      | 7p      | 8s      | 8p      | 9s      | 9p      |         |
|         | -(ps)øn- | -(ps)en- | -øn-    | -(v)øn- | -(ŕ)øn- | -(ŕ)øn- | -(ŕ)øn- | -(ŕ)en- |         |
Exemple : La mouche vole vers la maison (sous entendu, elle va y rentrer)
| eŕbœl-ay               | m<on>èn     | pa-rhevir  |
| voler-3S.NHUM.NOM.PRES | <ILL>maison | NOM-mouche |

- <<cas-lat>>Cas latif (/LAT/) :: mouvement vers l’élément (cas général), n’indique pas nécessairement de finalité.
| 1s    | 1p     | 2s     | 2p     | 3s     | 3p    | 4s     | 4p     | 5s    | 5p  |
| -(l)a | -(l)ei | -(l)øĺ | -(l)e  | -(l)au | -(l)ĺ | -(l)ń  | -(l)a  | -(l)a | -le |
|       | 6s     | 6p     | 7s     | 7p     | 8s    | 8p     | 9s     | 9p    |     |
|       | -la    | -la    | -(a)la | -(e)la | -(l)e | -(l)ai | -(l)ae | -la   |     |
Exemple : Je pars de Notń pour Ðbńo.
| wyhak-èìs               | li-Notń-vu   | Ðbńo-løĺ | nè       |
| quitter.1S.HUM.NOM.PRES | ABL-Notń-ACC | Ðbńo-LAT | 1S.N.NOM |

- <<cas-subl>>Cas sublatif (/SUBL/) :: mouvement vers la surface de l’élément.
| 1s | 1p    | 2s     | 2p    | 3s      | 3p      | 4s     | 4p     | 5s     | 5p     |        |
|    | -(i)ŧ | -(i)ŧ  | -(e)ŧ | -(i)đ   | -(i)ŧ   | -(i)nŧ | -(i)fŧ | -(i)þŧ | -(e)nŧ | -(eu)ŧ |
|    | 6s    | 6p     | 7s    | 7p      | 8s      | 8p     | 9s     | 9p     |        |        |
|    | -(a)ŧ | -(i)nŧ | -(i)ŧ | -(i)shŧ | -(i)chŧ | -(i)ŧ  | -(r)iŧ | -iŧ    |        |        |
Exemple : La mouche vole vers le livre. (sous-entendu, la couverture)
| eŕbœl-ay               | raøm-iŧ    | pa-rhevir  |
| voler-3S.NHUM.NOM.PRES | livre-SUBL | NOM-mouche |

- <<cas-term>>Cas terminatif (/TERM/) :: le mouvement a pour but l’élément.
| 1s     | 1p      | 2s      | 2p      | 3s       | 3p     | 4s     | 4p     | 5s      | 5p   |
| -(ae)n | -(ae)ng | -(þ)aen | -(ð)aen | -(þ)aeng | -(ae)m | -(ae)n | -aem   | -aeng   | -aem |
|        | 6s      | 6p      | 7s      | 7p       | 8s     | 8p     | 9s     | 9p      |      |
|        | -(ae)nz | ae(ng)- | -(ae)n  | -(ae)n   | -(ae)m | -ae    | -(ai)n | -(ai)ng |      |
Exemple : Je voyage jusqu’à Ðbńo.
| etrjål-èìs              | Ðbńo-þaen | nè       |
| voyager-1S.HUM.NOM.PRES | Ðbńo-TERM | 1S.N.NOM |

*** Déplacement via un élément
- <<cas-per>>Cas perlatif (/PER/) :: mouvement au travers ou le long de l’élément.
| 1s     | 1p      | 2s      | 2p     | 3s     | 3p     | 4s      | 4p      | 5s      | 5p      |
| jh(u)- | jh(y)-  | jh(u)-  | ch(u)- | ch(y)- | jh(u)- | ch(ui)- | jh(ui)- | ch(eu)- | ch(ey)- |
|        | 6s      | 6p      | 7s     | 7p     | 8s     | 8p      | 9s      | 9p      |         |
|        | ch(oy)- | jh(ou)- | jh(u)- | jh(e)- | jh(u)- | jh(u)-  | ch(y)-  | jh(u)-  |         |
Exemple : Je voyage le long de la rivière.
| etrjål-èìs              | chy-lhånt           | nè       |
| voyager-1S.HUM.NOM.PRES | PER-rivière.mineure | 1S.N.NOM |

- <<cas-prol>>Cas prolatif (/PROL/) :: mouvement en utilisant l’élément ou sur sa surface.
| 1s     | 1p     | 2s     | 2p      | 3s     | 3p      | 4s     | 4p      | 5s     | 5p     |
| ch(a)- | ch(a)- | ch(e)- | ch(ae)- | jh(a)- | ch(ay)- | cha-   | ch(e)-  | ch(e)- | jh(a)- |
|        | 6s     | 6p     | 7s      | 7p     | 8s      | 8p     | 9s      | 9p     |        |
|        | ch(e)- | che-   | ch(a)-  | chei-  | che-    | ch(a)- | ch(ey)- | jh(e)- |        |
Exemple : Je navigue sur l’océan côtier.
| ’elđœk-ay                | ch-ielt           | nè       |
| naviguer-1S.HUM.NOM.PRES | PROL-océan.côtier | 1S.N.NOM |

*** Temps
- <<cas-atemp>>Cas accusatif-temporel (/ACC.TEMP/) :: indication d’une durée de temps, peut remplacer l’accusatif d’une proposition nominative-accusative avec un verbe transitif.
| 1s   | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p      | 5s      | 5p       |
| -zhu | -zhu    | -zhu    | -zhu    | -zhoy   | -zhou   | -(a)zhu | -(e)zhu | -(u)zhu | -(ai)zhu |
|      | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s      | 9p      |          |
|      | -(i)zhu | -(u)zhu | -(o)zhu | -(o)zhu | -(o)zhu | -(o)zhu | -(o)zhu | -(o)zhu |          |
Exemple : J’ai dormis sept heures.
| ’oher-èntè             | heol-ì’   | pńtwån-zhu    | nè       |
| dormir-1S.HUM.NOM.PNEA | heure-GEN | sept-ACC.TEMP | 1S.N.NOM |

- <<cas-ess>>Cas essif (/ESS/) :: l’élément indique la date où le moment où un événement se produit.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p        | 5s        | 5p      |
| -(þ)yd- | -(þ)yd- | -(þ)ud- | -(þ)ud- | -(þ)yd- | -(þ)ud- | -(þ)yđ- | -(þ)yđ-   | -(ð)yŧ-   | -(ð)yŧ- |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s        | 9p        |         |
|         | -(þ)ud- | -(þ)ud- | -þy(d)- | -þy(d)- | -þy(d)- | -þy(d)- | -(oi)þyd- | -(oi)þyd- |         |
Exemple : Je dors habituellement à sept heures.
| ’oher-omèìs                  | hebéòm-i’ | p<ud>ńtwån | nè       |
| dormir-1S.HUM.NOM.PRES.HABIT | heure-GEN | <ESS>sept  | 1S.N.NOM |

- <<cas-lmt>>Cas limitatif (/LMT/) :: l’élément indique une limite dans le temps.
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p     |
| -(ø)mp | -(e)mp | -(ø)mp | -(ø)mp | -(ø)mp | -(ø)mp | -(ø)mp | -(ø)mp | -(ø)mp | -(ø)mp |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |        |
|        | -(e)mp | -(ø)mp | -(a)mp | -(a)mp | -(a)mp | -(a)mp | -(ø)mp | -(ø)mp |        |
Exemple : Je dors habituellement jusqu’à sept heures.
| ’oher-oméis                  | hebéòm-i’ | pńtwån-ømp | nè       |
| dormir-1S.HUM.NOM.PRES.HABIT | heure-GEN | sept-LMT   | 1S.N.NOM |

- <<cas-temp>>Cas temporel (/TEMP/) :: l’élément désigne un moment (cas général).
| 1s       | 1p       | 2s       | 2p       | 3s       | 3p       | 4s       | 4p       | 5s     | 5p      |
| -(i)ngni | -(i)ngni | -(i)ngni | -(i)mi   | -(i)ngni | -(i)nji  | -(y)ngni | -(ng)ne  | -engni | -(i)mji |
|          | 6s       | 6p       | 7s       | 7p       | 8s       | 8p       | 9s       | 9p     |         |
|          | -(i)ngni | -(ing)ni | -(i)ngni | -(i)ngni | -(e)ngni | -(i)ngni | -(y)ngni | -ingni |         |
Exemple : à sept heures
| hebèòm-i’ | pńtwån-ingni |
| heure-GEN | sept-TEMP    |

- <<cas-distemp>>Cas distributif-temporel (/DISTR.TEMP/) :: Similaire au [[cas-distributif][cas distributif]], montrant une répétition temporelle se produisant à chaque élément temporel décliné.
| 1s  | 1p  | 2s  | 2p    | 3s  | 3p   | 4s     | 4p  | 5s  | 5p  |
| -be | -be | -ve | -be   | -va | -fe  | -be    | -ba | -ba | -ve |
|     | 6s  | 6p  | 7s    | 7p  | 8s   | 8p     | 9s  | 9p  |     |
|     | -ve | -va | -(b)e | -be | -bei | -(b)ei | -be | -be |     |

*** Alignement morphosyntaxique
- <<cas-abs>>Cas absolutif (/ABS/) :: indique le patient d’un verbe transitif ou le sujet d’un verbe intransitif dans une proposition ergative. S’oppose à l’[[cas-erg][ergatif]].
| 1s     | 1p     | 2s      | 2p      | 3s     | 3p     | 4s     | 4p     | 5s     | 5p    |
| -(ts)a | -(ts)a | -(tsh)a | -(tsh)a | -(ts)a | -(ts)a | -(t)a  | -(ch)a | -(p)a  | -(v)a |
|        | 6s     | 6p      | 7s      | 7p     | 8s     | 8p     | 9s     | 9p     |       |
|        | -(st)a | -(jh)a  | -(r)a   | -(r)a  | -(qh)a | -(ch)a | -(rh)a | -(jh)a |       |
Exemple : J’ai brisé le vase. (action sous-entendue comme involontaire)
| nèì      | nweŧu-rha | kĺn-èìntè             |
| 1S.N.ERG | vase-ABS  | briser-1S.HUM.ERG.PAS |

- <<cas-acc>>Cas accusatif (/ACC/) :: indique le patient d’un verbe transitif dans une proposition nominative. S’oppose au nominatif.
| 1s  | 1p     | 2s     | 2p     | 3s     | 3p  | 4s     | 4p     | 5s     | 5p     |
| -vo | -vwo   | -vu    | -vwu   | -vo    | -vo | -(e)vo | -(e)vo | -(e)vo | -(e)vo |
|     | 6s     | 6p     | 7s     | 7p     | 8s  | 8p     | 9s     | 9p     |        |
|     | -(a)vo | -(a)vo | -(u)vo | -(u)vo | -vu | -vu    | -vy    | -vy    |        |
Exemple : J’ai brisé le vase. (action sous-entendue comme volontaire)
| kĺn-èntè              | nweŧu-vy | nè       |
| briser.1S.HUM.NOM.PAS | vase-ACC | 1S.N.NOM |

- <<cas-erg>>Cas ergatif (/ERG/) :: indique l’agent d’un verbe transitif dans une proposition ergative. S’oppose à l’[[cas-abs][absolutif]]. Peut-être remplacé par le [[cas-peg][pégatif]].
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p     |
| -(u)jo | -(y)jo | -(ì)jo | -(é)jo | -(u)jo | -(u)jo | -(ø)jo | -(y)jo | -(lj)o | -(lj)o |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |        |
|        | -(mj)o | -(lj)o | -jo    | -jo    | -(o)jo | -(e)jo | -(u)jo | -(u)jo |        |
Exemple : J’ai brisé le vase. (action sous-entendue comme involontaire)
| nèì      | nweŧu-rha | kĺn-èìntè             |
| 1S.N.ERG | vase-ABS  | briser.1S.HUM.PAS.PFV |

- <<cas-insc>>Cas instructif (/INSC/) :: indique le moyen employé, répond à la question /comment ?/.
| 1s     | 1p      | 2s     | 2p   | 3s     | 3p      | 4s     | 4p     | 5s      | 5p     |
| -(e)ng | -(e)ng  | -(a)ng | -eng | -(e)ng | -(a)ng  | -(e)ng | -eng   | -ang    | -(e)ng |
|        | 6s      | 6p     | 7s   | 7p     | 8s      | 8p     | 9s     | 9p      |        |
|        | -(ea)ng | -(e)ng | -eng | -engt  | -(e)ngz | -(e)ng | -(e)ng | -(e)ngt |        |
Exemple : J’ai brisé le vase en tombant. (comme je suis tombé, sous-entendu involontairement, j’ai brisé le vase)
| nèì      | jhybdin-èìntè-ng               | nweŧu-rha | kĺn-èìntè                 |
| 1S.N.ERG | tomber.1S.HUM.ERG.PAS.PFV-INSC | vase-ABS  | briser-1S.HUM.ERG.PAS.PFV |

- <<cas-instr>>Cas instrumental (/INS/) :: indique l’instrument utilisé, répond à la question /au moyen de quel objet ?/.
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s    | 5p  |
| -(d)ĺ | -(d)ĺ | -(d)ĺ | -(đ)ĺ | -(d)ĺ | -(đ)ĺ | -(d)ĺ | -(ŧ)ĺ | -(d)ĺ | -đĺ |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p    |     |
|       | -(d)ĺ | -(d)ń | -(d)ĺ | -(d)ĺ | -(d)ń | -(đ)ń | -(d)ĺ | -(d)ĺ |     |
Exemple : J’ai brisé (involontairement) le vase avec mon pied (avec un coup de pied).
| nèì      | pńt-euŧ-ń     | nweŧu-rha | kĺn-èìntè                 |
| 1S.N.ERG | pied-POSS-INS | vase-ABS  | briser-1S.HUM.ERG.PAS.PFV |

- <<cas-nomin>>Cas nominal (/NOMIN/) :: indique que l’élément décliné doit être considéré comme un nom dérivé de l’élément décliné, généralement traduisible à peu près par « /celui qui .../ ». Notez que le genre du resultat est le genre humain si ledit résultat décrit un humain, peu importe le genre d’origine, par défaut neutre.
| 1s     | 1p      | 2s      | 2p       | 3s      | 3p     | 4s      | 4p      | 5s      | 5p     |
| -(eu)s | -(eu)sh | -(eu)s  | -(eu)sht | -(eu)st | -(eu)s | -(eu)s  | -(eo)sh | -eus    | -eucht |
|        | 6s      | 6p      | 7s       | 7p      | 8s     | 8p      | 9s      | 9p      |        |
|        | -eus    | -(eu)sh | -(eu)s   | -(eu)sh | -(eu)s | -(ei)ch | -(eu)s  | -(eu)st |        |
Exemple : un cavalier (genre humain neutre) : nael-eus (cheval-NOMIN)

- <<cas-nom>>Cas nominatif (/NOM/) :: indique le sujet d’un verbe intransitif ou l’agent d’un verbe transitif dans une proposition nominative. S’oppose à l’[[cas-acc][accusatif]]. Peut-être remplacé par le [[cas-peg][pégatif]].
| 1s    | 1p     | 2s    | 2p     | 3s     | 3p      | 4s      | 4p     | 5s  | 5p  |
| p(a)- | p(e)-  | p(a)- | p(e)-  | p(a)-  | p(a)-   | pa(n)-  | pa(ń)- | pń- | pń- |
|       | 6s     | 6p    | 7s     | 7p     | 8s      | 8p      | 9s     | 9p  |     |
|       | pa(m)- | pa-   | pa(l)- | pa(l)- | pa(sh)- | pe(sh)- | pa-    | pa- |     |
Exemple : J’ai brisé le vase. (action sous-entendue comme volontaire)
| kĺn-èntè                  | nweŧu-vy | nè       |
| briser.1S.HUM.NOM.PAS.PFV | vase-ACC | 1S.N.NOM |

- <<cas-obl>>Cas oblique (/OBL/) :: marque le verbe, indique la proposition comme étant une citation. Les sous-propositions n’ont pas besoin d’être marquée. Remplace l’[[cas-acc][accusatif]] dans les propositions nominatives, et l’[[cas-abs][absolutif]] dans les propositions ergatives.
| 1s       | 1p        | 2s       | 2p       | 3s       | 3p       | 4s       | 4p        | 5s        | 5p       |
| -(rh)esh | -(rh)esht | -(rh)ef  | -(rh)eft | -(rh)esh | -(qh)esh | -(rh)ef  | -(rh)øsh  | -(rh)ef   | -(rh)øsh |
|          | 6s        | 6p       | 7s       | 7p       | 8s       | 8p       | 9s        | 9p        |          |
|          | -(rh)ef   | -(rh)øsh | -(qh)esh | -(qh)esh | -(qh)esh | -(qh)esh | -(qh)uish | -(qh)oish |          |
Exemple : j’ai dis que j’ai cassé (involontairement) le vase.
| rheð-èntè               | kĺn-èintè-rhøsh               | nweŧu-rha | nè       |
| dire.1S.HUM.NOM.PAS.PFV | briser-1S.HUM.ERG.PAS.PFV-OBL | vase-ABS  | 1S.N.NOM |

- <<cas-peg>>Cas pégatif (/PEG/) :: Remplace le [[cas-nom][nominatif]] et l’[[cas-erg][ergatif]] dans une proposition ayant un argument datif.
| 1s  | 1p  | 2s  | 2p  | 3s  | 3p  | 4s  | 4p  | 5s  | 5p  |
| ey- | eu- | ey- | ey- | eu- | ei- | ey- | ei- | ei- | eu- |
|     | 6s  | 6p  | 7s  | 7p  | 8s  | 8p  | 9s  | 9p  |     |
|     | ey- | eu- | eu- | ey- | ey- | ey- | ei- | ey- |     |

*** Relation
- <<cas-avrs>>Cas aversif (/AVRS/) :: indique que l’élément est évité ou craint.
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p   | 4s     | 4p     | 5s     | 5p     |
| lh(e)- | lh(e)- | lha-   | lh(e)- | lh(e)- | lha- | lh(e)- | lha-   | la-    | lh(e)- |
|        | 6s     | 6p     | 7s     | 7p     | 8s   | 8p     | 9s     | 9p     |        |
|        | lha-   | lh(e)- | lh(e)- | lh(e)- | lha- | l(e)-  | lh(e)- | lh(e)- |        |
Exemple : Je navigue sur l’océan côtier tout en évitant Notń.
| ’elđœk-ay                | lha-Notń  | ch-ielt           | nè       |
| naviguer.1S.HUM.NOM.PRES | AVRS-Notń | PROL-océan.côtier | 1S.N.NOM |

- <<cas-ben>>Cas bénéfactif (/BEN/) :: indique la personne ou le concept motivant une proposition d’un verbe d’action. S’il est omis à la première personne, on assume que le bénéfacteur est le sujet ou l’agent ; à la seconde ou à la troisième personne, on assume que le bénéfacteur est inconnu.
| 1s  | 1p  | 2s     | 2p  | 3s  | 3p   | 4s  | 4p  | 5s  | 5p  |
| -at | -et | -at    | -at | -at | -aŧ  | -at | -aŧ | -aŧ | -aŧ |
|     | 6s  | 6p     | 7s  | 7p  | 8s   | 8p  | 9s  | 9p  |     |
|     | -et | -(v)et | -at | -et | -ast | -aþ | -at | -et |     |
Exemple : Je navigue sur l’océan côtier (l’action est motivée par ou due à Mérian).
| Merian-aŧ  | ’elđœk-ay                | chi-elt           | nè       |
| Merian-BEN | naviguer.1S.HUM.NOM.PRES | PROL-océan.côtier | 1S.N.NOM |

- <<cas-caus>>Cas causal :: indique la cause d’une proposition
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s     | 5p     |
| -(o)by | -(o)bu | -(u)by | -(o)by | -(ob)y | -(b)y  | -(o)by | -(o)by | -(o)by | -(o)by |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p     |        |
|        | -(o)bu | -(o)bu | -(o)vu | -(e)vy | -(e)vy | -(e)vy | -vy    | -vy    |        |

- <<cas-com>>Cas comitatif (/COM/) :: indique un accompagnement par l’élément décliné, comparable au « avec » ou « et » en Français. L’action doit être partagée entre le sujet ou agent de la proposition et l’élément décliné, c’est à dire que l’élément est souvent un compagnon dans la situation (sans conotation positive ou négative).
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s       | 5p    |
| -ðai- | -ðei- | -ðei- | -ðai- | -ðei- | -ðey- | -ðeń- | -ðei- | -ðei(n)- | -ðey- |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p       |       |
|       | -ðei- | -ðey- | -ðei- | -ðei- | -ðeu- | -ðei- | -ðeu- | -ðeu-    |       |
Exemple : Je voyage le long de la rivière accompagné de Romur. (Romur et moi partageons l’expérience du voyage).
| etrjål-èìs              | chy-lhånt            | Romy<ðei>r | nè       |
| voyager-1S.HUM.NOM.PRES | PERL-rivière.mineure | Romyr<COM> | 1S.N.NOM |

- <<cas-dat>>Cas datif (/DAT/) :: élément recevant ou direction de l’action vers l’élément.
| 1s   | 1p   | 2s      | 2p   | 3s   | 3p    | 4s   | 4p   | 5s   | 5p   |
| -at- | -et- | -at-    | -at- | -at- | -aŧ-  | -at- | -aŧ- | -aŧ- | -aŧ- |
|      | 6s   | 6p      | 7s   | 7p   | 8s    | 8p   | 9s   | 9p   |      |
|      | -et- | -(v)et- | -at- | -et- | -ast- | -aþ- | -at- | -et- |      |
Exemple : Je crie (par colère) sur mon voisin.
| ŧůbům-åů              | k<aŧ>ipŕům  | nè       |
| crier-1S.HUM.NOM.PRES | <DAT>voisin | 1S.N.NOM |

- <<cas-distributif>>Cas Distributif (/DISTR/) :: Marque une distribution équitable entre les éléments déclinés. Comparable au cas [[cas-distemp][distributif-temporel]].
| 1s       | 1p      | 2s       | 2p      | 3s       | 3p       | 4s      | 4p      | 5s      | 5p     |
| qhe(ch)- | qhe(l)- | qhe(jh)- | qhe(l)- | rhe(ch)- | rhe(jh)- | he(l)-  | he(l)-  | he(l)-  | he(l)- |
|          | 6s      | 6p       | 7s      | 7p       | 8s       | 8p      | 9s      | 9p      |        |
|          | ha(l)-  | ha(l)-   | hei(l)- | hea(l)-  | hea(l)-  | hea(l)- | che(l)- | che(l)- |        |

- <<cas-gen>>Cas génitif (/GEN/) :: montre une relation entre deux éléments, l’élément décliné définit l’élément situé immédiatement après. Attention, contrairement à certaines langues, le génitif de dénote pas la possession de l’élément ; pour cela, il faut utiliser le [[cas-poss][possessif]].
| 1s    | 1p     | 2s     | 2p    | 3s    | 3p     | 4s  | 4p    | 5s     | 5p  |
| ŧ(y)- | ŧ(u)-  | ŧ(y)-  | ŧ(y)- | ŧ(y)- | ŧ(yi)- | ŧy- | ŧy-   | ŧy(i)- | ŧy- |
|       | 6s     | 6p     | 7s    | 7p    | 8s     | 8p  | 9s    | 9p     |     |
|       | ŧ(eu)- | ŧo(y)- | ŧy-   | ŧ(u)- | ŧ(u)-  | ŧu- | ŧ(y)- | ŧ(u)-  |     |

- <<cas-poss>>Cas possessif (/POSS/) :: marque l’élément comme le propriétaire de l’élément suivant immédiatement l’élément décliné. Il n’est pas utile de décliner l’élément (voire même de placer l’élément dans la phrase) si l’élément propriété est également décliné avec les déclinaisons possessives.
| 1s  | 1p     | 2s     | 2p    | 3s     | 3p    | 4s   | 4p   | 5s     | 5p   |
| -ŧy | -ŧy    | -(i)ŧy | -ŧy   | -(eu)ŧ | -(y)ŧ | -eŧy | -eŧy | -(i)ŧy | -oŧy |
|     | 6s     | 6p     | 7s    | 7p     | 8s    | 8p   | 9s   | 9p     |      |
|     | -(e)uŧ | -(o)iŧ | -(ŧ)y | -(e)ŧy | -iŧy  | -ŧy  | -yŧ  | -iŧ    |      |

- <<cas-prv>>Cas privatif (/PRV/) :: indique un manque ou une absence de l’élément décliné. Ce manque n’a aucune conotation positive ou négative.
| 1s  | 1p  | 2s  | 2p   | 3s  | 3p  | 4s  | 4p  | 5s   | 5p  |
| ei- | ei- | eń- | ejh- | ei- | éĺ- | ei- | ae- | eiđ- | ei- |
|     | 6s  | 6p  | 7s   | 7p  | 8s  | 8p  | 9s  | 9p   |     |
|     | ei- | ei- | ei-  | ei- | ei- | ei- | eń- | eń-  |     |

- <<cas-sempl>>Cas semplatif (/SEMPL/) :: indique une similitude entre le sujet/expérienceur ou l’agent de la proposition et le ou les éléments déclinés.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p      | 4s      | 4p      | 5s      | 5p      |
| -(rh)wo | -(rh)wo | -(rh)we | -(rh)wo | -(rh)wo | -rhwo   | -rhwe   | -(rh)wo | -rhwo   | -(rh)wo |
|         | 6s      | 6p      | 7s      | 7p      | 8s      | 8p      | 9s      | 9p      |         |
|         | -rhwo   | -rhwe   | -(rh)wo | -(rh)wo | -(rh)we | -(rh)wo | -(rh)wo | -(rh)wo |         |

- <<cas-soc>>Cas sociatif (/SOC/) :: indique que la situation de la proposition s’est déroulée avec l’agent ou le sujet étant avec l’élément décliné. L’élément n’a pas à partager la situation avec l’agent/sujet.
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s    | 5p    |
| t(o)- | t(e)- | t(o)- | t(o)- | ŧ(o)- | te-   | t(o)- | t(e)- | ŧe-   | t(o)- |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p    |       |
|       | to-   | ŧo-   | te-   | t(o)- | t(o)- | to-   | t(o)- | t(o)- |       |
Exemple : Je voyage le long de la rivière avec mes jumelles. (Les jumelles ne peuvent partager l’expérience dû au fait qu’elles soient inanimées et ne sont certainement pas mon moyen de voyage)
| etrjål-èìs              | chy-lhånt            | to-vyelegot  | nè       |
| voyager-1S.HUM.NOM.PRES | PERL-rivière.mineure | SOC-jumelles | 1S.N.NOM |

*** Sémantiques
- <<cas-ptv>>Cas partitif (/PTV/) :: s’utilise pour indiquer une quantité de l’élément donné s’il s’agit de désigner un sous-groupe, sans spécifier d’identité ou bien de marquer une partie uniquement de l’élément décliné.
| 1s      | 1p       | 2s       | 2p      | 3s      | 3p      | 4s      | 4p      | 5s       | 5p       |
| -’i(l)- | -’i(l)-  | -’y(l)-  | -’u(l)- | -’i(l)- | -’i(l)- | -’i(l)- | -’il-   | -’il(y)- | -ili(’)- |
|         | 6s       | 6p       | 7s      | 7p      | 8s      | 8p      | 9s      | 9p       |          |
|         | -’i(lh)- | -’e(lh)- | -’i(l)- | -gi(l)- | -’i(l)- | -ki(l)- | -’i(l)- | -’i(l)-  |          |

- <<cas-voc>>Cas vocatif (/VOC/) :: permet de s’adresser à quelqu’un en déclinant l’expression ou le nom utilisé pour s’y adresser.
| 1s  | 1p  | 2s  | 2p  | 3s  | 3p     | 4s  | 4p  | 5s   | 5p     |
| -wa | -we | -wa | -wa | -we | -(d)wa | -wa | -ja | -je  | -v(w)e |
|     | 6s  | 6p  | 7s  | 7p  | 8s     | 8p  | 9s  | 9p   |        |
|     | -va | -ve | -wa | -wa | -wein  | -wa | -wa | -weŕ |        |

*** État
- <<cas-abe>>Cas abessif (/ABE/) :: signale l’abscence que quelque chose en particulier
| 1s    | 1p     | 2s      | 2p    | 3s    | 3p     | 4s      | 4p     | 5s      | 5p      |
| e(m)- | e(ng)- | e(n)-   | e(n)- | e(l)- | e(dl)- | e(ng)-  | e(t)-  | e(st)-  | e(sht)- |
|       | 6s     | 6p      | 7s    | 7p    | 8s     | 8p      | 9s     | 9p      |         |
|       | e(nt)- | e(ngt)- | e-    | e(s)- | e-     | e(ngt)- | e(mt)- | e(ngt)- |         |

- <<cas-adv>>Cas adverbial (/ADV/) :: transforme un nom en adverbe
| 1s  | 1p  | 2s  | 2p  | 3s  | 3p  | 4s     | 4p     | 5s     | 5p  |
| -ei | -ey | -ei | -ei | -ey | -ey | -ei    | -ai    | -ai    | -ei |
|     | 6s  | 6p  | 7s  | 7p  | 8s  | 8p     | 9s     | 9p     |     |
|     | -eu | -ey | -ei | -ei | -ei | -(r)ei | -(ei)r | -(ey)r |     |

- <<cas-comp>>Cas comparatif (/COMP/) :: indique une similarité de l’élément décliné avec l’élément nominatif ou absolutif de la proposition.
| 1s     | 1p     | 2s     | 2p     | 3s     | 3p     | 4s     | 4p     | 5s      | 5p  |
| -(oi)r | -(oi)r | -(oi)r | -(oi)ŧ | -(oi)r | -(oi)t | -(oi)t | -(oi)ŧ | -oir    | -er |
|        | 6s     | 6p     | 7s     | 7p     | 8s     | 8p     | 9s     | 9p      |     |
|        | -(oi)r | -oit   | -(oi)r | -(oi)r | -or    | -(oi)r | -oirh  | -(oi)rh |     |

- <<cas-equ>>Cas équatif (/EQU/) :: indique une comparaison entre l’élément décliné et l’élément nominatif ou absolutif de la proposition.
| 1s    | 1p    | 2s    | 2p    | 3s     | 3p     | 4s    | 4p    | 5s    | 5p    |
| -(ń)t | -(ń)t | -(ń)t | -(ĺ)t | -(ń)st | -(ń)ft | -(ń)t | -(ń)đ | -(ń)ŧ | -(ń)t |
|       | 6s    | 6p    | 7s    | 7p     | 8s     | 8p    | 9s    | 9p    |       |
|       | -(ĺ)đ | -(ń)ŧ | -(ń)t | -(ń)t  | -ńt    | -(ń)t | -(ń)t | -ńt   |       |

- <<cas-exess>>Cas exessif (/EXESS/) :: Marque une transition de condition depuis l’élément décliné
| 1s   | 1p   | 2s   | 2p   | 3s     | 3p     | 4s   | 4p  | 5s   | 5p   |
| -eqh | -eqh | -erh | -eqh | -iqh   | -eqh   | -eqh | -eŕ | -eqh | -arh |
|      | 6s   | 6p   | 7s   | 7p     | 8s     | 8p   | 9s  | 9p   |      |
|      | -eqh | -erh | -eqh | -(e)qh | -(a)qh | -eqh | -eŕ | -eqh |      |

- <<cas-essfrm>>Cas essif formel (/ESSFRM/) :: indique un état d’être temporaire, une condition qualitative physique
| 1s    | 1p    | 2s    | 2p    | 3s     | 3p     | 4s     | 4p     | 5s      | 5p  |
| -(ø)ŧ | -(ø)d | -(o)d | -(o)đ | -(ø)d  | -(ø)ng | -(ŧ)ød | -(ŧ)ed | -(ŧ)ød  | -ød |
|       | 6s    | 6p    | 7s    | 7p     | 8s     | 8p     | 9s     | 9p      |     |
|       | -(ø)d | ø(d)- | -ød   | -(ø)ns | -ød    | -øts   | -(ø)sh | -(ø)sht |     |

- <<cas-essmod>>Cas essif modal (/ESSMOD/) :: indique un état d’être temporaire, une condition qualitative non-physique
| 1s      | 1p       | 2s      | 2p       | 3s      | 3p       | 4s      | 4p      | 5s      | 5p      |
| -(’)uix | -(’)uix  | -’yirh  | -(’)yirh | -(’)urh | -(’)uirh | -(’)urh | -(’)urh | -’u     | -(’)yrh |
|         | 6s       | 6p      | 7s       | 7p      | 8s       | 8p      | 9s      | 9p      |         |
|         | -(’)yirh | -(’)yrh | -(’)urh  | -(’)u   | -(’)u    | -(’)ust | -(’)urh | -(’)urh |         |

- <<cas-sim>>Cas identique (/SIM/) :: indique que l’élément décliné est identique (en certains points ou en totalité) avec l’élément nominatif ou absolutif de la proposition.
| 1s      | 1p      | 2s      | 2p      | 3s      | 3p     | 4s   | 4p      | 5s      | 5p      |
| -(e)tyr | -(a)tur | -(a)tyr | -(e)tur | -(e)tur | -tyr   | -tur | -(e)tur | -(a)tur | -(e)tur |
|         | 6s      | 6p      | 7s      | 7p      | 8s     | 8p   | 9s      | 9p      |         |
|         | -tyr    | -tyr    | -(e)tur | -(e)tur | -(t)ur | -tur | -(e)tur | -(o)tur |         |

- <<cas-ori>>Cas orientatif (/ORI/) :: indique une orientation d’un élément vers l’élément décliné.
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s    | 5p    |
| f(o)- | f(o)- | f(u)- | f(o)- | þ(o)- | f(o)- | f(o)- | v(o)- | þ(o)- | ð(o)- |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p    |       |
|       | þ(o)- | þo-   | f(o)- | f(u)- | f(o)- | vo-   | þo-   | fo-   |       |

- <<cas-transl>>Cas translatif (/TRANSL/) :: indique un changement, une transition d’état vers l’élément décliné.
| 1s    | 1p    | 2s    | 2p    | 3s    | 3p    | 4s    | 4p    | 5s     | 5p    |
| -(i)n | -(i)n | -(y)n | -(e)n | -in   | -(i)n | -(i)n | -(y)m | -(i)ng | -(i)n |
|       | 6s    | 6p    | 7s    | 7p    | 8s    | 8p    | 9s    | 9p     |       |
|       | -(i)m | -(i)n | -(i)n | -(i)n | -in   | -ing  | -ing  | -ing   |       |



# | 1s     | 1p      | 2s      | 2p       | 3s      | 3p     | 4s      | 4p      | 5s      | 5p     |
# | -(eu)s | -(eu)sh | -(eu)s  | -(eu)sht | -(eu)st | -(eu)s | -(eu)s  | -(eo)sh | -eus    | -eucht |
# |        | 6s      | 6p      | 7s       | 7p      | 8s     | 8p      | 9s      | 9p      |        |
# |        | -eus    | -(eu)sh | -(eu)s   | -(eu)sh | -(eu)s | -(ei)ch | -(eu)s  | -(eu)st |        |

src_latex{\newpage}
** Formation d’un mot
** Conjonctions
** Chiffres et nombres
** Interjections
* Structure des phrases
** Phrase et ordre des mots

# Beneficiaire-Verbe-Patient-Oblique-Agent
# Agent-Patient-Oblique-Verbe
# Verbe-Oblique-Expérienceur

** Constructions de phrases complexes
** Constructions spéciales

src_latex{\newpage}
* <<glossaire>>Glossaire

- clef ::  /transcription large/ /élément de langage./ Définition(s)
Définition

Abréviations :
- 1-9 : numéro de genre (voir [[morpho-nom-genre][les genres]])
- adj. : adjectif
- ind. : indénombrable
- n.X : nom du Xème genre
- pron. : pronom
- vi. : verbe intransitif
- vt : verbe transitif

** À trier

** Actions physiques
- kĺnyþ :: /kl̩.nyːθ/ (vt.) casser, briser
- ŧůbůmůþ :: /ʈʏ.bʏ.mʏθ/ (vi.) crier par colère, par rage
- jhybdinyþ :: /ʐyːb.diː.nyːθ/ (vi.) tomber
- ’oheryþ :: /ʔo:.he:.ry:þ/ (vi.) dormir
** Amour
** Animaux
- nael :: /nael/ (n.7) cheval
- rhevìr :: /ʁeː.vɪr/ (n.7) mouche
** Art
- raøm :: /raøm/ (n.9) livre
** Astronomie
- <<glos-bèòm>>bèòm ::  /bɛɔm/ (n.1) Soleil. Étymologie : /[[glos-bèm][bèm]]/ + /[[gloss-jaom][jaom]]/, astre du jour
- <<gloss-jaom>>jaom :: /jaom/ (n.1) astre
** Bâtiments
- mèn :: /mɛn/ (n.9) maison (bâtiment)
** Commerce
** Conflits
** Conteneurs
** Corps
- gar :: /ɡaːr/ (n.6) tête
- <<glos-pńt>>pńt :: /pn̩t/ (n.6) main
- <<glos-wån>>wån :: /waːn/ (n.6) pied
** Couleurs
- <<glos-ðùr>>ðùr :: /ðʊr/ (adj.) argent (couleur)
** Dimensions
** Direction
- ngam :: /ŋaːm/ (n.2) ouest
- watshùd :: /waːt.ʃʊd/ (n.2) nord
- wèmchal :: /wɛm.çaːl/ (n.2) est (direction)
- zelðeg :: /zeːl.ðeːɡ/ (n.2) sud
** Eau
- ånd :: /ɑnd/ (n.3) rivière majeure, cours d’eau dans lequel s’est jeté une autre rivière, mais ammenée à se jeter elle-même dans un autre cours d’eau
- hanđ :: /haːnɖ/ (n.3) fleuve mineur, cours d’eau n’ayant aucun confluent se jetant directement dans la mer ou l’océan
- ielt :: /ielt/ (n.3) océan côtier, vaste étendue d’eau au contact des côtes
- lhånt :: /ɬɑt/ (n.3) rivière mineure ou ruisseau, cours d’eau dans lequel ne s’est jeté aucun autre cours d’eau mais ammené à se jeter dans un autre cours d’eau
- omd :: /oːmd/ (n.3) océan non-côtier, vaste étendue d’eau n’étant pas au contact des côtes
- vilŧ :: /viːlʈ/ (n.3) fleuve majeur, cours d’eau ayant reçu d’autre cours d’eau et se jetant directement dans la mer ou l’océan
- ’èlđ :: /ʔɛlɖ/ (n.3) mer, petite étendue d’eau connectée à d’autres mers ou océans, ou région d’océan côtier
** Effort
** Éléments
** Émotions
- ferhan :: /feː.ʁaːn/ (n.2) tristesse
** Évaluation
- ’eshtef :: /ʔeːʃ.teːf/ (adj.) mauvais
** Événements
- gèn :: /ɡɛn/ (n.2) acte, action
** Existence
- neshøm :: /neː.ʃøːm/ (vt.) être (subjectif certain)
- revøm :: /reː.vøːm/ (vt.) être (objectif certain)
** Famille
- ånåm :: /ɑ.nɑm/ (n.6) parent
- månåm :: /mɑ.nɑm/ (n.5) mère, maman
- pånåm :: /pɑ.nɑm/ (n.4) père, papa
** Forme
** Gouvernement
** Grammaire
- pœb :: /pœb/ (pron. interrogatif) quoi, idée générale d’élément. Peut être décliné afin d’obtenir des questionnements plus précis.
*** Pronoms interrogatifs
**** Temps
- pejb ::  /pejb/ (pron. interr. essif) quand, à quel moment. /pœb/ décliné à l’essif.
- pœèmp ::  /pœɛmp/ (pron. interrogatif limitatif) jusqu’à quand. /pœb/ décliné au limitatif.
- pœvwò ::  /pœ.vwɔ/ (pron. interrogatif accusatif) sur quelle durée, pendent combien de temps. /pœb/ décliné à l’accusatif.

** Guerre
- wòùl :: /wɔʊl/ (n.2) attaque
** Légal
** Lieux
** Lumière
** Mental
** Mesures
** Métaux
** Mouvement
- etrjåløm :: /eː.trjɑ.lʏθ/ (vi.) voyager
- eŕbœlůþ :: /eːɹ.bœ.lʏθ/ (vi.) voler (dans le airs)
- jĺchek :: /jl̩.çeːk/ (n.9) chemin, voie
- probœlůþ :: /proː.bœ.lʏþ/ (vi.) s’envoler
Exemple : Probœlèntì parhevir. La mouche s’envola.
- wyhakøm :: /wyː.haː.køːm/ (vt.) quitter, partir.
Exemple : Nè liÐbńovu wyhakèìs. Je pars de Ðbńo.
- ’elđœkůþ :: /ʔeːl.ɖœ.kʏθ/ (vi.) naviguer
** Nature
** Nombres
- pńtwån ::  /pn̩.twɑn/ (nbrc) sept. Étymologie : /[[glos-p%C5%84t][pńt]]/ + /[[glos-wån][wån]]/
** Nourriture
** Outils
- vyelegot :: /vye.leː.ɡoːt/ (n.9) jumelles (instrument)
- nweŧu :: /nweː.ʈuː/ (n.9) vase
** Parole
- rheðyþ :: /ʁeː.ðyːθ/ (vt.) dire
- vår :: /vɑr/ (n.2) langue (linguistique), langage, parole
** Péchés
** Physique
** Possession
** Religion
- hjalp :: /hjaːlp/ (n.1) dieu céleste
- melex :: /meː.leːχ/ (n.1) dieu terrestre
** Savoir
- bòljøluþ :: /bɔ.ljøː.luːθ/ (vt.) savoir
- wańmjœd ::  /waːn̩.mjœd/ (n.2) savoir, connaissance
** Sensations
- ferhtef ::  /feːʁ.teːf/ (n.2) douleur mentale, dépression. Étymologie : /ferhan/ + /’eshtef/, une /tristesse mauvaise/
- nùòtœm :: /nʊɔ.tœm/ (vt.) voir
** Sexe
** Société
- kipŕům :: /kiː.pɹʏm/ (n.6) voisin
** Substances
- lùb :: /lʊb/ (n.9) air
** Temps
- <<glos-bèm>>bèm :: /bɛm/ (n.2) jour (mesure de temps)
- hebèòm ::  /heː.bɛɔm/ (n.2) heure (repère de temps). Étymologie : /[[glos-heol][heol]]/ + /[[glos-bèòm][bèòm]]/ l’heure par le Soleil
- <<glos-heol>>heol :: /heol/ (n.2) heure (mesure de temps)
- lhail :: /ɬail/ (n.2) année (mesure de temps)
- ŧealnat :: /ʈeal.naːt/ (adj.) précision temporelle, précis.
*** Jours de la semaine
- ðùbèm ::  /ðʊ.bɛm/ (n.2) septième jour de la semaine / jour d’agent. Étymologie : /[[glos-ðùr][ðùr]]/ + /[[glos-bèm][bèm]]/
** Travail
** Végétaux
** Vêtements
** Vie et santé
- ðenmòìl :: /ðeːn.mɔɪl/ (n.6) personne, individu
#  LocalWords:  phon-diphtongues phon-consonnes this Müller hit book button bottle Guéré bʌtn̩ bʌtn̩ cons-syll excl.singulier
