#+TITLE: Une Grammaire du Mattér
#+AUTHOR: Lucien Cartier-Tilet
#+EMAIL: phundrak@phundrak.fr
#+CREATOR: Lucien Cartier-Tilet
#+LANGUAGE: fr
#+SETUPFILE: theme-readtheorg.setup
#+LATEX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [a5paper,twoside]
#+LATEX_HEADER: \usepackage{xltxtra,fontspec,xunicode}\usepackage[total={4.5in,7.0in}]{geometry}\setromanfont[Numbers=Lowercase]{Charis SIL}
#+LATEX_HEADER: \usepackage{xcolor} \usepackage{hyperref}
#+LATEX_HEADER: \hypersetup{colorlinks=true,linkbordercolor=red,linkcolor=blue,pdfborderstyle={/S/U/W 1}}
#+LATEX_HEADER: \usepackage{multicol}
#+LaTeX_HEADER: \usepackage{indentfirst}\usepackage{allrunes}
#+HTML_DOCTYPE: html5
#+HTML_HEAD: <link rel="shortcut icon" href="https://cdn.phundrak.fr/img/mahakala-128x128.png" type="img/png" media="screen" />
#+HTML_HEAD: <link rel="shortcut icon" href="https://cdn.phundrak.fr/img/favicon.ico" type="image/x-icon" media="screen" />
#+HTML_HEAD: <meta property="og:image" content="https://cdn.phundrak.fr/img/rich_preview.png" />
#+HTML_HEAD: <meta name="twitter:card" content="summary" />
#+HTML_HEAD: <meta name="twitter:site" content="@phundrak" />
#+HTML_HEAD: <meta name="twitter:creator" content="@phundrak" />
#+HTML_HEAD: <meta name="description" content="Grammaire détaillée de la langue construite du Mattér" />
#+HTML_HEAD: <meta property="og:title" content="Grammaire du Mattér" />
#+HTML_HEAD: <meta property="og:description" content="Grammaire détaillée de la langue construite du Mattér" />
#+MACRO: if-latex-else (eval (if (org-export-derived-backend-p org-export-current-backend 'latex) "$1" "$2"))
#+MACRO: newline @@latex:\hspace{0pt}\\@@ @@html:<br>@@
#+OPTIONS: H:4
#+OPTIONS: toc:nil
src_latex{\newpage}
#+TOC: headlines
src_latex{\newpage}

* Avant-propos
La redistribution ou vente de ce document sont strictement interdits. Ce document est protégé par la loi française sur le droit d’auteur et appartient entièrement et totalement à son auteur. Ce document est un document disponible gratuitement au format web à l’adresse [[https://langue.phundrak.fr/matter/]] et au format PDF à l’adresse [[https://langue.phundrak.fr/matter/matter.pdf]]. Si vous l’avez obtenu depuis une autre source, gratuitement ou non, merci de m’en faire part en me contactant via mes réseaux sociaux ou par mail que vous trouverez sur mon site principal, [[https://phundrak.fr]]. Aucune personne, morale ou physique, n’est à l’heure actuelle autorisée à redistribuer ces documents. Si vous êtes intéressés par une redistribution de ce document, je vous invite à rentrer en contact avec moi afin que l’on en discute.

src_latex{\newpage}
* Introduction
Le Mattér est une langue construite humaine, inspirée phonétiquement et grammaticalement des langues latines et du Latin plus particulièrement, bien que gardant ses distances avec ce dernier. Elle bénéficie également de quelques inspirations germaniques et des langues elfiques de Tolkien concernant leur phonétique.

Cette langue est un projet à part de mon univers littéraire et fut créé dans le cadre de mes études, pour mon cours d’ingénierie des langues, enseigné par Ana Pappa, en troisième année de licence, à l’Université Paris 8. Je ne sais pas encore si j’en ferai autre chose que d’une langue-jouet.

src_latex{\newpage}
* Description du lexique
Le lexique du Mattér sera largement inspiré par des racines nordiques (Suédois, Norvégien, Danois), germaniques (Allemand principalement) et du Vieil Anglais, ainsi qu’occasionellement du Latin.

src_latex{\newpage}
* Phonologie
** Notes sur la romanisation du Mattér
Comme vous avez pu vous en rendre compte aux chapitres §[[*Consonnes]] et §[[*Voyelles]], le Mattér dispose de deux orthographes possibles, la transcription phonétique en IPA (/International Phonetic Alphabet/), soit une translittération qui sera généralement plus simple et intuitive à lire. Dans le cas du Mattér, les deux reflètent dans la large majorité des cas la prononciation de la langue, et c’est pour cela que j’utiliserai principalement la translittération. Cependant il peut y avoir certains cas où la prononciation peut légèrement différer de l’orthographe, comme dans les cas d’allophonie (§[[*Allophonie]]) ou autres cas inhabituels, auquel cas j’utiliserai la transcription phonétique afin de rendre claire la prononciation. Quand il sera question de transcription phonétique, il sera généralement question de phonétique générale, mais il se peut que certaines distinctions se fassent à un niveau plus fin où une transcription phonétique rapprochée sera nécessaire pour avoir la prononciation exacte.

La transcription phonétique générale sera ​/entre barres obliques/, la transcription phonétique rapprochée sera [entre crochets] tandis que des éléments translittérés du Mattér seront <entre chevrons>.

** Inventaire phonétique
Comme mentionné en introduction (§[[*Introduction]]), le Mattér est une langue dont la phonologie est inspirée de langues latines, en particulier le Latin lui-même, et les langues elfiques de Tolkien.

*** Consonnes
Le Mattér est une langue disposant d’un panel raisonnable de seize consonnes. Voici ci-dessous le tableau des consonnes du Mattér, en IPA et translittéré (voir le chapitre §[[*Notes sur la romanisation du Matt%C3%A9r]] concernant la translittération).

#+CAPTION: Consonnes du Mattér (IPA)
|               | nasal | occlusif | fricatif | spirant | battu | spir.-latt. |
|---------------+-------+----------+----------+---------+-------+-------------|
| bilabial      | m     | p b      |          |         |       |             |
| labio-dental  |       |          | f v      |         |       |             |
| alvéolaire    | n     | t d      | θ ð      |         | r     | l           |
| palatal       |       |          | ç        | j       |       |             |
| labio-velaire |       |          |          | w       |       |             |
| vélaire       |       | k g      |          |         |       |             |
| glottal       |       |          | h        |         |       |             |
| /             | <     | <        | <        | <       | <     | <           |

#+CAPTION: Consonnes du Mattér (translittération)
|               | nasal | occlusif | fricatif | spirant | battu | spir.-latt. |
|---------------+-------+----------+----------+---------+-------+-------------|
| bilabial      | m     | p b      |          |         |       |             |
| labio-dental  |       |          | f v      |         |       |             |
| alvéolaire    | n     | t d      | th dh    |         | r     | l           |
| palatal       |       |          | ch       | j       |       |             |
| labio-velaire |       |          |          | w       |       |             |
| vélaire       |       | c g      |          |         |       |             |
| glottal       |       |          | h        |         |       |             |
| /             | <     | <        | <        | <       | <     | <           |

On peut remarquer que la large majorité des consonnes se situe entre les points d’articulation alvéolaire et bilabial, et toutes les consonnes occlusives ou fricatives disposent de leur contrepartie sourde ou voisée.

Voici ci-dessous une description individuelle de chaque consonne :
- b :: Il s’agit du <b> standard dont disposent le Français dans « bonbon » [bɔ̃bɔ̃] ou l’Anglais « believe » [bɪlɪv], une consonne bilabiale occlusive voisée [b].
- c :: Il s’agit du <k> non aspiré que l’on peut retrouver en Français comme « cas » [ka] ou dans certains cas en Anglais comme dans « skirt » [skɜːtʰ]. Il s’agit donc de la consonne occlusive uvulaire sourde [k].
- ch :: Ce <ch> existe en Allemand dans des termes tels que « nicht » [nɪçt] ou en Anglais Britannique dans « hue » [çʉː]. Il s’agit d’une consonne fricative palatale sourde [ç].
- d :: Il s’agit de la consonne <d> standard que l’on peut retrouver en Anglais dans « dice » [daɪs], où le <d> est prononcé en bloquant l’arrivée d’air au niveau de la partie rugueuse du palais. Il est donc différent du <d> français qui est prononcé avec la langue rapprochée voire touchant les dents et qui est noté [d̪], comme dans « dance » [d̪ɑ̃s]. Le <d> du Hjelp est donc bel et bien une consonne occlusive alvéolaire voisée [d].
- f :: Il s’agit du <f> standard que l’on retrouve bon nombre des langues telles que le Français [fʁɑ̃sɛ] ou l’Anglais « fit » [fɪtʰ]. Il s’agit donc d’une consonne fricative labio-dentale sourde [f].
- g :: Il s’agit du <g> dur standard que l’on retrouve dans bon nombre des langues telles que le Français dans « Gar » [ɡɑʁ] ou en Anglais dans « get » [ɡɛt]. Il s’agit donc d’une occlusive vélaire voisée [g].
- h :: Il s’agit de la même consonne que le [h] que l’on retrouve en Anglais, tel que dans « high » [haɪ̯] ou en Allemand « Hass » [has]. Il s’agit donc de la consonne friccative glottale sourde [h].
- j :: Le <j> représente la voyelle <i> prononcée comme une consonne, la rendant donc effectivement semi-consonne. On la retrouve en Français dans des mots tels que « yak » [jak] ou « yoyo » [jojo]. Il s’agit donc d’une consonne approximante rétroflexe voisée [j].
- l :: Ce <l> est le <l> que l’on peut retrouver en Français dans « lire » [liʁ] et dans certains cas en Anglais dans « live » [lɪv]. Le <l> du Hjelp est donc une consonne alvéolaire spirante-latérale voisée [l].
- m :: Il s’agit du même <m> que le <m> standard en Français « mère » [mɛʁ] ou en Anglais « me » [miː]. Il s’agit donc de la consonne nasale bilabiale voisée [m].
- n :: Il s’agit du <n> standard que l’on retrouve en Anglais comme dans « not » [nɔt]. Attention, cette consonne est alvéolaire et non dentale comme le <n> français de « nuit » [n̪ɥi]. Il s’agit donc d’une consonne nasale alvéolaire voisée [n].
- p :: Il s’agit du <p> non aspiré que l’on retrouve en Français tèl que dans « père » [pɛʁ] ou dans certains cas en Anglais comme dans « spoon » [spuːn]. Il s’agit donc de la consonne occlusive bilabiale sourde [p].
- r :: Ce <r> peut être retrouvé en Scots « bricht » [brɪçt], en Espagnol « perro » [pe̞ro̞] ou encore en Portugais avec « ratu » [rato]. Il s’agit d’une consonne alvéolaire roulée voisée [r].
- t :: Ce <t> est la contrepartie voisée de <d> et peut se trouver en Dannois « dåse » [tɔ̽ːsə], en Luxembourgeois « dënn » [tən] ou en Finnois avec « parta » [pɑrtɑ]. Attention, le <t> Français est dental, comme dans « tante » qui est prononcé [t̪ɑ̃t̪]. Ainsi, le <t> du Hjelp est la consonne occlusive alvéolaire sourde [t].
- v :: Le <v> du Hjelp peut être retrouvé dans des langues tels que le Français dans « valve » [valv], en Allemand « Wächter » [vɛçtɐ] ou en Macédonien « вода » [vɔda]. Il s’agit donc d’une consonne fricative bilabiale voisée [v].
- w :: Le <w> est un son que l’on peut retrouver dans certaines langues comme le Français dans « oui » [wi], en Anglais avec « weep » [wiːpʰ], ou en Irlandais « vóta » [ˈwoːt̪ˠə]. Il s’agit de la consonne approximante labio-velaire voisée [w].
- dh :: Cette consonne <th> peut être trouvée dans des langues tels que l’Anglais dans « this » [ðɪs], en Allemand Autrichien « leider » [laɛ̯ða] ou en Swahili dans « dhambi » [ðɑmbi]. Il s’agit donc de la consonne fricative dentale voisée [ð].
- th :: Il s’agit de la contrepartie sourde de <dh> qui peut être trouvée en Anglais dans « thin » [θɪn], en Malaisien dans « Selasa » [θelaθa] ou en Espagnol Castillan « cazar » [käθär]. Il s’agit de la consonne fricative dentale sourde [θ].

Les consonnes nasales, occlusives ainsi que le ​/l/ peuvent être doublées, alongeant ainsi leur prononciation. Ainsi, le <tt> de <Mattér> sera prononcé ​/tː/, et <Mattér> sera prononcé ​/'mat:er/.

*** Voyelles
Le Mattér dispose de relativement peu de voyelles, uniquement six. Voici leur tableau :
#+CAPTION: Voyelles du Mattér (IPA)
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | i / y       | u            |
|   | mi-fermées  | e           | o            |
|   | mi-ouvertes | ɛ           |              |
|   | ouvertes    | a           |              |

#+CAPTION: Voyelles du Mattér (translittération)
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | i / y       | u            |
|   | mi-fermées  | é           | o            |
|   | mi-ouvertes | e           |              |
|   | ouvertes    | a           |              |

Les voyelles du Mattér montrent une plus grande complexité parmi les voyelles antérieures et les voyelles fermées.

Voici ci-dessous la description de chacune de ces voyelles :
- a :: Il s’agit de la voyelle antérieure ouverte non-arrondie [a] que l’on retrouve dans « patte » [pat] en Français.
- e :: Il s’agit de la voyelle antérieure mi-ouverte non-arrondie [ɛ] que l’on retrouve dans « bet » [bɛtʰ] en Anglais ou « fête » [fɛt̪] en Français.
- é :: Il s’agit de la voyelle antérieure mi-fermée non-arrondie [e] que l’on retrouve dans « blé » [ble] en Français.
- i :: On peut retrouver cette voyelle en Anglais comme dans « free » [fɹiː], « ív » [iːv] en Hongrois ou « vie » [vi] en Français. Il s’agit de la voyelle antérieure fermée non-arrondie [i].
- o :: Il s’agit de la voyelle postérieure mi-fermée longue arrondie [o] que l’on peut retrouver dans « hôtel » [o.tɛl].
- u :: On peut retrouver cette voyelle en Allemand standard dans « Fuß » [fuːs] ou en Français dans « tout » [t̪u]. Il s’agit de la voyelle postérieure fermée arrondie [u].
- y :: On peut retrouver cette voyelle en Allemand standard dans « über » [yːbɐ], en Hongrois avec « tű » [t̪yː] ou tout simplement en Français dans « lune » [lyn]. Il s’agit de la voyelle antérieure fermée arrondie [y].

*** Diphtonges
Les diphtongues sont des associations de voyelles considérées dans une langue comme étant une voyelle unique, avec la première unité portant la longueur de la voyelle, la seconde n’étant prononcée qu’en relachant la voyelle. Ainsi, en Anglais, les diphtongues sont assez communes comme avec le terme « je », « ​/I/ » prononcé ​/aɪ/. Voici la liste des diphtongues existant en Hjelp :

#+CAPTION:Diphtongues du Mattér
| ​/ɛi/ | ​/ai/ |
| ​/ea/ | ​/ae/ |
| ​/eu/ | ​/au/ |
| ​/ou/ |      |

Toutes ces combinaisons sont, comme décrit ci-dessus, monosyllabiques et sont considérées comme telles par les locuteurs de cette langue. Leur translittération est simple (il suffit de faire de même que s’il s’agissait de voyelles isolées) à l’exception du ​/ɛi/ qui est écrit <ei>. Ces diphtongues se produisent naturellement lors de la juxtaposition des deux voyelles les formant, et elles peuvent déjà être présentes dans une racine de mot. Ainsi, si une déclinaison ajoute un <a> après un <e>, la diphtongue <ea> se produira naturellement, comme pour la forme nominative de <teren> (/tour/) qui devient <tereant> dans sa forme accusative.

** Allophonie
Bien qu’étant rares, le Mattér a quelques règles à appliquer concernant l’allophonie.
- Le ​/i/ peut également se prononcer ​/ɪ/ dans certains cas, comme dans les diphones, devant un ​/ç/, ​/j/, ​/w/ ou ​/l/, selon le locuteur. Exemple : <neich> ​/nɛiç/ [nɛɪç]
- S’il est suivi d’une voyelle dans le même mot, le ​/i/ se transorme en la semi-consonne ​/j/.
- Le ​/l/ se transforme en « <l> sombre » ​/ɫ/ en fin de syllabe, en particulier avant une pause ou un silence. Exemple : <mael> ​/mael/ [maeɫ]
- Le ​/lː/ se prononce ​/ɫː/ dans toutes ses occurences.
- Le ​/h/ se transforme en ​/ç/ s’il est suivi par un ​/j/, un ​/e/ ou un ​/i/. Exemple : <hét> ​/het/ [çet]
- Si un ​/ɛ/ suit un ​/e/, alors le ​/ɛ/ devient un ​/e/.
- Si un ​/e/ suit un ​/ɛ/, alors le ​/e/ devient un ​/ɛ/.

** Phonotaxes
Les phonotaxes sont des règles importantes car elle permettent de déterminer quelles sont les associations de sons possibles dans une langue. C’est ce genre de règles qui permettent de savoir que des mots tels que <jchkwufrwt> ou <nkwej> ne sont pas possibles tandis que des mots tels que <éljond> ou <yndest> le sont. Nous avons déjà déterminé dans la partie dédiée aux diphtongues (§[[*Diphtonges]]) et les voyelles pouvant se succéder afin de créer une diphtongue. En revanche, si deux voyelles se suivent sans entrer dans les règles des diphtongues, elles seront considérées comme étant bisyllabiques, c’est à dire que chacune sera considérée comme une syllabe à part.

Concernant les consonnes, différentes règles s’appliquent selon la situation dans la syllabe.

*** Attaque
L’attaque est la première partie de la syllabe, les premières consonnes la composant. Elle peut comporter d’aucune consonne à deux consonnes ne contenant pas de semi-voyelle, trois avec une semi-voyelle comme consonne finale.
- Le ​/j/ ne peut être suivi par un ​/i/.
- Le ​/w/ ne peut être suivi par une voyelle postérieure.
- Les fricatives et occlusives peuvent être suivies par un ​/r/ ou un ​/l/, ou par une semi-voyelle.
- Les fricatives peuvent être suivies par une occlusive, par un ​/r/ ou un ​/l/.
- Le ​/ç/ ne peut être suivi par une occlusive voisée.
- Le ​/h/ ne peut être suivi que par un ​/j/ ou un ​/w/ et ne peut pas suivre une autre consonne.

*** Coda
Le coda (la seconde partie consonnantique de la syllabe la terminant) est composée d’aucune à deux consonnes.
- Les semi-consonnes ​/j/ et ​/w/ ne peuvent se situer dans le coda.
- Les consonnes ​/r/ et ​/l/ peuvent être suivies par une consonne nasale, occlusive ou fricative.
- Les fricatives sourdes ne peuvent être suivies que par des occlusives sourdes.
- Les fricatives voisées ne peuvent être suivies que par des occlusives voisées ou par des nasales.
- Les nasales peuvent êtres suivies par une occlusive ou une fricative.
- Les occlusives sourdes peuvent être suivies par un <th>.
- Les occlusives voisées peuvent être suivies par un <dh>.
- Le ​/h/ ne peut pas se situer dans le coda.

*** Inter-syllabe
Les consonnes inter-syllabes, situées entre deux voyelles, sont soumises elles-aussi à des règles qui leur sont propres.
- Toutes les règles de l’attaque (§[[*Attaque]]) sont applicables.
- Les consonnes occlusives peuvent être suivies par une fricative, par un ​/r/ ou un ​/l/.
- Les consonnes bilabiales peuvent être suivies par des occlusives voisées.
- Le ​​/h/, tel que dans l’attaque, ne peut s’associer qu’avec le ​/j/ ou le ​/w/ qui le suivent.
- Les consonnes longues (géminées) ne peuvent se produire qu’entre deux syllabes et ne peuvent s’associer à d’autres consonnes.

** Accentuation
Le Mattér est une langue dont l’accentuation est assez simple à suivre étant donné qu’elle se produit sur la syllabe initiale de tout mot constitué de plus de deux syllabes. Exceptionnellement, si le locuteur veut mettre une emphase sur un certain terme, l’accentuation portera sur la seconde syllabe, voire la troisième dans des cas plus rare et dont l’emphase est presque caricaturée.

src_latex{\newpage}
* Morphologie
La morphologie d’une langue est l’étude de la formation des mots de façon individuelle, de l’aspect et de la modification de ces mots afin de signifier des changements de sens. Pour ce qui est de l’organisation des mots, se référer au chapitre sur la syntaxe (§[[*Syntaxe]]).

Le Mattér est une langue à morphologie principalement agglutinatif puis synthétique ; cela signifie que le changement des mots va principalement s’opérer via des syllabes uniques affixées au mot, chacune portant potentiellement plusieurs significations.

** Genre
Ce chapitre sur le genre n’est pas un chapitre de morphologie en soit, mais il est important de connaître les genres en vigueur dans le Mattér afin de pouvoir étudier le reste de sa grammaire.

Le Mattér est une langue dont le genre est relativement peu significatif, où seuls les humains ont un genre et influence les éléments influençables, notamment les pronoms, déterminants et adjectifs. Le Mattér dispose ainsi de quatre genres :
- Neutre (~N~)
- Masculin (~M~)
- Féminin (~F~)
- Non-humain (~NHUM~)

Ainsi, pour les éléments genrés de la langue, le genre est soit connu, auquel cas le masculin ou le féminin seront utilisés, ou bien il sera inconnu auquel cas le neutre sera de vigueur. Pour tous les éléments non-genrés, le genre non-humain sera appliqué. Il arrive cependant que, par affection, un locuteur genre un animal ou un objet ; dans le cas d’un animal, le genre sera accordé à son sexe biologique, et l’objet sera assimilé au genre neutre.

** Noms
Les noms en Mattér servent généralement à se référer à des entités, des concepts ou bien des objets. Ils sont composés d’au moins une syllabe à laquelle peuvent s’ajoute des suffixes.

Voici la structure globale d’un nom :

#+CAPTION:Structure d’un nom en Mattér
| / | <>     | >           | >         | >      |
|---+--------+-------------+-----------+--------|
|   | racine | déclinaison | possessif | nombre |
|---+--------+-------------+-----------+--------|

*** Nombre
Le Mattér est une langue comportant trois nombres : le singulier, le paucal et le pluriel.
- singulier :: permet de se référer à un élément unique
- paucal :: permet de se référer à entre deux et six éléments, comporte une conotation de « peu d’éléments »
- pluriel :: permet de se référer à plus de six éléments, comporte une conotation de « beaucoup ».

Voici la liste des suffixes du Mattér afin de marquer le nombre :
#+CAPTION:Inflexion des nom en nombres
| /         | <            |
| nombre    | suffixe      |
|-----------+--------------|
| singulier | /non marqué/ |
| paucal    | -(e)t        |
| pluriel   | -(a)th       |
La voyelle entre parenthèse est omise lorsque le nombre s’accole à un mot se terminant déjà par une voyelle.

Comme indiqué plus haut, le paucal et le pluriel ont tous deux une conotation respectivement de « peu » et de « beaucoup ». Ainsi, il n’est pas rare pour les locuteurs de cette langue de transgresser la règle de séparation des deux à « 6 » afin de partager un jugement personnel sur la quantité décrite.

Les éléments indénombrables sont au singulier par défaut, mais à nouveau les locuteurs peuvent émettre un jugement personnel de quantité de ces éléments en les mettant au paucal ou au pluriel.

*** Déclinaisons
Selon son rôle dans la phrase, les noms en Mattér se présentent sous une forme différente via leur déclinaison. Huit déclinaisons existent en Mattér :
- le nominatif
- l’accusatif
- le datif
- le locatif
- l’ablatif
- le limitatif
- le génitif
- le vocatif

Le nominatif permet de marquer de manière générale le ou les sujets des verbes transitifs et intransitifs du Mattér. À l’inverse, l’accusatif permet de marquer le ou les objets des verbes transitifs. Le datif permet généralement de marquer ce à quoi on se réfère généralement en Français par « complément d’objet indirect ». Par exemple, en Français la phrase « j’ai offert un cadeau à ma sœur » comporte ces trois éléments, « je » qui est l’élément nominatif, « ma sœur » qui est l’élément datif et « un cadeau » qui est l’élément accusatif.

Le locatif, l’ablatif et le limitatif sont généralement utilisé pour se référer à des lieux, le locatif se référent au lieu directement, l’ablatif se référant à un point de départ et le limitatif à une limite. Ces trois derniers peuvent également se référer à des éléments temporels. Par exemple, dans la phrase « Je fais une escale à Paris dans mon voyage de Lyon à Bruxelles », « Paris » est l’élément locatif, « Lyon » l’élément ablatif et « Bruxelles » l’élément limitatif.

Le génitif permet de marquer une relation entre deux éléments, l’élément décliné étant l’élément possessif ou bien marqué par l’élément le précédant. Par exemple, dans la phrase « j’ai retrouvé le livre de mon père », « mon père » serait décliné au génitif, tandis que « le livre » serait décliné à l’accusatif.

Enfin, le vocatif permet de s’adresser à quelqu’un ou quelque chose, en attirant son attention. Dans la phrase « Monsieur, pourriez-vous m’aider ? », « Monsieur » serait décliné au vocatif.

Voici la table des suffixes à ajouter selon la déclinaison du mot :
#+CAPTION:Déclinaison des noms par cas grammaticaux
| /               | <            |
| cas grammatical | déclinaison  |
|-----------------+--------------|
| nominatif       | /non marqué/ |
| accusatif       | -ant         |
| datif           | -ith         |
| locatif         | -(o)ch       |
| ablatif         | -(r)ac       |
| limitatif       | -ém          |
| génitif         | -un          |
| vocatif         | -y           |
Les éléments entre parenthèse sont facultatifs selon le contexte précédant la déclinaison ; si une voyelle est entre parenthèse, elle sera omise si la déclinaison est déjà précédée par une voyelle, de même s’il s’agit d’une consonne entre parenthèse dans le cas de la déclinaison précédée par une consonne.

Ainsi, <tere> (« tour ») se déclinera ainsi :
#+CAPTION:Déclinaison de <tere> selon ses cas grammaticaux
| /               | <>          |                       |
| cas grammatical | déclinaison | signification         |
|-----------------+-------------+-----------------------|
| nominatif       | tere        | tour (sujet)          |
| accusatif       | tereant     | tour (objet)          |
| datif           | tereith     | tour (objet indirect) |
| locatif         | terech      | à la tour             |
| ablatif         | tererac     | depuis la tour        |
| limitatif       | tereém      | jusqu’à la tour       |
| génitif         | tereun      | de la tour            |
| vocatif         | terey       | Oh, tour !            |

On peut comparer à <velt> (« monde ») qui se déclinera ainsi :
#+CAPTION:Déclinaison de <velt> selon ses cas grammaticaux
| /               | <>          |                             |
| cas grammatical | déclinaison | signification               |
|-----------------+-------------+-----------------------------|
| nominatif       | velte       | monde (sujet)               |
| accusatif       | veltant     | monde (objet)               |
| datif           | veltith     | monde (objet indirect)      |
| locatif         | veltoch     | dans le monde (à sa surace) |
| ablatif         | veltac      | depuis le monde             |
| limitatif       | veltém      | jusqu’au monde              |
| génitif         | veltun      | du monde                    |
| vocatif         | velty       | Oh Monde !                  |

*** Possessif
En mattér, il est possible d’indiquer la possession d’une personne du mot auquel est ajouté un possessif. Voici la table des suffixes possessifs du Mattér :
#+CAPTION:Suffixes possessifs
| /             | <         | <      | <       |
|               | singulier | paucal | pluriel |
|---------------+-----------+--------+---------|
| 1ère personne | -ych      | -yth   | -yn     |
| 2ème personne | -(d)yn    | -(i)m  | -(e)nu  |
| 3ème personne | -én       | -an    | -eath   |

Ainsi, quand on voudra dire « ma maison », on pourra traduire soit par « chyn hyth », ou bien « hythyn ». La première solution est considérée en Mattér comme étant plus distinguée et faisant partie d’un niveau de language plus respectueux et formel, tandis que la seconde solution est plus souvent utilisée dans des conversations informelles, entre amis, famille ou collègues avec qui le locuteur s’entend bien.

** Déterminants
Le Mattér dispose de quatre catégories de déterminants :
- les articles définis
- les déterminants démonstratifs
- les déterminants interrogatifs
- les déterminants ordinaux

Les articles indéfinis n’existent pas en Mattér, et les déterminants indéfinis sont considérés comme étant des adjectifs et sont utilisés comme tels. Quant aux déterminants cardinaux, il s’agit simplement des nombres tels que décrits dans le chapitre dédié (§[[*Nombres]]).

*** Articles définis
Les articles définis servent à indiquer un élément précis, contrairement à un élément général désigné lors de l’absence d’article défini. Ainsi en Français, on utilise « le », « la » ou « les » comme articles définis. En revanche, le Mattér aura une absence de déterminants là où le Français dispose d’articles indéfinis. Comme on peut le voir ci-dessous, l’article défini s’accorde en genre et en nombre au nom auquel il est attaché.
#+CAPTION:Articles définis du Mattér
| / | <         | <      | <>      |
|   | nombre    | genre  | article |
|---+-----------+--------+---------|
|   | singulier | N,NHUM | a       |
|   | singulier | M      | é       |
|   | singulier | F      | al      |
|   | singulier | NHUM   | en      |
|   | paucal    | N,M,F  | od      |
|   | paucal    | NHUM   | yt      |
|   | pluriel   | N,M,F  | eth     |
|   | pluriel   | NHUM   | ev      |

Ainsi, « la tour » se traduira par <an teren> (au nominatif), « les chats » (peu de chats) se traduira <od cetenet> (genre neutre, paucal), « des villes » (nombreuses) se traduira <el urbyneth>.

*** Déterminants démonstratifs
Le déterminant démonstratif du Mattér a une fonction très similaire au déterminant démonstratif du Français, tels que « ce », « cet », « cette » et « ces ». De même que pour les articles définis, ils s’accordent en nombre, mais également selon la distance, allant de visible proche à invisible en passant par visible éloigné.
#+CAPTION:Déterminants démonstratifs du Mattér
| / | <        | <         | <>      |
|   | distance | nombre    | article |
|---+----------+-----------+---------|
|   | proche   | singulier | an      |
|   | proche   | paucal    | at      |
|   | proche   | pluriel   | adh     |
|   | éloigné  | singulier | em      |
|   | éloigné  | paucal    | ed      |
|   | éloigné  | pluriel   | edh     |
|   | lointain | singulier | un      |
|   | lointain | paucal    | ut      |
|   | lointain | pluriel   | udh     |

*** Déterminants interrogatifs

*** Déterminants ordinaux
Comme décrit dans le chapitre §[[*D%C3%A9terminants]], le Mattér ne dispose pas de déterminants cardinaux, ou plutôt il s’agit simplement du nombre approprié placé à l’emplacement du déterminant tel que défini plus tard dans le chapitre sur la syntaxe approprié (§[[*Syntaxe]]). Dans le cas des nombres cardinaux, il s’agit d’ajouter en suffixe au numéro le terme <norm> auquel un article défini accordé en genre et en nombre est également suffixé. Ainsi, pour le terme « premier » au singulier masculin, nous obtiendrons

** Adjectifs
Les adjectifs en Mattér s’accordent au nom ou à l’élément principal de la phrase nominale qu’ils définissent, que ce soit en nombre ou en déclinaison. Ils adopteront alors la même déclinaison avec la même terminaison que l’élément qu’ils décrivent. Voici un tableau d’exemple d’accord de <raedh> (« rouge ») avec <wachen> (« voiture »).

Singulier :
#+CAPTION:Exemple de déclinaison d’adjectif au singulier
| /         | <                    |
| nominatif | a raedh wachen       |
| accusatif | a raedhant wachenant |
| datif     | a raedhith wachenith |
| locatif   | a raedhoch wachenoch |
| ablatif   | a raedhac wachenac   |
| limitatif | a raedhém wacheném   |
| génitif   | a raedhun wachenun   |
| vocatif   | a raedhy wacheny     |

Paucal :
#+CAPTION:Exemple de déclinaison d’adjectif au paucal
| /         | <                         |
| nominatif | en raedhet wachenet       |
| accusatif | en raedhantet wachenantet |
| datif     | en raedhithet wachenithet |
| locatif   | en raedhochet wachenochet |
| ablatif   | en raedhacet wachenacet   |
| limitatif | en raedhémet wachenémet   |
| génitif   | en raedhunet wachenunet   |
| vocatif   | en raedhyet wachenuet     |

Pluriel :
#+CAPTION:Exemple de déclinaison d’adjectif au pluriel
| /         | <                           |
| nominatif | yt raedheth wacheneth       |
| accusatif | yt raedhanteth wachenanteth |
| datif     | yt raedhitheth wachenitheth |
| locatif   | yt raedhocheth wachenocheth |
| ablatif   | yt raedhaceth wachenaceth   |
| limitatif | yt raedhémeth wachenémeth   |
| génitif   | yt raedhuneth wachenuneth   |
| vocatif   | yt raedhyeth wachenyeth     |

Il existe une catégorie d’adjectifs qui ne seront cependant pas accordés en nombre et en déclinaison avec leur élément décrit : les adjectifs quantitatifs. Ainsi, des adjectifs tels que <vend> (« peu, un peu ») ne changeront jamais, peu importe la déclinaison du mot qu’ils déterminent.

La raison pour laquelle l’adjectif doit également être décliné est la liberté de l’ordre des mots qu’autorise le Mattér, ce qui fait qu’on peut se retrouver dans des situations où on ne peut savoir à quel élément de la phrase un adjectif se réfère. Par exemple « Un ours impressionnant est en train de manger un gros poisson » peut se dire « Bern mekkil thtorant ficjanant gjea thpichand ». On sait que l’adjectif <mekkil> se réfère à <bern> car il n’est pas décliné à l’accusatif, tout comme <thtor> qui se réfère à <ficjan> car les deux sont déclinés à l’accusatif. Or dans cette phrase, il est tout à fait possible que les deux adjectifs puissent se référer à l’ours ou au poisson si les adjectifs n’étaient pas déclinés, les deux phrases « Bern mekkilant thtorant ficjanant gjea thpichand » (« Un ours en train de manger un gros et impressionnant poisson ») et « Bern mekkil thtor ficjanant gjea thpichand » (« Le gros et impressionnant ours est en train de manger un poisson ») sont valides. Pour connaître le sens impliqué par la position de l’adjectif après le nom, voir la section dédiée (§[[*Groupe nominal]]).

** Pronoms
Le Mattér dispose d’un ensemble de cinq pronoms, tous correspondant à l’un des cas grammaticaux décrits plus haut (§[[*D%C3%A9clinaisons]]). On peut remarquer que le Mattér ne fait pas de distinction de genre pour la première et la seconde personne ; en revanche chaque genre l’est avec la troisième personne. La première personne est également la seule personne à ne pas avoir de vocatif. Voici le tableau des correspondances :

- Première personne :
#+CAPTION:Pronoms de la première personne
| /         | <>        | >         | >      |         |
|           | nominatif | accusatif | datif  | génitif |
|-----------+-----------+-----------+--------+---------|
| singulier | cheg      | chent     | cheidh | chyn    |
| paucal    | thi       | thid      | thidh  | thyn    |
| pluriel   | non       | nound     | nonth  | nun     |

- Seconde personne :
#+CAPTION:Pronoms de la seconde personne
| /         | <>        | >         | >     | >       |         |
|           | nominatif | accusatif | datif | génitif | vocatif |
|-----------+-----------+-----------+-------+---------+---------|
| singulier | du        | daun      | dudh  | dyn     | udy     |
| paucal    | im        | eint      | dhi   | nim     | eny     |
| pluriel   | min       | meint     | minth | meun    | miny    |

- Troisième personne :
#+CAPTION:Pronoms de la troisième personne
| /             | <>        | >         | >      | >       |         |
|               | nominatif | accusatif | datif  | génitif | vocatif |
|---------------+-----------+-----------+--------+---------+---------|
| sg neutre     | hé        | hét       | heth   | hén     | yhé     |
| sg masculin   | hae       | haed      | haedh  | haen    | yhae    |
| sg féminin    | hou       | hound     | hudh   | houn    | yhou    |
| sg non-humain | hit       | hint      | hith   | him     | yhi     |
| pau neutre    | hei       | heit      | heith  | hein    | yhei    |
| pau masculin  | tha       | thad      | thaidh | than    | ytha    |
| pau féminin   | thu       | thunt     | thou   | thun    | ythu    |
| pau neutre    | hou       | hot       | hoth   | dho     | ydhou   |
| pl neutre     | hea       | hint      | heath  | heam    | heathy  |
| pl masculin   | tha       | that      | thaidh | than    | thaidhy |
| pl féminin    | thu       | thunt     | thou   | thun    | ythu    |
| pl non-humain | hou       | hout      | houth  | dho     | houthy  |

** Verbes

*** Temps
À l’exception des verbes <o ber> (être), <o hab> (avoir) et <o gjer> (faire), la conjugaison des verbes en Mattér est très régulière. Trois temps principaux existent : le passé, le présent et le futur, cepedant il est possible d’exprimer du passé antérieur (passé dans un temps de locution passé), du passé postérieur (futur dans un temps de locution passé), du futur antérieur (passé dans un temps de locution futur) et du futur postérieur (futur dans un temps de locution futur).

Généralement parlant, le présent sert aux locuteurs du Mattér à se référer à des actions ou descriptions ou autre se passant lors de la locution de la phrase ou à se réferer à un passé ou futur immédiat, pouvant s’étendre jusqu’à une journée complète avant ou après le temps immédiat de locution. Par exemple, la phrase <mergoch, cinnemoch thi gache> (« demain, nous (paucal) allons au cinéma ») contient le verbe <o gach> conjugué à la première personne du paucal, cependant le sens porté par la phrase est comme quoi l’action d’aller au cinéma prendra lieu dans le futur, en l’occurence le jour suivant le moment de locution. Cepedant la proximité entre ce dernier et le moment de l’action en elle-même permet au locuteur d’utiliser le présent. En revanche, s’il souhaite exprimer la même action comme s’effectuant la semaine suivante, le futur sera utilisé : <nutht vococh, cinnemoch thi y gachatth>. Remarquez par ailleurs l’utilisation du locatif pour <morg> (« demain ») et <nutht voc> (« semaine prochaine ») pour signifier le temps durant lequel l’action s’exécutera.

*** Aspects
Les aspects servent à indiquer la relation du verbe au temps qu’il emploie. Les deux aspects principaux sont les aspects *perfectif* et *imperfectif*. Le premier sert à indiquer l’action du verbe comme étant un événement terminé et révolu, considérant ce dernier comme un objet unique et insécable ; à l’inverse, l’imperfectif permet de mettre en place une durée à l’action décrite, de la placer en élément de fond ou de décors, et permet d’y insérer de nouveau éléments. Comparez en Français « Henry IV régnais 21 ans » (imperfectif) et « Henry IV régna 21 ans ». De par sa nature, le présent ne dispose pas d’aspect perfectif, ainsi seuls le passé et le futur montreront ces deux aspects. Voici ainsi le tableau de conjugaison des verbes réguliers aux aspects perfectif puis imperfectif de l’indicatif (un mode, nous en parlerons plus en détail dans le chapitre §[[*Modes]]), le ~V~ représentant la racine du verbe :
#+caption: Conjugaison du perfectif de l’indicatif
| /    | <>    |       |
|      | passé | futur |
|------+-------+-------|
| 1S   | Vo    | y Vo  |
| 2S   | Vou   | y Vou |
| 3S   | Vo    | y Vou |
| 1PAU | Vur   | y Vur |
| 2PAU | Vun   | y Vur |
| 3PAU | Vur   | y Vur |
| 1P   | Vu    | y Vo  |
| 2P   | Vu    | y Vo  |
| 3P   | Von   | y Von |

#+caption: Conjugaison de l’imperfectif de l’indicatif
| /    | <>    | >       |         |
|      | passé | présent | futur   |
|------+-------+---------+---------|
| 1S   | Ver   | Ve      | y V     |
| 2S   | Vet   | Vei     | y Vei   |
| 3S   | Ver   | Vea     | y Ve    |
| 1PAU | Vedh  | Vet     | y Va    |
| 2PAU | Veth  | Vaet    | y Vath  |
| 3PAU | Verdh | Vaet    | y Va    |
| 1P   | Ven   | Vern    | y Vatth |
| 2P   | Vent  | Var     | y Vat   |
| 3P   | Ven   | Vér     | y Vat   |

Les conjugaisons de l’imperfectif et du perfectif aux temps antérieurs ou postérieurs du passé et du futur s’effectuent en utilisant soit le participe passé ou futur du verbe et en utilisant le verbe modal <o ber> pour les verbes d’états et <o gjer> pour les verbes d’action qui sera conjugué au passé ou au futur selon s’il s’agit respectivement d’un temps antérieur ou postérieur.

En revanche, les trois temps disposent d’un aspect commun : *le progressif* qui s’emploie grâce à l’utilisation des verbes <o ber> (verbes d’état) ou <o gjer> (verbes d’action) comme auxilliaires conjugué selon le temps et l’aspect imperfectif voulu, tandis que le verbe principal est sous sa forme de participe progressif (voir les participes §[[*Participes]]). Exemple :{{{newline}}}
Français : J’étais en train de manger une pomme rouge.{{{newline}}}
Mattér : cheg e gjéth thpichand raedhant eppelant

Français : Vous êtes tous deux en train de pêcher.{{{newline}}}
Mattér : im gjéta ficjanand{{{newline}}}

Français : Elles seront en train d’écrire des lettres.
Mattér : thu y gjér gérenand breifantath

*** Modes
**** Infinitif
C’est dans ce mode que vous verrez les verbes dans le dictionnaire. Il s’agit de la base de chaque verbe, précédé par un <o> marquant l’infinitif. Dans cette forme, le verbe peut être manipulé dans la phrase comme un nom commun, mais il peut également être utilisé afin de donner des instructions de façon polie, comme par exemple dans un manuel ou dans une recette, comme cela peut être le cas en Français.

**** Impératif
En Mattér, l’impératif est un moyen pour le locuteur de donner un ordre à son interlocuteur, mais également à un tiers, comme on pourrait le comprendre en Français dans la phrase « Qu’il le fasse ! ». Il ne s’applique donc qu’au présent, ainsi qu’à la deuxième et troisième personne (singulier, paucal et pluriel). Voici la conjugaison des verbes à l’impératif :

#+CAPTION:Conjugaison des verbes régulier à l’impératif
| /         | <                 | <                  |
| nombre    | deuxième personne | troisième personne |
|-----------+-------------------+--------------------|
| singulier | V(a)ge            | V(e)get            |
| paucal    | V(a)gér           | V(e)gent           |
| pluriel   | V(e)gi            | V(e)geat           |

Pour rappel, les voyelles entre parenthèses ne sont à rajouter que dans le cas où l’apposition de la terminaison créé une suite de consonne interdite par les règles de phonotaxes (voir §[[*Phonotaxes]]). Voici par exemple la conjugaison respectivement de <o seg> « dire » et <o thpich> « manger » à l’impératif :

#+CAPTION:Conjugaison de <o seg> à l’impératif
| /         | <                 | <                  |
| nombre    | deuxième personne | troisième personne |
|-----------+-------------------+--------------------|
| singulier | segge             | segget             |
| paucal    | seggér            | seggent            |
| pluriel   | seggi             | seggeat            |

#+CAPTION:Conjugaison de <o thpich> à l’impératif
| /         | <                 | <                  |
| nombre    | deuxième personne | troisième personne |
|-----------+-------------------+--------------------|
| singulier | thpichege         | thpicheget         |
| paucal    | thpichegér        | thpichegent        |
| pluriel   | thpichegi         | thpichegeat        |

Comme à leur habitude, les trois verbes <o ber>, <o hab> et <o gjer> ont leur propre forme que vous retrouverez dans leurs chapitres respectifs (§[[*Verbe %C3%AAtre <o ber>]], §[[*Verbe avoir <o hab>]] et §[[*Verbe faire <o gjer>]]).

Il est également possible pour le locuteur d’accentuer l’ordre en mettant le verbe au participe présent et en le précédant par le verbe <o gjer> conjugué à l’impératif. Exemple avec <o ficjan> :
#+CAPTION:Conjugaison à l’impératif fort de <o ficjan>
| /         | <                 | <                  |
| nombre    | deuxième personne | troisième personne |
|-----------+-------------------+--------------------|
| singulier | jeg ficjanta      | gjet ficjanta      |
| paucal    | jége ficjanta     | gjégent ficjanta   |
| pluriel   | jegi ficjanta     | gjeag ficjanta     |

**** Participes
#+CAPTION:Participes réguliers
| /                    | <       |
| type de participe    | forme   |
|----------------------+---------|
| participe passé      | V(dh)et |
| participe présent    | V(o)ta  |
| participe futur      | V(é)tér |
| participe progressif | Vand    |

Participes irréguliers :

*** Verbe être <o ber>
**** Perfectif
#+CAPTION:Perfectif de <o ber>
| /    | <>    |         |
|      | passé | futur   |
|------+-------+---------|
| 1S   | ver   | y ver   |
| 2S   | vet   | y vet   |
| 3S   | vath  | y vath  |
| 1PAU | vedh  | y vedh  |
| 2PAU | venth | y venth |
| 3PAU | vatth | y vatth |
| 1P   | vein  | y vein  |
| 2P   | veat  | y veat  |
| 3P   | veaen | y veaen |

**** Imperfectif
#+CAPTION:Imperfectif de <o ber>
| /    | <>        | >       |           |
|      | passé     | présent | futur     |
|------+-----------+---------+-----------|
| 1S   | e vath    | be      | u be      |
| 2S   | ea vart   | betht   | u betht   |
| 3S   | ei vart   | beith   | ou beidh  |
| 1PAU | e vatht   | erth    | u erdh    |
| 2PAU | ea vart   | erth    | o erdh    |
| 3PAU | ei varth  | aith    | ou aidh   |
| 1P   | e vaeth   | ther    | u ther    |
| 2P   | ea vaerth | therth  | u therdh  |
| 3P   | ei varth  | thet    | ou thetth |

**** Participe
#+CAPTION:Participes de <o ber>
| /                 | <     |
| type de participe | forme |
|-------------------+-------|
| participe passé   | bet   |
| participe présent | bote  |
| participe futur   | bétér |

*** Verbe avoir <o hab>
**** Perfectif
#+CAPTION:Perfectif de <o hab>
| /    | <>    |         |
|      | passé | futur   |
|------+-------+---------|
| 1S   | her   | hery    |
| 2S   | het   | hety    |
| 3S   | heath | y heath |
| 1PAU | hedh  | hedhy   |
| 2PAU | hedht | hety    |
| 3PAU | hetth | hety    |
| 1P   | hein  | y hein  |
| 2P   | heit  | heity   |
| 3P   | haent | y haent |

**** Imperfectif
#+CAPTION:Imperfectif de <o hab>
| /    | <>       | >       |           |
|      | passé    | présent | futur     |
|------+----------+---------+-----------|
| 1S   | e hath   | habe    | u habe    |
| 2S   | ae hat   | hatht   | u habetht |
| 3S   | ea hath  | hat     | ou hat    |
| 1PAU | e hatth  | habeth  | u habeth  |
| 2PAU | e hart   | hatth   | o hatth   |
| 3PAU | ea harth | habean  | ou haben  |
| 1P   | ae hat   | haber   | u harbe   |
| 2P   | ae haeth | haberth | y hardh   |
| 3P   | ei harth | habet   | u hebet   |

**** Participe
#+CAPTION:Participes de <o hab>
| /                 | <     |
| type de participe | forme |
|-------------------+-------|
| participe passé   | haet  |
| participe présent | hat   |
| participe futur   | hater |

*** Verbe faire <o gjer>
**** Perfectif
#+CAPTION:Perfectif de <o gjer>
| /    | <>      |          |
|      | passé   | futur    |
|------+---------+----------|
| 1S   | jer     | y jer    |
| 2S   | jeret   | y jeret  |
| 3S   | gjeth   | y jeth   |
| 1PAU | jardh   | y jarth  |
| 2PAU | jenth   | y jent   |
| 3PAU | gjetth  | y jetth  |
| 1P   | jerein  | y jerein |
| 2P   | gjereat | y jereat |
| 3P   | gjeraen | y jerean |

**** Imperfectif
#+CAPTION:Imperfectif de <o gjer>
| /    | <>        | >       |         |
|      | passé     | présent | futur   |
|------+-----------+---------+---------|
| 1S   | e jéth    | jere    | u jere  |
| 2S   | ae jét    | jei     | y jeit  |
| 3S   | ei gjéth  | gjea    | y jeath |
| 1PAU | e jétth   | jét     | u jét   |
| 2PAU | e jért    | gjéta   | y jérta |
| 3PAU | ea gjétth | jaet    | y jaeth |
| 1P   | ei jeath  | jern    | y jeath |
| 2P   | e gjeath  | gjerar  | y jerar |
| 3P   | e gjérth  | gjér    | y jér   |

**** Participe
#+CAPTION:Participes de <o gjer>
| /                 | <      |
| type de participe | forme  |
|-------------------+--------|
| participe passé   | get    |
| participe présent | gethte |
| participe futur   | gér    |
**** Impératif
| /         | <                 | <                  |
| nombre    | deuxième personne | troisième personne |
|-----------+-------------------+--------------------|
| singulier | jeg               | gjet               |
| paucal    | jége              | gjégent            |
| pluriel   | jegi              | gjeag              |

** Adverbes

** Prépositions

src_latex{\newpage}
* Syntaxe
** Groupe nominal
Le groupe nominal est l’ensemble des mots d’une phrase en Mattér déterminant un nom propre ou nom commun. L’ordre typique d’un groupe verbal est <déterminant>-<adjectifs>-<nom>-<proposition>, cependant seul le nom est obligatoire. Il est possible de placer un ou plusieurs adjectifs entre le nom et la proposition pour accentuer une note subjective de la part du locuteur, une opinion. Ainsi, « smodh eppel » est une pomme dont on on peut supposer qu’elle soit objectivement petite, alors que « eppel smodh » insinue que selon l’avis du locuteur la pomme est petite. Exemple :

Mattér : Hit galmant wachenant beith.{{{newline}}}
Français : C’est une vieille voiture.

Mattér : Hit wachenant galmant beith.{{{newline}}}
Français : C’est une voiture à mon avis vieille.

** Groupe verbal
** Propositions simples
L’ordre préféré en Mattér est <sujet>-<objet>-<oblique>-<verbe>, mais du fait de la déclinaison des éléments objets et obliques, il est possible de changer l’ordre de la proposition avant le verbe, qui restera en toutes circonstance en fin de proposition. Ces changements d’ordre peuvent permettre une mise en avant de certains éléments de la phrase par rapport à d’autres. Exemples :

Mattér : Fadhérych breifant cheidh gjea gérenand.{{{newline}}}
Français : Mon père est en train de m’écrire une lettre.

Mattér : Breifant fadhérych cheidh gjea gérenand.{{{newline}}}
Français : C’est une lettre que mon père est en train de m’écrire.

Mattér : Cheidh fadhérych breifant gjea gérenand.{{{newline}}}
Français : C’est à moi que mon père est en train d’écrire une lettre.

** Négations
** Questions
** Conjonctions et Coordination de propositions
src_latex{\newpage}
* Morphosyntaxe
** Citation
src_latex{\newpage}
* Sémantiques

src_latex{\newpage}
* Pragmatique

src_latex{\newpage}
* Phraséologie

src_latex{\newpage}
* Synchronie et diachronie

src_latex{\newpage}
* Nombres
Le Mattér est une langue comptant en base dix et prenant en compte l’existance du zéro. Cependant, contrairement au Français, le Mattér tend à grouper les dizaines de milliers ensemble plutôt que les milliers. Ainsi, nous avons les termes suivants :
#+CAPTION:Nombres en Mattér
|                 / |                < | <       |
| notation standard |  notation Mattér | terme   |
|-------------------+------------------+---------|
|                 0 |                0 | nyn     |
|                 1 |                1 | aen     |
|                 2 |                2 | twéa    |
|                 3 |                3 | dhe     |
|                 4 |                4 | fro     |
|                 5 |                5 | dheif   |
|                 6 |                6 | chcaec  |
|                 7 |                7 | thean   |
|                 8 |                8 | acht    |
|                 9 |                9 | onnén   |
|                10 |               10 | dran    |
|                20 |               20 | tjeg    |
|                30 |               30 | dhjea   |
|                40 |               40 | frje    |
|                50 |               50 | dheig   |
|                60 |               60 | chcjag  |
|                70 |               70 | thjeg   |
|                80 |               80 | achteig |
|                90 |               90 | onneg   |
|               100 |              100 | anrad   |
|             1 000 |             1000 | tanthen |
|            10 000 |           1 0000 | deten   |
|       100 000 000 |      1 0000 0000 | mollen  |
| 1 000 000 000 000 | 1 0000 0000 0000 | vreljen |

Le Mattér énonce les éléments d’un nombre du plus petit au plus grand, et les termes <anrad>, <tathen>, <deten>, <mollen> et <vreljen> peuvent être multipliés par un nombre inférieur le précédant. Par exemple, pour exprimer « 600 », on dira <chaecanred>. Indiquer un multiplicateur de un est considéré comme inutile, ainsi les termes tels que <deten>, <mollen> et <vreljen> se suffisent à eux-même pour signifier <1 0000>, <1 0000 0000> et <1 0000 0000 0000> respectivement. Par conséquence, le nombre 1789 se traduirait par <onnén achteig theananrad tanthen>.

Les termes <anrad>, <tathen>, <deten>, <mollen> et <vreljen> doivent également être précédés par <ar> lors d’un risque de confusion entre un nombre et leur multiplieur, de 1 à 10 pour <anrad et tanthen>, et de 1 à 999 pour <deten>, <mollen> et <vreljen>. Ainsi, <achtanred> signifie 800, alors que <acht ar anred> signifie 108, <onnénanrad deten> signifie 900 0000 (ou 9 000 000) alors que <onnénanrad ar deten> signifie 1 0900 (ou 10 900). Si aucune confusion n’est possible, le <ar> sera ommis. 1 2345 6890 (123 456 890) s’exprime donc <dran achteig theananred chceactanthan ar dheif frje dheanrad twéatanthen deten ar mollen>.

Typographiquement parlant, les multiplicateurs s’agglomèrent avec l’élément qu’ils multiplient.

src_latex{\newpage}
* Système d’écriture
Le système natif d’écriture Mattér est l’alphabet runique anglo-saxon. Voici la correspondance entre chacun des phonèmes du Mattér et des runes utilisées nativement dans leur ordre alphabétique natif :
#+CAPTION:Runes du Mattér
| /                     | <                                      |
| phonème (transcrit)   | rune                                   |
|-----------------------+----------------------------------------|
| f                     | {{{if-latex-else(\\textara{f},ᚠ)}}}    |
| u                     | {{{if-latex-else(\\textara{u},ᚢ)}}}    |
| th                    | {{{if-latex-else(\\textara{þ},ᚦ)}}}    |
| o                     | {{{if-latex-else(\\textara{o},ᚩ)}}}    |
| r                     | {{{if-latex-else(\\textara{r},ᚱ)}}}    |
| c                     | {{{if-latex-else(\\textara{c},ᚳ)}}}    |
| g                     | {{{if-latex-else(\\textara{g},ᚷ)}}}    |
| w                     | {{{if-latex-else(\\textara{w},ᚹ)}}}    |
| h                     | {{{if-latex-else(\\textara{h},ᚻ)}}}    |
| ch                    | {{{if-latex-else(\\textara{I},ᛇ)}}}    |
| n                     | {{{if-latex-else(\\textara{n},ᚾ)}}}    |
| i                     | {{{if-latex-else(\\textara{i},ᛁ)}}}    |
| j                     | {{{if-latex-else(\\textara{j},ᛄ)}}}    |
| p                     | {{{if-latex-else(\\textara{p},ᛈ)}}}    |
| dh                    | {{{if-latex-else(\\textara{s},ᛋ)}}}    |
| v                     | {{{if-latex-else(\\textara{\\ng},ᛝ)}}} |
| t                     | {{{if-latex-else(\\textara{t},ᛏ)}}}    |
| b                     | {{{if-latex-else(\\textara{b},ᛒ)}}}    |
| e                     | {{{if-latex-else(\\textara{e},ᛖ)}}}    |
| m                     | {{{if-latex-else(\\textara{m},ᛗ)}}}    |
| l                     | {{{if-latex-else(\\textara{l},ᛚ)}}}    |
| d                     | {{{if-latex-else(\\textara{d},ᛞ)}}}    |
| é                     | {{{if-latex-else(\\textara{\\oe},ᛟ)}}} |
| a                     | {{{if-latex-else(\\textara{a},ᚪ)}}}    |
| y                     | {{{if-latex-else(\\textara{y},ᚣ)}}}    |
| ae                    | {{{if-latex-else(\\textara{æ},ᚫ)}}}    |
| ea                    | {{{if-latex-else(\\textara{\\ea},ᛠ)}}} |
| séparateur de mots    | {{{if-latex-else(\\textara{.},᛫)}}}    |
| marquer de pauses     | {{{if-latex-else(\\textara{:},᛬)}}}    |
| séparateur de phrases | {{{if-latex-else(\\textara{*},᛭)}}}    |

Exceptionnellement, et contrairement aux autres, les diphtongues <ae> et <ea> disposent de leur propre morphème. Cet alphabet est généralement utilisé lors d’écritures horizontales de droite à gauche et de haut en bas, mais il arrive occasionnellement que ces runes soient écrites verticalement lors de gravures, de haut en bas et de droite à gauche.

Voici un texte d’exemple transcrit en alphabet latin ainsi qu’écrit en runes :{{{newline}}}
Français : Demain, du lever au coucher du soleil, nous irons pêcher.{{{newline}}}
Mattér (transcrit) : morgoch, gyrnegac thcyrmém, thi y ficjanur.{{{newline}}}
Mattér (runes) : {{{if-latex-else(\\textara{morgoI:gyrnegac.þcyrm\\oe m:þi.y.ficjanur*},ᛗᚩᚱᚷᚩᛇ᛬ᚷᚣᚱᚾᛖᚷᚪᚳ᛫ᚦᚳᚣᚱᛗᛟᛗ᛬ᚦᛁ᛫ᚣ᛫ᚠᛁᚳᛡᚪᚾᚢᚱ᛭)}}}

Le Mattér peut également être écrit avec les caractères romains comme fait dans quasiment tout ce document, cependant il est possible également d’utiliser quelques caractères alternatifs :
#+CAPTION:Caractères latins du Mattér
| /                      | <                    |
| caractère translittéré | caractère alternatif |
|------------------------+----------------------|
| th                     | Þ - þ                |
| dh                     | Ð - ð                |
| ch                     | Ȝ - ȝ                |
| w                      | Ƿ - ƿ                |
| j                      | I - i                |
| ae                     | Æ - æ                |
# C-x 8 RET 21C ou 21D pour Ȝ et ȝ, 1bf ou 1f7 pour ƿ - Ƿ

Ainsi, des mots tels que <brydh> ou <thpich> peuvent s’écrire <bryð> et <þpiȝ> respectivement.
Ainsi, trois façons d’écrire le Mattér sont possible : l’alphabet runique, natif à la langue, l’alphabet latin adapté au Mattér, apparu plus récemment dans le Mattér et utilisé principalement lors des échanges commerciaux avec des cultures utilisant cet alphabet, et enfin la translittération qui n’est utilisée que dans ce document afin de retranscrire aisément le Mattér sans avoir recours à des caractères spéciaux. Quelques exemples de ces différents systèmes d’écriture :
#+CAPTION:Exemples d’écritures native du Mattér
| /                | <     | <                                           |
| translittération | latin | runique                                     |
|------------------+-------+---------------------------------------------|
| brydh            | bryð  | {{{if-latex-else(\\textara{brys},ᛒᚱᚣᛋ)}}}   |
| thpich           | þpiȝ  | {{{if-latex-else(\\textara{þpiI},ᚦᛈᛁᛇ)}}}   |
| jea              | iea   | {{{if-latex-else(\\textara{j\\ea},ᛄᛠ)}}}    |
| maend            | mænd  | {{{if-latex-else(\\textara{mænd},ᛗᚫᚾᛞ)}}}   |
| nethty           | neþty | {{{if-latex-else(\\textara{neþty},ᚾᛖᚦᛏᚣ)}}} |
| wachen           | ƿaȝen | {{{if-latex-else(\\textara{waIen},ᚹᚪᛇᛖᚾ)}}} |

src_latex{\newpage}
* Glossaire

- mot en Mattér :: ​/phonétique/ (élément de langage) Définition(s)

Abréviations :
- adj : adjectif
- adv : adverbe
- ind : indénombrable
- n : nom
- pau : paucal
- pl : pluriel
- pron : pronom
- sg : singulier
- v : verbe

** Actions physiques

** Amour

** Animaux
- bern :: ​/bɛrn/ (n) ours
- ficjan :: ​/ˈfikjan/ (n) poisson
- o ficjan :: ​/o ˈfikjan/ (v) pêcher

** Art
*** Écriture
- breif :: ​/brɛɪf/ (n) lettre, missive
- géren :: ​/ˈɡerɛn/ (v) écrire, tracer des runes ou lettres latines sur une surface plane (parchemin, papier,…)
- rittan :: ​/ˈritːa/ (v) écrire, graver des runes
- ryn :: ​/ryn/ (n) rune, lettre alphabétique

** Astronomie

** Bâtiments
*** La ville
- urby :: ​/ˈurby/ (n) ville
*** Les types de bâtiments
- tere :: ​/ˈtɛrɛ/ (n) tour, haut monument
- hyth :: ​/hyθ/ (n) maison (bâtiment)

** Commerce

** Conflits

** Conteneurs

** Corps

** Couleurs
- raedh :: ​/raeð/ (adj) rouge
** Dimensions
*** Taille
- smodh :: ​/smoð/ (adj) petit
- thtor :: ​/θtor/ (adj) gros, grand, de grande taille, large
- mekkil :: ​/mekːil/ (adj) grand, imposant, puissant, fort

*** Quantifieurs
- maend :: ​/maend/ (adj) beaucoup
- vend :: ​/vend/ (adj) peu, un peu

** Direction

** Eau

** Effort

** Éléments

** Émotions
- lycce :: ​/ˈlykːɛ/ (adj) joyeux, content

** Évaluation

** Événements

** Existence

** Famille
- fadhér :: ​/ˈfaðer/ (n) père
- madhér :: ​/ˈmaðer/ (n) mère
** Forme

** Gouvernement

** Grammaire
*** Conjonctions
- ar :: ​/ar/ (conj) et
- aen :: ​/aen/ (conj) et, mais
- og :: ​/oɡ/ (conj) et, cependant, toujours est-il que
- men :: ​/mɛn/ (conj) mais
- dhea :: ​/ðea/ (conj) mais, introduit une question
- némmé :: ​/nemːe/ (conj) excepté, à moins que

*** Prépositions
- tél :: ​/tel/ (prep) pour, afin
- thiv :: ​/θiv/ (prep) pour la raison de, du fait de.

** Guerre

** Légal

** Lieux

** Lumière

** Mental

** Mesures

** Métaux

** Mouvements

** Nature
- velt :: ​/vɛlt/ (n) monde, la Terre

** Nombres
- norm :: ​/norm/ (n) nombre, numéro (ordinal)
- al :: ​/al/ (adj) tout, tous
*** Nombres cardinaux
Comme présenté dans le chapitre sur les nombres (§[[*Nombres]]), voici ci-dessous les nombres cardinaux du Mattér. Leur utilisation est détaillée dans le chapitre mentionné ci-dessus.
| /                 | <       |
|            nombre | terme   |
|-------------------+---------|
|                 0 | nyn     |
|                 1 | aen     |
|                 2 | twéa    |
|                 3 | dhe     |
|                 4 | fro     |
|                 5 | dheif   |
|                 6 | chcaec  |
|                 7 | thean   |
|                 8 | acht    |
|                 9 | onnén   |
|                10 | dran    |
|                20 | tjeg    |
|                30 | dhjea   |
|                40 | frje    |
|                50 | dheig   |
|                60 | chcjag  |
|                70 | thjeg   |
|                80 | achteig |
|                90 | onneg   |
|               100 | anrad   |
|              1000 | tanthen |
|            1 0000 | deten   |
|       1 0000 0000 | mollen  |
|  1 0000 0000 0000 | vreljen |

** Nourriture
- o thpich :: ​/o θpiç/ (v) manger

** Outils
- wachen :: ​/ˈwaçɛn/ (n) voiture

** Parole
- o seg :: ​/o sɛɡ/ (v) dire

** Péchés

** Physique

** Possession

** Religion

** Savoir
- o cyn :: ​/o kyn/ (v) savoir
- o sjea :: ​/o sjea/ (v) connaître, savoir superficiellement
- o vitté :: ​/o ˈvitːe/ (v) savoir, connaître, être conscient de
En Mattér, une différentiation est faite entre le fait de savoir ou connaître quelque chose superficiellement <o sjea>, avoir une connaissance plus approfondie du sujet <o cyn> ou bien avoir une véritable maîtrise de la connaissance sur le sujet <o vitté>. Par exemple, une personne connaissant de nom une langue dira <cheg an tyngant sjeae> (« j’ai connaissance de cette langue », sous-entendu qu’il sait de quoi il s’agit mais sans plus), une personne apprenant mais ne maîtrisant pas la langue dira <cheg an tyngant cyne> (« je connais cette langue », sous-entendu suffisamment pour pouvoir un peu s’exprimer avec sans pour autant la maîtriser), et une personne parlant couramment cette langue dira <cheg an tyngant vittée> (« je connais bien cette langue », impliquant une connaissance profonde du sujet).

** Sensations

** Sexe

** Société
*** Relations sociales
- je :: ​/jɛ/ (adv, inform.) ouais
- jea :: ​/jea/ (adv) oui
- ne :: ​/nɛ/ (adv, inform.) nan
- nea :: ​/nea/ (adv) non

** Substances

** Temps
- daeg :: ​/daeɡ/ (n) jour
- gaern :: ​/ɡaern/ (n) année
- galm :: ​/ɡalm/ (adj) vieux, ancien
- gyrneg :: ​/ˈɡyrnɛɡ/ (n) moment du lever de soleil, matin
- menyth :: ​/ˈmɛnyθ/ (n) mois
- morg :: ​/morɡ/ (adv) demain
- nethty :: ​/ˈnɛθty/ (adj) prochain, suivant
- tebyr :: ​/'tɛbyr/ (v) passer (du temps)
- thcyrm :: ​/θkyrm/ (n) crépuscule, moment du coucher de soleil
- voc :: ​/vok/ (n) semaine

** Travail

** Végétaux
*** Fruits
- eppel :: ​/ˈɛpːɛl/ (n) pomme

** Vêtements

** Vie et santé
- brydh :: ​/bryð/ (n) naissance
- brydhdeg :: ​/ˈbryðdɛɡ/ (n) jour de naissance, anniversaire (/brydh/ + /deg/)

** À trier

src_latex{\newpage}
* Annexes

#  LocalWords:  Pappa langue-jouet
