#+INCLUDE: "../headers.org"
#+LaTeX_HEADER: \usepackage{indentfirst}
#+LATEX_CLASS: article
#+TITLE: Une Grammaire du Mattér
#+HTML_HEAD: <meta name="description" content="Grammaire détaillée de la langue construite du Mattér" />
#+HTML_HEAD: <meta property="og:title" content="Grammaire du Mattér" />
#+HTML_HEAD: <meta property="og:description" content="Grammaire détaillée de la langue construite du Mattér" />

* Avant-propos
La redistribution ou vente de ce document sont strictement interdits. Ce document est protégé par la loi française sur le droit d’auteur et appartient entièrement et totalement à son auteur. Ce document est un document disponible gratuitement au format web à l’adresse [[https://langue.phundrak.fr/matter/]] et au format PDF à l’adresse [[https://langue.phundrak.fr/matter/matter.pdf]]. Si vous l’avez obtenu depuis une autre source, gratuitement ou non, merci de m’en faire part en me contactant via mes réseaux sociaux ou par mail que vous trouverez sur mon site principal, [[https://phundrak.fr]]. Aucune personne, morale ou physique, n’est à l’heure actuelle autorisée à redistribuer ces documents. Si vous êtes intéressés par une redistribution de ce document, je vous invite à rentrer en contact avec moi afin que l’on en discute.

src_latex{\newpage}
* Introduction
Le Mattér est une langue construite humaine, inspirée phonétiquement et grammaticalement des langues latines et du Latin plus particulièrement, bien que gardant ses distances avec ce dernier. Elle bénéficie également de quelques inspirations germaniques et des langues elfiques de Tolkien concernant leur phonétique.

Cette langue est un projet à part de mon univers littéraire et fut créé dans le cadre de mes études, pour mon cours d’ingénierie des langues, enseigné par Ana Pappa, en troisième année de licence, à l’Université Paris 8. Je ne sais pas encore si j’en ferai autre chose que d’une langue-jouet.

src_latex{\newpage}
* Description du lexique
Le lexique du Mattér sera largement inspiré par des racines nordiques (Suédois, Norvégien, Danois), germaniques (Allemand principalement) et du Vieil Anglais, ainsi qu’occasionellement du Latin.

src_latex{\newpage}
* Phonologie
** Notes sur la romanisation du Mattér
Comme vous avez pu vous en rendre compte aux chapitres §[[*Consonnes]] et §[[*Voyelles]], le Mattér dispose de deux orthographes possibles, la transcription phonétique en IPA (/International Phonetic Alphabet/), soit une translittération qui sera généralement plus simple et intuitive à lire. Dans le cas du Mattér, les deux reflètent dans la large majorité des cas la prononciation de la langue, et c’est pour cela que j’utiliserai principalement la translittération. Cependant il peut y avoir certains cas où la prononciation peut légèrement différer de l’orthographe, comme dans les cas d’allophonie (§[[*Allophonie]]) ou autres cas inhabituels, auquel cas j’utiliserai la transcription phonétique afin de rendre claire la prononciation. Quand il sera question de transcription phonétique, il sera généralement question de phonétique générale, mais il se peut que certaines distinctions se fassent à un niveau plus fin où une transcription phonétique rapprochée sera nécessaire pour avoir la prononciation exacte.

La transcription phonétique générale sera ​/entre barres obliques/, la transcription phonétique rapprochée sera [entre crochets] tandis que des éléments translittérés du Mattér seront <entre chevrons>.

** Inventaire phonétique
Comme mentionné en introduction (§[[*Introduction]]), le Mattér est une langue dont la phonologie est inspirée de langues latines, en particulier le Latin lui-même, et les langues elfiques de Tolkien.

*** Consonnes
Le Mattér est une langue disposant d’un panel raisonnable de seize consonnes. Voici ci-dessous le tableau des consonnes du Mattér, en IPA et translittéré (voir le chapitre §[[*Notes sur la romanisation du Matt%C3%A9r]] concernant la translittération).

#+CAPTION: Consonnes du Hjelp (IPA)
|                         | nasal | occlusif | fricatif | spirant | battu | spirant-lattéral |
|-------------------------+-------+----------+----------+---------+-------+------------------|
| bilabial                | m     | p b      |          |         |       |                  |
| labio-dental            |       |          | f v      |         |       |                  |
| alvéolaire              | n     | t d      | θ ð      |         | r     | l                |
| palatal                 |       |          | ç        | j       |       |                  |
| labio-velaire           |       |          |          | w       |       |                  |
| vélaire                 |       | k g      |          |         |       |                  |
| glottal                 |       |          | h        |         |       |                  |
| /                       | <     | <        | <        | <       | <     | <                |

#+CAPTION: Consonnes du Hjelp (translittération)
|               | nasal | occlusif | fricatif | spirant | battu | spirant-lattéral |
|---------------+-------+----------+----------+---------+-------+------------------|
| bilabial      | m     | p b      |          |         |       |                  |
| labio-dental  |       |          | f v      |         |       |                  |
| alvéolaire    | n     | t d      | th dh    |         | r     | l                |
| palatal       |       |          | ch       | j       |       |                  |
| labio-velaire |       |          |          | w       |       |                  |
| vélaire       |       | k g      |          |         |       |                  |
| glottal       |       |          | h        |         |       |                  |
| /             | <     | <        | <        | <       | <     | <                |

On peut remarquer que la large majorité des consonnes se situe entre les points d’articulation alvéolaire et bilabial, et toutes les consonnes occlusives ou fricatives disposent de leur contrepartie sourde ou voisée.

Voici ci-dessous une description individuelle de chaque consonne :
- b :: Il s’agit du <b> standard dont disposent le Français dans « bonbon » [bɔ̃bɔ̃] ou l’Anglais « believe » [bɪlɪv], une consonne bilabiale occlusive voisée [b].
- c :: Il s’agit du <k> non aspiré que l’on peut retrouver en Français comme « cas » [ka] ou dans certains cas en Anglais comme dans « skirt » [skɜːtʰ]. Il s’agit donc de la consonne occlusive uvulaire sourde [k].
- ch :: Ce <ch> existe en Allemand dans des termes tels que « nicht » [nɪçt] ou en Anglais Britannique dans « hue » [çʉː]. Il s’agit d’une consonne fricative palatale sourde [ç].
- d :: Il s’agit de la consonne <d> standard que l’on peut retrouver en Anglais dans « dice » [daɪs], où le <d> est prononcé en bloquant l’arrivée d’air au niveau de la partie rugueuse du palais. Il est donc différent du <d> français qui est prononcé avec la langue rapprochée voire touchant les dents et qui est noté [d̪], comme dans « dance » [d̪ɑ̃s]. Le <d> du Hjelp est donc bel et bien une consonne occlusive alvéolaire voisée [d].
- f :: Il s’agit du <f> standard que l’on retrouve bon nombre des langues telles que le Français [fʁɑ̃sɛ] ou l’Anglais « fit » [fɪtʰ]. Il s’agit donc d’une consonne fricative labio-dentale sourde [f].
- g :: Il s’agit du <g> dur standard que l’on retrouve dans bon nombre des langues telles que le Français dans « Gar » [ɡɑʁ] ou en Anglais dans « get » [ɡɛt]. Il s’agit donc d’une occlusive vélaire voisée [g].
- h :: Il s’agit de la même consonne que le [h] que l’on retrouve en Anglais, tel que dans « high » [haɪ̯] ou en Allemand « Hass » [has]. Il s’agit donc de la consonne friccative glottale sourde [h].
- j :: Le <j> représente la voyelle <i> prononcée comme une consonne, la rendant donc effectivement semi-consonne. On la retrouve en Français dans des mots tels que « yak » [jak] ou « yoyo » [jojo]. Il s’agit donc d’une consonne approximante rétroflexe voisée [j].
- l :: Ce <l> est le <l> que l’on peut retrouver en Français dans « lire » [liʁ] et dans certains cas en Anglais dans « live » [lɪv]. Le <l> du Hjelp est donc une consonne alvéolaire spirante-latérale voisée [l].
- m :: Il s’agit du même <m> que le <m> standard en Français « mère » [mɛʁ] ou en Anglais « me » [miː]. Il s’agit donc de la consonne nasale bilabiale voisée [m].
- n :: Il s’agit du <n> standard que l’on retrouve en Anglais comme dans « not » [nɔt]. Attention, cette consonne est alvéolaire et non dentale comme le <n> français de « nuit » [n̪ɥi]. Il s’agit donc d’une consonne nasale alvéolaire voisée [n].
- p :: Il s’agit du <p> non aspiré que l’on retrouve en Français tèl que dans « père » [pɛʁ] ou dans certains cas en Anglais comme dans « spoon » [spuːn]. Il s’agit donc de la consonne occlusive bilabiale sourde [p].
- r :: Ce <r> peut être retrouvé en Scots « bricht » [brɪçt], en Espagnol « perro » [pe̞ro̞] ou encore en Portugais avec « ratu » [rato]. Il s’agit d’une consonne alvéolaire roulée voisée [r].
- t :: Ce <t> est la contrepartie voisée de <d> et peut se trouver en Dannois « dåse » [tɔ̽ːsə], en Luxembourgeois « dënn » [tən] ou en Finnois avec « parta » [pɑrtɑ]. Attention, le <t> Français est dental, comme dans « tante » qui est prononcé [t̪ɑ̃t̪]. Ainsi, le <t> du Hjelp est la consonne occlusive alvéolaire sourde [t].
- v :: Le <v> du Hjelp peut être retrouvé dans des langues tels que le Français dans « valve » [valv], en Allemand « Wächter » [vɛçtɐ] ou en Macédonien « вода » [vɔda]. Il s’agit donc d’une consonne fricative bilabiale voisée [v].
- w :: Le <w> est un son que l’on peut retrouver dans certaines langues comme le Français dans « oui » [wi], en Anglais avec « weep » [wiːpʰ], ou en Irlandais « vóta » [ˈwoːt̪ˠə]. Il s’agit de la consonne approximante labio-velaire voisée [w].
- dh :: Cette consonne <th> peut être trouvée dans des langues tels que l’Anglais dans « this » [ðɪs], en Allemand Autrichien « leider » [laɛ̯ða] ou en Swahili dans « dhambi » [ðɑmbi]. Il s’agit donc de la consonne fricative dentale voisée [ð].
- th :: Il s’agit de la contrepartie sourde de <dh> qui peut être trouvée en Anglais dans « thin » [θɪn], en Malaisien dans « Selasa » [θelaθa] ou en Espagnol Castillan « cazar » [käθär]. Il s’agit de la consonne fricative dentale sourde [θ].

Les consonnes nasales, occlusives ainsi que le /​l/ peuvent être doublées, alongeant ainsi leur prononciation. Ainsi, le <tt> de <Mattér> sera prononcé /​tː/, et <Mattér> sera prononcé /​'mat:er/.

*** Voyelles
Le Mattér dispose de relativement peu de voyelles, uniquement six. Voici leur tableau :
#+CAPTION: Voyelles du Hjelp (IPA)
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | i / y       | u            |
|   | mi-fermées  | e           | o            |
|   | mi-ouvertes | ɛ           |              |
|   | ouvertes    | a           |              |

#+CAPTION: Voyelles du Hjelp (translittération)
| / | >           |             |              |
|   |             | antérieures | postérieures |
|---+-------------+-------------+--------------|
|   | fermées     | i / y       | u            |
|   | mi-fermées  | é           | o            |
|   | mi-ouvertes | e           |              |
|   | ouvertes    | a           |              |

Les voyelles du Mattér montrent une plus grande complexité parmi les voyelles antérieures et les voyelles fermées.

Voici ci-dessous la description de chacune de ces voyelles :
- a :: Il s’agit de la voyelle antérieure ouverte non-arrondie [a] que l’on retrouve dans « patte » [pat] en Français.
- e :: Il s’agit de la voyelle antérieure mi-ouverte non-arrondie [ɛ] que l’on retrouve dans « bet » [bɛtʰ] en Anglais ou « fête » [fɛt̪] en Français.
- é :: Il s’agit de la voyelle antérieure mi-fermée non-arrondie [e] que l’on retrouve dans « blé » [ble] en Français.
- i :: On peut retrouver cette voyelle en Anglais comme dans « free » [fɹiː], « ív » [iːv] en Hongrois ou « vie » [vi] en Français. Il s’agit de la voyelle antérieure fermée non-arrondie [i].
- o :: Il s’agit de la voyelle postérieure mi-fermée longue arrondie [o] que l’on peut retrouver dans « hôtel » [o.tɛl].
- u :: On peut retrouver cette voyelle en Allemand standard dans « Fuß » [fuːs] ou en Français dans « tout » [t̪u]. Il s’agit de la voyelle postérieure fermée arrondie [u].
- y :: On peut retrouver cette voyelle en Allemand standard dans « über » [yːbɐ], en Hongrois avec « tű » [t̪yː] ou tout simplement en Français dans « lune » [lyn]. Il s’agit de la voyelle antérieure fermée arrondie [y].

*** Diphtonges
Les diphtongues sont des associations de voyelles considérées dans une langue comme étant une voyelle unique, avec la première unité portant la longueur de la voyelle, la seconde n’étant prononcée qu’en relachant la voyelle. Ainsi, en Anglais, les diphtongues sont assez communes comme avec le terme « je », « ​/I/ » prononcé ​/aɪ/. Voici la liste des diphtongues existant en Hjelp :
| ​/ɛi/ | ​/ai/ |
| ​/ea/ | ​/ae/ |
| ​/eu/ | ​/au/ |
| ​/ou/ |      |

Toutes ces combinaisons sont, comme décrit ci-dessus, monosyllabiques et sont considérées comme telles par les locuteurs de cette langue. Leur translittération est simple (il suffit de faire de même que s’il s’agissait de voyelles isolées) à l’exception du /​ɛi/ qui est écrit <ei>. Ces diphtongues se produisent naturellement lors de la juxtaposition des deux voyelles les formant, et elles peuvent déjà être présentes dans une racine de mot. Ainsi, si une déclinaison ajoute un <a> après un <e>, la diphtongue <ea> se produira naturellement, comme pour la forme nominative de <teren> (/tour/) qui devient <tereant> dans sa forme accusative.

** Allophonie
Bien qu’étant rares, le Mattér a quelques règles à appliquer concernant l’allophonie.
- Le /​i/ peut également se prononcer /​ɪ/ dans certains cas, comme dans les diphones, devant un /​ç/, /​j/, /​w/ ou /​l/, selon le locuteur. Exemple : <neich> /​nɛiç/ [nɛɪç]
- Le /​l/ se transforme en « <l> sombre » /​ɫ/ en fin de syllabe, en particulier avant une pause ou un silence. Exemple : <mael> /​mael/ [maeɫ]
- Le /​h/ se transforme en /​ç/ s’il est suivi par un /​j/, un /​e/ ou un /​i/. Exemple : <hét> /​het/ [çet]

** Phonotaxes
Les phonotaxes sont des règles importantes car elle permettent de déterminer quelles sont les associations de sons possibles dans une langue. C’est ce genre de règles qui permettent de savoir que des mots tels que <jchkwufrwt> ou <nkwej> ne sont pas possibles tandis que des mots tels que <éljond> ou <yndest> le sont. Nous avons déjà déterminé dans la partie dédiée aux diphtongues (§[[*Diphtonges]]) et les voyelles pouvant se succéder afin de créer une diphtongue. En revanche, si deux voyelles se suivent sans entrer dans les règles des diphtongues, elles seront considérées comme étant bisyllabiques, c’est à dire que chacune sera considérée comme une syllabe à part.

Concernant les consonnes, différentes règles s’appliquent selon la situation dans la syllabe.

*** Attaque
L’attaque est la première partie de la syllabe, les premières consonnes la composant. Elle peut comporter d’aucune consonne à deux consonnes ne contenant pas de semi-voyelle, trois avec une semi-voyelle comme consonne finale.
- Le /​j/ ne peut être suivi par un /​i/.
- Le /​w/ ne peut être suivi par une voyelle postérieure.
- Les fricatives et occlusives peuvent être suivies par un /​r/ ou un /​l/, ou par une semi-voyelle.
- Les friccatives peuvent être suivies par une occlusive, par un /​r/ ou un /​l/.

*** Coda
Le coda (la seconde partie consonnantique de la syllabe la terminant) est composée d’aucune à deux consonnes.
- Les semi-consonnes /​j/ et /​w/ ne peuvent se situer dans le coda.
- Les consonnes /​r/ et /​l/ peuvent être suivies par une consonne nasale, occlusive ou fricative.
- Les fricatives sourdes ne peuvent être suivies que par des occlusives sourdes.
- Les fricatives voisées ne peuvent être suivies que par des occlusives voisées ou par des nasales.
- Les nasales peuvent êtres suivies par une occlusive ou une fricative.
- Les occlusives sourdes peuvent être suivies par un <th>.
- Les occlusives voisées peuvent être suivies par un <dh>.

*** Inter-syllabe
Les consonnes inter-syllabes, situées entre deux voyelles, sont soumises elles-aussi à des règles qui leur sont propres.
- Toutes les règles de l’attaque (§[[*Attaque]]) sont applicables.
- Les occlusives peuvent être suivies par une fricative, par un /​r/ ou un /​l/.

** Accentuation
Le Mattér est une langue dont l’accentuation est assez simple à suivre étant donné qu’elle se produit sur la syllabe initiale de tout mot constitué de plus de deux syllabes. Exceptionnellement, si le locuteur veut mettre une emphase sur un certain terme, l’accentuation portera sur la seconde syllabe, voire la troisième dans des cas plus rare et dont l’emphase est presque caricaturée.

src_latex{\newpage}
* Morphologie
La morphologie d’une langue est l’étude de la formation des mots de façon individuelle, de l’aspect et de la modification de ces mots afin de signifier des changements de sens. Pour ce qui est de l’organisation des mots, se référer au chapitre sur la syntaxe (§[[*Syntaxe]]).

Le Mattér est une langue à morphologie principalement agglutinatif puis synthétique ; cela signifie que le changement des mots va principalement s’opérer via des syllabes uniques affixées au mot, chacune portant potentiellement plusieurs significations.

** Genre
Ce chapitre sur le genre n’est pas un chapitre de morphologie en soit, mais il est important de connaître les genres en vigueur dans le Mattér afin de pouvoir étudier le reste de sa grammaire.

Le Mattér est une langue dont le genre est relativement peu significatif, où seuls les humains ont un genre et influence les éléments influençables, notamment les déterminants, adjectifs et verbes. Le Mattér dispose ainsi de quatre genres :
- Neutre (~N~)
- Masculin (~M~)
- Féminin (~F~)
- Non-humain (~NHUM~)

Ainsi, pour les éléments genrés de la langue, le genre est soit connu, auquel cas le masculin ou le féminin seront utilisés, ou bien il sera inconnu auquel cas le neutre sera de vigueur. Pour tous les éléments non-genrés, le genre non-humain sera appliqué. Il arrive cependant que, par affection, un locuteur genre un animal ou un objet ; dans le cas d’un animal, le genre sera accordé à son sexe biologique, et l’objet sera assimilé au genre neutre.

** Noms
Les noms en Mattér servent généralement à se référer à des entités, des concepts ou bien des objets. Ils sont composés d’au moins une syllabe à laquelle peuvent s’ajoute des suffixes.

Voici la structure globale d’un nom :
| / | <>     | >           | >         | >      |
|---+--------+-------------+-----------+--------|
|   | racine | déclinaison | possessif | nombre |
|---+--------+-------------+-----------+--------|


*** Nombre
Le Mattér est une langue comportant trois nombres : le singulier, le paucal et le pluriel.
- singulier :: permet de se référer à un élément unique
- paucal :: permet de se référer à entre deux et six éléments, comporte une conotation de « peu d’éléments »
- pluriel :: permet de se référer à plus de six éléments, comporte une conotation de « beaucoup ».

Voici la liste des suffixes du Mattér afin de marquer le nombre :
| / | <>        | >            |
|   | nombre    | suffixe      |
|---+-----------+--------------|
|   | singulier | /non marqué/ |
|   | paucal    | -(e)t        |
|   | pluriel   | -(a)th       |
|---+-----------+--------------|
La voyelle entre parenthèse est omise lorsque le nombre s’accole à un mot se terminant déjà par une voyelle.

Comme indiqué plus haut, le paucal et le pluriel ont tous deux une conotation respectivement de « peu » et de « beaucoup ». Ainsi, il n’est pas rare pour les locuteurs de cette langue de transgresser la règle de séparation des deux à « 6 » afin de partager un jugement personnel sur la quantité décrite.

Les éléments indénombrables sont au singulier par défaut, mais à nouveau les locuteurs peuvent émettre un jugement personnel de quantité de ces éléments en les mettant au paucal ou au pluriel.

*** Déclinaisons
Selon son rôle dans la phrase, les noms en Mattér se présentent sous une forme différente via leur déclinaison. Huit déclinaisons existent en Mattér :
- le nominatif
- l’accusatif
- le datif
- le locatif
- l’ablatif
- le limitatif
- le génitif
- le vocatif

Le nominatif permet de marquer de manière générale le ou les sujets des verbes transitifs et intransitifs du Mattér. À l’inverse, l’accusatif permet de marquer le ou les objets des verbes transitifs. Le datif permet généralement de marquer ce à quoi on se réfère généralement en Français par « complément d’objet indirect ». Par exemple, en Français la phrase « j’ai offert un cadeau à ma sœur » comporte ces trois éléments, « je » qui est l’élément nominatif, « ma sœur » qui est l’élément datif et « un cadeau » qui est l’élément accusatif.

Le locatif, l’ablatif et le limitatif sont généralement utilisé pour se référer à des lieux, le locatif se référent au lieu directement, l’ablatif se référant à un point de départ et le limitatif à une limite. Ces trois derniers peuvent également se référer à des éléments temporels. Par exemple, dans la phrase « Je fais une escale à Paris dans mon voyage de Lyon à Bruxelles », « Paris » est l’élément locatif, « Lyon » l’élément ablatif et « Bruxelles » l’élément limitatif.

Le génitif permet de marquer une relation entre deux éléments, l’élément décliné étant l’élément possessif ou bien marqué par l’élément le précédant. Par exemple, dans la phrase « j’ai retrouvé le livre de mon père », « mon père » serait décliné au génitif, tandis que « le livre » serait décliné à l’accusatif.

Enfin, le vocatif permet de s’adresser à quelqu’un ou quelque chose, en attirant son attention. Dans la phrase « Monsieur, pourriez-vous m’aider ? », « Monsieur » serait décliné au vocatif.

Voici la table des suffixes à ajouter selon la déclinaison du mot :
| / | <>              | >           |
|   | cas grammatical | déclinaison |
|---+-----------------+-------------|
|   | nominatif       | -(e)n       |
|   | accusatif       | -ant        |
|   | datif           | -ith        |
|   | locatif         | -(o)ch      |
|   | ablatif         | -(r)ac      |
|   | limitatif       | -ém         |
|   | génitif         | -un         |
|   | vocatif         | -y          |
Les éléments entre parenthèse sont facultatifs selon le contexte précédant la déclinaison ; si une voyelle est entre parenthèse, elle sera omise si la déclinaison est déjà précédée par une voyelle, de même s’il s’agit d’une consonne entre parenthèse dans le cas de la déclinaison précédée par une consonne.

Ainsi, <tere> (« tour ») se déclinera ainsi :
| / | <>              | >           | >                     |
|   | cas grammatical | déclinaison | signification         |
|---+-----------------+-------------+-----------------------|
|   | nominatif       | teren       | tour (sujet)          |
|   | accusatif       | tereant     | tour (objet)          |
|   | datif           | tereith     | tour (objet indirect) |
|   | locatif         | terech      | à la tour             |
|   | ablatif         | tererac     | depuis la tour        |
|   | limitatif       | tereém      | jusqu’à la tour       |
|   | génitif         | tereun      | de la tour            |
|   | vocatif         | terey       | Oh, tour !            |

On peut comparer à <velt> (« monde ») qui se déclinera ainsi :
| / | <>              | >           | >                           |
|   | cas grammatical | déclinaison | signification               |
|---+-----------------+-------------+-----------------------------|
|   | nominatif       | velten      | monde (sujet)               |
|   | accusatif       | veltant     | monde (objet)               |
|   | datif           | veltith     | monde (objet indirect)      |
|   | locatif         | veltoch     | dans le monde (à sa surace) |
|   | ablatif         | veltac      | depuis le monde             |
|   | limitatif       | veltém      | jusqu’au monde              |
|   | génitif         | veltun      | du monde                    |
|   | vocatif         | velty       | Oh Monde !                  |

** Déterminants
Le Mattér dispose de quatre catégories de déterminants :
- les articles définis
- les déterminants démonstratifs
- les déterminants interrogatifs
- les déterminants ordinaux

Les articles indéfinis n’existent pas en Mattér, et les déterminants indéfinis sont considérés comme étant des adjectifs et sont utilisés comme tels. Quant aux déterminants cardinaux, il s’agit simplement des nombres tels que décrits dans le chapitre dédié (§[[*Nombres]]).

*** Articles définis
Les articles définis servent à indiquer un élément précis, contrairement à un élément général désigné lors de l’absence d’article défini. Ainsi en Français, on utilise « le », « la » ou « les » comme articles définis. En revanche, le Mattér aura une absence de déterminants là où le Français dispose d’articles indéfinis. Comme on peut le voir ci-dessous, l’article défini s’accorde en genre et en nombre au nom auquel il est attaché.
| / | <         | <      | <>      |
|   | nombre    | genre  | article |
|---+-----------+--------+---------|
|   | singulier | N,NHUM | a       |
|   | singulier | M      | é       |
|   | singulier | F      | al      |
|   | singulier | NHUM   | en      |
|   | paucal    | N,M,F  | od      |
|   | paucal    | NHUM   | yt      |
|   | pluriel   | N,M,F  | eth     |
|   | pluriel   | NHUM   | ev      |

Ainsi, « la tour » se traduira par <an teren> (au nominatif), « les chats » (peu de chats) se traduira <od cetenet> (genre neutre, paucal), « des villes » (nombreuses) se traduira <el urbyneth>.

*** Déterminants démonstratifs
Le déterminant démonstratif du Mattér a une fonction très similaire au déterminant démonstratif du Français, tels que « ce », « cet », « cette » et « ces ». De même que pour les articles définis, ils s’accordent en nombre, mais également selon la distance, allant de visible proche à invisible en passant par visible éloigné.
| / | <        | <         | <>      |
|   | distance | nombre    | article |
|---+----------+-----------+---------|
|   | proche   | singulier | an      |
|   | proche   | paucal    | at      |
|   | proche   | pluriel   | adh     |
|   | éloigné  | singulier | em      |
|   | éloigné  | paucal    | ed      |
|   | éloigné  | pluriel   | edh     |
|   | lointain | singulier | un      |
|   | lointain | paucal    | ut      |
|   | lointain | pluriel   | udh     |

*** Déterminants interrogatifs

*** Déterminants ordinaux
Comme décrit dans le chapitre §[[*D%C3%A9terminants]], le Mattér ne dispose pas de déterminants cardinaux, ou plutôt il s’agit simplement du nombre approprié placé à l’emplacement du déterminant tel que défini plus tard dans le chapitre sur la syntaxe approprié (§[[*Syntaxe]]). Dans le cas des nombres cardinaux, il s’agit d’ajouter en suffixe au numéro le terme <norm> auquel un article défini accordé en genre et en nombre est également suffixé. Ainsi, pour le terme « premier » au singulier masculin, nous obtiendrons

** Adjectifs
Les adjectifs en Mattér s’accordent au nom ou à l’élément principal de la phrase nominale qu’ils définissent, que ce soit en nombre ou en déclinaison. Ils adopteront alors la même déclinaison avec la même terminaison, à l’exception du nominatif où seul le nombre est marqué. Voici un tableau d’exemple d’accord de <raedh> (« rouge ») avec <vagen> (« voiture »).

| /         | <>                  | >                        | >                          |
|           | singulier           | paucal                   | pluriel                    |
|-----------+---------------------+--------------------------+----------------------------|
| nominatif | a raedh vagenen     | en raedhet vagenenet     | yt raedheth vageneneth     |
| accusatif | a raedhant vagenant | en raedhantet vagenantet | yt raedhanteth vagenanteth |
| datif     | a raedhith vagenith | en raedhithet vagenithet | yt raedhitheth vagenitheth |
| locatif   | a raedhoch vagenoch | en raedhochet vagenochet | yt raedhocheth vagenocheth |
| ablatif   | a raedhac vagenac   | en raedhacet vagenacet   | yt raedhaceth vagenaceth   |
| limitatif | a raedhém vageném   | en raedhémet vagenémet   | yt raedhémeth vagenémeth   |
| génitif   | a raedhun vagenun   | en raedhunet vagenunet   | yt raedhuneth vagenuneth   |
| vocatif   | a raedhy vageny     | en raedhyet vagenuet     | yt raedhyeth vagenyeth     |

Il existe une catégorie d’adjectifs qui ne seront cependant pas accordés en nombre et en déclinaison avec leur élément décrit : les adjectifs quantitatifs. Ainsi, <

** Pronoms
Le Mattér dispose d’un ensemble de cinq pronoms, tous correspondant à l’un des cas grammaticaux décrits plus haut (§[[*D%C3%A9clinaisons]]). On peut remarquer que le Mattér ne fait pas de distinction de genre pour la première et la seconde personne ; en revanche chaque genre l’est avec la troisième personne. La première personne est également la seule personne à ne pas avoir de vocatif. Voici le tableau des correspondances :

- Première personne :
| /         | <>        | >         | >     | >       |
|           | nominatif | accusatif | datif | génitif |
|-----------+-----------+-----------+-------+---------|
| singulier | çeg       | çent      | çeidh | çyn     |
| paucal    | thi       | thid      | thidh | thyn    |
| pluriel   | non       | nound     | nonth | nun     |

- Seconde personne :
| /         | <>        | >         | >     | >       | >       |
|           | nominatif | accusatif | datif | génitif | vocatif |
|-----------+-----------+-----------+-------+---------+---------|
| singulier | du        | daun      | dudh  | dyn     | udy     |
| paucal    | im        | eint      | dhi   | nim     | eny     |
| pluriel   | min       | meint     | minth | meun    | miny    |

- Troisième personne :
| /                    | <>        | >         | >      | >       | >       |
|                      | nominatif | accusatif | datif  | génitif | vocatif |
|----------------------+-----------+-----------+--------+---------+---------|
| singulier neutre     | hé        | hét       | heth   | hén     | yhé     |
| singulier masculin   | hae       | haed      | haedh  | haen    | yhae    |
| singulier féminin    | hou       | hound     | hudh   | houn    | yhou    |
| singulier non-humain | hit       | hint      | hith   | him     | yhi     |
| paucal neutre        | hei       | heit      | heith  | hein    | yhei    |
| paucal masculin      | tha       | thad      | thaidh | than    | ytha    |
| paucal féminin       | thu       | thunt     | thou   | thun    | ythu    |
| paucal non-humain    | hou       | hot       | hoth   | dho     | ydhou   |
| pluriel neutre       | hea       | hint      | heath  | heam    | heathy  |
| pluriel masculin     | tha       | that      | thaidh | than    | thaidhy |
| pluriel féminin      | thu       | thunt     | thou   | thun    | ythu    |
| pluriel non-humain   | hou       | hout      | houth  | dho     | houthy  |

** Verbes

*** Temps
À l’exception des verbes <o ber> (être), <o hab> (avoir) et <o gjer> (faire), la conjugaison des verbes en Mattér est très régulière. Trois temps principaux existent : le passé, le présent et le futur, cepedant il est possible d’exprimer du passé antérieur (passé dans un temps de locution passé), du passé postérieur (futur dans un temps de locution passé), du futur antérieur (passé dans un temps de locution futur) et du futur postérieur (futur dans un temps de locution futur).

Généralement parlant, le présent sert aux locuteurs du Mattér à se référer à des actions ou descriptions ou autre se passant lors de la locution de la phrase ou à se réferer à un passé ou futur immédiat, pouvant s’étendre jusqu’à une journée complète avant ou après le temps immédiat de locution. Par exemple, la phrase <mergoch, cinnemoch thi gache> (« demain, nous (paucal) allons au cinéma ») contient le verbe <o gach> conjugué à la première personne du paucal, cependant le sens porté par la phrase est comme quoi l’action d’aller au cinéma prendra lieu dans le futur, en l’occurence le jour suivant le moment de locution. Cepedant la proximité entre ce dernier et le moment de l’action en elle-même permet au locuteur d’utiliser le présent. En revanche, s’il souhaite exprimer la même action comme s’effectuant la semaine suivante, le futur sera utilisé : <nutht vococh, cinnemoch thi y gachatth>. Remarquez par ailleurs l’utilisation du locatif pour <morg> (« demain ») et <nutht voc> (« semaine prochaine ») pour signifier le temps durant lequel l’action s’exécutera.

*** Aspects
Les aspects servent à indiquer la relation du verbe au temps qu’il emploie. Les deux aspects principaux sont les aspects perfectif et imperfectif. Le premier sert à indiquer l’action du verbe comme étant un événement terminé et révolu, considérant ce dernier comme un objet unique et insécable ; à l’inverse, l’imperfectif permet de mettre en place une durée à l’action décrite, de la placer en élément de fond ou de décors, et permet d’y insérer de nouveau éléments. Comparez en Français « Henry IV régnais 21 ans » (imperfectif) et « Henry IV régna 21 ans ». De par sa nature, le présent ne dispose pas d’aspect perfectif, ainsi seuls le passé et le futur montreront ces deux aspects. Voici ainsi le tableau de conjugaison des verbes réguliers aux aspects perfectif puis imperfectif de l’indicatif (un mode, nous en parlerons plus en détail dans le chapitre §[[*Modes]]), le ~V~ représentant la racine du verbe :

#+caption: Conjugaison du perfectif de l’indicatif
| /    | <>    | >     |
|      | passé | futur |
|------+-------+-------|
| 1S   | Vo    | y Vo  |
| 2S   | Vou   | y Vou |
| 3S   | Vo    | y Vou |
| 1PAU | Vur   | y Vur |
| 2PAU | Vun   | y Vur |
| 3PAU | Vur   | y Vur |
| 1P   | Vu    | y Vo  |
| 2P   | Vu    | y Vo  |
| 3P   | Von   | y Von |

#+caption: Conjugaison de l’imperfectif de l’indicatif
| /    | <>    | >       | >       |
|      | passé | présent | futur   |
|------+-------+---------+---------|
| 1S   | Ver   | Ve      | y V     |
| 2S   | Vet   | Vei     | y Vei   |
| 3S   | Ver   | Vea     | y Ve    |
| 1PAU | Vedh  | Vet     | y Va    |
| 2PAU | Veth  | Vaet    | y Vath  |
| 3PAU | Verdh | Vaet    | y Va    |
| 1P   | Ven   | Vern    | y Vatth |
| 2P   | Vent  | Var     | y Vat   |
| 3P   | Ven   | Vér     | y Vat   |

En revanche, les trois temps disposent d’un aspect commun : le progressif qui s’emploie grâce à l’utilisation des verbes <o ber> ou <o gjer> comme auxilliaires conjugué selon le temps et l’aspect perfectif ou imperfectif voulu, tandis que le verbe principal prend <-ande> comme terminaison.

*** Modes

*** Verbe être <o ber>
**** Perfectif
| /    | <>    | >       |
|      | passé | futur   |
|------+-------+---------|
| 1S   | ver   | y ver   |
| 2S   | vet   | y vet   |
| 3S   | vath  | y vath  |
| 1PAU | vedh  | y vedh  |
| 2PAU | venth | y venth |
| 3PAU | vatth | y vatth |
| 1P   | vein  | y vein  |
| 2P   | veat  | y veat  |
| 3P   | veaen | y veaen |

**** Imperfectif
| /    | <>        | >       | >         |
|      | passé     | présent | futur     |
|------+-----------+---------+-----------|
| 1S   | e vath    | be      | u be      |
| 2S   | ea vart   | betht   | u betht   |
| 3S   | ei vart   | beith   | ou beidh  |
| 1PAU | e vatht   | erth    | u erdh    |
| 2PAU | ea vart   | erth    | o erdh    |
| 3PAU | ei varth  | aith    | ou aidh   |
| 1P   | e vaeth   | ther    | u ther    |
| 2P   | ea vaerth | therth  | u therdh  |
| 3P   | ei varth  | thet    | ou thetth |

*** Verbe avoir <o hab>
**** Perfectif
**** Imperfectif
*** Verbe faire <o gjer>
**** Perfectif
**** Imperfectif
** Conjonctions
** Adverbes
** Prépositions

src_latex{\newpage}
* Syntaxe

src_latex{\newpage}
* Morphosyntaxe

src_latex{\newpage}
* Sémantiques

src_latex{\newpage}
* Pragmatique

src_latex{\newpage}
* Phraséologie

src_latex{\newpage}
* Synchronie et diachronie

src_latex{\newpage}
* Nombres
Le Mattér est une langue comptant en base dix et prenant en compte l’existance du zéro. Cependant, contrairement au Français, le Mattér tend à grouper les dizaines de milliers ensemble plutôt que les milliers. Ainsi, nous avons les termes suivants :
| / |                > |         |
|   |           nombre | terme   |
|---+------------------+---------|
|   |                0 | nyn     |
|   |                1 | aen     |
|   |                2 | twéa    |
|   |                3 | dhe     |
|   |                4 | fro     |
|   |                5 | dheif   |
|   |                6 | chcaec  |
|   |                7 | thean   |
|   |                8 | acht    |
|   |                9 | onnén   |
|   |               10 | dran    |
|   |               20 | tjeg    |
|   |               30 | dhjea   |
|   |               40 | frje    |
|   |               50 | dheig   |
|   |               60 | chcjag  |
|   |               70 | thjeg   |
|   |               80 | achteig |
|   |               90 | onneg   |
|   |              100 | anrad   |
|   |             1000 | tansen  |
|   |           1 0000 | deten   |
|   |      1 0000 0000 | mollen  |
|   | 1 0000 0000 0000 | vreljen |

Le Mattér énonce les éléments d’un nombre du plus petit au plus grand, et les nombres nommés <anrad> et plus grands sont suffixés à un nombre plus petit qui les multiplie. Ainsi, le nombre <1789> se traduirait par <onnén achteig theananrad tansen>, et <2345 6789> (ou <23 456 789> selon la typographie française) se traduirait par <onnén achteig theananrad chcaectansen ar dheif fro dheanrad twétansan deten>. Remarquez que la traduction littérale est « 6789 et 2345 0000 ». Entre chaque groupe de quatre chiffre, un <ar> (« et ») est ajouté afin de séparer les groupes. Indiquer un multiplicateur de un est considéré comme inutile, ainsi les termes tels que <deten>, <mollen> et <vreljen> se suffisent à eux-même pour signifier <1 0000>, <1 0000 0000> et <1 0000 0000 0000> respectivement.

src_latex{\newpage}
* Système d’écriture

src_latex{\newpage}
* Glossaire

- ar :: (conj.) et
- brydh :: (nn) naissance
- brydhdeg :: (nn) jour de naissance, anniversaire
- daeg :: (nn) jour
- gaern :: (nn) année
- galm :: (adj) vieux, ancien
- maend :: (adj) beaucoup
- menyth :: (nn) mois
- nethty :: (adj) prochain, suivant
- norm :: (nn) nombre, numéro (ordinal)
- smoz :: (adj) petit
- tere :: (nn) tour, haut monument
- urby :: (nn) ville
- velt :: (nn) monde, la Terre
- vend :: (adj) peu, un peu
- voc :: (nn) semaine

src_latex{\newpage}
* Annexes
** Règles de génération de mots
Le Mattér étant une langue-jouet, j’utiliserai occasionnellement le GenWord^{3} afin de créer du nouveau vocabulaire. Voici les paramètres utilisés pour cela :
#+BEGIN_SRC text
  --CATS--
  N=mn
  P=pbtdkg
  F=fvþðç
  R=rl
  C=nmpbtdkgfvþðçrl
  D=pbtdkgfvþðç
  J=j
  W=w
  A=aeé
  U=iouy
  V=aeéyiou
  --REWRITE--
  þ||th
  ð||dh
  ç||ch
  k||c
  --MONO--

  --MID--

  --INIT--
  CV
  CVC
  CVR
  CVPF
  CVFP
  CVFR
  CVPR
  DRV
  DRVC
  DRVR
  DRVFP
  DRVPF
  DRVPR
  DRVFR
  CJA
  CWA
  CJAC
  CWAC
  CJAR
  CWAR
  CJA
  CWA
  CJAFP
  CWAFP
  CJAPF
  CWAPF
  CJAFR
  CWAFR
  FPVPR
  PFVPR
  FPV
  FPVC
  PFVC
  FPVR
  PFVR
  PFVFP
  PFVFR
  PFVPF
  PFVPR
  FPVFP
  FPVFR
  FPVPF
  FPVPR
  --FINAL--

  --FLAGS--
  1 0 monoMostly dropoffMolasses
#+END_SRC

#  LocalWords:  Pappa langue-jouet
