#+INCLUDE: "../headers.org"
#+LATEX_CLASS: article
#+TITLE: Une Grammmaire du Hjelp
#+HTML_HEAD: <meta name="description" content="Grammaire détaillée de la langue construite du Hjelp" />
#+HTML_HEAD: <meta property="og:title" content="Grammaire du Hjelp" />
#+HTML_HEAD: <meta property="og:description" content="Grammaire détaillée de la langue construite du Hjelp" />

* Introduction
Le Hjelp est une langue construite représentant symboliquement la langue orale et écrite utilisée par les dieux célestes de l’univers de mon roman, les Hjalpel. Cela signifie que, bien que le Hjalp soit une langue /de facto/ réelle de part cette grammaire et au moins mon utilisation de cette langue dans mes ouvrages, elle n’est pas réellement la langue telle que je l’imagine pour les dieux célestes ; en effet, j’imagine la langue réelle des Hjalpel comme étant une langue d’une extraordinaire complexité, mais extrêmement concise, représentant l’esprit des dieux célestes. Je me référerais ainsi par « Hjelp théorique » au Hjelp tel qu’imaginé dans mon univers littéraire, et par « Hjelp construit » ou tout simplement « Hjelp » la langue présentée dans ce document.

Fort heureusement pour ceux qui se montreraient intéressé par le Hjelp, et malheureusement pour moi, créer une langue d’un tel niveau de complexité est littéralement impossible, considérant ne serait-ce que la difficulté théorique pour l’apprendre. Cependant, cela ne m’empêchera pas d’essayer de créer une langue complexe et concise du mieux que je peux, et j’essaierai d’imiter avec cette langue l’esthétique de la langue théorique des Hjalpel.

Le Hjelp est une langue construite dite /à priori/, c’est à dire qu’elle ne se base sur aucune langue naturelle. Sa grammaire a quelques inspirations de diverses langues telles que le Français, le Tibétain, le Japonais, le Finnois ou le Hongrois, cependant aucune partie majeure de leur grammaire n’est intégrée au Hjelp, et son lexique est entièrement construit de manière indépendante de toute langue naturelle.

J’utiliserai, comme indiqué plus haut, cette langue dans mes ouvrages littéraires concernant l’univers lié à cette langue, mais je l’utiliserai également pour des consructions d’autres langues qui descendront du Hjelp. Ces nouvelles langues, tel que le Melexeq, la langue de certains dieux terrestres, seront beaucoup plus simples. Les langues divines terrestres garderont un certain degré de complexité du fait du peuple la parlant en lui-même, et les langues descendant du Hjelp utilisées par les mortels seront d’un niveau de complexité similaire aux langues naturelles que l’on peut trouver dans notre monde.

Cette grammaire n’est pas un ouvrage destiné à l’apprentissage du Hjelp (peut-être en écrirai-je un destiné à cette application) mais s’addresse plus à mon propre besoin d’avoir une grammaire de référence pour le Hjelp et suppose donc que le lecteur a un minimum de connaissances linguistiques, bien que certains concepts seront expliqués dans leur chapitre ou paragraphe dédié.

** Quelques précisions sur le Hjelp théorique

Comme dit plus haut, le Hjelp théorique est une langue extrêmement complexe parlée par les Hjalpel dans mon univers littéraire. Apprendre cette langue prend plusieurs années d’études pour un humain afin de pouvoir ne serait-ce que commencer à former des phrases rudimentaires avec un vocabulaire limité, et les meilleurs ont un niveau tout de même faible ; selon le Cadre Européen Commun de Référence pour les Langues (CECRL) à l’heure où j’écris ces lignes, cela équivaut à un niveau A2.

Cette difficulté d’apprentissage de la langue est liée à la nature des Hjalpel et des dieux de façon générale dans mon univers : ils existent en dehors de la réalité, et leur parole sont une manifestation en soit de la réalité, exprimant toute sa complexité, sa subtilité. Comprendre parfaitement cette langue revient à comprendre parfaitement la réalité, d’où le niveau très bas même des meilleurs universitaires et étudiants du Hjelp théorique.

Le Hjalpel théorique étant une expression de la réalité en elle-même, tout élément qui est créé à un instant t entre à ce moment-là dans le domaine de la réalité qui se propage alors dans le passé, et un mot émerge alors naturellement en Hjelp théorique, ayant aux yeux des mortels existé depuis toujours mais n’ayant été découvert que récemment.

À l’inverse du passé et du présent, le futur ne reste qu’hypothétique dans cet univers, et bien qu’il puisse être prévu et prévisible aux yeux des divins, il est tout à fait possible de l’altérer si un dieux interfère avec la réalité, si un mortel fait usage de son libre arbitre (en effectuant une action réfléchie) ou en faisant usage de la magie. Ainsi, les éléments futurs ne font pas encore partie de la réalité et n’ont donc pas d’expression dans le présent. Attention, du moment qu’un concept est possible dans le futur, ce concept a été créé dans le présent de la personne (mortelle ou divine) y ayant pensé et entre donc dans le domaine de la réalité.

Je pense que vous comprenez maintenant pourquoi il est impossible pour moi en tant qu’auteur et simple mortel de réellement créer le Hjelp théorique.

* Lexique

Le Hjelp est une langue se basant sur le principe des racine consonantales, la grammaire étant exprimée quasiment uniquement via les voyelles. Du fait de ses très riches déclinaisons, et malgré son nombre limité de racines lexicales, le Hjelp peut exprimer un très grand nombre de différent mots, tous basés sur la même racine.

Afin de respecter la philosophie du Hjelp théorique, tous les mots de son lexique sont des mots ayant été créés soit /à priori/, soit à partir d’autres mots du Hjelp. Ainsi, le Hjelp n’est qu’une langue source dans la génétique des langues de mon univers linguistique et n’emprunte ainsi jamais à d’autre langues.

src_latex{\newpage}
* Phonologie
** Notes sur la translittération et la romanisation du Hjelp

Le Hjelp est une langue disposant d’un système d’écriture qui lui est unique, et par conséquent ne peut pas être aisément reproduisible par ordinateur, encore moins dans du texte comme celui-ci, à moins d’insérer des images dessinées au préalable. De plus, de par sa nature idéographique, le lecteur n’aura aucune idée de la façon dont les mots se prononcent, hors il est important de pouvoir partager l’aspect phonétique de cette langue afin d’assurer une bonne compréhension de ce document. Ainsi, j’utiliserai pour la quasi-totalité de cette grammaire une translittération du Hjelp, visant à renvoyer une prononciation proche de la réalité. Ainsi, la majorité des sons seront représentés par un unique caractère, à l’exception de quelques sons représentés par deux comme nous le verrons ci-dessous.

Pour des raisons d’esthétisme, le Hjelp dispose également d’un système de romanisation. Ce système repose sur moins de caractères comportant des accents et autres diacritiques mais permet une approche peut-être plus simple de la prononciation de la langue pour les non-linguistes. L’approche de la prononciation du Hjelp changeant selon la ou les langues parlées par le lecteur, la romanisation peut également changer en fonction de la langue cible. Ainsi, les francophones pourront retranscrire « qhø₃ð » comme « reuv » tandis que les anglophones le rentranscriront « rhoth ». Cette romanisation ne sera présente que dans le point suivant ([[*Inventaire phon%C3%A9tique]]) afin de donner une référence de lecture du Hjelp dans mes textes littéraires, cependant elle ne sera absolument pas utilisée dans ce document du fait du manque d’information qu’elle partage, contrairement à la translittération qui reste constante selon la langue du lecteur et transmet toutes les informations phonétiques (ou presque, c.f. la section [[*Allophonie]] sur l’allophonie) dont on a besoin.

Quelques fois, la translittération ne suffira pas, en particulier dans ce chapitre, pour exprimer avec détail la prononciation de certains mots ou de certaines phrases ; je devrai donc utiliser l’alphabet phonétique international (IPA, /International Phonetic Alphabet/) afin de pouvoir donner la prononciation de façon beaucoup plus précise que la translittération qui peut parfois ne pas être exacte (à nouveau, c.f. la section [[*Allophonie]] sur l’allophonie).

** Inventaire phonétique

La tendance en Hjelp est d’isoler les mots entre eux, marquant la séparation entre eux par de courtes pauses ou par un coup de glotte [ʔ] entre ces mots lors d’un passage d’une voyelle à une autre entre deux mots. Lorsqu’un mot est composé de plusieurs syllabes, une préférence est présente pour que les consonnes les plus proches de la voyelle fassent partie intégrale de la syllabe dont la voyelle est le cœur, avec un équilibre dans la répartition des consonnes entre les deux voyelles, avec un avantage pour la voyelle suivante. Ainsi, quand trois consonnes sépareront deux voyelles, la première consonne uniquement fait partie de la première syllabe. Si cette règle n’est pas suivie, la séparation sera marquée à l’écrit par la première consonne de la nouvelle syllabe écrite en majuscule, ou bien la voyelle elle-même si la syllabe ne commence pas par une consonne.

*** Les consonnes

Le Hjelp est une langue disposant d’un très large panel de consonnes. Voici ci-dessous le tableau des consonnes du Hjelp, translittéré puis en IPA.

#+CAPTION: Consonnes du Hjelp (translittération)
|            | nasal | occlusif | fricatif | spirant | roulé | fric-lat | spir-lat | semi-vow |
|------------+-------+----------+----------+---------+-------+----------+----------+----------|
| bilabial   | m     | p b      |          |         |       |          |          | w        |
| lab-dent   |       |          | f v      |         |       |          |          |          |
| dental     |       |          | þ ð      |         |       |          |          |          |
| alvéolaire | n ń   | t d      | s z      | ŕ       | r     | lh       | l ĺ      |          |
| pal-alv    |       |          | sh zh    |         |       |          |          |          |
| rétroflexe |       | ŧ đ      |          |         |       |          |          |          |
| palatal    |       |          | ch jh    | j       |       |          |          |          |
| vélaire    | ng    | k g      |          |         |       |          |          |          |
| uvulaire   |       |          | qh rh    |         |       |          |          |          |
| glottal    |       | ’        | h        |         |       |          |          |          |
| /          | <     | <        | <        | <       | <     | <        | <        | <        |

#+CAPTION: Consonnes du Hjelp (IPA)
|            | nasal      | occlusif | fricatif | spirant | battu | fric-lat | spir-lat | semi-vow |
|------------+------------+----------+----------+---------+-------+----------+----------+----------|
| bilabial   | m [m̩] [m̩ʲ] | p b      | [ɸ] [β]  |         |       |          |          | w        |
| lab-dent   |            |          | f v      |         |       |          |          |          |
| dental     |            |          | θ ð      |         |       |          |          |          |
| alvéolaire | n n̩        | t d      | s z      | ŕ       | ɾ     | ɬ        | l l̩ [l̩ʲ] |          |
| pal-alv    |            |          | ʃ ʒ      |         |       |          |          |          |
| rétroflexe |            | ʈ ɖ      |          |         |       |          |          |          |
| palatal    | [ɲ̩]        |          | ç ʝ      | j       |       |          |          |          |
| vélaire    | ŋ          | k g      | [x] [ɣ]  |         |       |          |          |          |
| uvulaire   |            |          | χ ʁ      |         |       |          |          |          |
| glottal    |            | ʔ        | h [ɦ]    |         |       |          |          |          |
| /          | <          | <        | <        | <       | <     | <        | <        | <        |

On peut remarquer une grande complexité au niveau des consonnes occlusives et fricatives, avec également un bon nombre de consonnes alvéolaires. Presque toutes les consonnes occlusives et fricatives sont par ailleurs dotées de leur équivalent voisé ou sourd, à l’exception des deux consonnes glottales. À noter que les phonèmes du tableau IPA entre crochets sont des allophones et n’ont pas de représentation qui leur est propre. Il est également à noter la présence de <ń> et <ĺ> qui sont toutes deux des consonnes syllabiques ; cela signifie qu’elles ne sont pas considérées comme des consonnes mais comme des voyelles à part entière au même titre que celles que nous verrons ci-dessous.

Voici ci-dessous une description individuelle de chaque consonne :
- b :: Il s’agit du <b> standard dont disposent le Français dans « bonbon » [bɔ̃bɔ̃] ou l’Anglais believe [bɪlɪv], une consonne bilabiale occlusive voisée [b].
- ch :: Ce <ch> existe en Allemand dans des termes tels que « nicht » [nɪçt]. Il s’agit d’une consonne fricative palatale sourde [ç].
- d :: Il s’agit de la consonne <d> standard que l’on peut retrouver en Anglais dans « dice » [daɪs], où le <d> est prononcé en bloquant l’arrivée d’air au niveau de la partie rugueuse du palais. Il est donc différent du <d> français qui est prononcé avec la langue rapprochée voire touchant les dents et qui est noté [d̪], comme dans « dance » [d̪ɑ̃s]. Le <d> du Hjelp est donc bel et bien une consonne occlusive alvéolaire voisée [d].
- f :: Il s’agit du <f> standard que l’on retrouve bon nombre des langues telles que le Français [fʁɑ̃sɛ] ou l’Anglais « fit » [fɪtʰ]. Il s’agit donc d’une consonne fricative labio-dentale sourde [f].
- g :: Il s’agit du <g> dur standard que l’on retrouve dans bon nombre des langues telles que le Français dans « Gar » [ɡɑʁ] ou en Anglais dans « get » [ɡɛt]. Il s’agit donc d’une occlusive vélaire voisée [g].
- h :: Le <h> représente l’aspiration effectuée dans certaines langues comme l’Anglais dans « had » [hæd]. Il s’agit d’une consonne glottale sourde [h].
- j :: Le <j> représente la voyelle <i> prononcée comme une consonne, la rendant donc effectivement semi-consonne. On la retrouve en Français dans des mots tels que « yak » [jak] ou « yoyo » [jojo]. Il s’agit donc d’une consonne approximante rétroflexe voisée [j].
- jh :: Le <jh> est l’équivalent voisé de <ch>. On retrouve cette consonne en Italien comme dans « figlio » [fiʝːo] ou en Russe avec яма [ˈʝämə]. Il s’agit donc d’une consonne fricative palatale voisée [ʝ].
- k :: Il s’agit du <k> non aspiré que l’on peut retrouver en Français comme « cas » [ka] ou dans certains cas en Anglais comme dans « skirt » [skɜːtʰ]. Il s’agit donc de la consonne occlusive uvulaire sourde [k].
- l :: Ce <l> est le <l> que l’on peut retrouver en Français dans « lire » [liʁ] et dans certains cas en Anglais dans « live » [lɪv]. Attention à ne pas le confondre avec le « l sombre » anglais que l’ont peut retrouver par exemple dans « feel » [fiːɫ]. Le <l> du Hjelp est donc une consonne alvéolaire spirante-latérale voisée [l].
- lh :: Ce <l> est en quelques sortes un équivalent non-voisé du <l> présenté ci-dessous. Il se retrouve en Groënlandais dans le mot « illu » [iɬːu] ou en Norvégien de Trøndersk « tatl » ou « tasl » [tʰaɬ]. Il s’agit donc d’une consonne alvéolaire latérale fricative sourde [ɬ].
- m :: Il s’agit du même <m> que le <m> standard en Français « mère » [mɛʁ] ou en Anglais « me » [miː]. Il s’agit donc de la consonne nasale bilabiale voisée [m].
- n :: Il s’agit du <n> standard que l’on retrouve en Anglais comme dans « not » [nɔt]. Attention, cette consonne est alvéolaire et non dentale comme le <n> français de « nuit » [n̪ɥi]. Il s’agit donc d’une consonne nasale alvéolaire voisée [n].
- ng :: Cette consonne se retrouve en Anglais dans des termes tels que « singer » [sɪŋɚ] ou « king » [kʰɪŋ], et on le retrouve à quelques occasion en Français comme dans « camping » [kɑ̃piŋ]. Il s’agit donc d’une consonne nasale vélaire voisée [ŋ].
- p :: Il s’agit du <p> non aspiré que l’on retrouve en Français tèl que dans « père » [pɛʁ] ou dans certains cas en Anglais comme dans « spoon » [spuːn]. Il s’agit donc de la consonne occlusive bilabiale sourde [p].
- qh :: Il s’agit d’une consonne que l’on retrouve en Français comme dans « proche » [pχɔʃ], en Allemand « Dach » [daχ] ou en Kabyle « axxam » [aχχam]. Il s’agit donc d’une voyelle fricative uvulaire sourde [χ].
- r :: Ce <r> peut être retrouvé en Scots « bricht » [brɪçt], en Espagnol « perro » [pe̞ro̞] ou encore en Portugais avec « ratu » [rato]. Il s’agit d’une consonne alvéolaire roulée voisée [r].
- rh :: Cette consonne est l’équivalent voisé de <qh>, que l’on peut retrouver en Français « rester » [ʁɛste], en Dannois « rød » [ʁ̞œ̠ð̠], en Allemand strandard « Rost » [ʁɔst] ou encore en Luxembourgeois « Kugel » [ˈkʰuːʁəl]. Il s’agit donc d’une voyelle fricative uvulaire voisée [ʁ].
- s :: Ce <s> est le <s> standard alvéolaire que l’on retrouve dans des langues tels qu’en Anglais « sit » [sɪtʰ], en Portugais « caço » [kasu] ou en Estonien « sõna » [sɤnɑ]. Attention, le <s> français tel que dans « façade » [fäs̪äd̪] est dentalisé, contrairement au <s> du Hjelp qui est donc une consonne fricative alvéolaire sourde [s].
- sh :: Cette consonne peut se retrouver dans des langues telles que le Français « cher » [ʃɛʁ], en Anglais « sheep » [ʃiːpʰ] ou en Breton « chadenn » [ʃadeñ]. Il s’agit donc d’une consonne fricative post-alvéolaire sourde [ʃ].
- t :: Ce <t> est la contrepartie voisée de <d> et peut se trouver en Dannois « dåse » [tɔ̽ːsə], en Luxembourgeois « dënn » [tən] ou en Finnois avec « parta » [pɑrtɑ]. Attention, le <t> Français est dental, comme dans « tante » qui est prononcé [t̪ɑ̃t̪]. Ainsi, le <t> du Hjelp est la consonne occlusive alvéolaire sourde [t].
- v :: Le <v> du Hjelp peut être retrouvé dans des langues tels que le Français dans « valve » [valv], en Allemand « Wächter » [vɛçtɐ] ou en Macédonien « вода » [vɔda]. Il s’agit donc d’une consonne fricative bilabiale voisée [v].
- w :: Le <w> est un son que l’on peut retrouver dans certaines langues comme le Français dans « oui » [wi], en Anglais avec « weep » [wiːpʰ], ou en Irlandais « vóta » [ˈwoːt̪ˠə]. Il s’agit de la consonne approximante labio-velaire voisée [w].
- z :: Ce <z> est la contrepartie voisée du <s>. On le retrouve dans des langues tels que l’Anglais dans « zoo » [zuː], en Esperanto dans « kuzo » [kuzo] ou en Japonais dans « zenbu » [zembɯ]. Attention, en Français le [z] est dentalisé en [z̪] et est donc différent du <z> du Hjelp qui est une consonne fricative alvéolaire voisée [z].
- zh :: Ce <zh> est la contrepartie voisée du <sh>. Il peut être retrouvé en Français dans « jour » [ʒuʁ], en Navajo « łizh » [ɬiʒ] ou en Corse avec « ghjesgia » [jeːʒa]. Il s’agit donc de la consonne fricative post-alvéolaire voisée [ʒ].
- ð :: Cette consonne <ð> peut être trouvée dans des langues tels que l’Anglais dans « this » [ðɪs], en Allemand Autrichien « leider » [laɛ̯ða] ou en Swahili dans « dhambi » [ðɑmbi]. Il s’agit donc de la consonne fricative dentale voisée [ð].
- þ :: Il s’agit de la contrepartie sourde de <ð> qui peut être trouvée en Anglais dans « thin » [θɪn], en Malaisien dans « Selasa » [θelaθa] ou en Espagnol Castillan « cazar » [käθär]. Il s’agit de la consonne fricative dentale sourde [θ].
- đ :: Il s’agit d’un <d> prononcé de façon rétroflexe et peut être trouvé dans des langues telles que le Norvégien dans « varde » [ʋɑɖːə] ou en Sicilien dans « coḍḍu » [kɔɖːu]. Il s’agit de la consonne occlusive rétroflexe voisée [ɖ].
- ŕ :: Ce <r> est une consonne signature de l’Anglais tel que dans « red » [ɹɛd], ainsi qu’en Allemand Autrichien standard « Rebe » [ɹeːbɛ] ou en Tagalog dans « parang » [paɹaŋ]. Cette consonne est la consonne alvéolaire approximante voisée [ɹ].
- ŧ :: Cette consonne est l’équivalent sourd de la consonne <đ>. Elle se retrouve dans certaines langues telles que le Javanais dans « bathang » [baʈaŋ], en Norvégien « kort » [koʈː] ou en Suédois « karta » [kʰɑːʈa]. Il s’agit donc de la consonne occlusive rétroflexe sourde [ʈ].
- ’ :: La consonne <’> est une consonne que l’on retrouve en Anglais Général Américain dans « button » [bɐʔn̩], en Danois avec « hånd » [hʌ̹nʔ] ou encore en Hawaiien avec « ’ele’ele » [ˈʔɛlɛˈʔɛlɛ]. Il s’agit donc de la consonne occlusive glottale sourde [ʔ].


*** Les voyelles
À l’instar des consonnes, le Hjelp dispose d’un inventaire phonétique très large, contenant un total de 23 voyelles simples, incluant le <ń> et le <ĺ> présentés ci-dessus. Les voici ci-dessous translittérées et en IPA.

#+CAPTION: Voyelles du Hjelp (translittération)
| / | >           |               |              |
|   |             | antérieures   | postérieures |
|---+-------------+---------------+--------------|
|   | fermées     | i / y         | u            |
|   | pré-fermées | ì / ĩ / ů     | ù / ũ        |
|   | mi-fermées  | e / é / ø / ö | o / õ        |
|   | mi-ouvertes | è / œ / ô     | ò            |
|   | ouvertes    | a             | å / ã        |

#+CAPTION: Voyelles du Hjelp (IPA)
| / | >           |                   |              |
|   |             | antérieures       | postérieures |
|---+-------------+-------------------+--------------|
|   | fermées     | iː / yː           | uː           |
|   | pré-fermées | ɪ / ɪ̃ / ʏ         | ʊ / ʊ̃        |
|   | mi-fermées  | eː / ẽː / øː / ø̃ː | oː / õː      |
|   | mi-ouvertes | ɛ / œ / œ̃         | ɔ            |
|   | ouvertes    | aː                | ɑ / ɑ̃        |

On remarque ci-dessus une complexité particulièrement importante au niveau des voyelles mi-fermées antérieures ainsi qu’une abscence de voyelles centrales. La majorité des voyelles sont dans une paire ouverte et courte ou fermée et longue, tels que le <i> et le <ì> ou le <a> et le <å>. Plusieurs voyelles ont également leur équivalent nasalisé, tels que le <ī>, <ö> et <ô>.

** Diphtongues

Les diphtongues en Hjelp sont très libres, dans le sens où toute voyelle peut s’associer avec une autre afin de créer une diphtongue, à la condition qu’il ne s’agisse pas deux fois de la même voyelle. Lors de l’association de deux voyelles, si l’une des voyelles est longue, alors elle perd cette qualité et devient courte. En Hjelp, la voyelle se maintenant durant un allongement de la diphtongue est la première des deux, la seconde restant courte peu importe la situation.

La marque tonale associée au diphone ne se marquera que sur la seconde voyelle, la diphtongue étant considérée en Hjelp comme étant une seule et unique voyelle. Il se peut que dans certains cas deux voyelles syllabiques se suivent sans former de diphtongue ensemble, auquel cas la marque tonale marquera la séparation des deux syllabes. Dans le cas où la première syllabe est sur le ton neutre, il sera obligatoire de le marquer explicitement à l’écrit, tel que dans *qhlö₄te₁ů₂ntrhae₂lf*. Pour plus de détails sur les tons du Hjelp, voir la section sur les sept tons ([[*Les sept tons]]).

** Triphtongues

À l’instar des diphtongues ([[*Diphtongues]]), le Hjelp est extrêmement permissif quand aux triphtongues, interdisant uniquement les successions immédiates de deux voyelles identiques. À nouveau, comme pour les diphtongues, la dernière voyelle reste courte ; la première voyelle est également courte, la longueur de la triphtongue étant supporté par la seconde voyelle la composant, telle la première voyelle des diphtongues.

À nouveau, la dernière voyelle de la triphtongue est celle qui supporte la marque tonale à l’écrit, et afin d’éviter une confusion entre une triphtongue et une voyelle simple accolée à une diphtongue, la marque tonale servira à les dissocier.

** Les sept tons
** L’accentuation
** Allophonie
** Phonotaxes

src_latex{\newpage}
* Morphologie

src_latex{\newpage}
* Syntaxe

src_latex{\newpage}
* Système d’écriture

src_latex{\newpage}
* Lexique

Le Hjelp étant une langue évoluant en permanence, je ne peux donner de lexique fixe dans ce document, cependant un dictionnaire en ligne est actuellement en cours de développement qui contiendra tous les mots de la langue et les traduira vers le français et l’anglais avec les détails nécessaires à une bonne compréhension des termes, les subtilités qu’ils induisent ainsi que leur étymologie s’ils en ont une.

src_latex{\newpage}
* Annexes

** Annexe A : Abbréviations
