#+TITLE: Cas grammaticaux du Hjalpi’ Vernaculaire
#+INCLUDE: ../headers/headers.org

Le  Hjalpi’  verniculaire   (je  m’y  référerai  plus   tard  comme  « Hjalpi’ »
uniquement) est une  langue ergative (le sujet du verbe  intransitif et du verbe
transitif ne sont pas confondus) (comme le tibétain)
- Transitivité :: aptitude ou non à gérer un objet

                  Un  verbe  transitif  ne  s'utilise (en  français)  que  quand
                  l'objet est connu par le contexte ("Il mange").

Ne pas confondre emploi intransitif et  verbe intransitif : un verbe intransitif
n'accepte jamais de complément d'objet direct  ou indirect. Il n'accepte que des
compléments circonstanciels.

Le COD (complément d'objet direct) est  en syntaxe un type de complément d'objet
du verbe  d'action employé à la  voix active. Il se  construit sans préposition.
Permet de répondre à la question "quoi ?" (il éclaire (quoi ?) la pièce).

Le  cas Syncrétique  est  une fusion  en  un seul  élément  de plusieurs  traits
grammaticaux.

Un exemple sera  donné avec le terme /mén/, « livre »  et /raëm/, « maison » (le
bâtiment).

- Abessif (= Caritif)  /e-/ ::  Cas grammatical exprimant l'absence d'une chose.
     Correspond en Français à la préposition « sans » Exemple\nbsp{}:
  - "sans parler"
  - "excepté" (= "sans prendre dans le nombre")
  /émén/ : sans livre\\
  /eraëm/ : sans maison

- Ablatif (depuis)  /li-/  :: Cas grammatical exprimant le  déplacement à partir
     d'un lieu ouvert. Exemple\nbsp{}: "Je viens /de Paris/"

     /límén/ : depuis l’extérieur du livre\\
     /liraëm/ : depuis l’extérieur de la maison

- Absolutif /-a/ :: Cas grammatical marquant  le sujet de verbes intransitifs et
                    l'objet des verbes transitifs. *En opposition au cas ergatif
                    qui marque le sujet des verbes transitifs.* Dans le Hjalpi’,
                    il   s’agit   juste   du   sujet   du   verbe   intransitif.
                    Exemple\nbsp{}:
  - "/Je/ suis tombé"
  - "J’ai bu /du lait/"
  /méná/ : le livre (sujet du verbe intransitif)\\
  /raëma/ : la maison (idem)

 Accusatif  /-vo/  :: Cas  grammatical  exprimant  le  COD, l'actant  qui  subit
                    l'action exercée  par le  sujet d'un verbe  transitif direct
                    actif. *Dans les langues ergatives,  peut être assumé par le
                    cas absolutif.* Exemple\nbsp{}:
  - "Elle a collé la photo /sur la porte/"
  - "La photo est collée /sur la porte/" = datif
  - "L'homme /dont/ je parle"
  - "L'homme lit une /lettre/" ("lettre") ("l’homme" ergatif ou nominatif)
  /ménvó/ : le livre (objet)\\
  /raëmvo/ : la maison (idem)

- Adessif /iŗ-/ :: Cas grammatical exprimant la  position en un lieu ouvert ou à
                   proximité immédiate de  quelque chose. Exemple\nbsp{}: "/près
                   du/ mur"

                   /íŗmén/ : près du livre\\
                   /iŗraëm/ : près de la maison (sous-entendu dehors)

- Allatif  (vers)  /-li-/  :: Cas  grammatical exprimant  le lieu non  clos vers
     lequel se produit un mouvement. Complémentaire de l'ablatif en exprimant le
     mouvement en  direction opposée, et  l'adessif se  situe entre les  deux en
     exprimant la position  en un lieu non clos  sans mouvement. Exemple\nbsp{}:
     "je vais /à/ la plage"

     /mélín/ : vers le livre (toujours à l’extérieur)\\
     /raëlin/ : vers la maison (sans aller à l’intérieur)

- *Bénéfactif ::   Trait grammatical exprimant  le rôle sémantique dévolu  à une
                 entité  bénéficiaire  d'un  procès,  càd  affectée  de  manière
                 avantaguese  pour elle  par  une action  ou  une situation.  Il
                 s'agit souvent de datif. En  Finnois, est marqué par l'allatif.
                 L'autobénéfactif est  un sens  possible de  la voix  moyenne en
                 grec et  sanskrit. Représenté  en langue  divine par  le datif.
                 Exemple\nbsp{}:  "Un   parent  a   dessiné  un   cheval  /pour/
                 l'enfant".

- Causal /-oby/  ::  Cas grammatical marquant la raison ou  le motif de l'action
                    exprimée par  le verbe  principal (utilisation du  "kara" en
                    Japonais)

                   /ménóbý/ : du fait du livre, à cause/grâce au livre\\
                   /raënoby/ : du fait de la maison, à cause/grâce à la maison

- Comitatif /-ðei-/  :: Cas  grammatical exprimant  l'accompagnement. Équivalent
     français : la proposition "avec". Exemple : "Il est venu /avec/ ses amis"
     /méðéín/ : avec le livre\\
     /raëðein/ : avec la maison

- Datif  /-at-/ ::  Cas grammatical  exprimant l'objet  indirect ou  second, càd
                  l'actant  dit  bénéficiaire  (à   ne  pas  confondre  avec  le
                  bénéfactif que le datif représente souvent). Peut marquer dans
                  beaucoup de langues la possession. Exemple\nbsp{}:
  - "J'ai cassé /le vase/"
  - /J/'ai un livre (Tibétain: "nga la dpe-cha yod", "nga")
  /mátén/ : pour le livre\\
  /rataën/ : pour la maison

- Délatif /ßa-/ :: Cas locatif séparatif  externe qui exprime le point de départ
                   d'un lieu géographique et  qui plus précisément peut exprimer
                   la  surface  d'un  support  depuis  laquelle  un  déplacement
                   s'effectue. Exemple\nbsp{}: "Je suis tombé /du toit/.

                   /ßámén/ : depuis le livre (sous entendu depuis sa couverture)\\
                   /ßaraën/ : depuis la maison (sous entendu du toit)

- *Direct  :: Cas  grammatical  comprenant la  forme de  citation  des mots  (ou
             lemme). Fonctionne par opposition au cas oblique. Applications :
  - Premier sens:  désigne le nominatif  comme forme de citation,  en opposition
    aux autres cas dits obliques
  - Par spécialisation, peut désigner dans une  déclinaison à deux cas celui qui
    s'emploie comme forme de citation, l'autre étant oblique
  - Réemployé pour désigner un cas syncrétique  couvrant à la fois les fonctions
    syntaxiques de sujet et d'objet, dans  un système comportant par ailleurs un
    ou plusieurs autres cas obliques.

- Directif  /-lë/   ::  Cas  grammatical   indiquant  un  changement   de  lieu.
                    Exemple\nbsp{}: "Je vais /dans la pièce/."

     /lêmén/ : vers le livre (sous entendu le livre étant dans un autre lieu)\\
     /lëraën/ : vers la maison (sous entendu dans la maison depuis un autre lieu)

- Distributif  /xelje-/ ::  Cas  grammatical indiquant  une distribution  égale.
     Exemple\nbsp{}: "cinq médecins /par commune/"

     /xéljémén/ : pour chaque livre\\
     /xeljeraën/ : pour chaque maison

- Élatif  /-ły/ ::  Cas  grammatical  exprimant le  lieu  de l'intérieur  duquel
                  provient le mouvement. Ex: "En sortant /de la maison/"

                   /ménłý/ : depuis l’intérieur du livre ou de son contenu\\
                   /raënły/ : depuis l’intérieur de la maison

- Équatif  =  Comparatif  /-ńt/  :: Cas  grammatical  marquant  la  comparaison,
     l'assimilation ou l'identité. Ex :
  - /comme/ une flèche
  - feindre ne rien voir (rien voyant /comme/ soi-même)
  - il mange /comme/ un cochon
  /ménńt/ : comme un livre\\
  /raënńt/ : comme une maison

- Ergatif /-jo/ ::  Cas grammatical marquant le sujet des  verbes transitifs, en
                   opposition à l'absolutif. Exemple\nbsp{}: /J/'ai bu du lait.

                   /ménjó/ : livre (sujet d’un verbe transitif)\\
                   /raënjo/ : maison (sujet d’un verbe transitif)

- Essif /-oiþyd-/  :: Cas  grammatical exprimant  un état  ou une  qualité. Peut
     exprimer le temps et le locatif. Exemple\nbsp{}:
  - "en tant qu'enfant" ("enfant"+essif)
  - "au Lundi" ("lundi"+essif)
  - "à la maison" ("maison"+essif)
  /móíþýdén/ : « /bookness/ » en anglais\\
  /roiþydaën/ : « /houseness/ » en anglais

- Génitif /ţu-/  :: Cas grammatical utilisé  pour marquer un complément  de nom.
                   Exprime également  la possession dans de  nombreuses langues.
                   Équivalent  de l'apostrohpe  en Anglais  (car souvent  appelé
                   avec le possessif). Exemple\nbsp{}:
  - "La maison /de Marie/"
  - "La jambe /de Marie/"
  /ţúmén/ : ... du livre (/book’s/ en anglais)\\
  /ţuraën/ : ... de la maison (/house’s/ en anglais)

- Illatif /-ën-/ :: Cas grammatical exprimant le lieu vers l'intérieur duquel se
                    produit un déplacement. Ex : "vers l'intérieur de la maison"

                    /mênén/ : vers l’intérieur du livre, vers son contenu\\
                    /rënaën/ : vers l’intérieur de la maison

- Inessif /-ŕo-/ :: Cas grammatical indiquant  le lieu dans lequel se déroule le
                    procès  exprimé par  le verbe.  Correspond à  la préposition
                    française "dans". Exemple\nbsp{}: "/dans/ la maison"

                    /méŕón/ : dans le livre, dans son contenu\\
                    /raëŕon/ : dans la maison

- *Instructif :: Cas gramatical utilisé pour marquer la manière dont s'accomplis
                 le procès  exprimé par  le verbe. Exprimé  dans le  Hjalpi’ par
                 l’instrumental.  Exemple\nbsp{}: "Je  suis venu  /à pied/"  (au
                 moyen de)

- Instrumental /-dļ/  :: Cas  grammatical exprimant  principalement l'instrument
     (actant  dit  instrument),  le   moyen  par  lequel  s'accomplit  l'action.
     Correspond  à la  préposition  française "avec".  Peut  s'utiliser avec  "à
     l'aide de", "au moyen de". Exemple\nbsp{} : "Il peint /avec/ un pinceau".

     /méndļ/ : au moyen d’un livre, grâce à un livre
     /raëndļ/ : au moyen de la maison

- Latif  /-og/ ::  Cas grammatical  indiquant un  déplacement en  direction d'un
                 endroit déterminé,  avec une  idée de limitation  du mouvement.
                 Correspond  aux préposition  françaises "jusqu'à",  "à", "aussi
                 loin que".

                  /ménóg/ : jusqu’au livre
                  /raënog/ : jusqu’à la maison

- Locatif /la-/ :: Cas grammatical exprimant la localisation dans l'espace (sans
                   mouvement), le lieu où se déroule l'action par le verbe. Peut
                   se subdiviser en plusieurs cas spécifiques, selon que le lieu
                   soit  fermé   (inessif)  ou  ouvert   (adessif,  superessif).
                   Exemple\nbsp{}: "J'habite à Paris"

                   /láraën/ à la maison

- *Nominatif :: Cas  grammatical exprimant la fonction syntaxique  de sujet d'un
                verbe  transitif ou  intransitif,  càd l'actant  dit acteur,  ou
                sujet patient. Utilisé pour indiquer le sujet d'une phrase, soit
                pour indiquer  un attribut d'un  sujet au nominatif ("il  est un
                homme", "il  devient un homme",  "il semble être un  homme"). En
                revanche, l'interjection  et l'exclamation  sont rendues  par le
                vocatif. Dans les  langues ergatives, on tend  à plutôt utiliser
                l'ergatif  et   l'absolutif.  Non  utilisé  en   langue  divine.
                Exemple\nbsp{}: "L'/homme/ lit une /lettre/" ("homme" nominatif,
                "lettre" accusatif)

- Oblique /-ŗeß/  :: Tout  type de  cas grammatical autre  que celui  servant de
                    forme  de citation  (ou de  forme canonique).  Fonctionne en
                    opposition avec  la notion de  cas direct. Dans  le Hjalpi’,
                    placé après un élément autre qu’un verbe, cela équivaut à le
                    placer entre guillemets pour citer tel quel l’élément. Après
                    un  verbe, toute  la phrase  construite autour  de ce  verbe
                    devient alors  une citation.  L’oblique peut  également être
                    utiliser  pour mettre  en valeur  l’élément décliné  : «  il
                    s’agit de /la Tour/ »

     /ménŗéß/ le « livre »\\
     /raënŗeß/ la « maison »

- Partitif /-ili’-/ ::  Cas grammatical marquant la partie  d'un tout. Considéré
     comme un nombre et non comme un cas dans certaines langues. Exemple\nbsp{}:
     "Il mange /de la/ purée"

     /mílí’én/ : une partie du livre\\
     /rili’aën/ : une partie de la maison

- Perlatif /žu-/ :: Cas grammatical exprimant le lieu par lequel, auprès duquel,
                    le long duquel on passe.  Exemple\nbsp{}: "Je marche le long
                    du fleuve"

                    /žúmén/ : près  du lieu où se trouve le  livre (la notion de
                    lieu  est  implicice à  la  déclinaison,  décliner un  objet
                    implicite le lieu lié à cet objet)\\
                    /žuraën/ : près / le long de la maison

- *Possessif ::  Cas grammatical  marquant une  relation de  possession. Souvent
                noté par le génitif dans  les langues disposant de déclinaisons.
                Le datif prend également un sens possessif dans d'autres langues
                également,  ainsi que  l'adessif. En  Anglais, le  possessif est
                marqué par le "'s", et par le "no" en Japonais.

- Prolatif -uþel-  ::  Cas grammatical expriment le lieu ou  le milieu à travers
     lequel se déroule un mouvement, ou encore le vecteur (support, médium) d'un
     déplacement ou d'un transfert d'information.

     /múþélén/ : (se  déplacer) dans un livre (recherche  d’information, lire le
     liver), via le  livre (peut se référer  à son contenu, une  histoire ou des
     informations transmises au moyen d’un livre)\\
     /ruþelaën/ : (quelqu’un s’est déplacé) dans la maison

- *Superlatif :: Cas locatif directif externe.  Il exprime le lieu sur lequel on
                 va (en général équivalent à  l'allatif finnois). Est utilisé en
                 Finnois  pour créer  des  adverbes de  lieu dynamique  externe.
                 Exprimé  en   langue  divine  via  l’allatif.   Utilisation  de
                 l’allatif en langue divine.

- Superessif /oi-/ ::  Cas locatif statique externe. Exprime un  lieu sur lequel
     on est (en général équivalent à un adessif finnois). Est utilisé en Finnois
     pour créer des adverbes de lieu statique externe.

     /óímén/ : vers le livre (sur sa surface plane, sa couverture)\\
     /oiraën/ : vers la maison (son toit, son mur)

- Terminatif  /-eg/  ::   Cas  grammatical  exprimant  la   limite  spatiale  ou
     temporelle, le  point ultime  d'un déplacement ou  d'une période  de temps.
     Correspond à la préposition française  "jusqu'à". N’est utilisé que pour la
     notion de temps en langue divine. Exemple\nbsp{}:
  - "jusqu'à la maison"
  - "jusqu'au soir"
  /jánég/ : jusqu’au soir (/ján/ : soir)

- Translatif /-in/  :: Cas grammatical  exprimant le RÉSULTAT d'un  processus de
     transformation.  En Finnois,  s'utilise beaucoup  avec le  verbe "devenir".
     Exemple\nbsp{}: "Je suis tombé malade" (je suis devenu malade)

     /ménín/ : transformation en un livre\\
     /raënin/ : transformation en une maison (construction de la maison,...)

- Vocatif  /-wa/ ::  Cas  grammatical exprimant  l'interpellation directe  d'une
                   personne  (ou  d'une chose)  au  moyen  d'un appellatif  (nom
                   propre ou  terme d'adresse). Dans le  Hjalpi’, peut également
                   marquer l’exclamation.

                    /ménwá/ : le livre !\\
                    /raënwa/ : la maison !
